### ISSUE TITLE
Could not get MvcOptions.ReturnHttpNotAcceptable to work together with ApiVersioning

### ISSUE THREAD

**Issue by frankfajardo** [Microsoft/aspnet-api-versioning#101]
Not sure if this is a bug or just ignorance on my part. but I could not get these two work together. I'd like to return HTTP 406 if the version requested is not supported. So I have:
```
services.AddApiVersioning(options =>
{
   options.ReportApiVersions = true;
   options.AssumeDefaultVersionWhenUnspecified = false;
   options.ApiVersionReader = new MediaTypeApiVersionReader();
});
services.AddMvc(options =>
{
   options.RespectBrowserAcceptHeader = true;
   options.ReturnHttpNotAcceptable = true;  // Return HTTP 406
});
```
But this always returns HTTP 406 even if the version is correct (e.g. `application/json;v=1.0` or `application\vnd.xxx+json;v=1`). 

If I set ReturnHttpNotAcceptable to false, I get HTTP 400 (Bad Request) when version is unsupported, and HTTP 200 if version is supported.

Also, if I set my ApiVersionReader to be the HeaderApiVersionReader, and set ReturnHttpNotAcceptable to true, it returns an HTTP 400 instead of 406 when the version is unsupported.

**Comment by commonsensesoftware** [comment]
I haven't tried combining the 406 options with the new media type versioning method, so it's certainly possible that something may not work as expected. I haven't looked at how the media type is matched and it's possible that there is some strict matching once you turn on this option. As a Litmus test, you could try using `application/json;q=1`. This should be acceptable and match the default JSON media type formatter. If it doesn't, then it seems to be a limitation in the way ASP.NET is mapping media type formatters. You _may_ have to clear and re-register the media type formatters with the API versioning parameter you define (or the default) in order for them to match up.

Another approach would be to define a new, custom [IErrorResponseProvider](../blob/master/src/Common/Versioning/IErrorResponseProvider.cs) that changes how 400s are generated. You can also just extend the [DefaultErrorResponseProvider](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/DefaultErrorResponseProvider.cs) class. To do so, you would just override the **BadRequest** method and return 406 when an API version is not supported instead of the default 400. The full description of standard error responses is on the [wiki](../wiki/Error-Responses). You wire your provider a la:

```c#
options => options.ErrorResponses = new MyCustomErrorResponses();
```

**Comment by frankfajardo** [comment]
I tested using `application/json, application/json;v=1.1` with my API which supported version 1.1, and I get HTTP 200 and it correctly called my v1.1 Controller, but  If I change it to just `application/json;v=1.1`, I get an HTTP 406. So it appears the versioned media type satisfied the MediaTypeApiVersionReader, but it was being rejected by the `AcceptHeaderParser` as a valid `MediaTypeSegmentWithQuality`.

I wonder if the `MediaTypeApiVersionReader` should come with an extension to the AcceptHeaderParser which ignores the version parameter, and correctly captures the media type.

**Comment by frankfajardo** [comment]
Also, I'm not sure what you mean by

> You may have to clear and re-register the media type formatters with the API versioning parameter you define (or the default) in order for them to match up.

But I tried adding FormatterMappings like the following, but it didn't work and still gives me HTTP 406: 
```
services.AddMvc(options =>
{
    options.FormatterMappings.SetMediaTypeMappingForFormat("application/json;v=1.1", 
        new MediaTypeHeaderValue("application/json"));
    options.ReturnHttpNotAcceptable = true;
});
```

**Comment by commonsensesoftware** [comment]
It seems you've hit a behavior in the platform that doesn't do what you'd expect. I didn't know where all the _landmines_ are, but I know there are some. This is why API versioning wasn't previously supported with content negotiation. Although content negotiation is the fully RESTful method, you have to _fight_ the platform to make it work. There are two workarounds that should work for you.

### Method 1
As previously mentioned, change the default error response provider. This is the least amount of work and should get you what you want.

```c#
public class MyErrorResponseProvider : DefaultErrorResponseProvider
{
    public override IActionResult BadRequest( ErrorResponseContext context )
    {
        var result = base.BadRequest( context );
        if ( context.Code == "UnsupportedApiVersion" || context.Code == "InvalidApiVersion" )
        {
             result.StatusCode = StatusCodes.Status406NotAcceptable;
        }
        return result;
    }
}
// ...
services.AddApiVersioning( options => options.ErrorResponses = new MyErrorResponseProvider() );
```

### Method 2
I would say this second method is technically the _right_ solution, but it's quite involved.  First, you need to subclass the built-in ASP.NET Core [ObjectResultExecutor](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/Internal/ObjectResultExecutor.cs) class. A sample implementation is too much for this thread, but this is the only place I see where you can alter how the **Accept** header is handled and potentially return 406.

Once you have the implementation the way you want, you wire it up a la:

```c#
services.Replace( ServiceDescriptor.Singleton<ObjectResultExecutor, MyObjectResultExecutor>() );
```

The current, default, and expected response from the server when an API version is not supported is 400. To keep things consistent, I'm not planning on changing the behavior just for content negotiation, even though 406 is a reasonable response. The API version is conveniently attached to the media type, but it's not really part of the media type.  For example, we expect that `application/json;v=42`, `application/xml;v=42`, or `[any media type];v=42` to all return 400, regardless of the media type value because version 42 isn't supported.

Hopefully, one of these solutions is sufficient for you. I'm currently focused on the API description stuff because a lot of people have been asking for it. I am, however, willing to consider entertaining a built-in option that would enable an easier configuration/setup for service authors that prefer 406 responses instead of 400.

**Comment by frankfajardo** [comment]
Thanks @commonsensesoftware for taking time to help.
I think I didn't quite explain myself earlier. If I remove ApiVersioning and set `MvcOptions.ReturnHttpNotAcceptable = true`, my API correctly returns Http 406 if the media type on the Accept Header is not supported, and Http 200 if it is supported. It is when I start adding a version on the Accept Header, that I get an Http 406 all the time even if the version and media type is supported.

Anyway, I have found out that I can just create a custom output formatter that defines which media types it supports (e.g. `application/json;v=1.0`). And I just added it to Mvc's OutputFormatters. In this case, I made my custom output formatter inherit from `Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter`.

**Comment by frankfajardo** [comment]
Ah, and yes, I will have to also apply your *Method 1* to force a 406 on unsupported API versions.

**Comment by commonsensesoftware** [comment]
Glad that helped. If you share your solution, I'll consider making some type of built-in support for it. At a minimum, I'll update the wiki for those that want to use this approach. I don't 100% know why the **Content-Type** header is not affected in a similar way, but I think this is because ASP.NET just ignores the media type parameters in that scenario. Clients do not usually specify _quality_ when content is provided.

The biggest challenge for me will be trying make things work consistently between ASP.NET Core and Web API. My goal is always to make API versioning light up for service authors the way they want and with the least amount of effort. While I'm glad you have a workable solution, it still feels like quite a bit of effort. Since 1.1.0 is still beta, now is good time to consider tightening things up. Thanks again for your support and feedback. It's very helpful.

**Comment by frankfajardo** [comment]
I used a response provider as you said:
```
public class UnsupportedApiVersionResponseProvider : DefaultErrorResponseProvider
{
    public override IActionResult BadRequest(ErrorResponseContext context)
    {
        if (context.Code == "UnsupportedApiVersion" || context.Code == "InvalidApiVersion")
        {
            return new StatusCodeResult(Status406NotAcceptable);
        }
        return base.BadRequest(context);
    }
}
```
But maybe if you can provide `ApiVersioning.ReturnHttpNotAcceptable` similar to that from `MvcOptions` and have that read by the `DefaultErrorResponseProvider`, maybe we can remove the need to implement a `ErrorResponseProvider` just to return Http 406.

As for the output formatter, I actually had to support versioned vendor media type (e.g. `application/vnd.acme+json;v=1.0`), so I simply created a subclass of JsonOutputFormatter but just provided the media types it needs to support:
```
public class VendorJsonOutputFormatter : JsonOutputFormatter
{
    private const string VendorJsonType = "application/vnd.acme+json"; 

    public VendorJsonOutputFormatter(
        IList<Microsoft.AspNetCore.Mvc.ApiVersion> versions,
       JsonSerializerSettings serializerSettings,
        ArrayPool<char> charPool) : this("v", versions, serializerSettings, charPool) { }

    public VendorJsonOutputFormatter(
        string versionParamName,
        IList<Microsoft.AspNetCore.Mvc.ApiVersion> versions,
        JsonSerializerSettings serializerSettings, 
        ArrayPool<char> charPool) : base(serializerSettings, charPool)
    {
        Contract.Requires(versions != null && versions.Count > 0);
        Contract.Requires(IsNullOrWhiteSpace(versionParamName) && Regex.IsMatch(versionParamName, "^[a-zA-Z]+$"));

        // Remove support for native json media types: "application/json", "text/json"
        SupportedMediaTypes.Clear();

        // Allow this formatter to be used on unversioned media type
        SupportedMediaTypes.Add(VendorJsonType);

        // Now add the versioned media types
        foreach (var version in versions)
        {
            if (version.MinorVersion.HasValue && version.MinorVersion.Value > 0)
            {
                SupportedMediaTypes.Add($"{VendorJsonType};{versionParamName}={version.MajorVersion}.{version.MinorVersion}");
            }
            else
            {
                SupportedMediaTypes.Add($"{VendorJsonType};{versionParamName}={version.MajorVersion}");
                SupportedMediaTypes.Add($"{VendorJsonType};{versionParamName}={version.MajorVersion}.0");
            }
        }

        // Ensure camelCased property names during serialization
        serializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
    }
}
```
And then I use it like this:
```
services.AddMvc(options =>
{
    options.RespectBrowserAcceptHeader = true;
    options.ReturnHttpNotAcceptable = true;
    var jsonSerializerSettings = new JsonSerializerSettings();
    var versions = new List<ApiVersion>
    {
        new ApiVersion(1, 0),
        new ApiVersion(1, 1)
    };
    options.OutputFormatters.Add(new VendorJsonOutputFormatter(versions, jsonSerializerSettings,
        System.Buffers.ArrayPool<char>.Shared));
});
```
This supports:
- application\vnd.acme+json  (if I provide a default version)
- application\vnd.acme+json;v=1
- application\vnd.acme+json;v=1.0
- application\vnd.acme+json;v=1.1

Regarding your statement 

> I don't 100% know why the Content-Type header is not affected in a similar way, but I think this is because ASP.NET just ignores the media type parameters in that scenario. 

Isn't the request Content Type about the data that comes with the request?
