### ISSUE TITLE
Not working with route consraints in attribute routing

### ISSUE THREAD

**Issue by imperat0r** [Microsoft/aspnet-api-versioning#102]
It gives unsupported api version error instead of real error.

**Comment by commonsensesoftware** [comment]
Can you provide some additional details? Are you using Web API or Core? Do you have an example of your route constraint? What does your route template look like? What was the _real error_ you were expecting? Do you have a repro?

**Comment by commonsensesoftware** [comment]
Since you haven't provided any additional input, I'm not sure how to help. From what I can discern, it seems you are experiencing the same behavior that is being discussed in #105. Feel free to join that conversation.

There is a known bug where 400 is returned instead of 405.  This was reported in #65 and has been fixed, but it has not yet been released. That will go out as part of the official 1.1.0 release. There is a beta version of the packages available now; otherwise, you can use the solution I provided in #105.

Thanks
