### ISSUE TITLE
Unable to install Microsoft.AspNet.OData.Versioning.2.1.0-beta1 nuget

### ISSUE THREAD

**Issue by janv8000** [Microsoft/aspnet-api-versioning#104]
Hello,

I'm unable to install the Microsoft.AspNet.OData.Versioning nuget @ version 2.1.0-beta1 into a new webapplication project.

VS2017 -> New Project -> .NET 4.6.2 -> ASP.Net Web Application (.NET Framework)

I get the following output from Package Manager Console:

> PM>  Install-Package Microsoft.AspNet.OData.Versioning -Prerelease
> 
> 
> Attempting to gather dependency information for package 'Microsoft.AspNet.OData.Versioning.2.1.0-beta1' with respect to project 'WebApplication2OdataVersioningNuget', targeting '.NETFramework,Version=v4.6.2'
> Gathering dependency information took 27,43 sec
> Attempting to resolve dependencies for package 'Microsoft.AspNet.OData.Versioning.2.1.0-beta1' with DependencyBehavior 'Lowest'
> Install-Package : Unable to find a version of 'Microsoft.AspNet.WebApi.Versioning' that is compatible with 'Microsoft.AspNet.OData.Versioning 2.1.0-beta1 constraint: Microsoft.AspNet.WebApi.Versioning (>= 2.1.0)'.
> At line:1 char:2
> +  Install-Package Microsoft.AspNet.OData.Versioning -Prerelease
> +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Time Elapsed: 00:00:28.6302428
> PM>

**Comment by petersondrew** [comment]
I was just looking at nuget this morning, and I don't think the package uploaded there was uploaded by anyone working on this project (based on the username only). So my guess is there are some issues with the nuspec.

Perhaps this project needs an official nuget upload?

**Comment by commonsensesoftware** [comment]
Apologies, there was a mistake in the \*.nuspec. The project was recently updated to VS2017 and switched to the new, integrated build process between MSBuild and NuGet. Unfortunately, `dotnet pack --version-suffix beta1` did not carry though to referenced projects (as it did with _project.json_) and I missed that before publishing.  It appears this is actually a NuGet bug as outlined in [Issue #4337](https://github.com/NuGet/Home/issues/4337).

I've updated the release to "beta2" with the metadata fix and unlisted "beta1" to avoid any confusion. I was able to confirm package resolution works [for me]. Let me know if you run into any more issues.

**Comment by commonsensesoftware** [comment]
As a side note, I'm not planning on having an official 2.1 release for OData 5.9.1. The final release will include the long-awaited support for OData 6.0.0. At least with respect to API Versioning, there are no visible changes between 5.9.1 and 6.0.0.  There are underlying changes in how things are implemented and ultimately how you use the OData APIs.

As OData users, I'd appreciate any thoughts you have on the matter. At some point, I have to draw a line in the sand just as the OData team did. I can't support 5.9.1 and 6.0.0 simultaneously. I'm not sure how many OData service authors really want to stay on 5.9.1. I'm willing to entertain a final, official 5.9.1 release, but after that it would only be critical bugs. Since most of the heavy lifting is actually in the Web API library, I don't expect much in the way of OData-related bug fixes.

**Comment by commonsensesoftware** [comment]
This should be fixed with the out-of-band "beta2" release that updates the metadata in the NuGet package. I haven't heard anything else on this topic, so I'm assuming it's resolved. If anyone is continuing to have a problem, let me know and I'll re-open this issue to investigate.

Thanks.
