### ISSUE TITLE
GET Method not working with API Versioning

### ISSUE THREAD

**Issue by JCorrell** [Microsoft/aspnet-api-versioning#110]
I'm having an issue with one of my GET methods not working with API Versioning turned on.

I'm using VS2017 & MVC.Versioning 1.0.3

This is that portion of my Startup.cs:

> services.AddApiVersioning(cfg =>
      {
        cfg.DefaultApiVersion = new ApiVersion(0, 1);
        cfg.AssumeDefaultVersionWhenUnspecified = true;
        cfg.ReportApiVersions = true;
  });

Here is how my controller is decorated:

> namespace NEHO.UnrealBaseball.Api.Controllers
{
  [Produces("application/json")]
  [Authorize]
  [EnableCors("AnyGET")]
  [ValidateModel]
  [ApiVersion("0.1")]
  [ApiVersion("1.0")]
  [Route("api/[controller]")]
  public class LeaguesController : BaseController

BaseController is just an extension of Controller

This GET Method works:

> [HttpGet("")]
    public IActionResult Get()
    {
      var leagues = _repository.GetAllLeagues();
      return Ok(_mapper.Map<IEnumerable<LeagueModel>>(leagues));
    }

While this one does not:

> [HttpGet("{leagueAbbreviation}", Name = "GetLeague")]
    [MapToApiVersion("0.1")]
    public IActionResult Get(string leagueAbbreviation)
    {
      try
      {
        var league = _repository.GetLeague(leagueAbbreviation);
       if (league == null)
        {
          return NotFound($"League {leagueAbbreviation} was not found.");
        }
       return Ok(_mapper.Map<LeagueModel>(league));
      }
      catch (Exception exception)
      {
        _logger.LogError($"Threw exception while getting league {leagueAbbreviation}: {exception}.");
      }
     return BadRequest();
    }

Using the above GET Method, I get a 400 UnsupportedApiVersion error.  If I turn off Versioning, the Method works as expected.

POST,  PUT, DELETE all work as expected.

Any guidance or suggestions would be most appreciated.

Jim

**Comment by commonsensesoftware** [comment]
Let me try to summarize the behaviors to ensure I understand. Given your configuration, here's what I'm seeing:

* `GET api/leagues` - returns 200 all leagues (because v0.1 is the default)
* `GET api/leagues?api-version=0.1` - returns 200 with all leagues
* `GET api/leagues?api-version=1.0` - returns 200 with all leagues
* `GET api/leagues/nl` - returns the 'NL' league (because v0.1 is the default)
* `GET api/leagues/nl?api-version=0.1` - returns the 'NL' league
* `GET api/leagues/nl?api-version=1.0` - returns 400 with UnsupportedApiVersion because the action is only mapped to v0.1

This is what I would expect to have happen. Are you seeing a different behavior?

**Comment by JCorrell** [comment]
Yes, I'm seeing a different behavior.

- GET api/leagues returns a 200 under all circumstances
- GET api/leagues/nl - returns a 400 under all circumstances, whether it's specifying a version or relying on default.

Furthermore...
- GET api/leagues/nl/teams/bos returns a 200 under all circumstances (with nearly identical code)

Only the GET api/leagues/nl example fails.

Here is the GET GET api/leagues/nl/teams/bos code....

> [HttpGet("{teamAbbreviation}", Name = "GetTeam")]
    [MapToApiVersion("0.1")]
    public IActionResult Get(string leagueAbbreviation, string teamAbbreviation, bool includePlayers = false)
    {
      try
      {
        Team team = null;

        if (includePlayers)
        {
          return BadRequest();  // Not implemented yet
        }
        else
        {
          team = _repository.GetTeam(leagueAbbreviation, teamAbbreviation);
        }
        if (team == null)
        {
          return NotFound($"Team: {teamAbbreviation} was not found.");
        }
        return Ok(_mapper.Map<TeamModel>(team));
      }
      catch (Exception exception)
      {
        _logger.LogError($"Threw exception while getting team {teamAbbreviation}: {exception}.");
      }
      return BadRequest();
    }

**Comment by commonsensesoftware** [comment]
I attempted to reproduce your scenario, but everything works as I would expect.  Here's the controller that I setup:

```c#
[ApiVersion( "0.1" )]
[ApiVersion( "1.0" )]
[Route( "api/[controller]" )]
public class LeaguesController : BaseController
{
    [HttpGet]
    public IActionResult Get() =>
      Ok(
        new {
          message = "All leagues",
          version = HttpContext.GetRequestedApiVersion().ToString()
        } );

    [HttpGet( "{leagueAbbreviation}", Name = "GetLeague" )]
    [MapToApiVersion( "0.1" )]
    public IActionResult Get( string leagueAbbreviation ) =>
      Ok(
        new {
          league = leagueAbbreviation,
          version = HttpContext.GetRequestedApiVersion().ToString()
         } );

    [HttpGet( "{leagueAbbreviation}/{teamAbbreviation}", Name = "GetTeam" )]
    [MapToApiVersion( "0.1" )]
    public IActionResult Get( string leagueAbbreviation, string teamAbbreviation, bool includePlayers = false ) =>
        Ok(
          new {
            league = leagueAbbreviation,
            team = teamAbbreviation,
            version = HttpContext.GetRequestedApiVersion().ToString()
          } );
}
```

The routes:

* `GET api/leagues/nl?api-version=1.0`
* `GET api/leagues/nl/bos?api-version=1.0`

fail with 400 because they are only mapped to v0.1. All other requests return 200 as expected. For your convenience, I've attached my repro project. There must be something different about your setup that I'm not seeing.

[BaseballRepro.zip](https://github.com/Microsoft/aspnet-api-versioning/files/926235/BaseballRepro.zip)

**Comment by JCorrell** [comment]
Thanks man.  I appreciate you looking into this.  I still have no idea what was going on, but after seeing your project and feeling like I wasn't doing anything fundamentally wrong, I rebuilt the controller from the ground up and all is working as expected.  Even looking at the controllers side by side, I can't see the problem.  I'm sure it's there, I just can't find it.

Thanks again, Jim
