### ISSUE TITLE
Routing broken in rc1 w/ swagger

### ISSUE THREAD

**Issue by senften** [Microsoft/aspnet-api-versioning#127]
Forking and updating another example for `PackageReference Include="SwashbuckleAspNetVersioningShim" Version="1.0.0-beta2"/>`, routing of the api endpoints fails with rc1 but works as expected with beta2. The controller endpoints for any version are never hit. Falling back to beta2 resolves the issues.

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <!--<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="1.1.0-rc1"/>-->
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="1.1.0-beta2"/>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0" />
    <PackageReference Include="SwashbuckleAspNetVersioningShim" Version="1.0.0-beta2"/>
  </ItemGroup>
```

Complete example at https://github.com/senften/AspNetCoreVersionedWebApi (This is a fork of https://github.com/rh072005/SwashbuckleAspNetVersioningShim)

**Comment by commonsensesoftware** [comment]
It appears that your example is no longer correct. In the **Startup.cs**, it does not contain **UseApiVersioning**. Unfortunately, this is _behavioral_ breaking change that is required in order to enable route constraints (amongst other things) across API versions. This only affects ASP.NET Core.  The details are called out in the [v1.1 RC release notes](../releases/tag/v1.1-rc1).

Add the following and you should be back in business:

```c#
app.UseMvc().UseApiVersioning();
```

**Comment by senften** [comment]
Thank you very much. That, indeed, works. My apologies. I should have checked the release notes.
