### ISSUE TITLE
Rerouting versions using url path

### ISSUE THREAD

**Issue by shreeena** [Microsoft/aspnet-api-versioning#128]
I'm trying to set up an ASP.NET Core service such that given versions 1.0, 1.1, 1.2, and 2.0:

- using `api/v1.1/*` would explicitly route to the specified major/minor version (1.1)
- using `api/v1/*` would implicitly route to the latest minor version under that major (1.2)

My controllers/endpoints are currently set up to use the `ApiVersionRouteConstraint`.

My initial attempt to use `IApiVersionSelector` was thwarted as the selector is only invoked when attempting to determine a default version. My next attempt to use `IApiVersionReader` failed, since it doesn't get used when the `ApiVersionRouteConstraint` is matched. I've managed to get something somewhat working by defining a custom IRouteConstraint. However, from the constraint, I'm lacking the `ApiVersionModel` that `IApiVersionSelector` has for figuring out what versions are available.

Are there any suggested approaches for doing this?

Thanks!

**Comment by commonsensesoftware** [comment]
For this case, you might just consider URL rewriting, which is effectively what you're doing anyway.  Basically, you would redirect `v1` to `v1.?`.  Dynamically doing this at runtime is obviously tricky, but can be done fairly easy with configuration. Static configuration is a reasonable compromise since it shouldn't change often. It's up to you if you want to use a _transfer_ or a _redirect_. Also consider that `1` and `1.0` are equivalent. I'll try to think of any other ways this might be done.

_enter soapbox..._

In my opinion, this is a bad idea. API versions should be explicit. Any variation of versions can break clients. A service can never know for sure that clients use _tolerance readers_ and can handle, even minor additions. I think it's dangerous to start forwarding clients to new versions without them knowing about
it. Ultimately it's your decision, but unless you own both sides, I urge strong caution.

**Comment by shreeena** [comment]
Thanks - that makes sense. I agree that services shouldn't be implicitly hiding any changes (esp. not breaking ones, which should warrant a new major version) but unfortunately it's a policy I have to work with. Luckily we do own the consuming client(s) and can be relatively positive that minor additions are fine. I've managed to get something working by resolving an `IApiVersionDescriptionProvider` from the HttpContext in the constraint, but I'll look into URL rewriting as well. Cheers!
