### ISSUE TITLE
calling API doesn't care about version number and Swagger issue

### ISSUE THREAD

**Issue by danboone** [Microsoft/aspnet-api-versioning#132]
I have a couple of questions and issues.
I am using version 2.0.3 for ASP.Net API's

the first one is I have found when I am calling the API's.
I have the API decorated as below so i would expect that version i could pass in to get data would be 1.   But I have discovered that I can pass any number into it and it calls the API

http://localhost:63932/api/v1/Brand
http://localhost:63932/api/v50/Brand

both of these return the same result to me is that to be expected?

 [ApiVersion("1.0")]
    public class BrandController : ApiController
    {
          /// <summary>
        /// Return list of brands the user has access to. 
        /// </summary>
        /// <param name="adid">UserLoginId from User API</param>
        /// <returns></returns>
        [ResponseType(typeof(List<BrandEntity>))]
        [Route("api/v{version:apiVersion}/Brand")]
public HttpResponseMessage Get()
        {
//stuff
}

The second issue is I'm using swagger to document my API's but am trying to have it recognize the different versions so that it is clear what API call works with what version.  I see you have a rc that the documentation uses to go through the swagger demo, but i can't use rc in our production environment.  I haven't looked to see if it works the way i'd expect in the demo yet anyway.
I'd like a nice way to tell swagger what version goes to what api and swagger display it cleanly
http://localhost:63932/api/v1/URI/{id}
http://localhost:63932/api/v2/URI/{id}/input/{input2}

**Comment by commonsensesoftware** [comment]
### Question 1
Can you share your configuration (e.g. WebApiConfig) or at least the relevant parts?

### Question 2
When you enable the API explorer support for API versioning, you can easily plug it into Swagger/Swashbuckle so that APIs are bucketized by API version.  This will produce distinct Swagger documents per API version and Swashbuckle can provide API version specific UIs. The example project does this exact thing and is based on Swashbuckle's **MultipleApiVersions** method. Take a copy of the current build if you want to see how it looks for yourself.

I'm not sure what advice I can give you about your development policies and the use of release candidates.  The Web API side is stable. A regression was just uncovered in the ASP.NET Core side. Once that is resolved, I'll be releasing the official 1.1 build. Alternatively, you can take and own a fork of the API explorer. Sadly, the Web API extensibility support for the API explorer is not great at all. Implementing or even forking the code is not for the faint of heart. If you must have it, can't use a RC, and can't wait for the official build, be my guest and take a stab copying the source into your codebase.

**Comment by danboone** [comment]
for question 1 i here is my webAPi config. Alos i noticed that your demo for swagger performs the same way.

 public static void Register(HttpConfiguration config)
        {
            var constraintResolver = new DefaultInlineConstraintResolver() { ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) } };

            // Web API configuration and services
            config.SuppressDefaultHostAuthentication();
            config.Filters.Add(new HostAuthenticationFilter(OAuthDefaults.AuthenticationType));
            config.EnableCors();
            config.Formatters.JsonFormatter.SerializerSettings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore, Formatting = Formatting.None };
            // Web API routes
            config.MapHttpAttributeRoutes(constraintResolver);

            //config.Routes.MapHttpRoute(
            //    name: "DefaultApi",
            //    routeTemplate: "api/{controller}/{id}",
            //    defaults: new { id = RouteParameter.Optional }
            //);
            //config.Routes.MapHttpRoute(
            //    name: "UserApi",
            //    routeTemplate: "api/user/{adid}/{controller}/{id}",
            //    defaults: new { id = RouteParameter.Optional }
            //);
        }

for question 2 i was trying to fill out the version # for each version, your example only does it for version 0.9 when you switch between the other versions nothing changes.

**Comment by commonsensesoftware** [comment]
For `#1`, I don't see `config.AddApiVersioning()`. It won't work without that. That would explain why any API version can be specified. The **ApiVersionRouteConstraint** only verifies that the API version is present and well-formed. The `AddApiVersioning` extension method updates and adds the required services to enable API versioning.

For `#2`, did you click **Explore** in the UI? There is drop down for each API version and Swagger document. You must click **Explore** in order to update the UI. This is how it works out-of-the-box. The UI should display the following drop-down list:

* `http://localhost:15721/v0.9/swagger`
* `http://localhost:15721/v1/swagger`
* `http://localhost:15721/v2/swagger`
* `http://localhost:15721/v3/swagger`

Selecting any other option and clicking **Explore** will definitely update the UI and render new information.

**Comment by danboone** [comment]
I had this line in my swaggerconfig file: configuration.AddApiVersioning(o => o.ReportApiVersions = true);
i moved it to the webapiconfig and it works now.  Thank you for that insight.

clicking explore did work thank you for the information :)

I am going to install the rc and test out your implementation in our setup.

**Comment by danboone** [comment]
I have implemented the rc and i can't get it to fire to get the version of the API's.  I think the issue has  to do with i'm injecting javascript to handle our token based API calls.  It never calls the ImplicitApiVersionParameter class to try and parse the API's

here is my webapiconfig

 var constraintResolver = new DefaultInlineConstraintResolver() { ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) } };
            config.AddApiVersioning(o => o.ReportApiVersions = true);
            // Web API configuration and services
            config.SuppressDefaultHostAuthentication();
            config.Filters.Add(new HostAuthenticationFilter(OAuthDefaults.AuthenticationType));
            config.EnableCors();
            config.Formatters.JsonFormatter.SerializerSettings = new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore, Formatting = Formatting.None };
            // Web API routes
            config.MapHttpAttributeRoutes(constraintResolver);

            var apiExplorer = config.AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VVV");

            var thisAssembly = typeof(SwaggerConfig).Assembly;
            config
                .EnableSwagger("{apiVersion}/swagger", c =>
                {
                    c.IncludeXmlComments(XmlCommentsFilePath);
                    c.MultipleApiVersions(
                        (apiDescription, version) => apiDescription.GetGroupName() == version,
                                info =>
                                {
                                    foreach (var group in apiExplorer.ApiDescriptions)
                                    {
                                        var description = " API versioning.";

                                        if (group.IsDeprecated)
                                        {
                                            description += " This API version has been deprecated.";
                                        }

                                        info.Version(group.Name, $"API {group.ApiVersion}")
                                            // .Contact(c => c.Name("Bill Mei").Email("bill.mei@somewhere.com"))
                                            .Description(description)
                                            //.License(l => l.Name("MIT").Url("https://opensource.org/licenses/MIT"))
                                            //.TermsOfService("Shareware")
                                            ;
                                    }
                                });


                   
                })
                .EnableSwaggerUi(c =>
                {
                    c.InjectJavaScript(thisAssembly, "WebSite.Scripts.basic-auth.js");
                    c.EnableDiscoveryUrlSelector();                    
                });
        }
        static string XmlCommentsFilePath
        {
            get
            {
                var basePath = System.AppDomain.CurrentDomain.RelativeSearchPath;
                var fileName = typeof(Startup).GetTypeInfo().Assembly.GetName().Name + ".xml";
                return Path.Combine(basePath, fileName);
            }
        }

**Comment by danboone** [comment]
I figured it out i left out one line thank you for all your help

**Comment by danboone** [comment]
I want to thank you for your help in figuring this out.  Everything is working as expected

**Comment by commonsensesoftware** [comment]
Glad you got it all sorted out. For additional clarification, you don't need to have a Swagger operation filter that is as complex as the example. That example is only meant to demonstrate showing query string and URL segment style API versioning at the same time. Most devs will choose one or the other. Supporting just one style is a much simpler implementation of the operation filter.
