### ISSUE TITLE
Inheritance version controller 

### ISSUE THREAD

**Issue by jcmordan** [Microsoft/aspnet-api-versioning#142]
I have a controller like this:

```
namespace WebApplication1.Controllers.V1
{
    [ApiVersion("1")]
    [RoutePrefix("api/v{version:apiVersion}/values")]   
    public class ValuesController : ApiController
    {
        // GET api/values
        public virtual IEnumerable<string> Get()
        {
            return new string[] { "value1 v1", "value2 v1" };
        }

        // GET api/values/5
        public virtual string Get(int id)
        {
            return $"value{id} v1";
        }      
    }
}
```
and another controller that inherits from V1.ValuesController like this: 

```
namespace WebApplication1.Controllers.V2
{
    [ApiVersion("2")]
    [RoutePrefix("api/v{version:apiVersion}/values")]    
    public class ValuesController : V1.ValuesController
    {
        // GET api/values
        public override IEnumerable<string> Get()
        {
            return new string[] { "value1 v2", "value2 v2" };
        }
    }
}
```

but when I make a request to  **http://localhost:51909/api/v2/values/5** , I got this response:

```
{
    "error": {
        "code": "UnsupportedApiVersion",
        "message": "The HTTP resource that matches the request URI 'http://localhost:51909/api/v2/values/5' does not support the API version '2'.",
        "innerError": {
            "message": "No route providing a controller name with API version '2' was found to match request URI 'http://localhost:51909/api/v2/values/5'."
        }
    }
}
```

Is there any whay to do this? I mean inherit code from a base controller to avoid duplicated code.

**Comment by commonsensesoftware** [comment]
Based on your setup, I don't conceptually see a reason why it wouldn't work. I suspect it may have something to do with your routing configuration. Are you using attribute or convention-based routing? Hopefully, you're not using both. I strongly discourage both; it's confusing. In addition, after many failed attempts, I've concluded that there is no real way to support API versioning for a single service using both routing styles. You can only mix styles if you use the same style for all API versions of a service that your controllers implement.

I mention that because I only see `[RoutePrefix]`.  The route prefix does not define a route.  That means your example has no routes. If it works or ever worked, it must be due to convention-based routing. You should be able to prove that by ensuring the following:

* Make sure your configuration does not call **MapHttpRoute** (which the default template does)
* Make sure your configuration does call **MapHttpAttributeRoutes**

At that point, you _should_ see that no routes work with or without API versioning.  To fix things, you should be able to do **one** of the following:

* Change `[RoutePrefix]` to `[Route]`
* Add `[Route]` to each action

With all of that in place, I expect that things should be working for you, including the inheritance bits.

**Comment by jcmordan** [comment]
> Change [RoutePrefix] to [Route]
Both the V1 and V2 controller mush have the `[Route] ` ?

**Comment by commonsensesoftware** [comment]
I believe not because the [RouteAttribute](https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/System.Web.Http/RouteAttribute.cs#L12) is inherited.

**Comment by jcmordan** [comment]
I tried your recomendations, this is how the controllers and the WebApiConfig look like:

- V1 Controller 
```
namespace WebApplication1.Controllers.V1
{
    [ApiVersion("1")]
    [RoutePrefix("api/v{version:apiVersion}/values")]   
    public class ValuesController : ApiController
    {
        // GET api/values
        public virtual IEnumerable<string> Get()
        {
            return new string[] { "value1 v1", "value2 v1" };
        }

        // GET api/values/5
        public virtual string Get(int id)
        {
            return $"value{id} v1";
        }      
    }
}
```

- V2 Controller

```
namespace WebApplication1.Controllers.V2
{
    [ApiVersion("2")]  
    public class ValuesController : V1.ValuesController
    {
        // GET api/values
        public override IEnumerable<string> Get()
        {
            return new string[] { "value1 v2", "value2 v2" };
        }
    }
}
```
- WebApiConfig

```
 public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services

            // Web API routes

            var constraintResolver = new DefaultInlineConstraintResolver()
            {
                ConstraintMap =
                {
                    ["apiVersion"] = typeof( ApiVersionRouteConstraint )
                }
            };

            config.MapHttpAttributeRoutes(constraintResolver);
            config.AddApiVersioning(options =>
            {
                options.ReportApiVersions = true;
            });

        }
```

but I'm getting the same response `UnsupportedApiVersion` calling `/api/v2/values/5` 

If I change `[RoutePrefix]` to `[Route]` I get the error on both the V1 and V2 controller.

**Comment by commonsensesoftware** [comment]
I found the issue. It's within ASP.NET Web API itself. Despite the `[Route]` and `[RoutePrefix]` attributes being inheritable, the platform intentionally ignores them.  Have a look at the [DefaultDirectRouteProvider.cs](https://github.com/ASP-NET-MVC/aspnetwebstack/blob/4e40cdef9c8a8226685f95ef03b746bc8322aa92/src/System.Web.Http/Routing/DefaultDirectRouteProvider.cs#L133) file and you'll see that inherited attributes are not considered. The framework implements **IDirectRouteFactory** through attributes. We all commonly call it _attribute routing_, but the name of the feature is actually _direct routing_.

You're probably raising up your stark fist right now, but fear not; there is a solution. I suspect the reason for this behavior is that inheritance would never work the way you are using it without API versioning. Web API would just barf and say the routes are ambiguous. To overcome the built in behaviors, you need to replace the **IDirectRouteProvider** with an implementation that will considered inherited attributes. I'll attached the world's simplest demo and it worked for me.  Give it a go for yourself and let me know how it works out.

[InheritanceDemo.zip](https://github.com/Microsoft/aspnet-api-versioning/files/1082078/InheritanceDemo.zip)

**Comment by commonsensesoftware** [comment]
Did this solution work for you? Just want to make sure your issue was resolved before closing. Thanks.

**Comment by jcmordan** [comment]
Sorry, this didn't, tomorrow I will upload an example of what exactly I
need to do.

**Comment by jcmordan** [comment]
This is the example app: 

**Call example to /api/v1/values** 
![image](https://user-images.githubusercontent.com/8495623/27336543-de86e312-559d-11e7-86fb-1030bb539d4e.png)

**Call example to /api/v1/values/2**
![image](https://user-images.githubusercontent.com/8495623/27336576-fe842c56-559d-11e7-9cad-2708e1010e6d.png)

**Call example to /api/v2/values**
![image](https://user-images.githubusercontent.com/8495623/27336605-13e7a122-559e-11e7-8480-2aaf1d29932e.png)

**Call example to /api/v2/values/2**

![image](https://user-images.githubusercontent.com/8495623/27336667-45c8b168-559e-11e7-91f5-c8963c7d645d.png)



[WebApplication1.zip](https://github.com/Microsoft/aspnet-api-versioning/files/1088366/WebApplication1.zip)

**Comment by commonsensesoftware** [comment]
I looked your example, but the approach you are trying to use will never work. You can inherit an implementation, but you cannot inherit the API version mapping. Doing so would result in ambiguous routes.

Using your method (if I understand what you are asking):
* V1.ValuesController
   * GET = `/api/v1/values`
   * GET = `/api/v1/values/1` 
* V2.ValuesController
   * GET = `/api/v1/values`
   * GET = `/api/v1/values/1`
   * GET = `/api/v2/values`
   * GET = `/api/v2/values/1` 

Using my method (as previously posted)
* V1.ValuesController
   * GET = `/api/v1/values`
   * GET = `/api/v1/values/1` 
* V2.ValuesController
   * GET = `/api/v2/values`
   * GET = `/api/v2/values/1` 

I think I understand what you're trying to solve, but admittedly I'm not a fan of using inheritance to solve this problem. Regardless, it's impossible to have more than one controller type and/or action that map to the same route and API version combination. That will result in runtime failures because they are ambiguous.

For clarity and maintenance, my suggestion would be to only use inheritance to share common functionality among all your controllers and leave the routing and API version mapping explicit per controller. If all your routes will be the same and only the implementation varies by API version, then you can use the extensions I demonstrated to realize that. Other than that, I'm not sure how you can achieve your goal.

Let me know if I've misunderstood something.

**Comment by jcmordan** [comment]
Just a few things:
Using my method:

V1.ValuesController
```
GET = /api/v1/values
GET = /api/v1/values/1
```
V2.ValuesController

```
GET = /api/v2/values /// since this actions is overiden
GET = /api/v2/values/1 /// since this action is inherited from V1.ValuesController but not overiden
```

The only way I cand reach this is overriden Get(int id) method on V2.ValuesController but jus invoking base.Get(id), something like this:

V1.ValuesController
```
namespace WebApplication1.Controllers.V1
{
    [ApiVersion("1")]
    [RoutePrefix("api/v{version:apiVersion}/values")]
    public class ValuesController : ApiController
    {
        // GET api/values
        [HttpGet]
        [Route("")]
        public virtual IEnumerable<string> Get() => new[] { "value1 v1", "value2 v1" };

        // GET api/values/5
        [HttpGet]
        [Route("{id:int}")]
        public virtual string Get(int id) => $"value{id} v1";
    }
}
```
V2.ValuesController

```
namespace WebApplication1.Controllers.V2
{
    [ApiVersion("2")]
    [RoutePrefix("api/v{version:apiVersion}/values")]
    public class ValuesController : V1.ValuesController
    {
        // GET api/values
        [Route("")]
        public override IEnumerable<string> Get() => new[] { "value1 v2", "value2 v2" };

        [Route("")]
        public virtual string Get(int id) => base.Get(id);
    }
}
```

Of course this dont look very useful, but in a real scenario the response will be a model that could be the same in each version..

**Comment by commonsensesoftware** [comment]
Correct; that will work. If you use extended **IDirectRouteProvider** I provided, you can get away with only overriding the methods; you won't have to re-specify the `[RoutePrefix]` and `[Route]` attributes. Beyond that I think you may be up against how Web API works.

My suggestion would be to make a collaborator the thing that is reused rather than the controller. IMO, it will also make it easier to rationalize what a controller implements when someone looks at the source.

For example:

```c#
namespace V1
{
  [ApiVersion( "1.0" )]
  [RoutePrefix( "api/v{version:apiVersion}/values" )]
  public class ValuesController : ApiController
  {
     readonly IRepository<Model> repository;
     public ValuesController( IRepository<Model> repository ) => this.repository = repository;

     [Route]
     public async Task<IHttpActionResult> Get() => Ok( await repository.GetAll() );

     [Route( "{id:int} " )]
     public async Task<IHttpActionResult> Get( int id ) => Ok( await repository.GetSingle( id ) );
  } 
}
namespace V2
{
  [ApiVersion( "2.0" )]
  [RoutePrefix( "api/v{version:apiVersion}/values" )]
  public class ValuesController : ApiController
  {
     readonly IRepository<Model> repository;
     public ValuesController( IRepository<Model> repository ) => this.repository = repository;

     [Route]
     public async Task<IHttpActionResult> Get() => Ok( await repository.GetAll() );

     [Route( "{id:int} " )]
     public async Task<IHttpActionResult> Get( int id ) => Ok( await repository.GetSingle( id ) );
  } 
}
```

Your repository and/or model might change between API versions or you might have multiple repositories.

Naturally, this is just one more variation of numerous possibilities. There are several solutions here that will work, but I'm not sure any of one of them individually gets you _everything_ you want. I think you're reaching the edge of what's possible without changing a significant amount of Web API plumbing.

**Comment by jcmordan** [comment]
Ok, thanks!

**Comment by irowbin** [comment]
The problem will go away if you do something like this i guess. @jcmordan 
```javascript
 [RoutePrefix( "api/v{version:apiVersion}/[controller]/[action]" )]
```

**Comment by commonsensesoftware** [comment]
Thanks for the suggestion @irowbin , but unless I'm wrong the support for the `[controller]` and `[action]` replacement tokens were added in ASP.NET Core. This context here is for Web API. Your suggestion _should_ work in Core.

**Comment by commonsensesoftware** [comment]
It seems like you have what you need @jcmordan . If you continue to run into any issues. Feel free to reopen this issue. Thanks.

**Comment by zdarovka** [comment]
This is very interesting topic! I am looking for a solution how that gives me a possibility to override just some endpoints in the version 2. I have tried to modify you solution, but it the routing of not overrided endpoint fails with this error.

No route providing a controller name with API version '2' was found to match request URI 'http://localhost:21956/api/v2/values/4'.

I am also attaching adjusted version of my desired setup
[InheritanceDemo.zip](https://github.com/Microsoft/aspnet-api-versioning/files/1489479/InheritanceDemo.zip)
