### ISSUE TITLE
How to add a new version for all controllers?

### ISSUE THREAD

**Issue by qazq** [Microsoft/aspnet-api-versioning#145]
If I have UsersController and ProductsController. The initial version is v1.0. I need to upgrade ProductsController to 2.0. If I don't add [ApiVersion("2.0")] to UsersController, the api cannot call by /api/users?api-version=2.0 (get error: "does not support the API version '2.0'."). I understand I can add [ApiVersion("2.0")] to ALL controllers, but if I have 20 controllers...
Thanks for help.

**Comment by commonsensesoftware** [comment]
It sounds like you have a scenario where you have a bunch of controllers that are the same API version.  Based on your statement, it also seems that all controllers have the same API version or at least mostly. Correct me if I'm wrong.

There isn't out-of-the-box for this type of scenario; however, the extensibility points make it pretty easy to implement. Here's a couple methods you can use:

* Use the [conventions](../wiki/API-Version-Conventions) method and apply the API versions centrally
* Use a custom attribute

It's not always clear that the framework only cares about **IApiVersionProvider**; it doesn't care about **ApiVersionAttribute**.  It just so happens that this attribute implements the interface. If you choose to use a custom attribute, then there are a couple of reasonable approaches to doing so:

* First, I recommend starting with [ApiVersionsBaseAttribute](../blob/master/src/Common/Versioning/ApiVersionsBaseAttribute.cs); it has most of what you want
* Implement **IApiVersionProvider**; you can use [ApiVersionAttribute](../blob/master/src/Common/ApiVersionAttribute.cs) as an example of how
* Define multiple API versions one of the following ways:
  * A constant, static list of known API versions for you services
  * Load from a configuration, etc. You'll probably need a _Service Locator_ for that since it's in an attribute
  * Support generating a range of API versions; optionally with a major and/or minor version step

Here's a simple example for a range:
```c#
[AttributeTargets( AttributeUsage.Class, AllowMultiple = true )]
public sealed class ApiVersionRangeAttribute : ApiVersionsBaseAttribute, IApiVersionProvider
{
  public ApiVersionRangeAttribute( int start, int end, int step = 1 ) =>
    base( GenerateRange( start, end, step ) )

  bool IApiVersionProvider.AdvertiseOnly => false;
  public bool Deprecated { get; set; }
  static ApiVersion[] GenerateRange( int start, int end, int step )
  {
     var versions = new List<ApiVersion>();
     for ( var major = start; major <= end; major += step )
     {
        versions.Add( new ApiVersion( major, 0 ) );
     }
     return versions.ToArray();
  }
}
```

The usage would look like:
```c#
[ApiVersionRange( 1, 3 )]
public class MyController { }
```

Also remember that the framework supports aggregating multiple **IApiVersionProviders** so that you can _stack_ attributes. This is useful in many ways, but in this scenario you can combine multiple ranges or even one-offs. For example:

```c#
[ApiVersion( "5.0" )]
[ApiVersionRange( 1, 3 )]
public class MyController { }
```

There's no one single _best_ way to do this and the requirements tend to be application-specific. Nevertheless, all the necessary hooks are there. I hope this gives you some ideas. Let me know if you have more questions.

**Comment by qazq** [comment]
Thanks for your swift reply.

I have a bunch of controllers. All of they support version 1.0 and 2.0. 

```cs
[ApiVersion( "1.0" )]
[ApiVersion( "2.0" )]
public class My01Controller { }

[ApiVersion( "1.0" )]
[ApiVersion( "2.0" )]
public class My02Controller { }

[ApiVersion( "1.0" )]
[ApiVersion( "2.0" )]
public class My20Controller { }
```

My clients call api by specific version

```txt
/api/{controller}?api-version=2.0
``` 

If today, I need to refactor one of a controller that return different JSON structure with version 2.0. So I modify the code and then upgrade version to 3.0.

```cs
[ApiVersion( "1.0" )]
[ApiVersion( "2.0" )]
[ApiVersion( "3.0" )]
public class My01Controller { }
```

My clients also upgrade

```txt
/api/{controller}?api-version=3.0
```

If I only add `[ApiVersion( "3.0" )]` for `My01Controller`, the client cannot work when calling `/api/My{02|03|20}?api-version=3.0` unless I add 3.0 attribute for all of controllers.

```cs
[ApiVersion( "1.0" )]
[ApiVersion( "2.0" )]
[ApiVersion( "3.0" )]
public class My01Controller { }

[ApiVersion( "1.0" )]
[ApiVersion( "2.0" )]
[ApiVersion( "3.0" )]
public class My02Controller { }

[ApiVersion( "1.0" )]
[ApiVersion( "2.0" )]
[ApiVersion( "3.0" )]
public class My20Controller { }
```
My original idea is to maintain a static version list. All the controllers check version automatically by using this list.

```cs
[AutoApiVersion]
public class My01Controller 
{ 
    public string Get() => "Hello world v1 and v2!";

    [MapToApiVersion( "3.0" )]
    public string GetV3() => "Hello world v3!";
}

[AutoApiVersion]
[ApiVersion( "1.0", Deprecated = true )]
public class My02Controller { }

[AutoApiVersion]
public class My20Controller { }
```
Make sure `/api/My{02|03|20}?api-version=3.0` can work without error.

Thanks for your suggestion. It seems I can use ` ApiVersionsBaseAttribute` to implement this idea. Is it a good implementation?

In you example, I need to change `[ApiVersionRange( 1, 2 )]` to `[ApiVersionRange( 1, 3 )]` for all controllers after I do some modifications.

My thinking is that don't change any controller source file if they no need to upgrade. Does it make sense?

Thanks

**Comment by commonsensesoftware** [comment]
Makes sense. You can definitely use a custom attribute in a variety of ways. As you're thinking, you can use the base attribute implementation to contain a static set. It doesn't even need to be a range.

The only arguable drawback is readability and understand in the source, but that's honestly up for you and/or your team to decide. If you want to apply some default API version set, you might consider something like `[StandardApiVersions]` or something like that, but the name is ultimately up to you.

One more example:

```c#
[AttributeTargets( AttributeUsage.Class, AllowMultiple = false )]
public sealed class StandardApiVersionsAttribute : ApiVersionsBaseAttribute, IApiVersionProvider
{
  public StandardApiVersionsAttribute () => base( new ApiVersion( 1, 0 ), new ApiVersion( 2, 0 ) );
  bool IApiVersionProvider.AdvertiseOnly => false;
  public bool Deprecated { get; set; }
}
```

**Comment by qazq** [comment]
I got it. Thanks!

**Comment by commonsensesoftware** [comment]
Seems like you're on your way. Come back if you have more questions. :)

**Comment by lleslie84** [comment]
Hi,
How would I automatically return the latest version for each controller? For instance.
`[ApiVersionRange(1, 3)]
	[Route("api/v{version:apiVersion}/[controller]")]
	[Route("v{version:apiVersion}/[controller]")]
	[Route("[controller]")]
	public class BaseApiController : Controller
	{

	}
	public class ThingsController : BaseApiController
	{
		[HttpGet]
		public IActionResult Get([FromBody] dynamic request)
		{
			return Ok(new List<dynamic> { new { Name = "James" } });
		}

		[HttpGet, MapToApiVersion("2.0")]
		public IActionResult PostV2([FromBody] dynamic request)
		{
			return Ok(new { Name = "James" });
		}

		[HttpGet, MapToApiVersion("3.0")]
		public IActionResult PostV3([FromBody] dynamic request)
		{
			return Ok(new { Name = "James", Company = "Test" });
		}
	}
	public class SettingsController : BaseApiController
	{
		[HttpGet]
		public IActionResult Get([FromBody] dynamic request)
		{
			return Ok(new List<dynamic> { new { Name = "James" } });
		}

		[HttpGet, MapToApiVersion("2.0")]
		public IActionResult PostV2([FromBody] dynamic request)
		{
			return Ok(new { Name = "James" });
		}
	}`
the customer would invoke the following endpoints:
http://localhost/app/v3/things
`result should be
{name: "james", company: "test"}
`
http://localhost/app/v2/things
`result should be
{name: "james"}
`
http://localhost/app/v3/settings
`result should be
{name: "james"}
`
http://localhost/app/v2/settings
`result should be
{name: "james"}
`
http://localhost/app/v1/settings
`result should be
[{name: "james"}]
`
http://localhost/app/v1/settings
`result should be
[{name: "james"}]
`
http://localhost/app/settings
`result should be
[{name: "james"}]
`

In the sample above SettingsController does not have a method corresponding to version 3. However, the latest version is returned for that controller and the default version is not returned
