### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Internal.IActionSelectorDecisionTreeProvider has been removed (preview2)

### ISSUE THREAD

**Issue by david-driscoll** [Microsoft/aspnet-api-versioning#154]
It appears that `Microsoft.AspNetCore.Mvc.Internal.IActionSelectorDecisionTreeProvider` has been removed, and causes the package to fail with the latest AspNetCore.Mvc 2.0.0-preview2-final packages.

Would be great if this was solved, for now I can work around it however. 👍

**Comment by commonsensesoftware** [comment]
Thanks for the heads up. I suppose that means I should mark the ASP.NET Core package is incompatible with 2.0+. I know there are a quite a few changes coming in 2.0+. I've only briefly had a chance to talk to the ASP.NET team about them. As soon as I have all the dust settled on the latest release here, I'll start looking into the 2.0 stuff.  Thanks again for sharing.

**Comment by pksorensen** [comment]
I can confirm that we also ran into this issue. Apps broke when upgrading to preview2 of aspnet core 2.0 due to apiversioning.

**Comment by pksorensen** [comment]
Looks like this could be relevant:

https://github.com/aspnet/Mvc/commit/e7130172d3e1c5af9f58ccfe4a20d7538b246669

https://github.com/aspnet/Mvc/issues/4802

**Comment by revocengiz** [comment]
@david-driscoll we also have the same issue. Could you tell us what is your work around?

**Comment by david-driscoll** [comment]
My work around is to remove it for the time being as we only have one versioned api in our stuff. 🤕

**Comment by commonsensesoftware** [comment]
I'll mark the next release to support >= 1.1 and < 2.0 of ASP.NET Core. I'll reach out to @rynowak  as well. We have a working relationship and I'll make sure I get things aligned for how they will change in 2.0.

**Comment by rynowak** [comment]
@commonsensesoftware it would be great if you could let us know today (or over the weekend) if you find any blocking issues. We are basically locked as of monday.

**Comment by emrahtokalak** [comment]
we have the same issue. For now, I removed the services.AddApiVersioning() in startup.

**Comment by commonsensesoftware** [comment]
I'll try integrating and making the changes for 2.0 (preview) over the long weekend. Based on my offline conversation with the ASP.NET team, I don't anticipate any big changes or surprises. I'll report back as soon as possible and perhaps with an accompanying preview packages since folks are clamoring for it.

**Comment by commonsensesoftware** [comment]
I've made the necessary changes to support **2.0.0-preview2-final**. The codebase is based on the [1.2.0](../releases/tag/v1.2.0) API Versioning release.  I've published the packages for [API Versioning](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/2.0.0-preview2-final) and the [API Explorer](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/2.0.0-preview2-final). I can't promise I'll keep things inline along the many forthcoming prereleases because I'm not sure I have the capacity for that, but I'll do my best. In the meantime, this should get folks unblocked and enable you to start playing with the bleeding edge of ASP.NET Core 2.0 with API Versioning.

Feel free to reopen this issue or post a new one if you run into any problems. Thanks.

**Comment by mejiamanuel57** [comment]
> services.AddApiVersioning(

I updated Microsoft.AspNetCore.Mvc.Versioning version and it's working.

**Comment by mejiamanuel57** [comment]
> we have the same issue. For now, I removed the services.AddApiVersioning() in startup.

I updated Microsoft.AspNetCore.Mvc.Versioning version and it's working.
