### ISSUE TITLE
Swagger sample. Why MVC services are registered twice?

### ISSUE THREAD

**Issue by ORuban** [Microsoft/aspnet-api-versioning#163]
Could you please explain the reason of using both `AddMvcCore()` and `AddMvc()` in [SwaggerSample](https://github.com/Microsoft/aspnet-api-versioning/blob/master/samples/aspnetcore/SwaggerSample/Startup.cs#L48-L50)
```
public void ConfigureServices( IServiceCollection services )
{
    ...
    services.AddMvcCore().AddVersionedApiExplorer( o => o.GroupNameFormat = "'v'VVV" );
    services.AddMvc();
    ...
}
```

**Comment by commonsensesoftware** [comment]
API Versioning only uses the _core_ NuGet package for ASP.NET Core; it doesn't use or depend on the full set of ASP.NET Core. More specifically, it doesn't need or use any of the UI components.  **UseMvcCore** is in _Microsoft.AspNetCore.Mvc.Core_, whereas **UseMvc** is in _Microsoft.AspNetCore.Mvc_.

In ASP.NET Core, the _API Explorer_ actually allows for multiple providers. Which you can follow that in the [AddApiExplorer](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ApiExplorer/DependencyInjection/MvcApiExplorerMvcCoreBuilderExtensions.cs) extension method. This comes from the  _Microsoft.AspNetCore.Mvc.ApiExplorer_ NuGet package, which the _core_ package does **not** depend on, but the _full_ package does. If you wanted the versioned API explorer without any of the UI stuff, you'd have to reference this package and change your configuration to something like:

```c#
services.AddMvcCore().AddApiExplorer().AddVersionedApiExplorer();
```

Since the _full_ package already does this inside [UseMvc](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc/MvcServiceCollectionExtensions.cs#L34), you typically don't need this call. In addition, the providers are registered with dependency injection and a declared order (by the defining types). This generally absolves you having to know or register things in the correct order. As long as things are registered at all, the _right_ thing just happens.

I hope that helps clear things up.

**Comment by ORuban** [comment]
@commonsensesoftware thanks for detailed answer. 

Yes, I see now, that methods like `AddVersionedApiExplorer` are extension methods over `IMvcCoreBuilder`, not over `IMvcBuilder` and so we cannot do something like

`services.AddMvc().AddVersionedApiExplorer( o => o.GroupNameFormat = "'v'VVV" );`
