### ISSUE TITLE
Default API version

### ISSUE THREAD

**Issue by eshenem** [Microsoft/aspnet-api-versioning#168]
Is there a way to get default API version in code? I tried ApiVersion.Default and it's always 1.0 which is not what was set in startup.cs for AddApiVersioning. Also, I have a project that has a mix of API and MVC app and I'm using ApiVersionNeutral; and those controllers with ApiVersionNeutral, Url.Action does not work.

**Comment by commonsensesoftware** [comment]
### Question 1
Is there a way to get the default API version in code?

### Answer 1
Yes. The method depends on which version of ASP.NET you are using.

#### ASP.NET Web API
```c#
public class MyController : ApiController
{
  public IHttpActionResult Get()
  {
    // from the current configuration
    var defaultApiVersion = Configuration.GetApiVersioningOptions().DefaultApiVersion;

    // from the current request
    defaultApiVersion = Request.GetApiVersioningOptions().DefaultApiVersion;

    return Ok();
  }
}


```
#### ASP.NET Core
```c#
public class MyController : Controller
{
   // provided via dependency injection
   public MyController( IOptions<ApiVersioningOptions> options )
   {
     var defaultApiVersion = options.Value.DefaultApiVersion;
   }
}
```

### Question 2
When I use a mix of API and MVC controllers, `Url.Action` does not work.

### Answer 2
You'll have to be more specific. First, which version of ASP.NET are you using? Which method of API versioning are you using? Please elaborate on what `Url.Action` _does not work_ means?

**Comment by eshenem** [comment]
Thanks for the answer. I'm using ASP.NET Core btw.

To clarify my second question, the view that has Url.Action and its controller is version neutral, I wanted the form to post data to API controller. Using Url.Action will result in null. I've moved it to the version neutral controller and the result is same. With default version set in startup.cs I was hoping it would work but it didn't.

**Comment by commonsensesoftware** [comment]
Do you have an example for your use of `Url.Action` that you can share? A barebones skeleton of the route templates, controllers, and actions would go a long way in illustrating the issue. Thanks.

**Comment by eshenem** [comment]
Sorry about the delay, attached is the zip file of the project I put together quickly to give you an example where Url.Action returns null.

[ApiAndMvcAppSample.zip](https://github.com/Microsoft/aspnet-api-versioning/files/1205523/ApiAndMvcAppSample.zip)

**Comment by commonsensesoftware** [comment]
Great! I'll take a look and report. Thanks.

**Comment by commonsensesoftware** [comment]
Based on your example, I believe you are experiencing the expected behavior.  There are a couple of reasons for this:

1. In your *.cshtml file, you are using `@Url.Action("Get", "HelloWorldApi")`
2. You have not provided a value for the **version** route parameter as defined in your route template `api/V{version:apiVersion}/[controller]`; this is not _auto-magically_ discovered
3. By not assigning a name to your route, the default name will be **Get**, which is fine for a single API version, but if you have multiple API versions I don't expect it to work; consider using explicit names (ex: "GetV1")
4. Your UI controller is version-neutral, but your APIs are version-specific, which means you cannot flow the requested API version from the UI to the API; you'll need to provide it - somehow

One solution is to have the UI always use the current API version. However, when you version by URL segment, it's more difficult to support default or otherwise implicit API versions. In order to support this scenario using a URL segment, you'll have to:

1. Allow implicit API versioning
2. Update the API version selector to choose the currently selected version
3. Define a second route on the controller the implements the current API version where the URL segment is omitted

For example:
```c#
[ApiVersion("1.0")]
[Route("api/[controller]")] // this moves to the most current controller during each version change
[Route("api/v{version:apiVersion}/[controller]")]
public class HelloWorldApiController : Controller
{
    [HttpGet]
    public IActionResult Get() => Ok(new { Message = "Hello world" });
}
````

I hope that helps. Let me know if you have more questions.

**Comment by commonsensesoftware** [comment]
It seems that you resolved your issue using my suggestion or a method of your own. Feel free to reopen this issue if things are not resolved. Thanks.
