### ISSUE TITLE
Remove Action in V3 that was available in V2

### ISSUE THREAD

**Issue by Amberg** [Microsoft/aspnet-api-versioning#172]
It is Possibly to remove an Action from version 3 that  was available in version 2 ?

I Modified the BasicODataWebApiSample:

    [ApiVersion( "1.0" )]
    [ApiVersion( "2.0" )]
    [ODataRoutePrefix( "People" )]
     public class PeopleController : ODataController
      {

        [ODataRoute("MyActionInV1AndV2")]
        public IHttpActionResult GetBoundMethod()
        {
            return Ok("Hello");
        }
        //... snip
     }
    
    public class PersonModelConfiguration : IModelConfiguration
    {
        private void ConfigureV1( ODataModelBuilder builder )
        {
            var person = ConfigureCurrent( builder );
            person.Ignore( p => p.Email );
            person.Ignore( p => p.Phone );
            person.Collection.Action("MyActionInV1AndV2").Returns<string>();
        }

        private void ConfigureV2(ODataModelBuilder builder)
        {
            var person = ConfigureCurrent(builder);
            person.Ignore(p => p.Phone);
            person.Collection.Action("MyActionInV1AndV2").Returns<string>();
        }
       // snip...
     }
     
      [ApiVersion( "3.0" )]
    [ControllerName( "People" )]
    [ODataRoutePrefix( "People" )]
    public class People2Controller : ODataController
    {
      // this Version does not contain the Action 'MyActionInV1AndV2'
     }
I would expect, that 
"http://localhost/BasicODataWebApiSample/**v1.0**/People/MyActionInV1AndV2"
is available
but not "http://localhost/BasicODataWebApiSample/**v3.0**/People/MyActionInV1AndV2"

But I get this error:

**The object has not yet been initialized. Ensure that HttpConfiguration.EnsureInitialized() is called in the application's startup code after all other initialization code.**

> bei System.Web.OData.Routing.Conventions.AttributeRoutingConvention.get_AttributeMappings()
   bei System.Web.OData.Routing.Conventions.AttributeRoutingConvention.SelectController(ODataPath odataPath, HttpRequestMessage request)
   bei System.Web.OData.Routing.ODataPathRouteConstraint.SelectControllerName(ODataPath path, HttpRequestMessage request)
   bei System.Web.OData.Routing.ODataPathRouteConstraint.Match(HttpRequestMessage request, IHttpRoute route, String parameterName, IDictionary`2 values, HttpRouteDirection routeDirection)
   bei Microsoft.Web.OData.Routing.VersionedODataPathRouteConstraint.Match(HttpRequestMessage request, IHttpRoute route, String parameterName, IDictionary`2 values, HttpRouteDirection routeDirection)
   bei System.Web.Http.Routing.HttpRoute.ProcessConstraint(HttpRequestMessage request, Object constraint, String parameterName, HttpRouteValueDictionary values, HttpRouteDirection routeDirection)
   bei System.Web.Http.Routing.HttpRoute.ProcessConstraints(HttpRequestMessage request, HttpRouteValueDictionary values, HttpRouteDirection routeDirection)
   bei System.Web.Http.Routing.HttpRoute.GetRouteData(String virtualPathRoot, HttpRequestMessage request)
   bei System.Web.Http.HttpRouteCollection.GetRouteData(HttpRequestMessage request)
   bei System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   bei System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   bei System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()

**Comment by commonsensesoftware** [comment]
First, the issue is that OData is failing to build out the route templates using the defined attributes. If you start by navigating to the root of the site, you should see the following error:

>_The path template 'People/MyActionInV1AndV2' on the action 'MyActionInV1AndV2' in controller 'People' is not a valid OData path template. The request URI is not valid. Since the segment 'People' refers to a collection, this must be the last segment in the request URI or it must be followed by an function or action that can be bound to it otherwise all intermediate segments must refer to a single resource._

I can't explain why the route template doesn't work. I didn't see anything wrong with it and, honestly, I was stumped by the error the same as you. I reviewed the [Supporting OData Actions](https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/odata-v3/odata-actions) topic on MSDN. For whatever reason, the `[ODataRoute]` attribute is **not** applied to OData actions. Perhaps they aren't supported for actions. I can't say for sure.  I can confirm, however, that the following works when put in **PeopleController.cs**, but not in **People2Controller.cs**:

```c#
[HttpPost]
public IHttpActionResult MyActionInV1AndV2() => Ok( "Hello" );
```

Here's the results:

```http
POST http://localhost:4129/v2/People/MyActionInV1AndV2
Host: localhost:4129
```
```http
HTTP/1.1 200 OK
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true
api-supported-versions: 1.0, 2.0, 3.0
OData-Version: 4.0
Content-Length: 82

{"@odata.context":"http://localhost:4129/v2/$metadata#Edm.String","value":"Hello"}
```

```http
POST http://localhost:4129/v3/People/MyActionInV1AndV2
Host: localhost:4129
```
```http
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true
OData-Version: 4.0
Content-Length: 353

{
  "error": {
    "code": "UnsupportedApiVersion",
    "message": "The requested resource with API version '3' does not support HTTP method 'POST'.",
    "innererror": {
      "message": "No route providing a controller name with API version '3' was found to match HTTP method 'POST' and request URI 'http://localhost:4129/v3/People/MyActionInV1AndV2'.",
      "type": "",
      "stacktrace": ""
    }
  }
}
```

You get 405 because there are no other supported POST operations in V3. Had there been at least one other POST operation, you would instead get 400. The message and error code are the same however. This response is the expected behavior.

I'm not sure why this is happening. It would appear to be more of an issue with the OData support for Web API since the versioning libraries do not get involved with routing. This may be the result of how OData generates the route templates. Despite supporting _attribute routing_, it's a bit of a misnomer in the OData libraries. Under the hood, the OData libraries still use convention-based routing. The attributes are used to build the underlying route templates. Perhaps you cannot specify an explicit action name. Regardless, simply removing the `[ODataRoute]` attribute on the action seems to make everything work.

I hope that helps.

**Comment by Amberg** [comment]
Thx .. I'll avoid [ODataRoute] in future
