### ISSUE TITLE
Plans/roadmap of .NET Core 2 Support?

### ISSUE THREAD

**Issue by dudleycodes** [Microsoft/aspnet-api-versioning#175]
Kicking the .NET Core 2 tires and noticed this library requires `Microsoft.AspNetCore.Mvc.Core < 2.0.0`.

Are there plans for 2.0.0+ support?

**Comment by commonsensesoftware** [comment]
There is. There was a request for support during the preview, which is officially published to NuGet (as prerelease package). Looks like 2.0.0 was officially released on Friday. I'll carve out some time to get the official support out this week. Thanks for the heads up.

**Comment by joeangry** [comment]
I look forward to it. This is the only dependency that needs to go RTM before we can switch to .NET Core 2.0 completely.

**Comment by raRaRa** [comment]
@commonsensesoftware That's great to hear! Any updates? 😃

**Comment by commonsensesoftware** [comment]
Sorry guys, I was out of town this last weekend. Despite the celestial event yesterday, I wasn't in the path of totality and the stars only reached 85% alignment. =P

I ran into a few tooling issues with the update to VS2017 15.3 and .NET SDK 2.0. The build is working, but the test coverage is incomplete. I'm things will probably work, but I'd rather not blindly publish an official release without 100% verification.

I expect this should only take another day or two. I'll post back to this thread once the package has been published. I know everyone is excited to move to 2.0. Thanks for your patience.

**Comment by raRaRa** [comment]
👂

**Comment by 206mph** [comment]
I'm anxious for the new version too! Any updates?

**Comment by rwgridstone** [comment]
Looking forward to .Net Core 2 support. Keep up the good work.

**Comment by commonsensesoftware** [comment]
I know many of you have been champing at the bit.  Hold your breath ... wait for it ... Are you blue yet? =P

I finally have everything working the way it should. There were a number of landmines to navigate that were more tooling changes due to .NET Standard 2.0 and Visual Studio than ASP.NET Core. I'm happy to report that I've resolved the last of the issues and everything builds and passes the tests the way that it should. :)

**The new packages will be published today!** I'm preparing the packages and release notes as we speak.
 You can expect to see things in about an hour or so. I'll post back here one final time before I close it out to let you know that the packages are available.

**Comment by commonsensesoftware** [comment]
v2.0 is officially out.

* [Release notes](../releases/tag/v2.0.0)
* [API Versioning package](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/2.0.0)
* [API Explorer package](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer/2.0.0)

**Comment by fisenkodv** [comment]
@commonsensesoftware Thank you so much!
