### ISSUE TITLE
No controllers matches after upgrading to 2.0

### ISSUE THREAD

**Issue by heapx** [Microsoft/aspnet-api-versioning#180]
After upgrading to 2.0 none of our controllers matches. After some debugging in turns out that the presence of a terminating handler causes the problem. 

Minimal repro

`donet new webapi`

with 

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddMvc();
    services.AddApiVersioning();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseMvc();
    app.Run(async (context) =>
    {
        await context.Response.WriteAsync("test");
    });
}
```

and then hitting the default controller at `/api/values`.

Removing either the `Run` or `AddApiVersioning` calls causes the controller action to be invoked, otherwise "test" is displayed. Maybe we are using the framework wrong and this is the intended behavior, but it was really convenient to have that `Run` call at the end of the pipeline, so it would be great to hear of any workarounds if they exist.

**Comment by commonsensesoftware** [comment]
Are you upgrading from 1.0 or 1.1/1.2? 1.1+ introduced a behavioral change that may be causing this. `AddApiVersioning` now injects a special router to the end of the pipeline. This is required to solve a different issue/limitation in ASP.NET Core itself where the **IActionSelector** might be called multiple times. Since an API versioning policy can not be fully applied until all of the candidates are considered, there needs to be a way to capture all passes and make a decision at the end (there's also some internal optimization).

I'm not sure if this behavior is compatible with `Run`, but it's definitely compatible with other middleware and routers. For example, things still work with the SPA fallback extensions.

**Comment by heapx** [comment]
Upgrading from 1.1. Ok, I see, thank you, I'll look into the fallback extensions.

**Comment by commonsensesoftware** [comment]
Ah ... that could be it. In 1.1, you had to register things manually in `UseApiVersioning`. This caused lot of confusion and issues, including not calling it at all or the way it was ordered. 1.2 solved this issue and made the process automatic after `AddApiVersioning` once again. There are no changes to this behavior in 2.0.

What exactly are you hoping to achieve in using `Run`? If there are no candidates, you _should_ get 404. If there are possible candidates, then you'll get 2xx on success or 400/405 for an unsupported API version. There _should_ only be a terminating handler when there  is at least one possible candidate for any API version of the requested URL.

Perhaps a formal middleware introduced into the pipeline will get you more of what your looking for?

**Comment by heapx** [comment]
Essentially, `Run` checked whether the path started with /api, if so return 404. Otherwise return "index.html" and let the client handle it. We can address this as you say by inserting middleware into the pipeline before mvc. I'll go ahead and close this, appreciate the assistance.
