### ISSUE TITLE
Unable to upgrade to Microsoft.Aspnet.WebApi.Versioning 2.1.0.0 from .net framework 4.5

### ISSUE THREAD

**Issue by d-saravanan** [Microsoft/aspnet-api-versioning#186]
While upgrading to Microsoft.Aspnet.WebApi.Versioning 2.1.0.0 , I am getting the following error,
Method not found: 'Void Microsoft.Web.Http.Versioning.Conventions.ApiVersionConventionBuilder.ApplyTo(System.Web.Http.Controllers.HttpControllerDescriptor)'.

Kindly suggest the fix

**Comment by d-saravanan** [comment]
Also, note that when we are using OData in parallel with WebApi, we are getting no response / UnSupportedApiVersion when we hit the Web Api, whereas the OData calls succeeds without any issue for all versions, is there something else to be done to enable both OData and WebAPI in a single project for versioning

**Comment by d-saravanan** [comment]
Also, please share the source code / branch for 2.0.3 so that, we can try to debug and see whats our issue

**Comment by commonsensesoftware** [comment]
I don't have a lot of details here, but based on what you've stated so far, I'm going to take a shot at it. It would appear that you may be extending the conventions features. This is totally a supported scenario. The return value of **ApplyTo** changed from `void` to `bool` back in **1.1 - Beta 1** (see the [release notes](../releases/tag/v1.1.0-beta1)).

The motivation behind the change was to improve extensibility and usage. The implementation may not apply any conventions as is evident on [ApiVersionConventionBuilder.cs (Line 60)](../blob/master/src/Microsoft.AspNet.WebApi.Versioning/Versioning/Conventions/ApiVersionConventionBuilder.cs#L60). This minor, but breaking, change allows callers and extenders to know whether any conventions were actually applied.  I suspect that if you change the return type from `void` to `bool`, you'll be back in business.

**Comment by commonsensesoftware** [comment]
You can definitely mix OData and Web API together. There are, however, some limitations. Have you already read the [OData Protocol Transitions](../wiki/OData-Protocol-Transitions) wiki topic? It describes the limitations and what you need to do in order to make things work. There is also a sample project that demonstrates this scenario. The link to it is in the wiki topic as well.

The short, short answer is that you should only use convention-based routing if you mix OData and Web API. This is the only guaranteed way that you can mix and match. If you use attribute-based routing for Web API, you might hit a scenario where things don't work as expected. It's a limitation of Web API.

**Comment by commonsensesoftware** [comment]
I don't create a full release every time there is a bug fix; however, I do make sure that I include the corresponding issue so that you can track it down. The commit that corresponds to the 2.0.3 package release is [94d7f8c](../commit/94d7f8cd7670bd0df37244f774bc7f6db3fd3e53). I hope that helps.

**Comment by d-saravanan** [comment]
Thank you very much for your faster response. I figured out the issue, the issue was due to the usage of the Route directly on the Controller and not on the action methods.
**Example**
The below ones were failing with the UnSupportedApiVersion error.
[RoutePrefix("api/testapi")]
public class TestApiController: ApiController
{
     public IHttpActionResult Get() => Ok("success");
}
However, the following passed without any errors
[RoutePrefix("api")]
public class TestApiController: ApiController
{
     [Route("testapi")]
     public IHttpActionResult Get() => Ok("success");
}

I tried this in a sample and got it working. However, need to try out with the main source code. Can you please explain how the routes are picked up by this implementation to choose the right action method so that it can be of great help. In case you do not have time, I am planning to draft a flow for this process over this weekend, I can prepare and share :)

**Comment by commonsensesoftware** [comment]
The routing infrastructure in Web API has not really been changed. The implementation has been forked from the original source and that is only because the required hooks and extensibility points do not exist to implement API versioning.

The flow has always been to match convention-based routes first and then _direct routes_ (aka attribute-based routing). Remember that attribute-routing was bolted on way after the fact. The attribute method really just pre-registers some route templates. API versioning doesn't change any of these behaviors. The thing that changes is how ambiguous matches are handled. In vanilla Web API, duplicate routes would be considered ambiguous and an exception would be thrown, resulting in a 500. API versioning injects an additional level of disambiguation and controller resolution by considering an API version. An API version never plays a direct role in routing. It's role is purely as a discriminator for the candidate routes. The API version can also act as a discriminator for actions when different versions of an action are interleaved on a single controller.

Mixing attribute-based and convention-based routing can be very confusing. I always recommend choosing one or the other. While mixing the two are supported by API versioning, it's in a limited capacity. There are some scenarios of mixing that will just not work due to limitations in Web API. Specifically, you cannot switch methods for a particular controller or any overlapping routes for that matter. You didn't specify which one you're using, but from what I see above, you are at least using attribute-based routing.

From your example, I would **not** expect the first example to work.
* `[RoutePrefix("api/testapi")]` only defines a prefix; it doesn't define a route
* No route has been defined

The second option works because you have a route and a prefix. It appears you were trying to avoid having to repeat the route templates. To achieve that, a more succinct approach would be:

```c#
[RoutePrefix( "api/testapi" )]
public class TestApiController : ApiController
{
  [Route]
  public IHttpActionResult Get() => Ok("Success");
}
```

If you're really interested in spelunking into the code, you want to look in the following namespaces:
* [Controllers](../tree/master/src/Microsoft.AspNet.WebApi.Versioning/Controllers)
* [Dispatcher](../tree/master/src/Microsoft.AspNet.WebApi.Versioning/Dispatcher)

The replaced services are **IHttpControllerSelector** and **IHttpActionSelector**, which are called by the Web API routing infrastructure. I hope that helps.

**Comment by d-saravanan** [comment]
Thank you very much for the detailed response.
** I am restating what I understand, can you please validate and correct if I am wrong **

 I hope that this would serve as a good discussion for any one that is implementing API Versioning. Kindly note that, as you said, we are using both the convention based routing and attribute routing like the one given below,

```
    public class RolesController : BaseODataController
    {
	[EnableQuery]
        public SingleResult<Role> GetRole([FromODataUri] long key) { .... }

        [ODataRoute("Roles({RoleId})")]
        public async Task<IHttpActionResult> DeleteRole([FromODataUri] long RoleId, ..) {...}
    }
```
From your detailed description of the routing used, I infer that the above scenario is most likely to fail because we are registering the convention in the webapiconfig like
```
config.MapVersionedODataRoutes("odata-by-path", "odata/v{apiVersion}", models, odataBatchHandler);
```
and then trying to use the attribute-routing on the specific action methods like the ```DeleteRole``` given above.  This in my understanding would help resolve the issue #193

**Comment by commonsensesoftware** [comment]
Have you reviewed the [Advanced OData Web API Sample](../blob/master/samples/webapi/AdvancedODataWebApiSample)? That example demonstrates how _protocol transition_ to and from OData works. You'll notice in the [Startup.cs](../blob/master/samples/webapi/AdvancedODataWebApiSample/Startup.cs) that there is no registration of `MapAttributeRoutes`.  All the routes are convention-based.

Looks like you're preparing a repro for #193. Once I look at that, I'll correlate the two so we get things working.

**Comment by commonsensesoftware** [comment]
Are you unblocked on this issue? It seems that you are still using OData 5.9.x. I may have accidently broke something during one of the revisions of the main API versioning package. I thought I left OData 5.9.x behind, but if you need it, I can create a backward `2.0.2` version to support it. Thanks.

**Comment by d-saravanan** [comment]
Thanks for your update. 

We are currently focussed on moving forward with the versioning changes made so far, further there are plans for upgrade to .net 4.7 which should help to move from 2.0.1.0 to 2.1.0.0 and that should give us a good progress.

**Comment by commonsensesoftware** [comment]
Seems like you are on your way. Let me know if you encounter any additional issues.
