### ISSUE TITLE
Route does not match for the ODataRoute and returns 404

### ISSUE THREAD

**Issue by d-saravanan** [Microsoft/aspnet-api-versioning#192]
I have the following code model in the ODataController and WebApiConfig.cs where the webapi and OData controllers are registered and used.

```
[ApiAuthorize]
public class RolesController : BaseODataController
{
        [EnableQuery]
        [ODataRoute("Roles({RoleId})/UserRoles")]
        public IQueryable<UserRole> GetUserRoles([FromODataUri] long RoleId)
	{
	//implementation goes here...
	}
}

**WebApiConfig.cs**

var constraintResolver = new DefaultInlineConstraintResolver() { ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) } };
// Web API routes
config.MapHttpAttributeRoutes(constraintResolver);

config.AddApiVersioning((vo) =>
{
    vo.ReportApiVersions = true;
    vo.DefaultApiVersion = new ApiVersion(1, 0);
    vo.AssumeDefaultVersionWhenUnspecified = true;
});

var modelBuilder = new VersionedODataModelBuilder(config);
modelBuilder.ModelConfigurations.Add(new MyModelConfiguration());
var models = modelBuilder.GetEdmModels();

config.MapVersionedODataRoutes("odata-wo-prefix", "", models, odataBatchHandler);
config.MapVersionedODataRoutes("odata-only-version-path", "v{apiVersion}", models, odataBatchHandler);
config.MapVersionedODataRoutes("odata-by-path", "odata/v{apiVersion}", models, odataBatchHandler);
config.MapVersionedODataRoutes("odata", "odata", models, odataBatchHandler);

config.AddODataQueryFilter();

```

However, when I access the above api using postmane like

> http://localhost:65314/odata/v1/Roles(47)/UserRoles

The response is a 404. I did try using /odata/v1/Roles, /Roles, /OData/Roles etc, but all in vain. I am not getting back the proper response [nothing but 404].

Kindly help me understand the routing to be happening in this case, Also if possible, can you please share some debugging techniques for version 2.0.1 like adding some overloads where the registered routes can be checked by leaving a breakpoint, or else dumping some data in the Output window for analysis. We kind of find it like a blackbox and couldn't figure out the exact way to resolve the issues. Some doumentation on how the routes are internally registered or matched will be of very great help to us.

Please do the needful.

**Comment by d-saravanan** [comment]
Further, to reproduce this issue, please use the following code snippet at the end of the People2Controller  the AdvancedODataWebApiSample project.

```
[ODataRoute("({data})/somedata")]
public IHttpActionResult GetSampleData([FromODataUri]string data) => Ok(data);
```

In case you need more details, I can even share the code here for your reference

**Comment by commonsensesoftware** [comment]
There's a lot going on here. Let's make sure we have the basics sorted out and then dive into the details. First, are you using regular Web API controllers in addition to OData? If not, then you don't need:

```c#
**WebApiConfig.cs**

var constraintResolver = new DefaultInlineConstraintResolver() { ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) } };
// Web API routes
config.MapHttpAttributeRoutes(constraintResolver);
```

In fact, you **don't** want it. OData uses convention-based routes despite the existence of _OData routing attributes_. Convention-based and attribute-based routes don't play well together in all cases. I always recommend choosing one or the other. Since your using OData, the decision is made for you. I recommend that you only use convention-based routes in your application.

It looks like you are trying to implement API versioning using a URL segment.  I recommend query string or media type, but it's your choice. You may be having an issue with routing because you have overlapping route templates. The router considers the registered routes in order. I show both in the examples **purely** for illustration purposes and so I don't have to create two separate projects. You should chose single API versioning strategy. 

To register by URL segment, the following should be the **only** registration required:
```c#
config.MapVersionedODataRoutes("odata-by-path", "v{apiVersion}", models, odataBatchHandler);
```

You can add an additional prefix such as `api/` or `odata/` if you like. I suspect if comment out or remove the other route registrations, things may just start working.

Finally, do you have a navigation property defined for `/UserRoles` on the _Roles_ entity? A 404 may be happening simply because OData doesn't know how to route the request. Keep in mind that API versioning is just letting you define a standard OData route multiple times and then disambiguating the implementation to select by API version. If you haven't already, you might want to validate the route works without API versioning enabled.

Let me know where that gets you and we'll investigate further.

**Comment by commonsensesoftware** [comment]
Is this issue resolved now? This seems related to some other issues you've posted.

**Comment by commonsensesoftware** [comment]
I have the impression you were able to resolve this issue. If you continue to encounter issues, feel free to come back or reopen the issue. Thanks.
