### ISSUE TITLE
Consider to return camelCase error messages

### ISSUE THREAD

**Issue by hikalkan** [Microsoft/aspnet-api-versioning#195]
Instead of

````js
{
  "Error": {
    "Code": "UnsupportedApiVersion",
    "Message": "The HTTP resource that matches the request URI..."
  }
}
````

return this:

````js
{
  "error": {
    "code": "UnsupportedApiVersion",
    "message": "The HTTP resource that matches the request URI..."
  }
}
````

Because it's more natural for javascript clients and ASP.NET Core team also use camelCase.

Or is there any configuration?

**Comment by hikalkan** [comment]
I support we can override default behavior:

````C#
services.AddApiVersioning(o =>
{
    o.ErrorResponses = //create a class implements IErrorResponseProvider
});
````

**Comment by commonsensesoftware** [comment]
Thanks for bringing this to my attention. I didn't realize that the default JSON settings in ASP.NET Core had changed. In ASP.NET Web API, the error messages are based on the **HttpError** class. Ultimately, this class was just a basic extension of **Dictionary<string, object>**. As a result, the ASP.NET Core **DefaultErrorResponseProvider** uses a simple dictionary to generate the error response content. Unfortunately, the new, default JSON settings in ASP.NET Core does not apply to dictionaries (intentionally). There are number of issues and discussions in the ASP.NET repo about this.

To achieve your desired result, you just need to change your setup like this:
```c#
services.AddMvc()
        .AddJsonOptions( o => 
            o.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver() );
```

This should work _as is_ today. The error responses, however, are still inconsistent with the default JSON serialization behavior so it's worth changing the way responses are generated. I'll update the implementation to return an object instead of a dictionary to provide the content. This will achieve parity with the default serialization behavior.

One final note. The _enhancement_ to align serialization behavior will result in one small side effect. Null values are returned in JSON with the default settings. To suppress this, you'll still need to change the default JSON settings, but it will apply to the entire ASP.NET Core application.

```c#
services.AddMvc()
        .AddJsonOptions( o => o.SerializerSettings.NullValueHandling = NullValueHandling.Ignore );
```

I find this to be a negligible compromise.

**Comment by hikalkan** [comment]
> I'll update the implementation to return an object instead of a dictionary to provide the content

That would be great. Thanks.
