### ISSUE TITLE
Handling of minor version increments.

### ISSUE THREAD

**Issue by Mike-Farquhar** [Microsoft/aspnet-api-versioning#205]
Hi,

I'm currently working on an API that ends up being added to on a regular basis but never with any breaking changes. Even though, we want to keep returning resources in their original form for each API Minor version, eg:

```C#
[ApiVersion("1.0")]
[ApiVersion("1.1")]
[ApiVersion("1.2")]
[RoutePrefix("api")]
public class ApiRootController : ApiController
{
  // v1.0 resource.
  [HttpGet, Route("myresource")]
  public HttpResponseMessage GetMyResource()
  {
    return Request.CreateResponse(HttpStatusCode.OK, new MyResourceModel { Message = "Hello!" });
  }

  // v1.1 resource
  [HttpGet, Route("myresource"), MapToApiVersion("1.1")]
  public HttpResponseMessage GetMyResourceV1_1()
  {
    return Request.CreateResponse(HttpStatusCode.OK, new MyResourceModel { Message = "Hello!", User = "Mike" });
  }

  // available from v1.2.
  [HttpGet, Route("myresource"), MapToApiVersion("1.2")]
  public HttpResponseMessage GetSomeOtherResource()
  {
    return Request.CreateResponse(HttpStatusCode.OK, new AnotherResourceModel { AppleCount = 5 });
  }
}
```

When I call "api/myresource?api-version=1.0" I get the original v1.0 version of the resource as expected.
When I call "api/myresource?api-version=1.1" I get the v1.1 version of the resource as expected.
When I call "api/myresource?api-version=1.2" suddenly I get the v1.0 resource, which was not expected.

I guess what I'm asking is is there a way to make the route match to the closest available Minor version <= the requested Minor version?

Thanks,
Mike

**Comment by commonsensesoftware** [comment]
The selection of an API version needs to provide an unambiguous value so that the infrastructure can select the correct action to dispatch to. There are ways to choose the _best_ API version when no API version is selected, but this facility is not used in other scenarios.

Succinctly, I'd say there are two ways to think about a client's request:
* No API version is provided (assuming it's even allowed by the service)
   * The client doesn't care which version they get
   * The server might have a policy that chooses a fixed version, lowest version, highest version, etc
* An explicit API version is specified

When a client specifies an API version, matching anything other than what they asked for is a bad idea IMO. With some customization, it would be possible for a client to ask for multiple API versions that you could choose from, but I don't think that's what you're asking for. It would behave like the **Accept** header. It is also possible to add support version ranges that map to controllers and/or actions, but - again - I'm not sure that's what you're looking for.

I'm assuming that you're using the latest package version. I created a basic sample (see attached) to simulate your scenario, but I could not reproduce the behavior you described. The respective requests to 1.0, 1.1, and 1.2 all produced the expected results. Hopefully, that might help you reconcile any differences from other parts of your configuration.

[ApiMinorVersionRepro.zip](https://github.com/Microsoft/aspnet-api-versioning/files/1402693/ApiMinorVersionRepro.zip)

**Comment by Mike-Farquhar** [comment]
Ah, my apologies, I'm stuck using VS 2013 / .net 4.5, but I made a mistake in the last route of the the above code. What I meant to write was:

```
// available from v1.2.
[HttpGet, Route("my-other-resource"), MapToApiVersion("1.2")]
public HttpResponseMessage GetSomeOtherResource()
{
  return Request.CreateResponse(HttpStatusCode.OK, new AnotherResourceModel { AppleCount = 5 });
}
```

So when you call the "api/myresource" route with a v1.2 query you get the v1.0 result rather than the v1.1 result. I don't know maybe I'm thinking about this all wrong...

**Comment by commonsensesoftware** [comment]
Interesting ... I was able to reproduce your scenario. All of the routes behave as expected **except** for the `api/my-other-resource?api-version=1.2`. This _may_ be a bug. I'll look into it and see what I find.

**Comment by commonsensesoftware** [comment]
OK ... sorry for the delay. Upon looking into the issue, the behavior is by design. I'm not sure how I didn't notice it right away. I guess it was the due to the update between the original post and the subsequent update. 

Now for the explanation...

Ultimately, this is a product of _version interleaving_.  By default, you only need to specify the API version at the controller level. **All** actions implicitly match the API versions defined by the controller. Just like controllers with overlapping routes are disambiguated by API version, so too are actions. At the action level, we use the `MapToApiVersion` to indicate an explicit mapping by API version.

In your controller, the `GetMyResource` method does not have any explicit API version mapping. This means that all API versions will match this action unless there is another action with the same route and explicit API version. The following table summarizes the matches:

| Route | Action | API Versions |
| ------ | ------- | -------------- |
| api/myresource | GetMyResource | 1.0 [implicit], 1.2 [implicit] |
| api/myresource | GetMyResourceV1_1 | 1.1 [explicit] |
| api/my-other-resource | GetSomeOtherResource | 1.2 [explicit] |

To get the behavior I believe you're hoping for, you need to decorate `GetMyResource` with `[MapToApiVersion( "1.0" )]`.

Version interleaving can be difficult to rationalize over time if there is a lot of complex mapping. The intent of supporting it all is for services that add only few extra actions that are available in the later versions. This type of additive approach tends to not be overly complex from a management perspective. For all other cases, it's probably better to break the controllers into multiple types.

I hope that clarifies things for you. Let me know if you have more questions or need additional assistance.

**Comment by Mike-Farquhar** [comment]
Thanks for looking into it, I hadn't thought of making the original route version explicit but that does indeed provide the expected behaviour. :)
