### ISSUE TITLE
Why is ODataRoutePrefix necessary?

### ISSUE THREAD

**Issue by bdebaere** [Microsoft/aspnet-api-versioning#209]
Hi,

I was wondering why ODataRoutePrefix is necessary when using versioning for OData. Can't this value be determined by convention?

I have two controllers like below, version 1 and version 2.
```
[ApiVersion("1.0")]
[ODataRoutePrefix("Customers")]
public class CustomersController : ODataController
{
}
```

When I remove the ODataRoutePrefix line, the code no longer works. With the following error which doesn't even seem related.
The path template '({key})' on the action 'Get' in controller 'Customers' is not a valid OData path template. Empty segment encountered in request URL. Please make sure that a valid request URL is specified.

**Comment by commonsensesoftware** [comment]
API versioning doesn't make any changes to routing. Using attribute routing of any kind is not required with OData or otherwise. Attribute routing tends to be the more prolific form of routing now and also tends to easier to convey intent in examples. I use attribute routing in most of my examples (I believe), but it's by no means a requirement.

In order to help you further, I'd need to see the action for the route you are trying to define. It might also help if you can share/show the configuration bits relevant to OData and API Versioning (usually in WebApiConfig.cs).

**Comment by bdebaere** [comment]
@commonsensesoftware Thank you for your response. Taking the code from SwaggerODataWebApiSample in your samples. If you remove the ODataRoutePrefix attribute, Swagger will give the error I specified earlier on:

```
        httpConfiguration.EnableSwagger(
                    "{apiVersion}/swagger",
                    swagger =>
                    {
                        // Build a swagger document and endpoint for each discovered API version.
                        swagger.MultipleApiVersions(
                            (description, version) => description.GetGroupName() == version,
                            info =>
                            {
                                **foreach (ApiDescriptionGroup group in apiExplorer.ApiDescriptions)**
                                {
                                    if (group.IsDeprecated)
                                    {
                                        apiDescription += " This version has been deprecated!";
                                    }

                                    info.Version(group.Name, $"{apiName} {group.ApiVersion}")
                                        .Description(apiDescription);
                                }
                            });
                    })
                .EnableSwaggerUi(swagger => swagger.EnableDiscoveryUrlSelector());
```

**Comment by bdebaere** [comment]
Any update here?

**Comment by commonsensesoftware** [comment]
Apologies, it seems I missed your reply. I'll take a look at this. On the surface, this looks ok to me. Can you share your Web API and OData configuration too? Thanks

**Comment by bdebaere** [comment]
@commonsensesoftware I'm not completely sure what you are requesting. But I basically followed the SwaggerODataWebApiSample.

```
            httpConfiguration
                .Count()
                .Filter()
                .OrderBy()
                .Expand()
                .Select()
                .MaxTop(null);

            httpConfiguration.AddApiVersioning(
                    setting =>
                    {
                        setting.AssumeDefaultVersionWhenUnspecified = true;
                        // This assumes the default to be the first version.
                        // TODO: the alternative is o => o.ApiVersionSelector = new CurrentImplementationApiVersionSelector(o)
                        setting.DefaultApiVersion = ApiVersion.Default;
                        // Adds HTTP headers "api-supported-versions" and "api-deprecated-versions" to the response.
                        setting.ReportApiVersions = true;
                    }
            );

            VersionedODataModelBuilder modelBuilder = new VersionedODataModelBuilder(httpConfiguration)
            {
                ModelBuilderFactory = () => new ODataConventionModelBuilder(),
                ModelConfigurations = { modelConfiguration }
            };  

            List<IEdmModel> models = modelBuilder.GetEdmModels().ToList();

            httpConfiguration.MapVersionedODataRoutes("odata", "", models, EnableUnqualifiedCaseInsensitiveUri);
            httpConfiguration.MapVersionedODataRoutes("odata-bypath", "v{apiVersion}", models, EnableUnqualifiedCaseInsensitiveUri);

        private static void EnableUnqualifiedCaseInsensitiveUri(IContainerBuilder containerBuilder)
        {
            containerBuilder.AddService(ServiceLifetime.Singleton, typeof(ODataUriResolver), sp => new UnqualifiedCaseInsensitiveUriResolver());
        }
```

**Comment by bdebaere** [comment]
@commonsensesoftware Hi, do you have any update?

**Comment by commonsensesoftware** [comment]
It's unclear to me if you are trying route by convention or using attributes. To my knowledge, OData will let you mix and match, but it doesn't _fill in the blanks_ if you don't provide all of the attributes. You either provide all of the attributes or none of them.

In your scenario, since you've applied the `[ODataRoute]` attribute to your routes, you need to do one of the following:
* Add the entity set name to your routes (ex: `[ODataRoute("Customers")]`)
* Add the `[ODataRoutePrefix("Customers")]` to your controller so you don't need to repeat the prefix for the route on each action

Now, if you want to route purely by convention, that is meant to be a supported scenario. However, in putting together an example for you, I found a bug. You can track it in issue #226. The bug only affects convention-only routing. I likely missed this scenario for Swagger since attribute routing is far more popular.

**Comment by bdebaere** [comment]
@commonsensesoftware Routing by convention (CustomersController => Customers) is something I would always prefer.

I originally added the [ODataRoute] attribute to my GET functions because Swagger was complaining with the following error message

> 500 : {"Message":"An error has occurred.","ExceptionMessage":"Not supported by Swagger 2.0: Multiple operations with path 'Customers' and method 'GET'. See the config setting - \"ResolveConflictingActions\" for a potential workaround"

Is there a way to have both routing by convention and Swagger to work properly?

**Comment by commonsensesoftware** [comment]
Apologies for the delay, there were a lot of little issues of resolve. A new version of the packages are now available. I've also update the OData Swagger example, which demonstrates the "Orders" service using attribute-routing and the "People" service using convention-routing.  I've also thrown in a few functions and actions to show off new features. Let me know if you have any questions.

**Comment by bdebaere** [comment]
@commonsensesoftware Why is routing by convention the least popular? I assume it is less work and prevents issues with naming from happening for example where your route attribute differs from the name of your controller. Am I wrong to prefer convention based routing?

You will never get the error I had because you only have one GET method in your controller in your samples. If you add a Get(int key) you will receive the error that I mentioned if you use the previous version of aspnet-api-versioning.

I assume you just pushed the update to the ApiExplorer NuGet packages. I can use convention based routing since I updated my packages.

**Comment by commonsensesoftware** [comment]
Yes - the packages are pushed. Both attribute and convention-based routing should work.

Attribute-based routing over convention-based routing isn't about how much code you have to write. Partially, it's a preference. OData, however, does have a few other considerations.

First, there are a few things that can still **only** be done with attribute routing (as I recall). For example, the number of segments in a path are strict when using conventions. There used to be other limitations such as composite keys that could only be done with attribute routing. Many of these design inconsistencies have been addressed in the latest releases of the OData libraries, but I think there may still be a few gaps.

The larger rationale for attribute-based routing is knowing what the _convention_ actually is. I've found that many developers do not know what the basic OData conventions are nor how they are realized in OData. Unless you've been working with OData and Web API for while, you'll unlikely to know these. For example, most developers probably don't know that the **key** route parameter must be defined as `({key})` in their route templates and action parameter names. The documentation will illustrate this in examples, but it doesn't really tell you that you **must** do this. This requirement doesn't apply to attribute routing. This can cause frustration because it's quite common to use `({id})`. It's not obvious that will not work using conventions. I know I've pulled my hair out more than once trying to figure out why my route wasn't matching because my action declared `Get(string id)` instead of `Get(string key)`.

Finally, attribute routing removes any ambiguity about what the route and/or convention will be. It's declared inline with the controller definition. If you're an OData guru or work as an army of one, this may not have much value. If you work in a larger team, especially one that may not have a lot of OData experts, then attribute routing tends to help understand routing better.

In general, most service authors have transitioned to using attribute-based routing. This is true of OData and non-OData web APIs.

I'll leave this open for a bit longer so you have a chance to confirm the newest package addresses your issue.

**Comment by commonsensesoftware** [comment]
This issue should now be resolved. Feel free to come back and reopen the issue or create a new one. Thanks.

**Comment by NetTecture** [comment]
@commonsensesoftware 
It is NOT resolved in 3.0.0 beta 1. I am getting:

InvalidOperationException: The path template 'Account({identity})/Operations.AcceptInvitation' on the action 'ActionOperationsInvitation' in controller 'Account' is not a valid OData path template. Resource not found for the segment 'Account'.

On a controller withe a method that reads:

        [HttpPost()]
        [ODataRoute("Account({identity})/Operations.AcceptInvitation")]
        public async Task<IActionResult> ActionOperationsInvitation(Guid identity, [FromBody] ActionOperationsAcceptInvitationParameter parameters)
        {

with the controlle rbeing prefixed with:

    /// <summary>
    /// Controller for the Account entity
    /// </summary>
    [ODataRouting()]
    public class AccountController

As a snippy side remark to your comment:

> The larger rationale for attribute-based routing is knowing what the convention actually is.

The problem here is the abysmal documentation of the Odata team. I pretty often spend half a day trying to get a convention working (i.e. naming my method right) according to all documentation, then just slap an attribute on it.

**Comment by commonsensesoftware** [comment]
@NetTecture the original question and issue involved Web API. There was an issue with URL generation by the OData API Explorer, but that is seemingly different from your issue. After carefully looking your example, I can tell you're using ASP.NET Core. There were a number of bugs in OData support in Beta 1. I believe they are resolved now, but I have **not** published Beta 2 yet. I just reached feature complete and I have some final testing to do before publishing. I expect to publish by the end of the week. You can review the ASP.NET Core with OData examples to look at working configurations. If you continue to see this issue post-Beta 2, then I encourage you to open an new issue. Thanks.

**Comment by NetTecture** [comment]
@commonsensesoftware Thanks foir the info. WIll wait for Beta 2 and then see what happens ;) Looking forward - getting swashbuckle to work is the missing piece for me (among a lot of functional issues around odata, obviously).
