### ISSUE TITLE
Using URL versioning for ASP.NET webapi project created with .NET 4.5

### ISSUE THREAD

**Issue by LakshmiPrasanna-Human** [Microsoft/aspnet-api-versioning#212]
Can you mention exact steps to be followed for supporting Versioning. We are planning to use asp.net-api-versioning, need to do POC with URL version approach. Steps mentioned in Quick start are not helping. When implemented with Quick steps with sample project its showing nothing.

**Comment by commonsensesoftware** [comment]
Are you saying that you cannot even get the [basic sample](../tree/master/samples/webapi/BasicWebApiSample) project working?  The [HelloWorldController.cs](../blob/master/samples/webapi/BasicWebApiSample/Controllers/HelloWorldController.cs) should be setup in the manner you are wanting to version by.

Once the sample is running, the following URL should light up:
`http://localhost:25282/api/v1/helloworld`

If you can share the relevant parts of you configuration/setup, I may be able to spot a misconfiguration issue. The minimum configuration for your scenario will be:

```c#
var constraintResolver = new DefaultInlineConstraintResolver()
{
  ConstraintMap = { ["apiVersion"] = typeof( ApiVersionRouteConstraint ) }
};
configuration.AddApiVersioning();
configuration.MapHttpAttributeRoutes( constraintResolver );
```

The remaining configuration depends on how you are hosting. The samples are all written using OWIN so that they have parity with the ASP.NET Core samples. If you're using the legacy IIS model with System.Web, then the setup will be different. You cannot use both.

**Comment by LakshmiPrasanna-Human** [comment]
Hi,

Let me share steps I have executed.
1. Created Sample c# ASP.NET Webapi project with Visual Studio 2015.
2. By Package Manager, have installed API version. Able to see the respective assembly reference being added.
3. Have added  code in WebAPIConfig Register method, here is the code:
 public static class WebApiConfig
    {
        public static void Register(HttpConfiguration config)
        {
            // Web API configuration and services

            // Web API routes
           

            //config.Routes.MapHttpRoute(
            //    name: "DefaultApi",
            //    routeTemplate: "api/{controller}/{id}",
            //    defaults: new { id = RouteParameter.Optional }

            //);

            var constraintResolver = new DefaultInlineConstraintResolver()
            {
                ConstraintMap =
                {
                    ["apiVersion"] = typeof( ApiVersionRouteConstraint )
                }
            };

            config.AddApiVersioning();
            config.MapHttpAttributeRoutes(constraintResolver);
        }
    }

4. Have added New controller class and action method, complete code below
 [ApiVersion("1.0")]
    [System.Web.Mvc.Route("api/v{version:apiVersion}/products")]

    public class productsController : ApiController
    {
       
        [System.Web.Mvc.Route]
        public string Get()
        {
            return "productV1";
        }
    }

5. Have run the application with IIS Express, when trying to access the below URL 404 Not Found error is coming:

http://localhost:31517/api/v1.0/products/Get

**Comment by commonsensesoftware** [comment]
Ah ... I see. You're trying to use _Classic_ ASP.NET MVC to author a web API.  This is not a supported scenario.  The older MVC model was meant for building user interfaces and was limited in creating in rich web APIs. This is why Web API was created. In ASP.NET Core, the team did a lot of good work to merge these two a make a single model for authoring UIs and APIs.

In your situation, you'll need to make your APIs services use Web API rather than MVC. While there are a few use cases for using MVC for authoring a simple REST API, it's too limited warrant a  whole new variant of API versioning (which would be required due to MVC vs Web API).

The simplest solution and recommendation I have would be to move your APIs into Web API controllers. This should have minimal impact to your application and will allow you to version your APIs. It seems that _might_ have been what you intended because you have MVC route attributes on a Web API controller class. You cannot mix the two. Additionally, you have the default convention route commented out.

API versioning supports both attribute and convention-based routes. You _can_ even mix and match. However, experience has taught me that mixing routing styles leads to a mess that is hard to understand and maintain over time. I strongly recommend you choose and commit to either all convention-based or attribute-based routing.  MVC and Web API do **not** share routing attributes or routing infrastructure so you can use convention-based for MVC (very common and the default) and attribute-based for Web API (the most popular).

The following should fix your controller and have you back in business:

```c#
using Microsoft.Web.Http;
using System;
using System.Web.Http;

// note: System.Web.Http.RouteAttribute (Web API) vs System.Web.Mvc.RouteAttribute (MVC)

[ApiVersion("1.0")]
[Route("api/v{version:apiVersion}/products")]
public class ProductsController : ApiController
{
 [Route]
 public IHttpActionResult Get() => Ok("productV1");
}
```

Try these changes and let me know how it goes.

**Comment by LakshmiPrasanna-Human** [comment]
Hi ,

Thanks for providing details. Have tried below steps however I am getting ApiVersionUnspecified error.

Below are the steps tried:
1. Create a new project in Visual Studio 2015. Have created empty WebAPI project.
2. Have installed Microsoft API Version package.
3. Created a new controller (derived from ApiController).
4. When created a new controller, Application_Start method in Global.asax, and have added below code inside of that:
 GlobalConfiguration.Configure(WebApiConfig.Register);
            AreaRegistration.RegisterAllAreas();
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
5. Have added below code in ProductsController: 

using Microsoft.Web.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
namespace EmptySampleWebAPI.Controllers
{
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/Products")]
    public class ProductsController : ApiController
    {
        // GET: Products
        [Route]
        public IHttpActionResult Get() => Ok("productV1");
       // GET: Products
        [Route]
        public IHttpActionResult GetSampleData() => Ok("Sample Data");
    }
}
When accessing the code below error is showing up:

<Code>ApiVersionUnspecified</Code>
<Message>An API version is required, but was not specified.</Message>

**Comment by commonsensesoftware** [comment]
What was the request URL? How are you versioning, by query string? The error is telling you that an API version needs to be provided in the request, but was not specified.

**Comment by commonsensesoftware** [comment]
Were you ever able to resolve this? In revisiting this, it appears your route attributes and mapping are incorrect. You need `[RoutePrefix]` instead of `[Route]` on the controller. You also have ambiguous actions for GET. The class should look like this based on your desire to version by URL segment:

```c#
namespace EmptySampleWebAPI.Controllers
{
    [ApiVersion("1.0")]
    [RoutePrefix("api/v{version:apiVersion}/Products")]
    public class ProductsController : ApiController
    {
        [Route]
        public IHttpActionResult Get() => Ok("productV1");

        [Route("sampleData")]
        public IHttpActionResult GetSampleData() => Ok("Sample Data");
    }
}
```

The following routes should now work with requests to:

* `http://localhost/api/v1/products`
* `http://localhost/api/v1/products/sampleData`

**Comment by commonsensesoftware** [comment]
It would seem that this issue has been resolved or you found a solution. Feel free to come back or reopen the issue if it's not. Thanks.

**Comment by commonsensesoftware** [comment]
Can you share your controller code? If you have a repro, that's even better. The hosting model is not a factor in how things work.

**Comment by PawelSpoon** [comment]
i did stumble over iisexpress. without publishing the api it did not run the latest code.F5 did build but then executed the old cached assemblies 
i did remove the comment when i finally did succeed.
Thanks !
thanks !
