### ISSUE TITLE
Question: Upgrading the whole API to a new version after a breaking change

### ISSUE THREAD

**Issue by ALITAYEBI** [Microsoft/aspnet-api-versioning#213]
I would like to upgrade the whole API, including multiple resources; to a new version if any breaking change happen. Is there any way to expose the unchanged API endpoints (controller/actions) from the last version to the new one, without forcing developers to add the new version attribute to every single controller in the project or updating the convention for every single controller? 

For example, endpoints A, B, C from different resources(controllers) are available in an API and the current version is 1.0 for the whole API. Endpoint A has a breaking change and it got implemented in the version 2.0 of this endpoint. I would like endpoint B and C also become available via version 2.0 without adding [ApiVersion("2.0")] attributes or updating the conventions.

**Comment by commonsensesoftware** [comment]
There are many ways this _could_ be solved. If I'm understanding you correctly, in your scenario A has breaking changes, but neither B or C do. I assume for consistency, you want A, B, C to all now have a version 2.0, even though B and C didn't really change. In addition, you don't want to update B and C with tons of new attributes or conventions.

It is _possible_ to create a range of implemented API versions. It's not supported out-of-the-box, but it is something that you can easily create as an extension point. I don't have the issue numbers handy, but if you search in the issues, I've provided some examples of how to achieve that.

An alternative way to achieve your goal would to be to just use the attributes as an anchor point for your own centralized API version management and mapping. This would require to you completely roll your own attribute, but it's not that difficult. It would look something like:

```c#
static class ApiVersionMap
{
    readonly static Dictionary<string, IReadOnlyList<ApiVersion>> map =
       Dictionary<string, IReadOnlyList<ApiVersion>>()
       {
          ["A"] = new List<ApiVersion>(){ new ApiVersion( 1, 0 ) }
          ["A2"] = new List<ApiVersion>(){ new ApiVersion( 2, 0 ) },
          ["B"] = new List<ApiVersion>(){ new ApiVersion( 1, 0 ), new ApiVersion( 2, 0 ) },
          ["C"] = new List<ApiVersion>(){ new ApiVersion( 1, 0 ), new ApiVersion( 2, 0 ) },
       }
     internal static IReadOnlyList<ApiVersion> Get( string key ) => map[key];
}

[AttributeUsage( AttributeTargets.Class, AllowMultiple = false )]
public sealed class KeyedApiVersionsAttribute : Attribute, IApiVersionProvider
{
   public KeyedApiVersionsAttribute( string key ) => Key = key;
   public string Key { get; }   
   bool IApiVersionProvider.AdvertiseOnly => true;
   bool IApiVersionProvider.Deprecated => true;
   public IReadOnlyList<ApiVersion> Versions => ApiVersionMap.Get( Key );
}

[KeyedApiVersions( "A" )]
public class AController : ApiController
{
}
```

You'll likely have additional optimization and so on. One thing to consider about this and any related approach is what happens when things diverge? Mapping this way for convenience works well when the everything is symmetrical. The point of having versions is so that APIs can evolve independently over time. Once you reach a point where you have something like A-1, A-2, A-3, B[1-2], B3, C1, C[2-3], the mapping can become quite untenable and make you go cross-eyed. If you keep the number of supported API versions low (_N-2_ is a common policy) then it shouldn't be a big deal. Of course, then you might also question why you need all the sophisticated custom mapping when attributes or conventions will likely suffice. Using an _API version range_ would suffer from a similar problem as you have to somehow manage the start and stop of each API.

Hopefully this gives you some ideas and that points you in the right direction. Let me know if you have any other questions.

**Comment by ALITAYEBI** [comment]
Thank you very much for getting back me quickly.
You understood me correctly. I am trying to keep the consistency and also an easy strategy for our developers. Thanks for explaining the possible options for me, too.

I will consider the good point you have mentioned about the unsymmetrical changes which will end up an untenable situation. 

What would be the recommended way fo versioning which can show the consistency of the API and doesn't confuse the consumers of the API with different versions for each resource?
Thanks in advance

**Comment by commonsensesoftware** [comment]
There's nothing wrong with driving the API version forward for all services. As you stated, it makes things pretty clear for clients. The management challenges are more of an implementation detail. One of the more popular approaches I've seen is to use namespaces per API version.

This would have the following implementation benefits:
* Developers can easily determine where the source is for a particular version
* New versions can be spun up with a _Copy-Paste-Replace_ of an existing folder
* If or when new versions diverge in behavior, you already have split implementations
* If it's only one API version per namespace, per controller, then you can map API version by namespace
   * This would require a custom attribute or use a convention that maps to the namespace name (ex: My.V1.Controllers => new ApiVersion( 1, 0 ))

The decision-making process is partially determined by how many concurrent API versions you'll support. I would recommend having a well-established versioning policy (ex: N-2) with guidelines about how and when API versions will be sunset. This will make it easy for developers to handle the API evolution over time and set the expectation with clients about how long an old API version will be around.

Ah ... for the non-generic conventions ... I don't there is anything else holding up the release. I'll try to get that shipped out during the upcoming long weekend.

**Comment by ALITAYEBI** [comment]
Thank you very much for your time and good advice.

My plan is using a namespace for each version. However, rather than copy and pasting controller, the new version controllers can inherit from the previous ones. Actions by default would be virtual so easily they can be overriden in the new version controller.

I think this pattern would make supporting and depreciating versions easier.

Thanks again and now I am happy to close this.

**Comment by ViktorDolezel** [comment]
> Thank you very much for your time and good advice.
> 
> My plan is using a namespace for each version. However, rather than copy and pasting controller, the new version controllers can inherit from the previous ones. Actions by default would be virtual so easily they can be overriden in the new version controller.
> 
> I think this pattern would make supporting and depreciating versions easier.
> 
> Thanks again and now I am happy to close this.

Hi, I wonder if you ever tried this approach and what are your lessons learned

**Comment by commonsensesoftware** [comment]
@ViktorDolezel 

- Isolated versions by namespace work pretty well in practice
- I've found inheritance to **not** be a great option in practice:
  - The biggest problem is that you cannot _uninherit_ an action, which is necessary when an API goes away
  - Inheritance is not the _right_ way to think about the problem and can be difficult to understand where the implementation is
  - Inheritance is reasonable for common, non-API actions that you can't achieve with extension methods
  - Your mileage will likely vary based on how many API versions you have
  - Keeping controllers limited to just HTTP and the API makes inheritance less necessary
  - Common logic is often better served to formatters, results, extension methods, and/or logic factored out to collaborators
  
  There's a few thought. May you find it useful.
