### ISSUE TITLE
Apply API versioning with Named routes

### ISSUE THREAD

**Issue by robvanpamel** [Microsoft/aspnet-api-versioning#218]
Hi, 

For our API we have the requirement that we can access the route as 
* controller/action => will go the latest version of the api
* v{version}/controller/action => will go the specific version of the api 

We have achieved this by 

```
    [ApiVersion("1")]
    [Route("[controller]")]
    [Route("v{version:apiVersion}/[controller]")]
    public class ApplicationController : BaseController
    {
    ...
    }
```

Now we also have some named routes on our controller 

```
    [HttpGet]
    [Route("{id}", Name = "GetAppById")]
    public ActionResult GetApplication(int id)
```

However now we get this exception when trying to execute the request. 
```
The following errors occurred with attribute routing information: Error 1: Attribute routes with the same name 'GetAppById' must have the same template: Action: 'Sag.SystemCenter.Api.Controllers.AdminUserController.Get (Sag.SystemCenter.Api)' - Template: 'Application/{id}' Action: 'Sag.SystemCenter.Api.Controllers.AdminUserController.Get (Sag.SystemCenter.Api)' - Template: 'v{version:apiVersion}/Application/{id}'
```
Any idea how to resolve this ? 

Kind regards
  Rob

**Comment by commonsensesoftware** [comment]
You should be able to achieve this by convention. The behavior would work similar to how you are defining the routes. As the current version shifts, you have to shift where the _current_ route maps.

If your APIs are symmetrical, then you can do something like:

```c#
[HttpGet("{id}", Name = "GetAppByIdV1")]
public ActionResult GetApplication(int id)
{
    var version = HttpContext.GetRequestedApiVersion();
    var routeName = "GetAppByIdV" + version.Major.ToString();
    var link = Url.Link( routeName, new { id = id } );
}
```

If your API versions are not symmetrical, then you'll need some type of internal mapping. In addition, I'm not sure how you'd decide which version you choose when the API versions are disjoint, but I guess that must be something you must have already considered.

This approach doesn't solve the scenario for the _current_ controller itself. A route can only have one name; therefore, you cannot have "GetAppById" and "GetAppByIdV1" on the same action.

An alternative to all this is to come up with your own link generator since the built-in one is not _API version aware_. You can reuse a lot of the existing infrastructure. An implementation might look something like:

```c#
[HttpGet("{id}")]
public ActionResult GetApplication(int id)
{
    var requestedVersion = HttpContext.GetRequestedApiVersion();
    var link = customGenerator.Link( "Application", "Get", requestedVersion, new { id = id } );
}
```

The custom generator can hide the mapping and centralize the link generation process.

I'm not sure there any concrete solutions in the space, certainly not out-of-the-box. Hopefully this gets you moving in the right direction though.

**Comment by robvanpamel** [comment]
Ok, with your advise we were able to get a solution, thanks!

**Comment by zinov** [comment]
what if I need to have the Name route at the level of the action because it helps on the swagger output with Swashbuckle instead of centralizing the link generation process? How can I solve it if I have 2 controllers with the same code, different routes but the same Name

api/v1/controller
api/v2/controller

```
       [HttpOptions(Name = "GetWeatherForecastOptions")]
        public IActionResult GetWeatherForecastOptions()
        {
            Response.Headers.Add("Allow", "GET,OPTIONS,POST,PATCH");
            return Ok();
        }
```
