### ISSUE TITLE
Sample for ErrorResponses CreateResponse

### ISSUE THREAD

**Issue by NimmyJohn** [Microsoft/aspnet-api-versioning#233]
Hello ,
Can you provide a sample on how APIVersioningOptions can be configured to create error responses based on error codes . I need to send a different error messages based on error codes .
Please provide a sample to create response using options.ErrorResponses.CreateResponse

**Comment by commonsensesoftware** [comment]
I suppose since most cases only involve changing the status code, there hasn't been much need to provide such an example. You didn't specify which platform you're using, but the process is the same for both and is incredibly simple. Your logic will based on the standard [error responses](../wiki/Error-Responses).

```c#
class MyErrorResponseProvider : DefaultErrorResponseProvider
{
    // note: in Web API the response type is HttpResponseMessage
    public override IActionResult CreateResponse( ErrorResponseContext context )
    {
           switch ( context.ErrorCode )
           {
               case "UnsupportedApiVersion":
                   context = new ErrorResponseContext(
                       context.Request,
                       context.StatusCode,
                       context.ErrorCode,
                       "My custom error message.",
                       context.MessageDetail );
                   break;
           }

           return base.CreateResponse( context );
    }
}
```

To wire it up, just add the following to your configuration:

```c#
options => options.ErrorResponses = new MyErrorResponseProvider();
```

The design is such that you can influence the inputs to the standardize responses or you can completely replace the response with your own.

I'll consider adding this to the wiki. I've intentionally kept the documentation in this area light because it's not really something that service author should want or need to change. It's there, however, for those scenarios I can't think of or where things really need to bend to the will of the service author. ;)

**Comment by commonsensesoftware** [comment]
This issue seems to be resolved. Feel free to come back or reopen the issue if it's not.  Thanks.
