### ISSUE TITLE
NullReferenceException in ApiDescriptions

### ISSUE THREAD

**Issue by bdebaere** [Microsoft/aspnet-api-versioning#234]
Problem since the last update.

Take the code from SwaggerODataWebApiSample.

Add the following code to the PersonModelConfiguration:
```csharp
                builder
                    .EntitySet<Person>("People")
                    .EntityType
                    .Function("Test")
                    .Returns<Task<IHttpActionResult>>();
```

Add the following code to the PeopleController.cs:
```csharp
        [HttpGet]
        public async Task<IHttpActionResult> Test([FromODataUri] int key)
        {
            return StatusCode(HttpStatusCode.NoContent);
        }
```

Notice that a null reference exception now happens for the ApiDescriptions property in Startup.cs line 73:
`foreach ( var group in apiExplorer.ApiDescriptions )`

Removing Task<> from both code parts causes the error to dissapear. Other generics (SingleResult<> ...) also suffer from this problem.

**Comment by commonsensesoftware** [comment]
A `NullReferenceException` should not occur so that's worth investigating.

The return value in your EDM model is incorrect. The EDM configuration indicates what _model_ type the _function_ returns, not the API action signature. If the function returns a _Person_, then the return value should be **.ReturnsFromEntitySet\<Person\>( "People" )**. The sample project demonstrates how to correctly configure this.

**Comment by bdebaere** [comment]
@commonsensesoftware I was assuming that your return type had to match the function return type. This is apparently not the case? Why?
Indeed after changing it to .ReturnsFromEntitySet<>("") it no longer gives a NullReferenceException.

**Comment by commonsensesoftware** [comment]
It seems that this issue has been resolved. In the event that it's not, feel free to reopen the issue or post a new one.  Thanks.
