### ISSUE TITLE
Api versioning for web api core 2 does not work with TestServer 

### ISSUE THREAD

**Issue by majdee** [Microsoft/aspnet-api-versioning#235]
Hi,

I'm trying to test web api controller(.net core 2 ) that use api-versioning.
The configuration of api-versioning:
  ReportApiVersions = true;
  AssumeDefaultVersionWhenUnspecified = false;
  ApiVersionReader = new MediaTypeApiVersionReader();

The controller works well using swagger and postman, the problem when I use TestServer client ( for integeration tests), I get all the time bad request with error message "api version is required", the accept header is set correctly.

If I change the configuration key AssumeDefaultVersionWhenUnspecified to true I did not get the exception anymore even if I don't use the default version.

Any advice ?

Thanks.

**Comment by commonsensesoftware** [comment]
I'm going to need more input with respect to your configuration. I can assure you that **TestServer** is not the issue. I use it for the acceptance tests.  I would recommend you compare your configuration with the configuration I use for the [media type negotiation tests](../blob/master/test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/MediaTypeNegotiation/given%20a%20versioned%20Controller/when%20using%20media%20type%20negotiation.cs). You'll probably have to work your way backward a few levels, but it illustrate what you need to set things up.

**Comment by commonsensesoftware** [comment]
Were you ever able to resolve your issue?

**Comment by commonsensesoftware** [comment]
I presume you found a resolution. If you haven't resolved the issue, feel free to come back. Thanks.

**Comment by majdee** [comment]
I set AssumeDefaultVersionWhenUnspecified to true, and it fixed the issue.

**Comment by commonsensesoftware** [comment]
You can use `AssumeDefaultVersionWhenUnspecified = true`, but that isn't necessary to make it work. I should elaborate that you have configured things to use media type negotiation. If you're getting 400 with this error message, then that means you are **not** specifying the API version in the media type. By default, API versioning requires an API version to always be explicitly specified.

I'll assume that you're using JSON payloads. This means that the client now needs to explicitly specify a media type that includes the API version in requests. For requests that do not specify a body such as GET or DELETE, the client needs to specify `Accept: application/json; v=1.0`. For requests that have a body, the client should specify `Content-Type: application/json; v=1.0`.

The behavior of using `AssumeDefaultVersionWhenUnspecified = true` will allow the client omit the `v` media type parameter or even omit the media type altogether. Remember that only **one** API version can be implicitly matched this way (by default). You should never change the default API version if you enable this feature because you might break existing clients.

I hope that helps.
