### ISSUE TITLE
Wrong middleware behaviour, when Spa services is integrated.

### ISSUE THREAD

**Issue by merqlove** [Microsoft/aspnet-api-versioning#238]
So, subj.

Also posted here:
https://github.com/aspnet/JavaScriptServices/issues/1483

Problem:
Wrong behavior means, that existing routes (From MVC Razor stack) redirecting/proxy to the React app.

For me this behavior looks WRONG!

Sample project, that illustrates this behaviour:
[Sample](https://github.com/Mubicon/aspnet-spa-bug)

I really surprised, that no one has reported this bug.

**Comment by merqlove** [comment]
Currently I removed ApiVersioning module, to make it works.

**Comment by commonsensesoftware** [comment]
This is an expected, but unfortunate, behavior based on how the current ASP.NET Core routing infrastructure works. API versioning **must** go last in order to make the correct decision, but this can conflict with some types of other _end of route_ behaviors. This includes, but is not limited to, SPA, exception handling, re-execution, etc. There is more to the story, but I've articulated that in many, many similar issues. You can find a more detailed answer in the existing issues, if you're interested.

In order to achieve the behavior you want, you need to split the routes between your UI routes and your API routes. In fact, this specific scenario is outlined in the wiki [known limitations](../wiki/Known-Limitations#aspnet-core-routing) for ASP.NET Core and illustrates how to update your configuration with SPA enabled.

Let me know if you are unable to make things work after you update your configuration.

**Comment by merqlove** [comment]
@commonsensesoftware For now I'm totally removed this package from our project, we have strong time limits. 
Yeah, I've seen this page with known limitations, but that page about Core 1.x, in Core 2.x we are loading Versioning modules in the `ConfigureServices`, but routing loads in the Configure.
Thanks anyway for your answer.
Maybe back in the future to this problem 👍

**Comment by commonsensesoftware** [comment]
Sorry you weren't able to get things working. When you have more time, I suggest reviewing your service design such that retries and custom error pages are opted out from the non-SPA paths. APIs _should_ not have such requirements. As previously mentioned, there is some guidance in the wiki as well as in other closed issues. Feel free to come back and ask more questions if you're unable to get things working when you have time to give it another go around. Thanks.

**Comment by merqlove** [comment]
@commonsensesoftware, right. I think we will think about later. But I also think, that MapWhen via proxy is nice one solution. For now our own versioning works for us. But later we have plans to give a task to coders for adopt our app for aspnet-api-versioning & cleanup some buggy JS integration parts.

**Comment by commonsensesoftware** [comment]
Totally fair. This problem has creeped up a number of times. I'm really hoping to get some traction with the ASP.NET team to help improve this behavior. They _are_ listening, but have been tied up with other priorities.
