### ISSUE TITLE
How would package reference contention be handled between API versions

### ISSUE THREAD

**Issue by bnolan001** [Microsoft/aspnet-api-versioning#256]
If my understanding is wrong I apologize but it looks like a single project in the solution would hold all of the API versions for a REST service.  This makes sense but I'm not sure how this setup would handle package version issues.  If an updated package reference is needed that isn't compatible with, or would require a major rewrite of, the older APIs how would the package version problem be handled in this type of a project setup?  This is assuming that the namespaces are all the same.  It seems like you would end up with one project that has API v1 through vX and then another project for the new API and updated package references.  That is all well and good but then other difficulties would arise when it comes time to deploy the legacy and new APIs under the same domain.

Another way to setup the solution would be to have each API version in its own project.  This could cause a lot of code and configuration duplication but would make package management and deployments simpler.  I'm sure there are other drawbacks that I'm not thinking of at this time.

The reason for my question is because I'm doing research for my team on how we want to standardize on REST API project setup and versioning for internal enterprise development.  Our current deployments have been quite the mix of solution/project definitions and API version handling.  I'd like to get us to settle on one or two ways of setting up our projects and maintaining the APIs.  

This repository has been very educational so thank you for giving me a good place to start.

**Comment by commonsensesoftware** [comment]
There are rather large number of ways a service taxonomy can be broken up and implemented. I've provided samples that outline the basics scenarios, but there are many more. Perhaps things are reaching an impasse where it makes sense to break out the samples into their own repos with independent evolutions.

The scenario you appear to be describing is what I would call _composition_. You have one or more _host_ applications that are just the entry point and configuration for a group of services. Beyond configuration and hosting concerns, the _host_ contains no implementation or services of its own. The _real_ services are implemented in separate projects that are subsequently referenced by the _host_ project or discovered through dependency injection (DI). This is definitely a scenario supported by this project and is the approach I would consider for a large service taxonomy.

There is little dependency between services (e.g. controllers) and API versioning. In fact, there is a scenario where there are no dependencies at all. Most service authors use the attribute style because it's easy to understand and implement. That part of the design has not changed since the first release and is unlikely to ever change. Any library dependencies would be forwarded with assembly binding redirection. Unless a change to the metadata is introduced nothing breaks when new versions are introduced. While I can't predict the future, it's unlikely this will ever change.

If you want zero coupling, then you can use the _[conventions](../wiki/API-Version-Conventions)_ approach. This will allow the _host_ application to apply API versions to the services defined in all associated projects. One of the main reasons to support this feature was exactly for this type of design. In particular, conventions support adding API versioning semantics to externally defined controllers; especially, controllers that are defined in assemblies you don't own, don't have the source code for, and/or controllers you can't otherwise change. The only trade-off is that the _host_ has to understand and define all the API versioning information, but something has to have this knowledge. A _host_ is a reasonable entity to have this responsibility.

There are a lot of ways to make this work and likely a number of ways to simplify things for your particular needs. There are lot of extension and customization points that should enable to you to make things work the way you want.

I hope that gets you marching toward success. Let me know if you have more questions. Thanks.

**Comment by bnolan001** [comment]
Thank for taking the time to answer my question.  This will definitely help me on my research.
