### ISSUE TITLE
Adding ApiVersioning causes HttpContext.Handler to not load on first call

### ISSUE THREAD

**Issue by patricknolan** [Microsoft/aspnet-api-versioning#257]
In my ASPNET Core 2.0 API I register GetRoutesMiddleware (see below) to load the RouteData so that it's available in subsequent middleware components (similar to [here](https://stackoverflow.com/questions/38505184/asp-net-core-get-routedata-value-from-url)). This was all working fine.

However, since adding ApiVersioning (see config below), the context.Handler is always null on the first call to my API operation. On the second call it's set correctly. If I remove ApiVersioning again it's set correctly on the first call as expected. 

Is this a bug? Is there anything I can do make this work?

**GetRoutesMiddleware**
```
public virtual void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    app.UseGetRoutesMiddleware();  
    ...
}

public class GetRoutesMiddleware
{
    private readonly IRouter _router;
    protected readonly ILogger Logger = Log.Logger.ForContext(MethodBase.GetCurrentMethod().DeclaringType);
    private readonly RequestDelegate _next;

    public GetRoutesMiddleware(RequestDelegate next, IRouter router)
    {
        this._next = next;
        this._router = router;
    }

    public virtual async Task Invoke(HttpContext httpContext)
    {
        var context = new RouteContext(httpContext);
        context.RouteData.Routers.Add(this._router);

        await this._router.RouteAsync(context);

        if (context.Handler != null)
        {
            httpContext.Features[typeof(IRoutingFeature)] = new RoutingFeature
            {
                RouteData = context.RouteData
            };
        }

        // proceed to next...
        await this._next(httpContext);
    }
}

public static IApplicationBuilder UseGetRoutesMiddleware(this IApplicationBuilder app)
{
    if (app == null)
    {
        throw new ArgumentNullException(nameof(app));
    }

    var routes = new RouteBuilder(app)
    {
        DefaultHandler = app.ApplicationServices.GetRequiredService<MvcRouteHandler>()
    };

    routes.Routes.Insert(0, AttributeRouting.CreateAttributeMegaRoute(app.ApplicationServices));
    var router = routes.Build();

    return app.UseMiddleware<GetRoutesMiddleware>(router);
}
```

**ApiVersioning Configuration**
```
services.AddMvcCore().AddVersionedApiExplorer(
options =>
{
    options.GroupNameFormat = "'v'VVV";
    options.DefaultApiVersion = new ApiVersion(1, 0);
    options.AssumeDefaultVersionWhenUnspecified = true;
    // note: this option is only necessary when versioning by url segment. the SubstitutionFormat
    // can also be used to control the format of the API version in route templates
    options.SubstituteApiVersionInUrl = true;
});
services.AddApiVersioning(options =>
{
    options.ReportApiVersions = true;
    options.DefaultApiVersion = new ApiVersion(1, 0);
    options.AssumeDefaultVersionWhenUnspecified = true;
});
```

I'm using Microsoft.AspNetCore.Mvc.Versioning 2.2.0

**Comment by commonsensesoftware** [comment]
This is definitely **not** a bug, but it can be confusing to those who get deep down in the routing layers. I'm not sure best how to explain this in a broad, generic sense because the consequences vary a lot depending on what you're trying to do. In the context of what you're seeing and trying to achieve, let me explain things the best I can.

The current ASP.NET Core routing infrastructure design allows a scenario that could result the **IActionSelector** being called multiple times. As it relates to API versioning, this means that the decision to match a route cannot be deterministically made on the first pass because **all** possible candidates have not been considered. This actually caused a bug in earlier versions where the pipeline ended without a match because additional candidates were yet to be presented. The side effect of this behavior is that the API versioning **IActionSelector** always reports no match on the first pass, even if there was one. This guarantees that all candidates are considered. A special **IApiVersionRoutePolicy** is injected at the end of pipeline when `AddApiVersioning` is called. This is were the decision is ultimately made.

It would be highly inefficient if the pipeline did this for every request. The infrastructure captures the relevant API versioning information and caches it. When the same candidate is hit 2+ times, the cached information can be used to make a final decision much earlier in the pipeline. This is why you see a difference in the first request versus all others.

The consequence of all this is that certain types of _end of route_ middleware and routers run into unexpected problems. I've been in talks with the ASP.NET team about this issue, but some fundamental changes are required to the routing infrastructure to make that happen, which unfortunately continues to be deprioritized (but not forgotten). Ideally, all possible candidates should be deterministically discovered by the time the **IActionSelector** is called. It might be possible to replace the existing implementation to make that happen, but it's a rather daunting task for me to do by myself.

All that said, what can you do? Fortunately, there **are** options. It largely depends on what your expected behavior is. If you want to run **after** API versioning, you'll have to skip using `AddApiVersioning` and register things manually. This isn't terribly difficult to do. You can look at the source or there are some examples in the issues list. Let me know if you get stuck. The key to making things work with manual registration is that you need to register the **IApiVersionRoutePolicy** (which is also currently an **IRouter**) **before** your custom routers.

If all you want is the route data, then there's another approach. You have access to the same facilities that the rest of the infrastructure uses. You should be able to get what you want from:

```c#
var selectionResult = httpContext.ApiVersionProperties().SelectionResult;
var match = selectionResult.BestMatch
var routeData = match?.RouteData;

if ( routeData != null )
{
    // TODO: use route data
}
```

It's worth noting that the built-in ASP.NET Core routing infrastructure aggressively tries keep allocations and copies of route data around. I've discovered, as it seems you have too, that you can't always get the route data when you want it. API versioning makes it's own copy when needed so that the required route data is present when the final decision and successful match is executed. Normally, the route data would no longer be available.

For your scenario, I believe you want the process to be:

1. Try to get the route data the _normal_ way
2. If the route data is not available, fallback to using the _best match_ from the possible candidates (as shown above)

When both methods fail, that _should_ mean:

1. There is no match (e.g. 404)
2. There is an ambiguous match (e.g. 500)
3. The final decision hasn't been made yet and _may_ re-enter (I'm not sure the effect on middleware)

Sorry for the long explanation, but hopefully that puts you on the path to success. Let me know if you have more questions.

**Comment by patricknolan** [comment]
Hi @commonsensesoftware  thanks for such a detailed explanation...greatly appreciated.

I  tried using the best match from the possible candidates (as shown above) and routeData is always null.

If I add my middleware registration after the app.UseMvc() statement routeData is populated, however, the middleware component is only invoked on the first call\request. It ins't invoked for any subsequent requests.

I've created a simple AspNet Core API to demonstrate the issue and attached to this thread.

**To reproduce**
1. Load API
2. Expand the Get operation and execute (enter any value for the tenant).
3. The TestMiddleware is invoked, however, the routeData is null
[VersioningApiTest.zip](https://github.com/Microsoft/aspnet-api-versioning/files/1761778/VersioningApiTest.zip)

**Comment by commonsensesoftware** [comment]
Apologies for the delay. I believe the attached revision will get you what you want. The key difference is that your middleware must run **after** MVC. This is more or less the same guidance provided by link you provided above.

```c#
app.UseMvc();
app.UseMiddleware<TestMiddleware>();
// ...
```

[VersioningApiTest-Revision1.zip](https://github.com/Microsoft/aspnet-api-versioning/files/1799938/VersioningApiTest-Revision1.zip)

**Comment by commonsensesoftware** [comment]
Where you able to solve your problem?

**Comment by commonsensesoftware** [comment]
Seems like you were able to resolve this issue. If not, feel free to return or return reopen the issue. I'm hoping to queue up a refactoring in 3.0 that will make middleware integration seamless.
