### ISSUE TITLE
DefaultApiVersion not working with MediaTypeApiVersionReader

### ISSUE THREAD

**Issue by jaspar** [Microsoft/aspnet-api-versioning#260]
Hey there,

I'm evaluating this quiet nice set of libraries to find out if we may use it in our software. I started by looking at the sample projects provided. Since my favorite way of versioning our own apis would be versioning by accept header/media type I made some changes to the BasicWebApiSample source code. Here is what I came up with:
```C#
configuration.AddApiVersioning( o =>
{
  o.ReportApiVersions = true;
  o.DefaultApiVersion = new ApiVersion (1, 0);
  o.AssumeDefaultVersionWhenUnspecified = true;
  o.ApiVersionReader = new MediaTypeApiVersionReader ();
  o.ApiVersionSelector = new CurrentImplementationApiVersionSelector (o);
});
```
```C#
[ApiVersion( "1.0" )]
[RoutePrefix( "api/values" )]
public class ValuesController : ApiController
{
  // GET api/values?api-version=1.0
  [Route]
  public IHttpActionResult Get() => Ok( new { controller = GetType().Name,
    version = Request.GetRequestedApiVersion().ToString() } );
}
```
```C#
[ApiVersion( "2.0" )]
[RoutePrefix( "api/values" )]
public class Values2Controller : ApiController
{
  // GET api/values?api-version=2.0
  [Route]
  public IHttpActionResult Get() => Ok( new { controller = GetType().Name,
    version = Request.GetRequestedApiVersion().ToString() } );
}
```
This works really well except for one thing. If I don't provide a version in the accept header or content-type header it's always the latest api version controller that responds. But I'd like the version 1.0 controller to respond in that case. I thought this is supposed to work by configuring api versioning with ```o.DefaultApiVersion = new ApiVersion (1, 0);``` and ```o.AssumeDefaultVersionWhenUnspecified = true;```. But somehow it's not working.

Maybe I am missing something here. Any help is highly appreciated.

Thanks in advance!

**Comment by commonsensesoftware** [comment]
You're just about there. You changed the **IApiVersionSelector** to **CurrentImplementationApiVersionSelector**, which will **not** get you the result you're looking for. This selector will always select the maximum API version available (e.g. _current_) or fallback to the **DefaultApiVersion** configured in the options.  Just remove that configuration and you should be good to go.

As an aside, the current use of the **IApiVersionSelector** only happens when `o.AssumeDefaultVersionWhenUnspecified = true` is set **and** a client doesn't provide an API version. There are a set of built-in implementations that decide which API version to resolve given all discovered API versions. If you need something extra, you can roll your own implementation. The current request is also provided so that you can pair specific request contexts with the selection process.

I hope that helps.

**Comment by jaspar** [comment]
Thumbs up! That was it. Thank you very much.
