### ISSUE TITLE
Base functionality is wrong? Or am I being stupid?

### ISSUE THREAD

**Issue by rossdempster** [Microsoft/aspnet-api-versioning#261]
Hey guys,

I'm trying to add some versioning to my ASP.NET Core project and running into a very basic issue.

Thinking about my requirements for versioning, the very first thing on my list is:
- Upon defining a new version, say v1.1, the full functionality of v1.0 should already be available, at which point I can then decide which methods to remove, replace etc.

Looking at the documentation for this, the samples propose a new controller for each version. This leads me to believe I am expected to re-implement the full API surface for each revision! Call me crazy, but that just isn't practical (unless you have a tiny API).

I have tried creating new controllers by inheriting the older version, but this does not work properly when replacing a method with a newer version. The ambiguity resolution does not favour the most derived method, thus fails when it finds two methods that implement the same action. Overriding is only possible if the parameters match exactly which of course is rarely the case. I have no choice but to reimplement every method on every controller.

Another option is the [MapToVersion] attribute, but again the default behaviour of this is causing me issues. If I use [MapToVersion("2.0")] and then later introduce a v2.1 version, the method reverts to its pre-2.0 behaviour because it uses an == instead of a >=. This then requires a manual search for all methods using [MapToVersion] and to tag them with the new version too. Ultimately, this manual process will lead to methods being forgotten and bugs being introduced.

Is there any advice on how to inherit existing functionality into each new version? I'm struggling a bit.

Many thanks,
Ross.

**Comment by commonsensesoftware** [comment]
A controller per API version is certainly the _safest_ and easiest to understand, but it's not a hard requirement. As you've noted, you can use _action interleaving_ to have a single controller with multiple versions when there are small variations between API versions. You can also use a combination of both. There is currently an open issue to address the feature request to support interleaving across controllers. This would make implementation large API surfaces easier. Unfortunately, it's a lot more complicated under the hood that it looks. That will likely be some time coming.

If I step on my services _soapbox_, every service author's goal should be to make their clients' lives easier - and stable. All too quickly service authors want to jump to making their _implementations_ easier for them. Certainly that's not unfounded and this project aims to help make that a reality, but not at the cost of unpredictably for clients. It's, therefore, important that versions match exactly by default. This makes things predicable for the service and clients. All too often, service authors only consider new API versions. Well, what about old API versions that are removed? This eventually does happen and can even happen in the middle of a range (ex: a bad version becomes unpublished). This becomes a mess when ranges are used. I've witnessed teams doing this in the field and it didn't end well.

All that being said, there is a way to support a _range_ of sorts, but it's not provided out-of-the-box. There are many extension and customization points. I can't remember if there are an examples in the wiki, but there are definitely examples in the issues. You can create an attribute or use conventions that produces a range albeit a discrete range. It _might_ look like:

```c#
[ApiVersionRange(1, 2, MinorStep = 1)]
public class MyController : Controller
{
   [MapToApiVersionRange(1.5, 2, MinorStep = 1)]
   public IActionResult Get() => Ok();
}
```

One of the many reasons why this isn't supported out-of-the-box, is that an API version doesn't intrinsically support incrementing or decrementing. That process is wholly dependent on your style of versioning. Nevertheless, there are plenty of base implementations to start from or you can roll your own **IApiVersionProvider**. The framework doesn't care about attributes, it only cares about this interface. That means you can create your own attributes from scratch if you want to.

You might also consider using conventions. The process of creating complex mapping will be a little onus, but you'll have full control over how to graft the API versions onto controllers and their actions. You might even achieve this using your own configuration (ex: a *.json file, *.xml file, db, etc) to populate at startup and then apply the conventions.

Ultimately, the least amount of mapping comes from using independent controllers. All actions implicitly map to the same API version as their defining controller. One of the many ways to make this less painful is to keep all of the business logic out of the controller. The controller _is_ the service. The only thing it should be doing is invoking business logic and controlling the wire protocol. If you adhere to that type of style, then it should be pretty safe to _copy and paste_ new controllers for new API versions and only modify the minimal changes. Most service taxonomies have a stated versioning policy of _N-2_ or something like that. If the number of API versions you support per service is less than 5 (just throwing out a number), it shouldn't be that hard to manage.

Beware trying to make the API version of all services congruent. I won't say _don't do it_, because it can make it easier for clients, but each service should be allowed to evolve independently. If you're trying to achieve having all your services support the same API version, then you'll definitely want to use a custom attribute or conventions because it will be much easier to manage.

I hope that helps. Let me know if you have more questions.

**Comment by rossdempster** [comment]
Thanks for the detailed reply, much appreciated!

I'll have to mull over some of your points on version ranges. You definitely have an angle on this that's different to my own. Perhaps this is a comparative lack of experience on my side.

Judging by the opening sentence to your second paragraph, I fear I gave a bad impression of my motivations! To be clear, my concern is exactly that of making my clients' lives "easier and stable". It looks like we've arrived at a different conclusion on how best to achieve that!

To aid understanding, let me put a bit more context on this. I am doing this for backwards compatibility. Once v1.0 of the API is released it must remain unchanged because there is a mobile application that depends upon it (and I do not want to force our users into an upgrade). On the flip side, the product is young and we will inevitably want to introduce breaking changes, possibly even revisions of the API structure as we evolve our thinking on how the service should work. I foresee there being a v1.1, v1.2 etc. over the course of the first year. Ultimately, the intention is to make the API publicly available.

You talk of each controller being an independent service, so I suspect you have bigger APIs to manage than me. In our case, there is one logical "service" and the controllers each implement a particular _aspect_ of that service (i.e. the individual REST resources). It is therefore easier for clients if I version the API as a whole. I do not want new consumers hunting around in documents to figure out which particular version they need to call for each API. Simply point at the latest version and go.

The rest of my thinking stems from safety.

I am completely on board with introducing a new controller per version.

```csharp
[IntroducedInVersion("1.0")]
[Route("{api-version}/users")]
public class UsersController1_0 : Controller
{
  // all methods of 1.0
}
```

I think we disagree on how to introduce later versions. In my experience, copy and pasting duplicate code is not a good approach. Your point on the controllers being no more than thunks to another class is noted, but I feel like this may be a hack to cover the fact that the route didn't land in the correct place to start with.

In my opinion, the _safest_ way to introduce a new version is simply to decree "v1.1 now exists" at a higher level of abstraction and then to describe the _changes_ present in that version. The functionality in the preceding version should be available by default. In theory, there is less code to maintain and less chance of introducing mistakes through manual housekeeping.

```csharp
[IntroducedInVersion("1.1")]
[Route("{api-version}/users")]
public class UsersController1_1 : Controller
{
  // MODIFIED FUNCTIONALITY ONLY
}
```

This was actually incredibly simple to implement using just a custom attribute and a custom convention. A testament to how well designed MVC is 👍. I use another attribute [RemovedInVersion] to flag the methods that are being replaced in a later version (or no longer available).

I will be sure to report back if my experience from running this approach changes my viewpoint!

**Comment by commonsensesoftware** [comment]
Apologies if I got a little riled up.

In my vernacular, _resource_ == _API_. IMO, there is no such thing as a _Web API_ per se. The _API_ is HTTP (e.g. the _uniform interface_). Arguably, that's why purists, including Fielding himself, disagree with the concept of _API versioning_ and tend to accept media type negotiation as the only practical method of versioning. I can get onboard with that position.

You can certainly slice implementations, even for a single resource, across multiple controller types. This would certainly make sense from something like `DELETE`, which is unlikely to ever be different for any API version.

There are many, many ways to version resources and I don't think there is one single implementation flavor that matches them all. Part of that decision will be based on the number of resources and the cohesion between them. In large service taxonomies, services tend to use a date rather than a number (which is supported) because a number becomes meaningless at some point. While it's admirable to have a single version for all resources, that is unmanageable in large service taxonomies and can be argued to be counter to service-orientation. However, for small sets of resource or a particular resource _group_ there's no reason why they can't all have the same version.

It sounds like what you want is actually inheritance. This can work if you use an _add or update_ only approach. You cannot _remove_ an inherited method/action, so to completely sunset an action, things get tricky. In ASP.NET Core, you don't need to do anything special to make picking up existing actions work.

For example:
```c#
namespace App.Controllers.V1
{
  [ApiVersion("1.0")]
  [Route("api/[controller]")]
  public class UsersController : Controller
  {
    [HttpGet]
    public virtual IActionResult Get() => Ok(new []{ new User() });
  }
}

namespace App.Controllers.V2
{
  [ApiVersion("2.0")]
  [Route("api/[controller]")]
  public class UsersController : V1.UsersController
  {
    [HttpGet("{id}",Name="GetUserByIdV2")]
    public virtual IActionResult Get(int id) => Ok(new User(){ Id = id });

    [HttpPost]
    public virtual IActionResult Post(User user) =>
      CreatedAtRoute("GetUserByIdV2", new {id = 42}, user);
  }
}

namespace App.Controllers.V3
{
  [ApiVersion("3.0")]
  [Route("api/[controller]")]
  public class UsersController : V2.UsersController
  {
    [HttpDelete("{id}")]
    public virtual IActionResult Delete(int id) => NoContent();
  }
}
```

You don't have to separate version by namespace. It's only one of many possible forms of organizing the implementation.

I'm not sure where you are in your transition, but here's some additional things to be consider about versioning via the URL:
* You can't have a default route without declaring multiple routes on at least one controller
   * This may not be an issue for you, but it is for some
   * If your existing routes don't have a version segment, then you'll want this for the _initial_ version
* Hypermedia links generated for HATEOS requires coupling because a service must know the applicable version of a related resource to put in the URL
   * Resources usually evolve independently and it's up to a client to decide which version to request
   * Since you're using a single version for all resources, this may be a non-issue

There are more minor points, but those are a few that can cause quite a bit of grief. The URL segment approach is common, but fundamentally approaches the problem incorrectly within the context of REST IMO. A resource is a resource. The _API version_ is really just a different representation of a resource. This is the strongest argument to version by media type. The URL is the identifier of a resource in accordance with the _uniform interface_ constraint. An identifier for the same resource should not change between versions. For example, the URLs `api/v1/users/1` and `api/v2/users/1` implies that the resources are different, when, in fact, they are not. In your case, they are _possibly_ different representations, but in each case, the resource is for a _User_ with ID 1. Media type negotiation is not so _convenient_ to consume, so the query string approach tends to be a reasonable compromise. This allows for `api/users/1?api-version=1.0` and `api/users/1?api-version=2.0`.  If you need or want to support the implicit `api/users/1` route, that's possible too. The query string is never considered in routing (on any stack I know). This gives clients more stable and consistent URLs. Appending the API version to the URL tends to be simpler for clients too.

Ultimately, the decision is up to you. My musings and opinions shouldn't be weighted any heavier than others. While I have done a lot of research and made a lot of observations from the field, there is no _perfect_ answer. The goal of this project was to support the most common versioning methods and let service authors decide what works for them. Some care more about conforming to the REST constraints than others.

Naturally, you're free to go your own route as well. _Inheritance_ in its many forms is something that the community is asking for so it's something I am actively looking into. May you find this all informative and help you in rolling out your service[s].

**Comment by rossdempster** [comment]
I definitely fall into that camp of people that care less about conforming to REST than others. My background is in commercial development so I am far more practically focused than academic.

Fielding's HATEOAS is an interesting concept, but putting my practical hat on for a minute I am unable to see how it fits the modern mobile app/service API approach. The idea that a client could recognize the _semantics_ of an operation and render an appropriate UI simply by the presence of a new hyperlink in the response is somewhat fanciful to me. Modern mobile applications tend to be highly refined, with bespoke purpose-specific gestures for different operations. New operations need to be properly considered and designed-in. Hyperlinks work on the web, _because it's used by humans!_ I have actually used APIs with HATEOAS and found them a pain to work with from a programmatic perspective.

If you ask me, REST is successful not because of any specific ruleset but because it is simpler than what came before it. It is the _idea_ of REST that people like. I doubt most people actually know the full story!

Look at that, you've got me challenging Roy Fielding!

Per-resource versioning via the query-string is something I looked into but dismissed for schema flexibility reasons. To me, versioning sits at the protocol level (i.e. my _service_ protocol, not to be confused with HTTP). If we decide to split "users" into two different resources e.g. "accounts" and "personas" then having a clean root to branch away from seems preferable.

I find the argument that "the URL is the resource, therefore the version shouldn't be part of it" to be somewhat self-entangled. The same argument surely applies to the protocol scheme and hostname. HTTP may not be the only protocol you want to publish resources over (perhaps you're developing a game with a dedicated UDP endpoint) and taking a full HTTP URL as your resource identifier is not conducive to interop! Rebranding may also move your resources even though they are the same resources. A resource identifier is a far more specific thing in my mind, and certainly shouldn't include the mechanism by which you access it as part of its identifier.

Anyway, as you say, the solution needs to fit the circumstances. We can agree on that much! There is no one-size-fits-all.

Thanks again for sharing your experience, I appreciate the advice.

Regards,
Ross.

**Comment by commonsensesoftware** [comment]
I have no qualms about people being pragmatic when it comes to building services. If you've never read Fielding's dissertation, I recommend it. It's not that long and there is so much in there that holds true today. The part about REST is actually very short. One of his key premises is that people suck at designing software that requires long-term evolution. HTTP is actually but one, if the most prolific, example.

>_~~The Code~~ REST is more what you call guidelines, than actual rules..._

HATEOAS can be very effective, when done right. Sadly, I've see it done wrong many times. I happen to be an OData advocate and it's one of the few complete protocols that includes strong support for implementing HATEOAS. I agree that there is generally no practical way to make HTTP clients _auto-magically_ do the next thing outside of a browser. While generating hyperlinks is convenient, I think the real value is knowing whether a resource can perform an action as opposed to what action link is (which most clients know in API development). For example, if `api/orders/123` advertises link `DELETE api/order/123` as a way to cancel an order. The fact that the link is advertised at all is the server telling the client that the action is available. The link and advertisement together _can_ be really useful, but does not determine the success or completeness of an API.

The term **URL** tends to be highly overloaded. When I use it in the context of identification, I only mean the **path**. Everything else is additional metadata. Hostnames usually don't come into the picture, but the could. (ex: _INT_ vs _PROD_ resource). I agree with your assertion about protocols. The protocol is indicating _how_ to get something, not _what_ to get.

Thanks for all the input and feedback. It's interesting on a personal level and also helps fuel knowledge back to the community about why service authors choose the path they do. There are many strong opinion out there. I certainly have mine, but when people arrive here for advice I try to convey the reasons _why_ service authors make the choices they do. Thanks for your contribution.

Hopefully I've demonstrated a path that works for you. If you're wondering what the remaining value propositions are, it will largely be the ancillary features like version advertisement, Swagger integration, etc. If you don't care about that or you have your own way of providing that, more power to you. :)

Good luck with your API.

- Chris

**Comment by rossdempster** [comment]
Thanks again Chris. I have achieved what I need to for now.

Feel free to close the issue - I'm not sure what the etiquette is, is that my job or yours?!

**Comment by commonsensesoftware** [comment]
I like to keep my issues low because I can't manage huge lists alone. I don't know that there is an official etiquette, but I give people 3-4 weeks to close their own issues - since they opened the issue. If not, I tend to close them off myself. If I think the issue might still be open, I usually ping the thread and give it up to a week.

Thanks again for your thoughts.
