### ISSUE TITLE
Can't build webapi swagger sample

### ISSUE THREAD

**Issue by ebarke** [Microsoft/aspnet-api-versioning#268]
I'm trying to build the swaggerwebapi sample and tried both 2015 and 2017 and I get a nuget ref error

The missing file is ..\..\..\packages\Microsoft.Net.Compilers.1.3.2\build\Microsoft.Net.Compilers.props.

I've got my settings to automatically download/restore, but it doesn't work, I even tried downgrading the microsoft.net.compilers nuget package to 1.3.2 but I still get the same error.

Any ideas would be greatly appreciated as I'm trying to use the versions package to version and api service with swagger definitions.

Thanks.

**Comment by commonsensesoftware** [comment]
VS2015 isn't going to work because it doesn't have all the support for the _Common Project System_ (CPS; aka "SDK" projects).

I just tried cleaning the entire repo, nuking all packages, and rebuilding from command-line. It all appears to work. I suspect you may be missing something or something is out-of-date. I keep VS2017 fresh all the time and I'm currently running 15.6.4, but any version near that _should_ work.

Aside from building within Visual Studio, you can fully build from the command-line at the root directory using:

```batch
nuget.exe restore
msbuild /v:m /t:Restore;Build
```

Let me know if you continue to be blocked.

**Comment by commonsensesoftware** [comment]
Were you unable to unblock yourself and get things rolling again?

**Comment by commonsensesoftware** [comment]
This issue appears to be resolved. Please come back if it's not. Thanks.
