### ISSUE TITLE
Falling back to default version

### ISSUE THREAD

**Issue by kdelwat** [Microsoft/aspnet-api-versioning#287]
I have multiple versions of the same controller, like so:

    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/todo")]
    public class TodoController : ControllerBase
    {
        ...
    }

    [ApiVersion("2.0")]
    [Route("api/v{version:apiVersion}/todo")]
    public class Todo2Controller : ControllerBase
    {
        ...
    }

Is there any way to specify a "default" version, where all versions given in the URL without a specific controller would use the default controller? For example, navigating to `/api/v3/todo` would redirect to the version 2.0 controller, as would `/api/v100/todo`.

Any help is very appreciated, I'm not sure if this is even possible 😄

**Comment by commonsensesoftware** [comment]
It's possible - sort of. You can change the **IApiVersionSelector**, which complements the `AssumeDefaultVersionWhenUnspecified` option. The default configuration selects the `DefaultApiVersion`; however, this can be changed. There are a few selectors out-of-the-box. There is one called **CurrentImplementationApiVersionSelector**, which always selects the highest available API version for a given route.

This configuration is more difficult for your scenario because you've elected to version by URL. There is **not** way to _fill-in_ or otherwise default the API version for your _default_ route. The only workable solution I know of is:

1.  Add a default route without the API version in it
2. The default route be a second route definition on current/highest implementation of the service
3.  You'll have to _float_ (e.g. move) the default route to a new controller when you bump the version

If you have a small number of controllers, that isn't a huge deal. If you have a large number of controllers, it can be tedious to maintain. Other versioning approaches do not share this issue. It's specific to using the path.

Another alternate, separate from API versioning, would be to use URL rewriting. This would negate the need to touch or otherwise decorate controllers with the _default_ route information. When a request without an API version comes in, you can forward it to the correct URL. This approach has less touch points for maintenance, but it's probably nasty for configuration. Most of the URL rewriting stuff uses regular expressions or other pattern matching to define the rules. If you can write your own custom rule with code that would probably be easier, but I'm not sure that's possible. The number of rules you need will likely depend on your API size.

There's a few ideas. I hope that helps.

**Comment by commonsensesoftware** [comment]
You question appears to have been answered or you otherwise found a solution. If you're still having trouble, feel free to re-open this issue or create a new one. Thanks.
