### ISSUE TITLE
Support multiple version constructor in ApiVersionAttribute 

### ISSUE THREAD

**Issue by jzeferino** [Microsoft/aspnet-api-versioning#296]
Since `ApiVersionAttribute` extends `ApiVersionsBaseAttribute ` witch supports multiple versions in the constructor, would be great to made it visible in the `ApiVersionAttribute`.

**Comment by jzeferino** [comment]
@commonsensesoftware ping.

**Comment by jzeferino** [comment]
Thank for the reply. Our use case relies in the goal of having different versions (three at the same time, atm) witch share a lot of methods inside a `Controller`. 
In our particular case we have three simultaneous versions  in witch the diferences are very small and we want that the controller support all versions and only specify the methods that differ.

At the moment we ended up creating a `ApiMultiVersionAttribute`that extends `ApiVersionsBaseAttribute` and implements `IApiVersionProvider`.

``` C#
namespace Microsoft.Web.Http
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using Microsoft.Web.Http.Versioning;
    using static System.AttributeTargets;

    [AttributeUsage(Class, AllowMultiple = false, Inherited = false)]
    [SuppressMessage("Microsoft.Design", "CA1019:DefineAccessorsForAttributeArguments", Justification = "An accessor property is provided, but the values are typed; not strings.")]
    [SuppressMessage("Microsoft.Performance", "CA1813:AvoidUnsealedAttributes", Justification = "Allows extensibility.")]
    public class ApiMultiVersionAttribute : ApiVersionsBaseAttribute, IApiVersionProvider
    {
        public ApiMultiVersionAttribute(params string[] versions) : base (versions)
        {
        }

#pragma warning disable CA1033 // Interface methods should be callable by child types
        bool IApiVersionProvider.AdvertiseOnly => false;
#pragma warning restore CA1033 // Interface methods should be callable by child types

        /// <summary>
        /// Gets or sets a value indicating whether the specified set of API versions are deprecated.
        /// </summary>
        /// <value>True if the specified set of API versions are deprecated; otherwise, false.
        /// The default value is <c>false</c>.</value>
        public bool Deprecated { get; set; }

        /// <summary>
        /// Returns a hash code for the current instance.
        /// </summary>
        /// <returns>A hash code.</returns>
        public override int GetHashCode() => (base.GetHashCode() * 397) ^ Deprecated.GetHashCode();
    }
}
```

Would be nice to instead of adding the constructors to `ApiVersionAttribute` like I did, have a class like the above in the library.

Does it make sense to you?

**Comment by commonsensesoftware** [comment]
Let's try to flush this out in a more practical sense with examples. You're effectively claiming that:

```c#
[ApiVersions("1.0", "2.0", "3.0")]
public class MyController : Controller { }
```

Is _better_ or more _convenient_ than:

```c#
[ApiVersion("1.0")]
[ApiVersion("2.0")]
[ApiVersion("3.0")]
public class MyController : Controller { }
```

or

```c#
[ApiVersion("1.0"), ApiVersion("2.0"), ApiVersion("3.0")]
public class MyController : Controller { }
```

In scenarios where you have fewer than 5 API versions, the current method, while more verbose, is still within reason. In practice, I've only really observed 1-3 API versions. As I mentioned, the original design did support this, but I organically discovered that most developers don't do that. Arguably, if you have more than 5 API versions on a single controller, you're probably doing it _wrong_ and leading yourself down an unmanageable path.

I can see and even appreciate the _convenience_ factor, but you said that your scenario only has 3 API versions. In terms of _value_, we're splitting hairs on approach for this few API versions. The value really only appears when you have large numbers of API versions on a single controller, which in practical coding practices is not done because it doesn't make sense.

Is there something else I'm missing?

**Comment by jzeferino** [comment]
I totally agree with you. As you though this is a matter of _convenience/appearance/clean_
Should we close it?

**Comment by commonsensesoftware** [comment]
I'm inclined to - yes, but I wanted to make sure I fully heard your argument first. The primary counter-arguments are:

1. The _convenience_ has relatively low value
2. Suggesting that you can add a laundry list of API versions to a controller can lead you astray

For those that _really_ want it, it's a very simply extension as you've already demonstrated. Additionally, you can use the _conventions_ configuration method, which does have overloads to add multiple API versions at once. The intent there was that you might be loading from a persistence store such as a file or database.

Thanks for all you input. At a minimum, I'm sure someone will find this discussion useful. :)

**Comment by jzeferino** [comment]
Sure, and thanks for your time and clarifications. Closing.

**Comment by jzeferino** [comment]
cc @eliamartani

**Comment by sdepouw** [comment]
I do have a scenario for this that extends beyond low-value convenience: Maintaining a *set* of APIs which universally are tied together, version-wise. Meaning when we require a version upgrade, we have to visit *every* Controller and update its `ApiVersion` collection, and update them.

We tried putting these versions on a base controller, but that seems to break down once you start adding `MapToApiVersion`, as the first time you do, *every* method requires *every* required version to be `MapToApiVersion`'d. So, we keep `[ApiVersion]` on every Controller to not have to go through that pain.

If we could either specify the version on the base class correctly, or if `ApiVersion` supported "add multiple versions" so that I can create a derived class that bottles up our versions (so we only have to update code in one class, instead of *n* classes), that'd be super. As it is now, it's "update n controllers" which is far more error-prone and extends beyond simple convenience.

For now I'm going to try to make my own attribute that implements `IApiVersionProvider`, but it would be much easier if this supported multiple-versions-in-one out of the box! (Even if it wasn't on `ApiVersion` specifically.)

**Comment by sdepouw** [comment]
https://github.com/dotnet/aspnet-api-versioning/issues/296

I do have a scenario for this that extends beyond low-value convenience: Maintaining a *set* of APIs which universally are tied together, version-wise. Meaning when we require a version upgrade, we have to visit *every* Controller and update its `ApiVersion` collection.

(As an aside, no, I cannot change this set-up, so even if this isn't "best practice" it's what we're saddled with, and this ask/comment is centered around supporting this.)

We tried putting these versions on a base controller, but that seems to break down once you start adding `MapToApiVersion`, as the first time you do, *every* method requires *every* required version to be `MapToApiVersion`'d. (And when I try to make a custom Api Version provider that bundles, it seems to just let every version through, including non-supported versions). So, we keep `[ApiVersion]` on every Controller to not have to go through that pain.

If we could either specify the version on the base class correctly, or if `ApiVersion` supported "add multiple versions" so that I can create a derived class that bottles up our versions (so we only have to update code in one class, instead of *n* classes), that'd be super. As it is now, it's "update n controllers" which is far more error-prone and extends beyond simple convenience.

For now I'm going to try to make my own attribute that implements `IApiVersionProvider` (which will work until we need to mark certain versions as `Deprecated` or otherwise have their own `ApiVersionProviderOptions` per-version), but it would be much easier if this supported multiple-versions-in-one out of the box! (Even if it wasn't on `ApiVersion` specifically.)

**Comment by commonsensesoftware** [comment]
@sdepouw The first issue that you are seeing is that **ApiVersionAttribute** is not inherited. This is by design. Honestly, I'm of the opinion that inheritance is the wrong approach for HTTP APIs, but the reasoning is more than my dogma. If API versions were inherited, you can easily get into a situation where 2 different super types implement the same versions and routes. While it's true that it is technically possible to avoid that from happening it is not clear in code. You also cannot _uninherit_ a method or API version if it was allowed. In the spirit of the _Principal of Least Astonishment_ and _intention-revealing_ code, API versions must be explicitly declared on the types that implement them. One of the original core design principles was that API version information should be pure metadata. In alignment to that, you can use whatever you want for inheritance, but then you must explicitly state which implementations have which versions.

I've outline some of the original history around the design of one value per attribute. I ultimately settled on a single value because it aligned with the attribute name (singular) and it is very easy to create your own multi-value attribute. The implementation shown above is correct, although you might prefer another name such as **ApiVersionsAttribute**. The built-in **ApiVersionsBaseAttribute** is the foundation for several of the built-in attributes, but it intentionally does not implement **IApiVersionProvider** because the implementation varies on the derived types. Again - the example above does illustrate putting that all together.

API Versioning does not have a concept of _no version_, unless the controller is completely ignored/filtered out (ex: a UI controller). As you've observed, if you do not specify any versions or mappings, there is an assumed default (e.g. `ApiVersioningOptions.DefaultApiVersion`). Once you apply an explicit mapping, any mapping, that convention is negated. This allows existing APIs to be grandfathered in without touching them. Once you touch anything, then all bets are off and you have to explicitly specify everything.

Based on your description of the problem, I _think_ you would be better off using _conventions_ as opposed to attributes. These are not mutually exclusive and you can use both, if you want. For example:

```c#
public sealed class MyAppConvention : IControllerConvention
{
    public bool Apply( IControllerConventionBuilder controller, ControllerModel controllerModel )
    {
        controller.HasApiVersion(1,0)
                  .HasApiVersion(2,0)
                  .HasApiVersion(2,1)
                  .HasApiVersion(3,0);
    }
}
```

Then, you'd just add it in the configuration:

```c#
services.AddApiVersioning(options =>  options.Conventions.Add( new MyAppConvention() );
```

You mentioned something about _groups_. This approach could be enhanced with your own attribute, metadata, or additional convention so that you apply a set of API versions to specific groups. An attribute would probably be the most appropriate and can be accessed via `controllerModel.Attributes`.

You can also map specific versions to methods this way; however, unless all of your controllers use the same names (which I suspect they don't), it is probably messy. The best option here is probably to continue using `[MapToApiVersion]`. No built-in convention exists actions for that, but you _could_ create one that works similar to**VersionByNamespaceConvention**. If your actions use suffixes such as `GetV1`, `GetV2`, and so on, you can figure out which action methods map to which version. If multiple versions map, then you might need something like `GetV1V2`. It's easy to identify action methods because they must be `public`, not `static`, and have not have `[NoAction]` applied. You can probably even get the pre-filtered list from `controllerModel.Actions` without any additional work.

If conventions aren't workable for you, then I would still recommend taking the attribute approach a step further. Rather than just list all of the versions for each application of the attribute, wrap it up in a single, more meaningful attribute. Something like:

```c#
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public abstract class ApiVersionsAttribute : ApiVersionsBaseAttribute, IApiVersionProvider
{
    protected ApiVersionsAttribute(params string[] versions) : base (versions) { }
    bool IApiVersionProvider.AdvertiseOnly => false;
    public bool Deprecated { get; set; }
}

// NOTE: you can even change the behavior to allow inheritance; WARNING: There be dragons!
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
public class GroupXApiVersionsAttribute : ApiVersionsAttribute
{
    public GroupXApiVersionsAttribute() : base ("1.0", "2.0", "2.1", "3.0") { }
}
```

You could then apply this to your controllers, or even your base controller, with `[GroupXApiVersions]`. 

Regardless of which way you go, there _is_ way that you an centrally manage your defined API versions. Careful consideration has to be made as to what is provided out-of-the-box and what you can customize or extend. There might not be a constructor for **ApiVersionAttribute** that allows multiple versions, but you can create one in ~10 lines of code. That's a fairly low bar in my box. 😉 

I hope that helps.
