### ISSUE TITLE
URL Path versioning does not work properly if Version is only set on base class

### ISSUE THREAD

**Issue by itavero** [Microsoft/aspnet-api-versioning#299]
Framework: .NET Core 2.0
Package version: 2.2.0

I made a `RoutePrefixExtension` to simplify/enforce using versioning via the URL Path (see [this gist](https://gist.github.com/itavero/2b40dfb476bebff756da35b5c7ff7384) for more information).
However, while using it I came across an error.

As I test I created two abstract base classes that inherit from `Microsoft.AspNetCore.Mvc.Controller`, have the `ApiVersion` attribute set and have some helper methods specific to that version of the API.
Lets say I have a `Version1BaseController` with the version set to `1` and a `Version2BaseController` with the version set to `2`.
I also have two "actual" controllers, one for v1 and one for v2. These only have the `RouteAttribute` added to the class (and some methods with `HttpGetAttribute` on them). Note that, like in the gist, the global prefix is set to `api/v{version:apiVersion}`.

When calling the V1 api (on the first controller) I get the expected response, when calling the same path but on the V2 api (lets say `/api/v1/test` vs `/api/v2/test`) I get an `UnsupportedApiVersion` error.
If I add the `ApiVersionAttribute` directly to the test controllers, I also get the expected output for the v2 endpoint.

To me this feels like a bug, but perhaps it is actually expected behaviour. I'd love to know. 😉

**Comment by itavero** [comment]
My configuration looks more like this

```csharp
[ApiVersion("1.0")]
public abstract class Version1Controller : Controller
{
  /* some protected helper methods over here */
}

[ApiVersion("2.0")]
public abstract class Version2Controller : Controller
{
  /* some protected helper methods over here */
}

[Route("api/v{version:apiVersion}/endpoint")]
public class FooController : Version1Controller
{
    [HttpGet]
    public override IActionResult Get() => Ok();
}

[Route("api/v{version:apiVersion}/endpoint")]
public class BarController : Version2Controller
{
    [HttpGet]
    public override IActionResult Get() => Ok();
}
```

As far as I can tell, I do not see any ambiguity in this code. However, I will not be able to hit one of those Get methods, because it will get redirected to the wrong controller.

**Comment by commonsensesoftware** [comment]
Yes - this _could_ work if the service author sets things up correctly. It's too much of a landmine, which is why it's not supported that way today. The **only** reason that this setup works is because the `Options.DefaultApiVersion` is `1.0`. If you used `2.0` and `3.0` or changed the default API version to some other value, I would expect them both to fail.

Controllers that have no direct decoration/annotation will have the default API version. This helps grandfather in existing services. As soon as any explicit version is apply by attribution or convention, then this behavior is out the window.

While I can certainly appreciate the desire to reduce duplication and improve efficiency, I've seen inheritance cause nothing but complexity and grief. Honestly, I think it's the wrong way to think about the problem and I steer people away from it. Agility and maintenance are important factors. I'll continue to noodling on this problem. Maybe there is an elegant way that inheritance can work, but so far I've only seen it cause issues.

A commonly overlooked issue is that you cannot _uninherit_ an API version or method. Inheritance is workable for additive scenarios, but, eventually, the time will come to completely remove functionality. That can be troublesome with inheritance.

**Comment by commonsensesoftware** [comment]
Were you able to resolve this issue? As far as I can tell, this is the expected behavior. In addition, `[ApiVersion]` is not inherited. This because most inheritance scenarios want to inherit code and/or functionality, not the API version. Furthermore, if it was, you could easily end up in a scenario with multiple controllers implementing the same API version which cause a separate set of headaches.

If you don't have anything else on this issue, then I think we can close it out. Thanks.

**Comment by itavero** [comment]
It was not clear to me that this is expected behaviour as I can apparently think of a use case for this (however I can also think of use cases where you would not want this).
I'll close this issue for now.
