### ISSUE TITLE
Adding a direct route doesn't work

### ISSUE THREAD

**Issue by Steveiwonder** [Microsoft/aspnet-api-versioning#305]
Hey,

I'm manually mapping a single route (which does't work) + using attribute routing (which does work).

For a single controller i'm calling the following:
```
  config.Routes.Add(
                action,
                new HttpRoute(
                    $"api/helloworld/sayhello",
                    new HttpRouteValueDictionary { { "controller", "helloworld" }, { "action", "sayhello" } }));
```
I then use
```
   config.AddApiVersioning(
                    o =>
                    {
                        o.Conventions.Controller<HelloWorldController>().IsApiVersionNeutral();                   
                    });
```

However i get
![image](https://user-images.githubusercontent.com/1899448/40924379-0ccef0be-680f-11e8-9086-af493f856cb1.png)
If i supply an api version i get
![image](https://user-images.githubusercontent.com/1899448/40924420-2029ce0e-680f-11e8-9a4c-c106c40636ae.png)

All routes that use attribute routing work fine i'ts just the manually added route. Is this supported?

**Comment by commonsensesoftware** [comment]
Yes - this is supported.

First, I'll say that I would avoid mixing direct routing (aka attribute routing) and convention-based routing. While it's a supported scenario, it's difficult to reason about. You definitely should not mix styles for a logical API controller (e.g. "HelloWorld") or you _could_ hit an unsupported scenario due to the limitations in Web API's routing.

You didn't provide your controller description, but I assume it's something like:

```c#
public class HelloWorldController : ApiController
{
    [HttpGet]
    public IHttpActionResult SayHello() => Ok("Hello world!");
}
```

You also didn't say what the route was that you requested, but I assume that it was probably:
`http://localhost/api/helloworld/sayhello`

This would not work because you have not specified an API version. A version-neutral controller means that it accepts **any** API version, including none at all. This often trips developers up. I document it as _opting out_ of API versioning, but that is a misnomer. I use that language because it tends to be the easiest to understand, but it's not entirely accurate. API versioning requires and enforces that **all** APIs have an API version. A _version-neutral_ controller just means it doesn't care which version you give it.

To make this request work without specifying any API version, you must also configure `options.AssumeDefaultVersionWhenUnspecified = true`. Use caution when configuring this option as it may have other unintended side effects. This option was meant to support legacy APIs that are grandfathered into versioning, but some developers use it for other purposes.

If you don't want to allow requests without an API version, then all you need to do is add an API version to your request - any API version. The following will work as currently configured:
`http://localhost/api/helloworld/sayhello?api-version=1.0`

I hope that helps.

**Comment by commonsensesoftware** [comment]
Were you ever able to get things working?

**Comment by commonsensesoftware** [comment]
Seems like you found a solution. Feel free to re-open this or open a new issue if you're still stuck. Thanks.
