### ISSUE TITLE
Support Microsoft.AspNet.OData v7.0

### ISSUE THREAD

**Issue by artsherwood** [Microsoft/aspnet-api-versioning#315]
With Microsoft.AspNet.OData v7.0, namespaces were changed from System.Web.OData to Microsoft.AspNet.OData

**Comment by commonsensesoftware** [comment]
I am aware of this. It's not pushed up yet, but I've already made the required changes. It's unfortunate that they keep shifting things around, but I do agree the consistency makes sense. The forthcoming v3.0 of API versioning for OData will align to v7.0. Sadly, that means that v6.x, like v5.x, will be left behind because I can't support all the variations save for critical bugs (which I doubt) that may require something out-of-band. I'm working the acceptance tests now. You should expect to see all the new OData for Web API and Core sometime later this week at which time I'm hoping to publish out the first beta release. Thanks for the heads up.

**Comment by commonsensesoftware** [comment]
Things are progressing well and we're almost to the beta release. You can checkout all the latest, including the updates to OData 7.0 in the [v3.0](../tree/v3/src/Microsoft.AspNet.OData.Versioning) branch. Thanks.
