### ISSUE TITLE
Different behavior between V1.0 and Vx.x when a route is not found

### ISSUE THREAD

**Issue by alex-sameli** [Microsoft/aspnet-api-versioning#316]
I'm getting different behavior depending on what version I request when accessing a route which does not exist.

Setup:

```
 var constraintResolver = new DefaultInlineConstraintResolver
            {
                ConstraintMap =
                {
                    ["apiVersion"] = typeof(ApiVersionRouteConstraint)
                }
            };
 config.MapHttpAttributeRoutes(constraintResolver);
  config.AddApiVersioning();
   var options = config.GetApiVersioningOptions();

...
 config.Routes.MapHttpRoute("Error404", "{*url}", new { controller = "Error", action = "Handle404" });
```

Controllers:

 ```
    [RoutePrefix("api/test")]
    [ApiVersion("1.0")]
    public class Test1Controller : ApiController
    {
        [Route]
        public HttpResponseMessage Get()
        {
            return Request.CreateResponse(HttpStatusCode.Accepted,
                ResponseDataDocument.Create(new { Values = new[] { "3", "4" } }));
        }
    }

    [RoutePrefix("api/test")]
    [ApiVersion("2.0")]
    public class Test20Controller : ApiController
    {
        [Route]
        public HttpResponseMessage Get()
        {
            return Request.CreateResponse(HttpStatusCode.Accepted,
                ResponseDataDocument.Create(new { Values = new[] { "1", "2" } }));
        }
    }
```
A request to api/test/foo?api-version=1.0 results in a 404 (Handled by the error controller) which is in my opinion the expected behavior.

A request to api/test/foo?api-version=2.0 results in a 400 (Handled by the api version error provider)

Any idea why this is? It behaves the same if I use 1.5, 2.4 etc. instead of 1.0.

Cheers (Great package by the way!)

**Comment by commonsensesoftware** [comment]
This is almost certainly because you are mixing routing styles. _Direct routes_ (aka attribute routing) was bolted on as an after thought. There were already a number of limitations in the routing infrastructure and that just further conflated it.

I faced similar problems supporting OData side-by-side because, despite it having attributes, only really uses conventions under the hood. I wanted to be able to transition to or away from OData in manner that can coexist with vanilla Web API routes. After many attempts, I came to the conclusion that it's only possible if you stick to the same routing method.

It should be possible to mix and match, but the routing style per logical service should be the same. In my experience, I've seen nothing but trouble when routing styles are mixed. My recommendation is to choose one style and stick to it.

In re-reading your question, it seems you may only be asking about the difference between 404 vs 400. By design, 400 is returned when a request _could_ match, but didn't. This concept used to be based on an early version of the Microsoft REST guidelines that has since been removed. It's a tricky edge case. There isn't a clean way to disambiguate between the thing I asked for doesn't exist and I asked for it the wrong way. The 400 in this case (e.g. the API version is unmatched) is very much like the behavior for 405, 406, or 415. In fact, if the match fails because the HTTP method is unmatched, you'll get 405 with the same error message. The API version is really more of a request for representation rather than identity. 404 suggests the resource does not exist. In this case, the resource _might_ exist, but it can't be represented by the API version requested.

I hope that helps clear thing up. While this is the default behavior, it is possible to change or otherwise customize the error response, including mutating that status code.

**Comment by alex-sameli** [comment]
Thanks for the extensive answer, I'll try to elaborate my question a bit further. 

I expect that requests with the same url but only a different version behave exactly the same because handling components are (supposedly) setup the same.

While the request to "1.0" gets handled by the "catch all" route 
`config.Routes.MapHttpRoute("Error404", "{*url}", new { controller = "Error", action = "Handle404" });`

the "2.0" request gets handled by my custom IErrorResponseProvider

```
 public class ApiVersionErrorResponseProvider : IErrorResponseProvider
    {
        public HttpResponseMessage CreateResponse(ErrorResponseContext context)
        {
            return context.Request.CreateResponse(HttpStatusCode.BadRequest,
                ResponseExceptionDocument.Create(context.Message, new[] { context.MessageDetail }, HttpStatusCode.BadRequest));
        }
    }
```

Setup like this 

```
var options = config.GetApiVersioningOptions();
 options.ErrorResponses = new ApiVersionErrorResponseProvider();
```

Thats why I get different status codes for a similar request (The difference itself is clear, also what component produces them), I just can't elaborate on why this is happening.

Cheers Alex

**Comment by commonsensesoftware** [comment]
Interesting... I was able to repro  the behavior you're seeing. It does seem it should behave like that. The requested route doesn't exist so it _should_ always be 404. Never seen this before. I'll look into it.

**Comment by alex-sameli** [comment]
Thanks, much appreciated!

**Comment by alex-sameli** [comment]
Any news on the issue? 

Thanks!

**Comment by commonsensesoftware** [comment]
Thanks so much for your patience. As you may have noticed, most of my extra time has been buried in trying to get the 3.0 release, especially the OData on ASP.NET Core, out the door.

I'm a little embarrassed to say that this is actually by design. I wasn't paying close enough attention to your setup. Here's why...

Once you enable API versioning, all controllers must be versioned - period end. You can make a controller API _version-neutral_, but that does not truly _opt-out_. It just means that all API versions are accepted, including no version at all. If you already had a bunch of services (e.g. controllers) and you had to go touch every, single one to turn API versioning, that could be painful. To accommodate that scenario, if a controller has no other decoration or conventions applied, it will be inferred to be whatever `options.DefaultApiVersion` indicates. If you don't specify your own value, the default value is `1.0`. Once any decoration or convention is applied, this rule no longer applies (or you could never get rid of that version).

So what does that mean in your scenario? Coincidentally, you have two `api/test` controllers with API versions `1.0` and `2.0`. You also have an _error_ controller. However, the **ErrorController** does not have any attribute decoration. With your specific setup, this means that controller has an API version of `1.0`.  This is why `api/test/foo?api-version=1.0` gives you the expected result, but `api/test/foo?api-version=2.0` doesn't. To resolve this issue, you can use one of the following:

### Version the Errors Controller
```c#
[ApiVersion("1.0")]
[ApiVersion("2.0")]
public class ErrorController : ApiController
{
    [HttpGet]
    public IHttpActionResult Handle404() => Ok(new { Message = "A 404 has occurred." });
}
```

### Make the Errors Controller Version-Neutral
```c#
[ApiVersionNeutral]
public class ErrorController : ApiController
{
    [HttpGet]
    public IHttpActionResult Handle404() => Ok(new { Message = "A 404 has occurred." });
}
```

With this change, you'll see that `api/test/foo?api-version=1.0` and `api/test/foo?api-version=2.0` both give you the expected result.

Sorry about the confusion. I hope that clears things up.

**Comment by alex-sameli** [comment]
Hey there,

Don't worry about it, the little wait was no issue at all. Thanks for taking a closer look at my setup and point me in the right direction!

Consider the issue solved, thanks again for the awesome work you're doing!
