### ISSUE TITLE
v3.0 Beta 1

### ISSUE THREAD

**Issue by Mhirji** [Microsoft/aspnet-api-versioning#324]
Hi, So I must be missing something, but cannot figure out what.  I added in the nuget package for Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer 3.0.0-beta1.  Everything installed without an issue.  Following the example for Swagger and Odata on dotnet core, 

Calling
services.AddOData().EnableApiVersioning(); 
Gives me IODataBuilder does not contain a definition for EnableApiVersioning();

Calling

services.AddODataApiExplorer(
                options =>
                {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                });
Gives me IServiceCollection does not contain a definition for AddODataApiExplorer

Passing VersionedODataModelBuilder to Configure() gives me VersionedODataModelBuilder cannot be found. 

I have the same using statements so there must be something I have missed.  Any help would be greatly appreciated.

Thanks!!

Also, Thanks for working so hard on this package, it really is useful!!

**Comment by Mhirji** [comment]
Not a problem, I'll keep an eye out.  Thanks for getting back so soon!!

**Comment by commonsensesoftware** [comment]
The issue seems to be resolved. The `i`'s are dotted and the `t`'s are crossed. The packages should now be available at:

* [Microsoft.AspNetCore.OData.Versioning](https://www.nuget.org/packages/Microsoft.AspNetCore.OData.Versioning)
* [Microsoft.AspNetCore.OData.Versioning.ApiExplorer](https://www.nuget.org/packages/Microsoft.AspNetCore.OData.Versioning.ApiExplorer)

I'll be updating links, documentation, and the wiki in the coming days.
