### ISSUE TITLE
Custom Error Response

### ISSUE THREAD

**Issue by Inquisitor-Sparkles** [Microsoft/aspnet-api-versioning#325]
My organization uses it's own internal error format across all services which is not compatible with the standard error format generated by the library when an invalid API version is supplied.

Is there any way of customizing the error response?

**Comment by commonsensesoftware** [comment]
There sure is. It's documented under the [Error Response Provider](../wiki/Error-Response-Provider) topic. In short, you just need to implement the **IErrorResponseProvider** interface and change it in your options. It is also possible to extend the built-in **DefaultErrorResponseProvider**, but it sounds like you want to replace the entire thing.

The information available is pretty limited by design because you can't be guaranteed where you are in the pipeline. The only thing you can be sure is available is the current request, selected status code, error code, and an error message. You can choose to use as much as or as little of that information as you like. You can make the shape of the response whatever you want from that information or anything else that might be available from your application.

I hope that helps.

**Comment by Inquisitor-Sparkles** [comment]
Yes that's exactly what I was looking for. Thank you!
