### ISSUE TITLE
System.Resources.MissingManifestResourceException

### ISSUE THREAD

**Issue by imabusyman** [Microsoft/aspnet-api-versioning#331]
I get the following error when updating to latest alpha nuget

---------------
Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.SR.resources" was correctly embedded or linked into assembly "Microsoft.AspNet.OData.Versioning" at compile time, or that all the satellite assemblies required are loadable and fully signed.'
---------------

Happens when I call this

         public virtual void Configuration(IAppBuilder app, HttpConfiguration config)
        {
             config.EnsureInitialized(); <---Errors here
        }

I bring this to any of my projects and computers and get the same results

Thanks in advance

**Comment by imabusyman** [comment]
Here is the full stack

   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.SR.get_InvalidODataRouteOnAction()
   at Microsoft.AspNet.OData.Routing.VersionedAttributeRoutingConvention.GetODataPathTemplate(String prefix, String pathTemplate, IServiceProvider serviceProvider, String controllerName, String actionName)
   at Microsoft.AspNet.OData.Routing.VersionedAttributeRoutingConvention.<>c__DisplayClass13_0.<GetODataPathTemplates>b__0(ODataRouteAttribute route)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.AspNet.OData.Routing.VersionedAttributeRoutingConvention.BuildAttributeMappings(IEnumerable`1 controllers)
   at Microsoft.AspNet.OData.Routing.VersionedAttributeRoutingConvention.<>c__DisplayClass2_1.<.ctor>b__0(HttpConfiguration config)
   at Com.TheToroCo.Common.Odata.Versioning.Odata.ToroVersionOwinStartup.Configuration(IAppBuilder app, HttpConfiguration config) in .....

**Comment by commonsensesoftware** [comment]
Which package versions are you using? You mentinoed _alpha_, but I don't have any _alpha_ packages published. If you're able to share the world's simplest repro project, that would go a long way in helping troubleshoot the problem.

**Comment by imabusyman** [comment]
Sorry, beta

https://www.nuget.org/packages/Microsoft.AspNet.OData.Versioning/3.0.0-beta1

**Comment by commonsensesoftware** [comment]
Unfortunately, I'm unable to repro your scenario. Attached is the basic OData sample for Web API using only NuGet package references. I was able to build and run it with issue. Perhaps you can use it to compare against your setup.

[BasicODataWebApiSample.zip](https://github.com/Microsoft/aspnet-api-versioning/files/2307859/BasicODataWebApiSample.zip)

**Comment by lalitjairaj** [comment]
@imabusyman were you able to resolve this? Facing similar issue.

**Comment by imabusyman** [comment]
No I had to make a new Selector class and SelectController to give our a custom error for invalid routes. 

The SR resx file was the issue not only on my primary machine, but it was on my secondary machine as well, something to do with the resx file??  

I might be doing something wrong as well.

**Comment by lalitjairaj** [comment]
I took the latest from the source and built in again. It got rid of this error, but results in a routing issue.

**Comment by lalitjairaj** [comment]
Is it possible for the admins to update the nuget repository. It seems to be a passing glitch.

**Comment by commonsensesoftware** [comment]
Before anything can be classified as a _glitch_ there needs to be a repro. I provided a working example above that uses the published package. I've even gone so far as to delete the cached NuGet package and restore store package again. It still works fine.

Given the seemingly bizarre nature of this issue, my first guess is that you have a bad binding redirect - somewhere. It's hard to troubleshoot the problem without some type of repro to work with. Please compare your project with the working example above or provide the world's simplest repro so I can help you troubleshoot it.

Thanks

**Comment by lalitjairaj** [comment]
Hi Chris, Understand your predicament. I am attaching a sample. I was able to repro the problem. The issue is that when ODataPathTemplateHandler.ParseTemplate call in VersionedAttributeRoutingConvention.GetODataPathTemplate throws an error, the catch block goes and looks for a resource file based on the current culture which it does not find and throws the following error 
![image](https://user-images.githubusercontent.com/19303044/45211312-95614180-b2af-11e8-8d1f-42ed40daf684.png)

I have deliberately passed the wrong path to the  ODataRoute in SampleOdataController.ComplexPatch action.

[Sample.OData.Versioning.Issue.zip](https://github.com/Microsoft/aspnet-api-versioning/files/2360491/Sample.OData.Versioning.Issue.zip)

Hope this helps.

**Comment by icnocop** [comment]
Hi.

I was able to reproduce this issue as follows:
In `.\aspnet-api-versioning\samples\webapi\BasicODataWebApiSample\Controllers\OrdersController.cs`
Change `[ODataRoutePrefix( "Orders" )]` to `[ODataRoutePrefix( "api/Orders" )]`
Try to perform a `GET` request on `http://localhost:4129/api/Orders?api-version=1.0`

Thank you.

**Comment by commonsensesoftware** [comment]
@lalitjairaj  thanks for the repro. I'll take a lot as needed.
@icnocop thanks for the scenario. this is easily repeatable. this enabled me to final repro the issue with minimal effort.

I was finally able to confirm that this issue occurs [here](../blob/master/src/Common.OData/AspNet.OData/Routing/VersionedAttributeRoutingConvention.cs#L124) in **VersionedAttributeRoutingConvention.cs**. This location is shared between Web API and ASP.NET Core using a _Shared_ project. It appears that the code from the typed resources are compiled and linked in, but the corresponding \*.resx files, and thus the \*.resources files, are not.

The _real_ reason that @imabusyman  and @lalitjairaj  are seeing this is because they have an invalid OData configuration. Either the containers or route configurations are incorrect. This causes an exception to be thrown, but the corresponding string resource for the error message can't be loaded, which results in a new and misleading **MissingManifestResourceException**.

This should be an easy fix. I expect to have something out this week. Thanks for your patience.

**Comment by lalitjairaj** [comment]
Thanks

**Comment by imabusyman** [comment]
Thanks
