### ISSUE TITLE
API versioning and Controllers inheritance does not work well together.  Unexpected code invoiced.

### ISSUE THREAD

**Issue by paveldayneko** [Microsoft/aspnet-api-versioning#332]
I'm trying to use versioning along with controllers inheritance but facing an unexpected behavior.
I'm using .net Framework 4.7.1 + Owin + Autofac. 

 WebApi configuration:

``` C#    
public class Startup
    {
        public void Configuration(IAppBuilder appBuilder)
        {
            var config = new HttpConfiguration();
            
            var resolver = new DefaultInlineConstraintResolver
            {
                ConstraintMap =
                {
                    ["apiVersion"] = typeof(ApiVersionRouteConstraint)
                }
            };

            config.MapHttpAttributeRoutes(resolver);
            config.AddApiVersioning();

            var builder = new ContainerBuilder();
            builder.RegisterApiControllers(Assembly.GetExecutingAssembly());
            config.DependencyResolver = new AutofacWebApiDependencyResolver(builder.Build());

            appBuilder.UseWebApi(config);
        }
    }
```
Controller: 
``` C#
namespace Versioning.API.Controllers
{
    using System.Web.Http;
    using Microsoft.Web.Http;

    [ApiVersion("1.0")]
    [RoutePrefix("api/v{api-version:apiVersion}")]
    public class ValuesController : BaseController
    {
        [Route("categories/{categoryId}/values")]
        [HttpPost]
        public IHttpActionResult PostIt(string categoryId, object body)
        {
            return Ok(nameof(PostIt));
        }
    }

    public class BaseController : ApiController
    {
        public IHttpActionResult GetAll()
        {
            return Ok(nameof(GetAll));
        }
    }
}
```
When I perform POST request to child controller's resource categories/{categoryId}/values everithing works fine, but if I try to perform GET request to the same resource GetAll method from Base contoller is called and result from it is returned which is really confusing.

I've spend some time debugging Source code and found courious parts which im my opinini might be in charge of issue described abowe.

ActionSelectorCacheItem.SelectAction() method performs 2 attempts to find appropriate method to process request. 
```C#
var firstAttempt = FindAction( controllerContext, selector, ignoreSubRoutes: false );

if ( firstAttempt.Succeeded )
{
    return firstAttempt.Action;
}

if ( controllerContext.RouteData.GetSubRoutes() == null )
{
    throw firstAttempt.Exception;
}

var secondAttempt = FindAction( controllerContext, selector, ignoreSubRoutes: true );

if ( secondAttempt.Succeeded )
{
    return secondAttempt.Action;
}
````
So during the first attempt of processing invalid GET request it fails, but during the second attempt it finds method in base class without paramethers and threats it as an appropriate one within method
ActionSelectorCacheItem.FindActionMatchRequiredRouteAndQueryParameters()

Could you take a look at it and provide an advice on how this issue could be resolved or bypassed, considering that I still would like to use controllers inheritance?

**Comment by commonsensesoftware** [comment]
As you're observing for yourself, inheritance causes a lot of problems, which is why I don't recommend it. The **only** type of inheritance I would recommend are base classes with common utility functions and so on. If you move all the business logic and other processing code to common types outside of the controller, then the functionality is still common and shared without all the complexity of inheritance. Also keep in mind that you cannot _uninherit_ an action, which really complicates things if you need to sunset an API.

If I understand your question correctly, you have an action on a base class that you only want to expose using attribute routing. The reason you are seeing this behavior is that API versioning has to consider both convention-based routing and direct route routing (aka attribute routing). The two are not mutually exclusive. As crazy as it might sound to some (myself included), there are a number of cases where services mix and match routing styles (I've seen it a few times). To function properly, API versioning first considers direct routes (e.g. attributes) and then considers convention-based routes. This is what you're seeing in the action selection.

Since your method is `public` it is considered a valid convention-based candidate. You could decorate it with `NonActionAttribute`, but I noticed that this attribute is inheritable. It will likely not yield the result you want even you override it in subclasses. It _might_; I honestly haven't tried. It will depend on whether inherited attributes are considered by infrastructure code. The only true way to make this work is to reduce the scope of method and then expose it with a `public` method in a subclass. For example:

```c#
namespace Versioning.API.Controllers
{
    using System.Web.Http;
    using Microsoft.Web.Http;

    [ApiVersion("1.0")]
    [RoutePrefix("api/v{api-version:apiVersion}")]
    public class ValuesController : BaseController
    {
        [Route("categories/{categoryId}/values")]
        [HttpPost]
        public IHttpActionResult PostIt(string categoryId, object body) => Ok(nameof(PostIt));

       [Route("categories")]
       public IHttpActionResult Get() => GetAll();
    }

    public class BaseController : ApiController
    {
        protected IHttpActionResult GetAll() => Ok(nameof(GetAll));
    }
}
```

If you don't know about it or haven't hit it yet, the other problem you will face with inheritance is that the `RouteAttribute` is not inheritable and the default `IDirectRouteProvider` will not honor inherited routes. This can be overcome by rolling your own implementation. There some existing issues that discuss how to do that. It's not particular difficult, but it's a default behavior in Web API.

The behavior that you're likely looking for is what's described in #230 to _stitch_ a logic API implementation together across multiple types. It's on my radar, but it's a lot more complicated under the hood than is being eluded to. Once the rest of 3.0 is solidified and out the door, that will likely be the next big investment area.

I hope that helps and clears things up. Let me know if you have more questions.

**Comment by paveldayneko** [comment]
@commonsensesoftware thanks a lot for such a detailed answer!
