### ISSUE TITLE
Is group versioning supported

### ISSUE THREAD

**Issue by phatcher** [Microsoft/aspnet-api-versioning#334]
Is the Microsoft REST API group versioning supported i.e.

12.1.1 Group versioning
Group versioning is an OPTIONAL feature that MAY be offered on services using the query string parameter mechanism. Group versions allow for logical grouping of API endpoints under a common versioning moniker. This allows developers to look up a single version number and use it across multiple endpoints. Group version numbers are well known, and services SHOULD reject any unrecognized values.

Internally, services will take a Group Version and map it to the appropriate Major.Minor version.

**Comment by commonsensesoftware** [comment]
Yes! ;) The full documentation can be found on the wiki under the [version format](../wiki/Version-Format) 
topic. In code the value manifests itself as `ApiVersion.GroupVersion`, which is a `DateTime` assuming that style is used. The _group version_ seems to imply other capabilities, but it's more or less just versioning by date. You can use the date value alone or combine it with major, minor, and/or status. I hope that helps.

**Comment by phatcher** [comment]
@commonsensesoftware Thanks for that, what I was trying to do was slightly different as per the Azure versioning where you have a date say 2018-08-15 and that equates to version 1.3 or version 2.0.

Looking at the docs again I can see it's one of the overloads on ApiVersion, might be good to provide at least one example of this.

BTW Would you like a pull request(s) for this and also updating the samples to ASP.NET Core 2.1 etc?

**Comment by commonsensesoftware** [comment]
What the REST guidelines are referring to is a scenario where a service team wants to map a _group version_ to a conventional _version_.

e.g. `ApiVersion -> Version`

The **ApiVersion** type supports a union of all forms - in total or in part, but there is no direct support for _translation_ to **System.Version**. The use of **System.Version** is an implementation detail behind the service. If a service team wants to create their own mapping between API version and a compiled assembly version, they are welcome to do so. People have asked for that before, but honestly, I don't really see what value that would bring. If that's really something a team wants for _traceability_ of the compiled code, I would recommend using **AssemblyInformationalVersionAttribute** or **AssemblyMetadataAttribute** instead, which would allow specifying the corresponding API version.

Is there something specific from ASP.NET Core 2.1 that you think should be in the samples? There are countless possibilities for the samples. I try to keep to them as simple as possible to highlight the relevant API versioning parts. I'm open to making them more _realistic_ though.

**Comment by phatcher** [comment]
I think the idea from what I can see with the Azure APIs is to allow you to semi-fix your client to a supported version whilst allowing the service team to define what they support for particular endpoint...

From the guidelines we see this table

Group | Major.Minor
-- | --
2012-12-01 | 1.0
  | 1.1
  | 1.2
2013-03-21 | 1.0
  | 2.0
  | 3.0
  | 3.1
  | 3.2
  | 3.3

I view these as API gateway entry points; we wrote version 1.0 and incrementally developed it to 1.2. Then we did a complete re-write for version 2.0 but due to the nature of it we could only implement 1.0 support.

May be these sorts of concepts are too much to implement in at this layer but one approach would be to allow ApiVersion(string, [DateTime]) which would then provide enough information to return this sort of data.

How this is exposed via the versioning API is left as an exercise for the reader ;-)

Updating for 2.1 was just making the code work with the latest public version of the library and the most likely versions for all of the ASP.NET Core libraries/Swashbuckle etc

**Comment by commonsensesoftware** [comment]
It appears that this thread has reached a conclusion. I'm happy to reopen to discuss further. Thanks.

**Comment by BlackRider97** [comment]
@commonsensesoftware  I am not fully sure what is exact requirement of @phatcher around group versioning. but what I am looking for the scenarios is like this which is somewhat similar to his requirement.

**On date 2020-12-01**
Two new APIs added first time in two different controllers. i.e. `CatController` and `DogController`

- `GET /cat`  (implementation 1.0)
- `GET /dog` (implementation 1.0)

**On date 2020-12-02** 
`/cat` implementation updated to 1.1  which is guaranteed backward compatible while `/dog` API implementation is still older.

- `GET /cat`  (implementation 1.1)
- `GET /dog` (implementation 1.0)

**On date 2020-12-03** 
`/dog` implementation updated to 2.0 which is not backward compatible while `/cat` API implementation is still older.

- `GET /cat`  (implementation 1.1)
- `GET /dog` (implementation 2.0)

**On date 2020-12-04** 
`/dog` implementation updated to 2.1 which is guaranteed backward compatible while `/cat` implementation updated to 2.0 which is not backward compatible.

- `GET /cat`  (implementation 2.0)
- `GET /dog` (implementation 2.1)

Group versioning concept says end user should be able communicate to service with a single common versioning moniker. 
> Group versions allow for logical grouping of API endpoints under a common versioning moniker  [link](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#1211-group-versioning)

So considering product stability in mind we want to group all exposed API endpoints under 3 different group versions with status. like 

`2020-12-01-preview`  (Preview)
- `GET /cat`  (implementation 1.0)
- `GET /dog` (implementation 1.0)

`2020-12-02`  (Stable)
- `GET /cat`  (implementation 1.1)
- `GET /dog` (implementation 1.0)

`2020-12-03-preview`  (Preview)
- `GET /cat`  (implementation 1.1)
- `GET /dog` (implementation 2.0)

`2020-12-04`  (Stable)
- `GET /cat`  (implementation 2.0)
- `GET /dog` (implementation 2.1)

Following REST API guidelines [example ](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#1211-group-versioning)
If an user hit an API  
- `GET/cat?api-version=2020-12-01-preview` then it should land on `1.0` implementation
   - Optionally `GET/cat?api-version=1.0` then it should land on `1.0` implementation
- `GET/dog?api-version=2020-12-01-preview` then it should land on `1.0` implementation
   - Optionally `GET/dog?api-version=1.0` then it should land on `1.0` implementation
 
- `GET/cat?api-version=2020-12-02` then it should land on `1.1` implementation
   - Optionally `GET/cat?api-version=1.1` then it should land on `1.1` implementation
- `GET/dog?api-version=2020-12-02` then it should land on `1.0` implementation
   - Optionally `GET/dog?api-version=1.0` then it should land on `1.0` implementation
   
- `GET/cat?api-version=2020-12-03-preview` then it should land on `1.1` implementation
   - Optionally `GET/cat?api-version=1.1` then it should land on `1.1` implementation
- `GET/dog?api-version=2020-12-03-preview` then it should land on `2.0` implementation
   - Optionally `GET/dog?api-version=2.0` then it should land on `2.0` implementation

- `GET/cat?api-version=2020-12-04` then it should land on `2.0` implementation
   - Optionally `GET/cat?api-version=2.0` then it should land on `2.0` implementation
- `GET/dog?api-version=2020-12-04` then it should land on `2.1` implementation
   - Optionally `GET/dog?api-version=2.1` then it should land on `2.1` implementation

Now questions are
1. how we can implement a versioning logic like this ?
2. Is it recommended API versioning pattern or I misunderstood the concept of group versioning ?
3. Is it common ask across different service owners who want to introduce concept of group versioning to their code base ?
4. If it is common ask then can that be handled by library itself where mapping is defined/controlled by service owner.

Also it is worth considering adding new implementation to a controller should not effect (no git diff change) all other controllers while introducing a single group version for all endpoints.

**Comment by commonsensesoftware** [comment]
This is a long one, but I'll try to keep it succinct.

1. Not really. By design, API versions must have a discrete mapping; ranges are not supported. The simplest way this can be achieved is having all of the _Major.Minor_ versions locked on the target implementation and then _float_ (e.g. move) the _Group_ version to the most current. That is more or less the same approach used when versioning by URL segment. It is possible to get range-like behavior using your own customizations and extensions.
2. Personally, I say - no - it's not a recommended pattern, but some people insist on doing/wanting it. The rationale is simple, the server **must** give consistent responses to the client. _Backward compatible_ is misunderstand and often done wrong in services. **Any** visible change to the contract over the wire is **not** _guaranteed_ to be backward compatible. People think that additive changes are backward compatible, but this is not always the case and you (the server) cannot _guarantee_ that it doesn't break some client (unless you own both sides in a closed system). In fact, the advent of _minor_ version is kind of a misnomer. It seems to imply that things are backward compatible, but there's no guarantee. The implementation version is a whole other matter that is internal to the service. If there are no visible changes, it doesn't matter which implementation version is used as the service version and contract haven't changed. The guidelines are just that - _guidelines_. They claim you shouldn't only use the _Group_ (e.g. date) version format, but that's the only format that clients refer to, what's the point or relevance of a _Major.Minor_. Experience has taught me that using dates is preferable to _Major.Minor_ because they express when a service was released. If/when it matters, it's impossible to do without additional documentation using _Major.Minor_. A date only also has the benefit that it doesn't imply there is any compatibility between versions. 
3. I wouldn't say it's a _common_ ask. There have been lots of asks about forwarding or floating versions. The rule of thumb is that things should be as explicit as possible. If a client asks for version `42.0`, then that's the version they should get or the server should fail. The server should not decide to give them something else. The one and only exception to this rule is _grandfathering_ in a service that didn't express a version. It has some _unnamed_ version that a client doesn't know how to ask for. Forcing versioning on these clients breaks them. You can configure things to allow no version to be specified and then choose the appropriate version via one of several selectors, though typically it should be the lowest version or a fixed version. Some people have abused this capability. If you're shifting around what the client asks for, then you're breaking the contract with the client and effectively defeating the purpose of versioning.
4. It's not a common ask, so no. To facilitate something like this, you'd need to replace and used your own _matcher policy_ in the routing system
5. Organization is highly subjective; however, organizing by version-per-folder is fairly sane. You don't _have_ to use attributes. You can use _conventions_ too. There is a built-in convention that will derive the API version from the containing namespace and, hence, the containing folder. Refer to the [version by namespace convention](../wiki/API-Version-Conventions#version-by-namespace-convention) documentation. I've seen teams use the _Copy and Paste_ method into a new folder to start a new version. This isn't all that unreasonable as a starting point. A key factor in long-term maintenance is defining a versioning policy ahead of time. If you're only going to support _N-2_ versions, then replicating into a new folder isn't big deal as you'll only ever have 3 folders at any one give time. You also have to decide if you'll use _symmetric_ versioning - meaning all services have the same version. That's harder to maintain, but easy for clients to understand. _Asymmetric_ versioning promotes more flexible service evolution, especially in a large taxonomy, but that is difficult to maintain all in one place. If you have many services that way, it's best to break them apart into separate projects and/or use a plug-in style hosting model that makes it easy to shift things around. This all very situational.

Using conventions, be it by namespace or some custom method, may be the more flexible method versioning groups and/or swaths of controllers. By namespace and the fluent interface are the only out-of-the-box convention implementations, but you can certainly create a custom convention that can read from some configuration in a file, database, etc.

I hope that gives you some insight and direction to proceed.

**Comment by BlackRider97** [comment]
Yes @commonsensesoftware  you provided enough pointers to proceed further. From library perspective, discrete versioning makes more sense as order of versioning is subjective to implementer and things get dirty quickly if it mix of versioning format. 
For our team, I have written range extensions which works on group API versioning format and using different name spaces to separate out contracts.

**Comment by BlackRider97** [comment]
Yes @commonsensesoftware  you provided enough pointers to proceed further. From library perspective, discrete versioning makes more sense as order of versioning is subjective to implementer and things get dirty quickly if it mix of versioning format. 
For our team, I have written range extensions which works on group API versioning format and using different name spaces to separate out contracts.
