### ISSUE TITLE
Header Version Reader showing up as query parameter in Swashbuckle/Swagger

### ISSUE THREAD

**Issue by luke-barnett** [Microsoft/aspnet-api-versioning#344]
I've configured api versioning and set my options to use HeaderAPIVersionReader:

```
GlobalConfiguration.Configuration.AddApiVersioning(options =>
                {
                    options.ReportApiVersions = true;
                    options.DefaultApiVersion = new ApiVersion(1, 0);
                    options.AssumeDefaultVersionWhenUnspecified = true;
                    options.ApiVersionReader = new HeaderApiVersionReader("api-version");
                });
````
But it is showing up in swagger as a query parameter and hence confusing end users:

![image](https://user-images.githubusercontent.com/3019217/45732695-942a0000-bc31-11e8-8959-2500869f443e.png)

What am I missing to get this showing up as a header parameter?

**Comment by commonsensesoftware** [comment]
Have you added the API versioning flavor of the [API Explorer](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Versioning.ApiExplorer)? This is required to populate the information correctly in Swagger. I assume that you probably have.

The issue is more likely a problem with using a header in Web API. Unfortunately, the **ApiParameterSource** defined by Web API only supports the values `FromUri`, `FromBody`, and `Unknown`. This is clearly a significant oversight in Web API. The API Explorer really has no _good_ alternative for headers, so the source is mapped to `Unknown`. Since Swashbuckle doesn't know what to do with `Unknown` to falls back to assuming the query string. This should be the behavior that you're seeing.

To workaround this limitation, you'll need to create and register a custom **IOperationFilter**. For example:

```c#
public class UpdateParameterSource : IOperationFilter
{
  public void Apply(
      Operation operation,
      SchemaRegistry schemaRegistry,
      ApiDescription apiDescription )
  {
      foreach ( var parameter in operation.parameters )
      {
          var descriptions = apiDescription.ParameterDescriptions;
          var description = descriptions.First( p => p.Name == parameter.name );

          if ( description.Source == ApiParameterSource.Unknown )
          {
              parameter.@in = "header";
          }
      }
  }
}
```


I hope that helps.

**Comment by luke-barnett** [comment]
@commonsensesoftware Thanks, that's exactly what I needed. Is this the case with the core equivalents for api versioning? Just so that I'm aware to look out for this in all cases.

**Comment by commonsensesoftware** [comment]
This issue does **not** apply to ASP.NET Core. The ASP.NET team did a much better job of thinking this through and there are many locations for parameters. As a basic example, Web API only had `FromUri`, but that doesn't indicate whether the descriptor is from the path or query string. Swashbuckle detects the difference by determining whether the descriptor is also a route parameter. In ASP.NET Core, the descriptors clearly indicate if they come from the path or query string.
