### ISSUE TITLE
Possible to use semantic versioning?

### ISSUE THREAD

**Issue by KarinBerg** [Microsoft/aspnet-api-versioning#346]
I want to use semantic versioning (https://semver.org) format for my APIs inside the url.
Like this: /api/v1.2.3/foo

But as far I could see this is not possible at the moment. Is that true or did I miss something?

**Comment by commonsensesoftware** [comment]
Correct. The **ApiVersion** is a sealed, unswappable type by design. _Semantic Versioning_ is not supported for API versions and likely never would be. API versions are meant to be explicit. They cannot intrinsically _float_ or have ranges, although there are some ways to _pseudo_ achieve such a goal. Concepts like _patch versions_ do no make sense in APIs because that's an implementation detail.

**Comment by commonsensesoftware** [comment]
Small point of order. The **ApiVersion** class isn't actually sealed; however, subclassing it probably wouldn't bring you much value and would be difficult to lace throughout the system. You would need to ensure you extend parsing and any other conventions where an instance of **ApiVersion** is created.

Aside from being difficult to do, it's still unlikely to achieve your goal. The matching process is explicit. The only use case for comparison (beyond equality) is for sorting purposes, which is used in scenarios like collation in the API Explorer.

It appears that you're content with this answer. Feel free to reopen the issue if you'd like to discuss things further.
