### ISSUE TITLE
Selecting highest implemented version

### ISSUE THREAD

**Issue by andyphilpotts** [Microsoft/aspnet-api-versioning#353]
If a request specifies version 2.0, and that specific version is not available, but a version 1.0 of the action could be a match, as far as I can tell there is no fallback, the answer is not found.

Instead, could we somehow specify that the resolution selects the highest implemented version that is less than, or equal to, the requested version.

Where this would seem to be useful is in the case of adding just a few version 2.0 actions to a large pre-existing API marked as version 1.0, this without requiring consumers to "just know" which methods do have 2.0 versions, and which do not.

In a sense, the requested version here is the client version, which stays the same across all requests.

**Comment by commonsensesoftware** [comment]
Correct - there is no fallback.  The client doesn't have a version; only the server does. This would be like if the client asks for JSON, but the server returns 200 + XML instead of returning 406 (Not Acceptable).

In my opinion, there should never be a case where the proverbial rug is pulled out from under the client. They should always know which version they are getting and be able to count on that. The one and only exception to that rule is the case of a legacy API where the client doesn't know the version. This API has _some_ unnamed, unnumbered version (perhaps _initial_, _legacy_, etc) that isn't spelled out, but clients are bound to it and it should never change. Everything else should always require an explicitly, requested API version or risk breaking the client. Despite what a service author might think is backward-compatible (say an attribute was added), a server cannot make any assumption that such a change will not break a client. In all likelihood it won't, but the server cannot guarantee that. Breaking a client would be bad.

I think that it is ill-advised, but you can make your scenario work by allowing the ommission of the API version and changing the API version selection method. For example:

```c#
AddApiVersioning( options =>
{
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.ApiVersionSelector = new CurrentImplementationApiVersionSelector( options );
});
```

This will allow a client to specify no API version and always get the latest version. Clients that don't want to roll the dice can still explicitly ask for specific API version.

From your description, it sounds like you have more of a server implementation issue. What I _think_ you are saying is that you have a small number of _actual_ changes and you want to roll everything forward to 2.0. Your current approach would only include _some_ new version 2.0 API changes, resulting in a need to _fallback_.

Solving this problem can be achieved fairly simply a few ways:
* When a new API version is declared, existing actions implicitly map to that version
* Use different controller types or API version interleaving to handle the split 
* Conventions can be used to minimize the amount of code that is touched
* Custom extensions, such as a custom attribute, can be used to map your _standard_ set of API versions

At the end of this, the client sees things as distinct, independent API versions, even though the implementation on the server might be exactly the same between versions. Services _should_ be allowed to version and evolve independently, but if you want all APIs to have the same consistent API version, this is how you can achieve it with consistent semantics for the client.

I hope that helps

**Comment by andyphilpotts** [comment]
This helps a lot, thanks, I agree there is something a bit icky about the client asking for 2.0, and getting 1.0, I appreciate all the detail you went into, and will see if I can plumb this in, in the cleanest way possible, I am dealing with existing behavior and third party clients which I am not able to change. Currently we have a "home-grown" versioned API and I would like to try to use this package as a replacement.
