### ISSUE TITLE
Version 3.0.0 beta 1 Odata route prefix shows up like a controller

### ISSUE THREAD

**Issue by figuerres** [Microsoft/aspnet-api-versioning#362]
i am trying to update a project to use the new Api Explorer. we have OData 4 controllers and i am seeing the route Prefix name showing up as if it was a controller.
if i remove the OData Explorer the phantom disappears.

Seems like a bug in the logic somewhere when it tries to enumerate the OData controllers.

**Comment by figuerres** [comment]
@commonsensesoftware   not core, my projects are asp.net 4.6.2  full framework at this time.
i will see if later this week or weekend i can post a repo with my code.
the bad data has the odd pattern of being  the routeprefix but no OData entity
so say the prefix was "odata"  and my model has Names and Addresses
i got something like this:

odata get
odata get 
odata post
odata patch
odata delete
odata/addresses get
odata/address get 
odata/addresses post
odata/addresses patch
odata/addresses delete
odata/names get
odata/name get 
odata/names post
odata/names patch
odata/names delete

so i filter out the ones that do not have a "/" to get a correct list

**Comment by commonsensesoftware** [comment]
Interesting. I haven't seen that before. I won't rule out the possibility of a bug. There are some oddities with the way OData deals with route prefixes. The ODL parser doesn't even consider it. A repro will definitely help with the investigation. Thanks.

**Comment by figuerres** [comment]
also i am seeing another issue

i have some api controllers that have the RoutePrefix("") attribute and methods have the Route("") attribute
with Swashbuckle i get them all with the route i expect to see.
with the new api explorer it looks like the Route("")  attribute is ignored or not applied so the swagger is actually missing a large number of methods on my api controllers.
i will not have time to create a repo of this right now but it looks like it is the use of the attributes.
it's geting http verbs for the prefix but not checking for multiple api methods as far as i can see.

i am going to have to see if i have to go back to pre 3.0  or back to the old packages i have been using.
can't go with missing service methods.

**Comment by commonsensesoftware** [comment]
There are some limitations in Web API routing that I cannot overcome (I've tried a few times). In particular, you cannot mix vanilla Web API direct routes (aka _attribute routing_) with OData with the same route template; more specifically to the same _logical_ controller. OData _attribute routing_ is completely different from the _Direct Routing_ feature (despite them both using attributes). As long as the route templates do not cross each other, it _should_ work.

I've always found mixing _Direct Routing_ and _Convention Routing_ together confusing. Due to this routing limitation, I recommend _Convention Routing_ **only** in this scenario as is demonstrated in the [Advanced OData Web API Sample](../tree/master/samples/webapi/AdvancedODataWebApiSample). If you insist on using _Direct Routing_ and you know the paths do not cross, there _shouldn't_ be anything more for you to do. It doesn't matter what combination of **RoutePrefixAttribute** and **RouteAttribute** you use. The default **IDirectRouteProvider** combines these two parts as required when it registers them in the route table.

I hope that helps clarify things. Let me know if you're still stuck.

**Comment by commonsensesoftware** [comment]
Seems like this issue is resolved. If you're still stuck or it's not resolved, feel free to reopen it. Thanks.
