### ISSUE TITLE
Is it possible to create non-numeric versions?

### ISSUE THREAD

**Issue by silkroadscott** [Microsoft/aspnet-api-versioning#37]
In addition to the standard, incrementing version numbers, we want to support a version called "beta" on our API (inspired by Microsoft's Graph API). Of course, the code in ApiVersion.Parse stops that in its tracks, as it strictly adheres to the version formatting rules laid out in the Microsoft REST API Guidelines. (I suspect that also means that it's unlikely to be an enhancement anytime soon.) I've been striking out with my attempted workarounds so far. Is there any way I can pull off including a version called "beta"?

**Comment by commonsensesoftware** [comment]
In the vernacular of these libraries, the term _beta_ is interpreted as a **status**.  _Status_ is fully supported and still compliant with the guidelines.

The following illustrates a few examples:
* /resource?api-version=0.9-**beta**
* /resource?api-version=1.0-**beta**
* /resource?api-version=1-**beta**
* /resource?api-version=2016-10-19-**beta**
* /1.0-**beta**/resource

I don't think the wiki lists every possible permutation, but if you'd like to see the numerous combinations, check out the [ApiVersion tests](../blob/master/test/Microsoft.AspNet.WebApi.Versioning.Tests/ApiVersionTest.cs).

Defining an API version that only has a _status_ is not supported.  I'm not sure there is any sensible way to rationalize just a status for an API version.  What does "beta" by itself mean? The "beta" of what?  I assume in your case, it's currently the beta of version 1.0; however, it could be the beta of any number of API versions. The status should, therefore, never be used by itself because it can be ambiguous.

If you have rolling updates for beta capabilities where breaking a client is known and acceptable, then you don't need API versioning for those routes. For example, in the Microsoft Graph API routes, all of the beta functionality is hung off the ```/beta``` segment.  This path is API version-neutral.  It's always a beta without any consideration for different versions.  I'm not familiar with that specific team, but I'm willing to bet that the expectation is that the beta URLs are allowed to break and change over time. If you want beta routes of your own like that without foregoing API versioning for other routes, I would map those routes under the "beta" prefix and mark them as API version-neutral. If you want to support varying beta implementations, then you'll need API version plus the _beta_ status as I've shown.

If you chose this type of implementation, keep in mind that a route cannot be both API versioned and API version-neutral at the same time. For example:

```
/v1.0/resource
/beta/resource
```

won't work if even one implementation of the _ResourceController_ is API version-neutral. You could, however, make the controller initially API version-neutral and then promote it to API version 1.0. In this scenario, the beta version doesn't exist anymore; hence, no ambiguity. This appears to be what the Microsoft Graph APIs do.

The only other approach that I can think of that would enable this scenario is to have an assumed, default API version for all beta APIs. This would allow you to maps beta implementations under the ```/beta``` segment and not require the client to provide an API version. Behind the scenes, you have a constant value or other mechanism to determine how the API version should be selected/mapped.  I generally steer people away from this type of advanced scenario because it can be quite complex to understand. If you're really interested in pursing this path, you'll want to review the [API Versioning Options](../wiki/API-Versioning-Options) and [API Version Selector](../API-Version-Selector) topics. There are also some built-in implementations and numerous tests you can follow for examples. If you get stuck, I can help point you in the right direction.

I hope that helps.

**Comment by silkroadscott** [comment]
I really appreciate the input. I'll review the links you provided and discuss it with my team. Thanks for all the information.
