### ISSUE TITLE
AddVersionedApiExplorer documentation out of date?

### ISSUE THREAD

**Issue by sugarjig** [Microsoft/aspnet-api-versioning#385]
The [instructions for adding the versioned API explorer to ASP.NET Core](https://github.com/Microsoft/aspnet-api-versioning/wiki/API-Documentation#aspnet-core) don't seem to be working for me. I get the following error when trying to call `services.AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VVV");`:
```
error CS1929: 'IServiceCollection' does not contain a definition for 'AddVersionedApiExplorer' and the best extension method overload 'IServiceCollectionExtensions.AddVersionedApiExplorer(IMvcCoreBuilder, Action<ApiExplorerOptions>)' requires a receiver of type 'IMvcCoreBuilder'
```
Calling `services.AddMvcCore().AddVersionedApiExplorer();` works. Is the documentation out of date, or am I missing something?

I am using Microsoft.AspNetCore.Mvc.Versioning version 2.3.0 and Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer version 2.2.0. Should there be a version 2.3.0 of Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer available in Nuget?

**Comment by commonsensesoftware** [comment]
It's actually the inverse - the documentation is **more** up-to-date. There are a number of improvements and optimizations that are introduced starting in 3.0. I've already updated the documentation for 3.0.  Full side-by-side documentation is difficult. The [API Explorer Options](../wiki/API-Explorer-Options) topic does call out this difference. I'll add an inline comment for this example.

**Comment by commonsensesoftware** [comment]
I've added a side note to hopefully avoid future confusion. Thanks.

**Comment by sugarjig** [comment]
Ah, that makes sense now. Thanks!

**Comment by commonsensesoftware** [comment]
I believe this issue has been resolved. Thanks for helping keep me up to date on the documentation. Let me know if you catch anything else or have more questions.

**Comment by desaifly** [comment]
This changes happened in core 2.2 and not 3.0. Please change the side note!

**Comment by commonsensesoftware** [comment]
@desaifly, I _think_ you may be confused by the term _"Core"_. ASP.NET Core != .NET Core. Until 3.0, ASP.NET Core could run on .NET Core or the full .NET Framework. In a similar fashion - I, nor this project, are part of the ASP.NET team or their release cadence. This project owns its releases and version numbers. The change you are referring to occurred in version 3.0 of API Versioning and has no implied relationship to ASP.NET Core or .NET Core. Unless something has changed in the last month, which I don't believe has happened, the examples for both 3.0 and the forthcoming 4.0 versions of API Versioning use the same setup. You can see the current example of API versioning 4.0 with Swagger using ASP.NET Core 3.0 which also happens to use .NET Core 3.0 [here](../blob/release/4.0/samples/aspnetcore/SwaggerSample).

If there are specific changes required for ASP.NET Core 3.0, I will update the wiki accordingly **after** it has been officially released. Thus far, however, I have not seen any changes that require an update. If you believe you have found or are otherwise aware of something that has changed or is out-of-sync, please feel free to bring it to my attention. Thanks.
