### ISSUE TITLE
[Question] Versioning behavior without specifying the minor

### ISSUE THREAD

**Issue by Sbou** [Microsoft/aspnet-api-versioning#388]
Hi,

I have a question about a behavior.
If we have 3 versions.
_1.0, 1.1, 2.0_

If I ask the API with **api-version=1** which version will be used ? 1.0 or 1.1 ?

If it's 1.0, how it's possible to ask the API with something like 1.* to be sure that I use the latest minor version (without breaking change) ?

Thank you,

**Comment by commonsensesoftware** [comment]
If a _major_ version component is specified without the _minor_ version component, then it is implied to be zero. This means that `1 == 1.0`.

API Versioning, intentionally, does not support ranges and most other types of implicit matching. There is absolutely nothing about the convention of `1.0 -> 1.1.` that _says_ it's backward-compatible. This is an assumption, falsely made, by human beings. Although it's entirely possible that it is backward-compatible, only an external policy can define that. The API version itself conveys no such policy. Furthermore, a server cannot guarantee backward-compatibility with a client, even with additive changes. While clients should be using a _tolerant reader_, that is not the only way that a client might break. A server doesn't know or have control over what a client is doing. Suppose a client uses schema validation on their side in validation of responses or uses it in their test suite. Adding any new attributes will likely break them, even with additive changes. In a small, closed, or well-documented environment where the versioning policy is stated, an implicit backward-compatibility story _may_ work.

The API version is not purely numeric. It can be a date, number, and/or have a status. Comparisons and equality can be performed, but incrementing and decrementing cannot. There's no logical way to determine what the next minor version should be. Furthermore, unless you are enforcing a symmetric versioning scheme across all APIs (which is not required), then the _latest_ minor version will vary by API. Enforcing symmetry on large API surfaces tends to seriously stymie service evolution because you may have to roll out new versions of APIs that haven't changed.

At the end of the day, a client _should_ know what they are asking for and get exactly that. Allowing the server to effectively pull the rug out from under the client is a bad idea. If you really want to implement such a behavior, it may be possible. The approach will depend on what platform you're running on. The API version will treat `1 == 1.0` for equivalency, but it doesn't actually make the minor version zero. This means that you can test if a minor version was specified and treat it like `*` when it's not (e.g. it's `null`).

I hope that helps.

**Comment by commonsensesoftware** [comment]
Did the answer help you come up with a solution or strategy?

**Comment by Sbou** [comment]
Thank you for your answer.

I figured out what you explained.

We’re going to change our strategy.

Thanks

Le samedi 3 novembre 2018, Chris Martinez <notifications@github.com> a
écrit :

**Comment by commonsensesoftware** [comment]
Great! Come back if you have more questions.
