### ISSUE TITLE
Looks like CORS is not supported

### ISSUE THREAD

**Issue by surajts** [Microsoft/aspnet-api-versioning#393]
When calling api with OPTIONS verb the library is throwing exception. Please see the sample code where I enabled cors. Then after that it can be reproduced by calling from POSTMAN. attaching the code where exception is occuring.

[BasicWebApiSample.zip](https://github.com/Microsoft/aspnet-api-versioning/files/2539782/BasicWebApiSample.zip)

![image](https://user-images.githubusercontent.com/7926724/47874265-61068f00-dde1-11e8-9505-1388704d0663.png)
![image](https://user-images.githubusercontent.com/7926724/47874281-67950680-dde1-11e8-9b19-61a080a0d2a6.png)

**Comment by commonsensesoftware** [comment]
I've often wondered about this case, but no one has ever reported it. I suspect that I **will** promote this to a bug because CORS should definitely be supported. A CORS preflight should also never enforce the requirement of an API version.

**Comment by figuerres** [comment]
hey just a general note:  i have long found that CORS can be a bloody pain to deal with.
it's well intended but it really does very little to secure anything and gives us another thing to configure.

**Comment by commonsensesoftware** [comment]
It's completely based on what you're doing. If you're doing **anything** with JavaScript to make web requests to another origin (e.g. domain), CORS is a must. The old mechanisms of using cross-site policy files (commonly used by Flash and Silverlight), were just plain dumb and hacks. All modern browsers support CORS and will flat out block cross-origin requests or deny JavaScript access to the response.

There are a couple of cases where this can be relevant to API versioning. It's not unthinkable for large applications to have separated UI and API domains. For example: `www.foo.com` and `api.foo.com`.  JavaScript API clients on `www.foo.com` will need a CORS policy defined on `api.foo.com` or the topology will not work. I've also seen this type of setup where the Swagger UI was hosted externally from the actual services. In order to use the **_Try It_** feature, a CORS policy must be defined for the Swagger UI to invoke the API.

>As an aside, CORS highlights a scenario that demonstrates using HTTP headers as the sole means for API versioning as the worst option. When a browser sends a CORS preflight request, it doesn't consider custom headers. This can be problematic on the API side if a version is required, but not provided.

I haven't dug into exactly how ASP.NET Core implements CORS, I suspect that conceptually it isn't that different from Web API. Effectively, the registered middleware lets a request go through. If it's not handled, the request is for `OPTIONS`, and the CORS headers are present, the middleware handles the CORS request; otherwise, the request ends up being 404 or 405. It should arguably always be 405, but I don't think that's necessarily reflected in the platforms' implementations.

**Comment by surajts** [comment]
The CORS is working ok with this library. Please see the attached project. 
[BasicWebApiSample (2).zip](https://github.com/Microsoft/aspnet-api-versioning/files/2550833/BasicWebApiSample.2.zip)

**Comment by commonsensesoftware** [comment]
What was the _magic_? A simple missing configuration or something?

**Comment by surajts** [comment]
I had to add the configuration in web.config. But I am still unable to use `    EnableCorsAttribute cors = new EnableCorsAttribute("http://something.com", "*", "*");
            configuration.EnableCors(cors);` So cannot control different domains at the controller or at the action level
