### ISSUE TITLE
Swagger support for ODataQueryOptions and ProducesResponseType

### ISSUE THREAD

**Issue by jimmy3912msncom** [Microsoft/aspnet-api-versioning#397]
I am utilizing 
```
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.5" />
<PackageReference Include="Microsoft.AspNetCore.OData" Version="7.0.1" />
<PackageReference Include="Microsoft.AspNetCore.OData.Versioning" Version="3.0.0-beta2" />
<PackageReference Include="Microsoft.AspNetCore.OData.Versioning.ApiExplorer" Version="3.0.0-beta2" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
```

In my controller when I want to enable query filter support 

```
[HttpGet]
[ODataRoute]
[ProducesResponseType(typeof(IEnumerable<Thing>), StatusCodes.Status200OK)]
public async Task<IActionResult> GetThingsAsync(ODataQueryOptions<Thing> queryOptions)
{
    ...
}
```

2 things of note:
1. The swagger documentation has queryOptions and assumes it's an object. Is there a way to enable it to understand the $filter, $count, etc... query options in OData? The only way I can do this today is by adding an IOperationFilter to edit this manually but I wanted to know if there was an out of box solution. I couldn't see any in the sample: https://github.com/Microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample
2. The ProducesResponseType attribute doesn't take into account OData returning collections in the form:
```
{
    "value": [
        {...},
         ...
    ]
}
```
so in swagger it shows up like:
```
[
   {...},
    ...
]
```

Is there some out of box way to support this? The only way I can get this to work is to create a class that looks like it and mention that type instead of IEnumerable<T>.

**Comment by jimmy3912msncom** [comment]
@Discjoggy Thanks. That answers my second question regarding the IEnumerable :)

Now if I can get an answer to my first question haha

**Comment by commonsensesoftware** [comment]
Thanks @Discjoggy. Yes - for the second part you definitely want to use `ODataValue<T>`. The **only** purpose of this type is to support the correct shape for the API Explorer, which then plugs into Swagger.

`ODataQueryOptions` is not currently supported. I'm not all opposed to supporting it. In fact, I actually consider it an important of an OData endpoint's API documentation. Such a feature will likely take some time to design, but I believe I still have some old code as a starting point; that's actually where the OData API Explorer implementation originated from.

The feature _should_ include support for `ODataQueryOptions` and `ODataQuerySettings`. The complex part is _how_ to express this information because it can come from conventions, attributes, or imperatively in code. I'm not sure there's enough time left to do this before the 3.0 release, but I'm happy to track it and certainly queue it up for 3.1. The determining factor will be how many issues creep up during the Beta 2 burn-in. If there aren't a lot of issues, then I may have bandwidth to investigate this before the release.

**Comment by commonsensesoftware** [comment]
This request is now being tracked as #400

**Comment by jimmy3912msncom** [comment]
@commonsensesoftware  Thanks Chris. I'll continue tracking this. In the meantime I can work around it with my custom IOperationFilter implementation

**Comment by commonsensesoftware** [comment]
Great. Thanks for surfacing this. Hopefully, I'll be able to get the feature out sooner than later. If you have suggestions or feedback on what you have built for your **IOperationFilter** that you think would be useful for the API Explorer, feel free to add your comments to #400. Thanks.
