### ISSUE TITLE
UrlSegementApiVersionReader doesn't work with Microsoft.AspNet.WebApi.Cors

### ISSUE THREAD

**Issue by seanyao1** [Microsoft/aspnet-api-versioning#402]
It seems the preflighting of CORS was broken by aspnet-api-versioning if we use UrlSegmentApiVersion.
It always returns errors like below, although my request URL contains /api/v2/<controllerName>.

HTTP/1.1 400 Bad Request
Content-Length: 105
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
api-supported-versions: 1.0, 2.0, 3.0
Date: Tue, 20 Nov 2018 07:42:43 GMT

{"Error":{"Code":"ApiVersionUnspecified","Message":"An API version is required, but was not specified."}}

**Comment by commonsensesoftware** [comment]
Do you have a simple repro you can share? The only scenario I'm aware that may have issues with CORS is versioning by header because a preflight request will not automatically send custom headers.

**Comment by commonsensesoftware** [comment]
Since no additional information or repro was provided, I'm closing this issue out. Perhaps you solved things on your side. Using CORS is a supported scenario, but I need more context such as URLs and configurations. If you are able to provide more information or, better still, a repo, then I'm happy to reopen this issue and investigate. Thanks.
