### ISSUE TITLE
Does this work with RESTier?

### ISSUE THREAD

**Issue by Tiberriver256** [microsoft/aspnet-api-versioning#404]
I didn't see any specific documentation about working with RESTier but it does use all the same underlying technologies, so it should work in theory right?

**Comment by commonsensesoftware** [comment]
From a purely technical perspective, API versioning _could_ support RESTier. Unfortunately, the routing configuration for OData holistically is not all that extensible. The design has gotten more flexible with the adoption of dependency injection, but there would still be considerable developer work to make the necessary route configurations for API versioning. In fact, if you happen to look at the API versioning source code for OData, a significant part of it is merely reimplementing all of the route configurations.

Honestly, I don't have a deep knowledge of RESTier. I took a peek at their source and it appears that `MapRestierRoute` wraps over `MapODataServiceRoute`. The `MapODataServiceRoute` method is not used by API versioning and it instead provides the similarly named methods `MapVersionedODataRoute` and `MapVersionedODataRoutes`, which are API version aware. It don't see why - yet, a flavor of RESTier setup could not be created that could support API versioning.

I'm not opposed seeing a supported flavor of RESTier be supported, but it's quite doubtful at this point in time that I would support it. I'm virtually an army of one on this project and I already support 3 platforms. I'm not sure that I can take on more. Furthermore, from the information I've found there are quite a few flags that would make me hesitant, including:

* There's no _official_ release; despite calling it _General Availability_ (GA), the released package is still _Beta_
* There hasn't been any active development on RESTier for more than two years
* RESTier currently only supports ASP.NET Web API and not even the current version 7.x+
* Adoption numbers, based on package downloads, is fairly low
* Issues no longer seem to be answered, triaged, or otherwise resolved

It would seem that RESTier never got the true _green light_ for GA. It has all the indications that no more work is being done or may ever be done on it again. It might be worth asking the OData team or perhaps even an issue on RESTier itself to see if the project is still active. If it's still active and there is enough interest, I would consider supporting it in a future iteration. Otherwise, it would be up to the RESTier community to create a package that is API version aware, which should be a combination of API versioning for OData and RESTier.

I'm sure that's not the answer you were looking for, but I hope that provides some useful information.

**Comment by Tiberriver256** [comment]
Thank you for the great answer! The OData team continues to insist they are almost back to supporting RESTier. You can read our conversation with that team here:

https://github.com/OData/RESTier/issues/540

I fully understand the response though. Hopefully we can see some action on the project.

**Comment by NetTecture** [comment]
Well, it all runs around that Odata needs to start moving out of their slumber and move to the new 2.2 endpoint routing. Then this opens a lot of possibilities down the road to integrate.

Sadly, I am quite negative about the Odata team actually ever going to significantly move out of their slumber. History sadly talks badly about it ;( Still wishing. Like many here I am sold on OData - and stuck with the MS Stack. As bad as it partially is, trying to integrate in typescript is even worse.

**Comment by Tiberriver256** [comment]
Just thought I'd post back on this and say RESTier is back in active development and has released a couple of release candidates. They are getting very close to the first GA and then will focus on a re-write for .NET core. I opened a discussion on their end for versioning and support.

**Comment by robertmclaws** [comment]
Hello, my name is Robert McLaws, and I'm one of the project leads for Restier. I don't see any reason why we couldn't ship a NuGet package that bridges the gap between this library and Restier by shipping a .MapVersionedRestier() extension method.

We also refactored how services were added vs routing, so that should also make this a bit easier.

I'll look into it over the break and see if we can ship something by RTM. Thanks!

**Comment by commonsensesoftware** [comment]
No problem. Some of the work may (or may not) be predicated by the OData work happening for .NET Core 3.0/3.1. On both the old Web API stack and the (now legacy) **IRouter** method of routing in ASP.NET Core, API Versioning has to replace/extend the core action selection logic. This has been at odds with OData in the past, which does some of the same things. This is also what drove the OData-specific `EnableApiVersioning()` extension method because it was the only way to ensure the API Versioning changes came after OData. This requirement, in part, influenced the design of _Endpoint Routing_ (I met with the ASP.NET team a couple of times) and made it possible to extend the action selection rather than replace it. As it still currently stands, I've effectively had to fork a significant portion of the OData routing code to make it support versioning. =/

At its most basic roots, API Versioning doesn't really change anything about routing. It merely allows duplicates routes where duplicate routes would not have been allowed before and disambiguates them by API version. If duplicates still arise (e.g. developer mistake), the behavior should remain unchanged from routing without API Versioning. How API Versioning discovers and manages the versions is a cross-cutting concern that can be provided by attributes or conventions.

As things more specifically apply to the OData implementation, all of the other rules apply and API Versioning additionally creates a single EDM per API Version. This provides clean separation of each EDM and most things continue to work the same or similar to how they worked before (ex: `$metadata`, but now also with `$metadata?api-version=2.0` or whatever versioning method was used). Each EDM is also annotated with the **ApiVersionAnnotation** so you can tell which version the EDM is for.

Unfortunately, because OData uses a _catch-all_ route template (e.g. `{*odataPath}`) and then bolts on its own conventions, this adds some additional complexity. Specifically, an OData route is generated per API Version and EDM. There is also a special _unversioned route_ to maintain parity with the 400 behavior or an unmatched API version vs the normal 404 response.

I assume the ask is mostly for .NET Core, but I'm open to supporting the Web API stack too. You can find the .NET Core implementation setup [here](../blob/master/src/Microsoft.AspNetCore.OData.Versioning/AspNet.OData/Extensions/IRouteBuilderExtensions.cs) if you hadn't already seen it. It should look strikingly similar to the built-in OData setup, with additional configuration or hooks. I'm open to other ideas for setup too. I never really liked it, but I went with an approach that was similar to the out-of-the-box OData experience.

**Comment by robertmclaws** [comment]
Restier does not support .NET Core at all. We are shipping v1 with support for WebAPI2, so we can honor the work that the original team did. Since that tech was started in 2014, it doesn't make sense to carry that into 2020. We can support .NET Core more quickly if we rebuild Restier's interception pipeline so that it properly supports DI.

**Comment by commonsensesoftware** [comment]
Ah … ok … so were just talking about the Web API stack. No problem. It's certainly less work in the short run. ;)

[Here's the configuration setup](../blob/master/src/Microsoft.AspNet.OData.Versioning/System.Web.Http/HttpConfigurationExtensions.cs
) for Web API. The majority of things are the same between the platforms. The majority of the work has been making OData's routing API Version aware. There's a ton of unit and acceptance tests if that helps flush out things work. There's also a few sample applications.

Happy to answer any questions or chew on ideas. I'm not all that familiar with RESTier's inner working.

**Comment by commonsensesoftware** [comment]
I'm going back and cleaning up old issues. In terms of what _this_ project will do, I think the issue has reached its conclusion. As a one-man project, there's only so much I can facilitate on my own. Had I not already had a deep and long history with OData, it may never have been supported at all.

[5.0.0-RC.1](https://www.nuget.org/packages/Microsoft.AspNet.OData.Versioning/5.0.0-rc.1) is now available. This version has undergone a complete overhaul of the internal OData setup mechanics. It's simpler and more straight forward than ever before. As it relates to RESTier, the [IContainerBuilder](../blob/master/src/Microsoft.AspNet.OData.Versioning/OData/IContainerBuilderExtensions.cs) extensions required to enable API versioning services are publicly accessible. As proposed above, RESTier would likely need something like **MapVersionedRestier** which would use a setup similar to the [HttpConfiguration.MapVersionedODataRoute](../blob/master/src/Microsoft.AspNet.OData.Versioning/System.Web.Http/HttpConfigurationExtensions.cs) extension methods. If you had looked at these in the past, you'll notice that they are vastly simpler and is now able to pipe through to the core OData implementation. There may be a few things need to setup the correct routing conventions, etc, but all the pieces are there and it should be straight forward.

API Versioning replaces the following services in Web API:

- **IHttpControllerSelector**
- **IHttpActionSelector**
- **IApiExplorer** (if using API explorer extensions)

I don't see those being changed by RESTier so it shouldn't be affected. The changes to the way **ODataQuerySettings** are registered _might_ affect the way API Exploration works or otherwise reports query options. These can be addressed by using the query option configuration conventions for the versioning API Explorer extensions or it can be handled in your OpenAPI/Swagger generator of choice.

I'm happy to provide guidance, input, or potentially even make changes to support anyone's effort to bring versioning to RESTier. My best estimation is that versioning is possible with minimal effort. If ASP.NET Core is ever supported, the interaction and APIs to connect versioning to OData is very similar.

>Aside: The RC label is to allow for a little _burn-in_ to 5.0 before officially publishing. That should happen within the next 2 weeks from this post.

Thanks again for the interest, but this isn't a project I can take on here. Feel free to continue asking questions on this issue if there are any. Thanks.
