### ISSUE TITLE
services.AddMvc().SetCompatibilityVersion() does not work with OData

### ISSUE THREAD

**Issue by anish714** [Microsoft/aspnet-api-versioning#410]
```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

             app.UseMvc(routeBuilder =>
            {
                routeBuilder.MapODataServiceRoute("ODataRoutes", "odata", dwhBuilder.GetEdmModel(app.ApplicationServices));
            });
```
....

now throws the following exception when using OData.  

> System.InvalidOperationException: 'Cannot use 'Microsoft.AspNet.OData.Routing.ODataRoute' with Endpoint Routin

g.'

**Comment by commonsensesoftware** [comment]
The out-of-the-box OData implementation does **not** support _Endpoint Routing_. You'll want to file this issue on their repo. I'm not connected to their team directly or indirectly. There's no way I can _fix_ this.

API Versioning will support _Endpoint Routing_ soon, but it will using it's own facilities. The built-in OData routing facilities are different.

**Comment by commonsensesoftware** [comment]
I was hoping I'd be able to get a jump on this, but it's a lot of work that I honestly cannot own. API versioning is imminently about to support _Endpoint Routing_, but since OData does not intrinsically support _Endpoint Routing_ the API versioning support for OData doesn't either. As soon as the OData team supports _Endpoint Routing_, I'll make the necessary changes, if any. You can weigh-in on the existing, open issue in the OData repo OData/WebApi#1707. Thanks.
