### ISSUE TITLE
can't mapping not identify ApiVersionAttribute controller

### ISSUE THREAD

**Issue by ihenjoy** [Microsoft/aspnet-api-versioning#416]
my rest api has published, and has no control of apiversion
how do i can mapping not identify ApiVersionAttribute controller

**Comment by commonsensesoftware** [comment]
You'll need to clarify, but I _think_ you're asking how to apply an API version without using `[ApiVersionAttribute]`. This can be achieved using [conventions](../wiki/API-Version-Conventions). For example,

```c#
AddApiVersioning( options =>
    options.Conventions.Controller<ValuesController>().HasApiVersion( 1, 0 );
```

There are several ways that conventions can be applied. You _could_ even create a custom convention which loads information from an external storage such as a database.

You _might_ also be stating that you have an existing API and now you want to introduce API versioning. To prevent existing clients from breaking, you can use the option:

```c#
AddApiVersioning( options => options.AssumeDefaultVersionWhenUnspecified = true );
```

API versioning requires all controllers to have a formal API version, but this will allow clients to continue using the existing API without any changes. If a controller doesn't have any attributes, then it is assumed to have the API version defined by `options.DefaultApiVersion`. If not otherwise configured, this property has the value of `1.0`.

I hope that helps; otherwise, I'll need a little more information. Thanks.

**Comment by ihenjoy** [comment]
i have find the solution through checking the resource code .
and thank you for your anwser ,this is useful for me too

> You'll need to clarify, but I _think_ you're asking how to apply an API version without using `[ApiVersionAttribute]`. This can be achieved using [conventions](../wiki/API-Version-Conventions). For example,
> 
> ```cs
> AddApiVersioning( options =>
>     options.Conventions.Controller<ValuesController>().HasApiVersion( 1, 0 );
> ```
> 
> There are several ways that conventions can be applied. You _could_ even create a custom convention which loads information from an external storage such as a database.
> 
> You _might_ also be stating that you have an existing API and now you want to introduce API versioning. To prevent existing clients from breaking, you can use the option:
> 
> ```cs
> AddApiVersioning( options => options.AssumeDefaultVersionWhenUnspecified = true );
> ```
> 
> API versioning requires all controllers to have a formal API version, but this will allow clients to continue using the existing API without any changes. If a controller doesn't have any attributes, then it is assumed to have the API version defined by `options.DefaultApiVersion`. If not otherwise configured, this property has the value of `1.0`.
> 
> I hope that helps; otherwise, I'll need a little more information. Thanks.
i have got the solution for checking the source code. thank you so much for the answer, which is useful for me

**Comment by commonsensesoftware** [comment]
Great. Is this issue good to close now?
