### ISSUE TITLE
UnsupportedApiVersion error when route constraint prevents a match

### ISSUE THREAD

**Issue by sugarjig** [Microsoft/aspnet-api-versioning#423]
I have a controller with an action that specifies a route constraint. Here is a snippet.
```csharp
namespace Foo
{
    [ApiVersion("1.0")]
    [Produces("application/json")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiController]
    public sealed class ValuesController : ControllerBase
    {
        [HttpPut("{id:guid}")]
        public async Task<IActionResult> PutValueAsync(
            [FromRoute] Guid id,
            [FromBody] Value value)
        {
        }
    }
```
If I make a request with a valid GUID in the path (i.e. `PUT /api/v1/12345678-90ab-cdef-1234-567890abcdef`), everything works as expected. But if I use an invalid GUID in the path (e.g. `PUT /api/v1/1234`), I get a 400 with the following body:
```json
{
    "error": {
        "code": "UnsupportedApiVersion",
        "message": "The HTTP resource that matches the request URI 'https://localhost:5001/api/v1/consumers/be4d7d66-f01d-4766-a71d-66c0d82d947/consumption' does not support the API version '1'.",
        "innerError": null
    }
}
```
I'm expecting a 404 because no route is supposed to match, according to the [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#route-constraint-reference).

I'm using ASP.NET Core 2.2 and API Versioning version 3.1.

**Comment by commonsensesoftware** [comment]
Technically, this has been the existing behavior for API versioning due to limitations in the routing system. _Endpoint Routing_ addresses most of these limitations. I had things short-circuiting if a candidate is already invalid. This might exclude candidates that match the requested API version, but are already invalid (ex: due to an invalid route constraint) and ultimately produce an unexpected response. Since this wasn't the expected intent, I'll consider it a bug.  I should have the fix out shortly.

For future reference, here are the behavioral differences:

**Legacy Routing**

| Status Code | Source | Description |
| ------------- | -------- | ------------ |
| 400 | API Versioning | No matching API versions |
| 400 | API Versioning | Possible candidates, but no matches |
| 400 | ASP.NET | Invalid model state |
| 404 | ASP.NET | No matching candidates |
| 405 | API Versioning | No matching HTTP method |

**Endpoint Routing**

| Status Code | Source | Description |
| ------------- | -------- | ------------ |
| 400 | API Versioning | No matching API versions |
| 400 | ASP.NET | Invalid model state |
| 404 | ASP.NET | No matching candidates |
| 405 | ASP.NET | No matching HTTP method |

**Comment by commonsensesoftware** [comment]
[3.1.1](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/3.1.1) with the fix is now available. Thanks.

**Comment by sugarjig** [comment]
It's working now! Thank you!

**Comment by pwdst** [comment]
This issue appears to have returned as a regression in version 4.2.0
