### ISSUE TITLE
UnsupportedApiVersion on HttpPost without route [controller] value and provided route at action level

### ISSUE THREAD

**Issue by mail2sarathee** [Microsoft/aspnet-api-versioning#427]
I am having the error

{"error":{"code":"UnsupportedApiVersion","message":"The HTTP resource that matches the request URI 'http://localhost:40021/api/v1.0/PostOnly/dashboard/GetStatusChartData' with API version '1.0' does not support HTTP method 'GET'.","innerError":null}}

I try to hit a http post call with http://localhost:40021/api/v1.0/PostOnly/dashboard/GetStatusChartData and with some data

My Controller look like

```
   [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/")]
    [Authorize]
    public class PostonlyDashboardController : ControllerBase
    {

        [ActionName("GetStatusChartData")]        
        [HttpPost("Postonly/Dashboard/GetStatusChartData")]
        public async Task<IActionResult> GetStatusChartData([FromBody]ChartParams chartParams)
        {
            try
            {
```

Please suggest me where I went wrong

**Comment by commonsensesoftware** [comment]
You didn't happen to show or mention _how_ you are reaching this error, but from the message, it's pretty clear that you are receiving HTTP status code 405 (Method Not Allowed). This could only happen if you made a request to your service with GET instead of POST. This is exactly what I would expect to happen. I suspect if you make the request with the POST method, thing will start working.

**Comment by mail2sarathee** [comment]
Thanks for your response, I understand Its my silly mistake

**Comment by commonsensesoftware** [comment]
Sounds like you've solved your problem. Feel free to come back or reopen this issue if it's unresolved. Thanks.
