### ISSUE TITLE
Autoincrement version for controller

### ISSUE THREAD

**Issue by lleslie84** [Microsoft/aspnet-api-versioning#436]
Hi,
How would I automatically return the latest version for each controller? For instance.
`
        [ApiVersionRange(1, 3)]
	[Route("api/v{version:apiVersion}/[controller]")]
	[Route("v{version:apiVersion}/[controller]")]
	[Route("[controller]")]
	public class BaseApiController : Controller
	{

	}
	public class ThingsController : BaseApiController
	{
		[HttpGet]
		public IActionResult Get([FromBody] dynamic request)
		{
			return Ok(new List<dynamic> { new { Name = "James" } });
		}

		[HttpGet, MapToApiVersion("2.0")]
		public IActionResult GetV2([FromBody] dynamic request)
		{
			return Ok(new { Name = "James" });
		}

		[HttpGet, MapToApiVersion("3.0")]
		public IActionResult GetV3([FromBody] dynamic request)
		{
			return Ok(new { Name = "James", Company = "Test" });
		}
	}
	public class SettingsController : BaseApiController
	{
		[HttpGet]
		public IActionResult Get([FromBody] dynamic request)
		{
			return Ok(new List<dynamic> { new { Name = "James" } });
		}

		[HttpGet, MapToApiVersion("2.0")]
		public IActionResult GetV2([FromBody] dynamic request)
		{
			return Ok(new { Name = "James" });
		}
	}`
the customer would invoke the following endpoints:
http://localhost/app/v3/things
`result should be
{name: "james", company: "test"}
`
http://localhost/app/v2/things
`result should be
{name: "james"}
`
http://localhost/app/v3/settings
`result should be
{name: "james"}
`
http://localhost/app/v2/settings
`result should be
{name: "james"}
`
http://localhost/app/v1/settings
`result should be
[{name: "james"}]
`
http://localhost/app/v1/settings
`result should be
[{name: "james"}]
`
http://localhost/app/settings
`result should be
[{name: "james"}]
`

In the sample above SettingsController does not have a method corresponding to version 3. However, the latest version is returned for that controller and the default version is not returned

related to https://github.com/Microsoft/aspnet-api-versioning/issues/145

**Comment by lleslie84** [comment]
or is there a hook into ApiVersionActionSelector where I can change the behavior of SelectBestActions with having any performance penalty

**Comment by commonsensesoftware** [comment]
First, let's make sure we're on the same page with terminology here. When you say:

>_SettingsController does not have a method corresponding to version 3_

I think what you mean is that it is not explicitly decorated such that it maps to a specific API version. This is completely allowable and the default behavior; otherwise, you'd always have to use `[MapToApiVersion]` on every action  method. Based on your definition, the mapping is as follows:

```c#
public class SettingsController : BaseApiController
{
  // GET settings
  // GET v1/settings
  // GET api/v1/settings
  // GET v3/settings (because no other explicit mapping was found)
  // GET api/v3/settings (because no other explicit mapping was found)
  [HttpGet]
  public IActionResult Get([FromBody] dynamic request)
  {
    return Ok(new List<dynamic> { new { Name = "James" } });
  }

  // GET v2/settings
  // GET api/v2/settings
  [HttpGet, MapToApiVersion("2.0")]
  public IActionResult GetV2([FromBody] dynamic request)
  {
    return Ok(new { Name = "James" });
  }
}
```

I'm not sure why you need or want 3 different ways to get to the same controller. For people that like versioning by URL segment and want a _default_ route, they usually have two routes: one with the API version and one without (e.g. `api/settings` and `api/v1/settings`).

Then you stated:

>_the default version is not returned_

You haven't shared your configuration, so what _is_ your default API version? If it hasn't been otherwise specified, then the value is `1.0`.

The title of your question indicates _Auto Incrementing_, which is not supported - intentionally. It would seem you understand this and have extended things to generate a range, which is perfectly acceptable. Your actual question in the first few lines state:

>_How would I automatically return the latest version for each controller?_

Which is something else entirely. If you always want the latest or most current version of a controller returned, then you can use the configuration:

```c#
.AddApiVersioning( options =>
{
   options.AssumeDefaultVersionWhenUnspecified = true;
   options.ApiVersionSelector = new CurrentImplementationApiVersionSelector( options );
} );
```

This only works when no API version is specified (e.g. `api/settings` or `settings`). The API version for the current implementation (e.g. the max) is selected, which in this case is `3.0`. Selection is per controller so API versions do not need to be symmetrical across controllers. If no API version is available, the selection falls back to the value of `options.DefaultApiVersion`, which is usually `1.0`. When a client asks for a specific API version, that always takes precedence over other selection mechanisms.

I hope that helps clear things up.

**Comment by commonsensesoftware** [comment]
Well ... we're making some progress. I read your message a few times, but I still keep seeing 3 scenarios:

1. Legacy clients need to call an API, but get the original API version (this is the oldest API version it sounds like in your context, but that's not necessarily always the case)
2. New clients specify an explicit API version
3. _Some_ clients need to always get the latest API version

I'm struggling to understand how 3 comes into play. If you really need the behavior of 1 and 3, then I think you need a custom **IApiVersionSelector** that decides the behavior to take. This is why the current request is also provided during API version selection.

For example, you may be able to determine whether the incoming request is for a legacy client. When it is, choose the lowest API version from the available set. Likewise, you may be able to determine clients that want or need to use the most current implementation, in which case you return the max API version available. In all other cases, the API version should **always** match exactly what the client asked for.

If 3 isn't actually a required scenario and legacy clients always use the _initial_ API version, then you can use the **LowestImplementedApiVersionSelector**. I'm personally not a fan of devs that want to implement 3 because it's way too easy to pull the rug out from under the client. Service authors often assume that their clients can handle additive changes, but that's not necessarily true nor can they guarantee it.

The extension points allow you to define custom attributes for actions too. In fact, you can probably even use your existing **ApiVersionRangeAttribute** at the action level as long as you let it target a method. That should certainly be better than using Reflection. In addition, if attributes aren't working for you, you can use the _conventions_ approach. That _might_ be easier and would certainly be faster than using Reflection.

**Comment by lleslie84** [comment]
Thanks Chris,
I'll look into using the conventions approach, I think that should work.
I'll provide an update with the solution that worked, just in case any other developers have a similar requirement.

Thanks,
Lyon

**Comment by commonsensesoftware** [comment]
Sounds good. You can find documentation about _conventions_ on the [wiki](../wiki/API-Version-Conventions). You can also follow the [Conventions example project](../tree/master/samples/aspnetcore/ConventionsSample).

It's possible for you to provide the source of your conventions from an external data store such as a configuration file or database. You need only define how controller types map to API versions, load up the configuration, and apply it as a convention.

Let me know if you have more questions.

**Comment by lleslie84** [comment]
Hi Chris,
Below is the code used to achieve the behaviors described above. Hopefully, this helps someone if they have a similar requirement.

`
#if NETSTANDARD2_0

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.Versioning;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.Mvc.Versioning.Conventions;
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using Microsoft.AspNetCore.Mvc.Internal;

namespace ViaSat.PTE.TPT.Applications.Web.PTWS.CommonWeb.Versioning
{
	/// <summary>
	/// Convention that can be used to map the latest declared API version for a controller to the latest supported API version configured with the use of ApiVersionRangeAttribute
	/// https://github.com/Microsoft/aspnet-api-versioning/issues/145
	/// </summary>
	public static class LatestControllerApiVersionConvention
	{
		static bool ControllerDiscoveryInProgress { get; set; } = false;
		static List<(ActionDescriptor ActionDescriptor, ControllerActionDescriptor ControllerActionDescriptor, int MaxApiVersion)> _latestApiVersions;

		/// <summary>
		/// Discoveries the latest API version that is implemented by a controller and maps it to the latest API version specified by ApiVersionRangeAttribute .
		/// </summary>
		/// <param name="services">The services.</param>
		/// <returns></returns>
		public static List<(ActionDescriptor ActionDescriptor, ControllerActionDescriptor ControllerActionDescriptor, int MaxApiVersion)> DiscoveryLatestApiVersion(this IServiceCollection services)
		{
			/*
			* Retrieving an instance of IActionDescriptorCollectionProvider will cause the framework to re-invoke the AddApiVersioning middle-ware. In that case we need to
			* cache the result form the discovery providers and pass that data to the ApiVersioningOption convention.
			* I opted for IActionDescriptorCollectionProvider instead of ControllerActionDescriptorProvider since IActionDescriptorCollectionProvider will contain all controllers and their actions including the controllers
			* that are found by PageActionDescriptorProvider
			* 
			* */

			if (_latestApiVersions != null && _latestApiVersions.Any())
			{
				return _latestApiVersions;
			}


			var latestApiVersions = new List<(ActionDescriptor ActionDescriptor, ControllerActionDescriptor ControllerActionDescriptor, int MaxApiVersion)>();
			if (ControllerDiscoveryInProgress)
			{
				//Since retrieving an instance of IActionDescriptorCollectionProvider will cause AddApiVersioning to again, the second invocation will return an empty list.
				// so no need to cache this data
				//Another interesting tidbit, if you are using Swagger, then AddApiVersioning middle-ware will be re-invoked, so caching the data is pretty handy 
				return latestApiVersions;
			}
			ControllerDiscoveryInProgress = true;

			using (var serviceProvider = services.BuildServiceProvider())
			{
				var provider = serviceProvider.GetRequiredService<IActionDescriptorCollectionProvider>();

				foreach (var controllerDescriptor in provider.ActionDescriptors.Items.GroupBy(GetControllerNameAndVerb))
				{
					(ActionDescriptor ActionDescriptor, ControllerActionDescriptor ControllerActionDescriptor, int MaxApiVersion) latestApiVersion;
					if (!ApiVersionExists(controllerDescriptor, out latestApiVersion))
					{
						/* 
						 * I guess there might be a possibility that ControllerActionDescriptor is null based on the discovery provider that was used.
						 * for instance PageActionDescriptorProvider vs ControllerActionDescriptorProvider
						 * In my case, I know that ControllerActionDescriptor should be populated. So I'll check for that
						 * 
						 * */
						//
						if (latestApiVersion.ControllerActionDescriptor != null)
						{
							//map the latest method to the max API version supported by the controller and its respective HTTP verb.
							latestApiVersions.Add(latestApiVersion);
						}
					}
				}
			}
			_latestApiVersions = latestApiVersions;

			ControllerDiscoveryInProgress = false;
			return latestApiVersions;
		}

		/// <summary>
		/// Uses the latest API version for a controller if the requested API version is not apart of the controller and the requested 
		/// API version is greater than the latest API version supported by the controller.
		/// </summary>
		/// <param name="options">The options.</param>
		/// <param name="services">The services.</param>
		public static void UseLatestApiVersions(this ApiVersioningOptions options, IServiceCollection services)
		{
			var latestApiVersions = services.DiscoveryLatestApiVersion();
			options.UseLatestApiVersions(latestApiVersions);
		}

		/// <summary>
		/// Uses the latest API version for a controller if the requested API version is not apart of the controller and the requested 
		/// API version is greater than the latest API version supported by the controller.
		/// </summary>
		/// <param name="options">The ApiVersioning options.</param>
		public static void UseLatestApiVersions(this ApiVersioningOptions options, List<(ActionDescriptor ActionDescriptor, ControllerActionDescriptor ControllerActionDescriptor, int MaxApiVersion)> latestApiVersions)
		{
			if (ControllerDiscoveryInProgress)
			{
				return;
			}
			ControllerDiscoveryInProgress = true;

			foreach (var latestApiVersion in latestApiVersions)
			{
				//map the latest method to the max API version supported by the controller.
				//Keep in mind that this code does not account for verbs, we could update our group by to group by controller name and verb
				options.Conventions.Controller(latestApiVersion.ControllerActionDescriptor.ControllerTypeInfo)
					.HasApiVersion(latestApiVersion.MaxApiVersion, 0)
					.Action(latestApiVersion.ControllerActionDescriptor.MethodInfo)
					.MapToApiVersion(latestApiVersion.MaxApiVersion, 0);
			}


			ControllerDiscoveryInProgress = false;
		}


		private static string GetControllerNameAndVerb(ActionDescriptor action)
		{
			//we know that routeValues will always contain a key with the name of controller; however lets make sure its there
			string controllerName = action.RouteValues.ContainsKey("Controller") ? action.RouteValues["Controller"] : "[controller]";
			var verbMethod = action.ActionConstraints.FirstOrDefault(x => x is HttpMethodActionConstraint) as HttpMethodActionConstraint;
			string verb = verbMethod?.HttpMethods?.FirstOrDefault();

			return $"{controllerName}-{verb}";
		}

		private static bool ApiVersionExists(IGrouping<string, ActionDescriptor> controllerDescriptor, out (ActionDescriptor ActionDescriptor, ControllerActionDescriptor ControllerActionDescriptor, int MaxApiVersion) latestApiVersion)
		{
			latestApiVersion = (default(ActionDescriptor), default(ControllerActionDescriptor), -1);
			int latestMethod = 0;

			Dictionary<int, int> methodSignatures = new Dictionary<int, int>();
			//actions can be the same method for each route that was defined
			var actions = controllerDescriptor.ToList();

			foreach (var action in actions)
			{
				var controllerActionDescriptor = action as ControllerActionDescriptor;
				if (controllerActionDescriptor != null)
				{
					if (methodSignatures.ContainsKey(controllerActionDescriptor.MethodInfo.MetadataToken))
					{
						continue;
					}
					methodSignatures.Add(controllerActionDescriptor.MethodInfo.MetadataToken, controllerActionDescriptor.MethodInfo.MetadataToken);
				}

				var model = action.GetApiVersionModel();
				if (latestApiVersion.MaxApiVersion < 0)
				{
					//Invoking DiscoveryLatestApiVersion outside of AddApiVersioning middle-ware will always result in controllerModel returning an empty ApiVersionModel
					//lets use the lazy approach instead of attempting to find ApiVersionRangeAttribue and retrieving its values.
					//another approach could be to pass in a max version number for all controllers
					var controllerModel = action.GetProperty<ControllerModel>()?.GetProperty<ApiVersionModel>() ?? ApiVersionModel.Empty;
					latestApiVersion.MaxApiVersion = controllerModel.DeclaredApiVersions.Max(x => x.MajorVersion) ?? 0;

					if (controllerModel.DeclaredApiVersions.Count <= 1)
					{
						//OK... if the controller using the ApiVersionRangeAttribue has only 1 or no API version, then don't waste your time searching and mapping.
						return true;
					}
				}

				if (model.IsApiVersionNeutral || model.DeclaredApiVersions.Contains(new ApiVersion(latestApiVersion.MaxApiVersion, 0)))
				{
					latestApiVersion.ActionDescriptor = action;
					latestApiVersion.ControllerActionDescriptor = controllerActionDescriptor;
					return true;
				}

				int maxVersion = model.DeclaredApiVersions.Max(x => x.MajorVersion) ?? 0;

				if (maxVersion > latestMethod)
				{
					latestMethod = maxVersion;
					latestApiVersion.ActionDescriptor = action;
					latestApiVersion.ControllerActionDescriptor = controllerActionDescriptor;
				}

				if (maxVersion == (latestApiVersion.MaxApiVersion - 1))
				{
					//at this point we found the previous version.. so we really don't need to check the other functions that is if our functions have the same name 
					//and we only added the api version to the end of the function.
					//If thats not the case, then we need to check all the method
					//latestMethod = majorVersion;
					//latestApiVersion = model;
				}
			}

			return false;
		}
	}
}

#endif
`

`
services.AddApiVersioning(option =>
			{
				option.ReportApiVersions = true;
				option.AssumeDefaultVersionWhenUnspecified = true;
				option.DefaultApiVersion = new ApiVersion(1, 0);
				option.UseLatestApiVersions(services);
			});
`
