### ISSUE TITLE
405 UnsupportedApiVersion when deleting

### ISSUE THREAD

**Issue by jorismathijssen** [Microsoft/aspnet-api-versioning#439]
Hello, i currently have a problem when i send a delete request without a id specified.

```c#
[HttpDelete("routes/{routeId}")]
[ProducesResponseType(204)]
[ProducesResponseType(400)]
[ProducesResponseType(401)]
[ProducesResponseType(403)]
[ProducesResponseType(500)]
public async Task<IActionResult> DeleteRoute(int routeId, [FromQuery]InputModelBase languageInput)
{
    DoThings();
}
```
When i dont specify the id i want removed, the server will return the following 405 message:
```json
{
    "error": {
        "code": "UnsupportedApiVersion",
        "message": "The specified API version is not supported",
        "innerError": null
    }
}
```

I was expecting a more detailed message about missing a parameter.

**Comment by commonsensesoftware** [comment]
You've stumbled upon a gray that simply doesn't have a _perfect_ answer. It is, however, [documented](../wiki/Error-Responses#unsupported-api-version) in the wiki.

You haven't listed your other actions, but I'm willing to venture that `GET routes` or `POST routes` is a valid route template. This results in a precarious situation. The URL (e.g. _identifier_) `routes` exists, but may not support a particular HTTP method. Furthermore, once you throw in API versioning, it may simply not support a particular API version.

In either case, when API versioning determines that a route _could_ match, it provides it's own response. If it doesn't match purely due to an unmatched API version, you'll receive 400 with this message. When the reason they don't match includes an unmatched HTTP method, you'll receive 405 with the same error message. This behavior is meant to help provide a hint to the client as to why the request failed. A 405 means that the API version _might_ be supported, but not for the requested HTTP method. A 400 means that some API version exists, but not the one you asked for. A 404 means no matches at all - for any API version.

It should be noted that ASP.NET Core has not had intrinsic support for 405 until 2.2 with _Endpoint Routing_. If/when you upgrade, you should observe a similar behavior, but without the error message because this will be short-circuited by ASP.NET Core before it even reaches API versioning.

As an aside, I don't know that you can achieve your goal of a _"...detailed message about a missing parameter."_. Remember that as part of the _Uniform Interface_ REST constraint, the URL **is** the identifier, which is commonly misunderstood. This means that from an API perspective, the ID is `routes/123` and not `123`. The actual server may use `123` as an internal identifier, but that is purely an implementation detail. 404 or 405 are perfectly acceptable in the scenario you described. I believe there may be some ways you can make ASP.NET Core respond with 400 instead of 404 if `abc` (alphbetic) characters are used instead of `123`, but - again - this is specific to the platform and highly debated. The semantics of a URL are text so either it should match or it shouldn't (2xx or 404). Implying or requiring that a particular part of a URL must be in a specific format is undefined and likely unknown to a client.

I hope that helps.

**Comment by jorismathijssen** [comment]
That's correct i have a GET Routes, POST routes (and a PUT, maybe i'm combining these 2).

Your explanation is very clear! Thanks. Also thanks you for the link you provided. i should have found that first.

I was thinking of upgrading to 2.2 so i will definitely look into that.

Your also correct with the "detailed message" i would have wanted. But i now have one more question. If i don't specify the id for the delete action. Shouldn't i get a 404? is this possible instead of the error message in the original post?

**Comment by commonsensesoftware** [comment]
How you customize the error message depends on whether it was generated by API versioning or intrinsically by ASP.NET Core, but - yes - this can be done.

For API Versioning, you'll want to create a custom [error response provider](../wiki/Error-Response-Provider) or extend the default implementation. The interface and built-in class are quite simple. If you extend the built-in class, you simply need to change the response for `StatusCode=405` and `ErrorCode=UnsupportedApiVersion` to whatever you like. You have the ability to change the status code, error code, and error message using the built-in error response object or you can create and return a response completely of your own choosing.

The documentation is somewhat intentionally _light_ to discourage this type of customization. Returning 404 instead of 400 or 405 has been asked quite a few times. This is how you handle it. For those versioning by media type, some prefer to return 406 or 415 as well. Most customizations just change the status code returned, but you have full control over what gets returned.

**Comment by jorismathijssen** [comment]
Thank you for your time and information! I can solve my problems with this :)
