### ISSUE TITLE
Semantic Versioning 

### ISSUE THREAD

**Issue by eaidland** [Microsoft/aspnet-api-versioning#447]
.Net Core 2.2
Microsoft.AspNetCore.Mvc.Versioning (3.1.0)

Hi!
Why is it not possible to apply the versioning like "1.0.0-alpha"/"1.0.0-a" to ApiVersion attribute?
`[ApiVersion("1.0.0-a")]`

If I set the attribute it throws and format exception "Message=The specified API version status '0-alpha' is invalid."

According to [https://semver.org/](url) Semantic Versioning Specification number 9 this should be valid. Do I need to set any options in services.AddVersionedApiExplorer ?

Thanks!

**Comment by commonsensesoftware** [comment]
The answer is quite simple actually. An API version is **not** a _semantic version_ and does not use the same rules. Perhaps the concept of a _status_ suffix catches those familiar with semantic versioning off-guard. You certainly wouldn't be the first to ask this question or be hung up by it.

The [version format](../wiki/Version-Format) in the wiki documents the format of the API version in detail. This format was born years ago during the standards evolution within Microsoft. They are now publicly published as the [Microsoft REST API Guidelines](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md). The version format is effectively a union of `{date}` and `{major}.{minor}`. The official recommendation has since dropped the concept of _status_, but I already had it incorporated and thought it was worth preserving.

Semantic versioning is powerful, but it is arguably not well suited to web-based API versioning because:

* Build labels do not make sense in web APIs
* Patch versions have (or at least should have) little or no meaning in web-based APIs
* Web-based APIs often use dates in lieu of major and minor version numbers as they are easier to rationalize for human beings (ex: Azure)
* Web-based APIs required discrete version numbers, which rules out semantic version ranges

The versioning semantics for RESTful APIs almost exclusively center around content transferred over the wire. In accordance with the _Uniform Interface_ constraint, HTTP **is** the API and defines the methods available. The URLs are the _identifiers_ of the content retrievable. The API version, therefore, almost always refers to a change in the content, which is _best_ satisfied by media type negotiation. There are no _official_ rules regarding the meaning of an API version, but a reasonable interpretation would be that in a numeric scheme the minor version would represent an additive content change that should be consumable by _tolerant readers_ and a major version change would be a complete new representation of the resource. Ultimately, an API version has a discrete mapping to a particular representation, which is why a date is just as suitable.

I hope that helps clarify things. It probably would have been more obvious if _magic strings_ weren't required for attributes. This is, unfortunately, a limitation of how attributes work in .NET. In other places of API versioning, such as conventions, you would see that the API version is a first-class object in the type system and can be constructed from its constituent parts.

**Comment by eaidland** [comment]
Thank you so much for your elaboration and quick respons :)
