### ISSUE TITLE
Route Not correct while each controller have different version

### ISSUE THREAD

**Issue by akhilrajau** [Microsoft/aspnet-api-versioning#449]
Hi ,
I have 2 controllers for Product and Order. We are maintaining separate version for each module / controller. So Product Controller is in version 1 and Order Controller is in version 2. 

I think this is good for easy maintenance so that i can upgrade next version if that module only changed.

Now let me explain my code and issue. I have the following sample models and sample view model.
```
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```

```
    public class Order
    {
        public int Id { get; set; }
        public IEnumerable<Product> Products { get; set; }
    }

    public class OrderViewModel
    {
        public int Id { get; set; }
        public IEnumerable<string> Products { get; set; }
    }
```

In Order View Model, I have Products enumerable of string which means the url of the products instead of entire product model. To accomplish this, I used UrlHelper class to generate product url.
Please see my response 
```
[
    {
        "Id": 1,
        "Products": [
            "http://localhost:50054/api/v1/products/1",
            "http://localhost:50054/api/v1/products/2"
        ]
    }
]
```

If both controller have same version (version 1) it working fine and I am getting correct url for each product in the order.

Here Product has version 1 and Order has 2 versions. So if i call version 2 of order, I am getting version 2 of product which is not available. 
Please see my response 
```
[
    {
        "Id": 1,
        "Products": [
            "http://localhost:50054/api/v2/products/1",
            "http://localhost:50054/api/v2/products/2"
        ]
    }
]
```

The following are my controller implmentations
```
    [ApiVersion("1.0")]
    [RoutePrefix("api/v{version:apiVersion}/products")]
    public class ProductV1Controller : ApiController
    {
        [Route("{id}", Name = "GetProduct")]
        public IHttpActionResult Get(int id)
        {
            var repo = new ProductRepo();
            var item = repo.Get(id);
            return Ok(item);
        }
    }
```

```
    [ApiVersion("1.0")]
    [RoutePrefix("api/v{version:apiVersion}/orders")]
    public class OrderV1Controller : ApiController
    {
        [Route("", Name ="GetOrders")]
        public IHttpActionResult Get()
        {
            var repo = new OrderRepo();
            var orders = repo.GetAll();

            IList<OrderViewModel> orderViewModel = new List<OrderViewModel>();
            foreach(var order in orders)
            {
                IList<string> productUrls = new List<string>();
                UrlHelper helper = new UrlHelper(Request);
                foreach(var product in order.Products)
                {
                    var productUrl = helper.Link("GetProduct", new { id = product.Id });
                    productUrls.Add(productUrl);
                }
                orderViewModel.Add(new OrderViewModel()
                {
                    Id = order.Id,
                    Products = productUrls
                });
            }

            return Ok(orderViewModel);
        }
    }
```
```
    [ApiVersion("2.0")]
    [RoutePrefix("api/v{version:apiVersion}/orders")]
    public class OrederV2Controller : ApiController
    {
        [Route("", Name = "GetV2Orders")]
        public IHttpActionResult Get()
        {
            var repo = new OrderRepo();
            var orders = repo.GetAll();

            IList<OrderViewModel> orderViewModel = new List<OrderViewModel>();
            foreach (var order in orders)
            {
                IList<string> productUrls = new List<string>();
                UrlHelper helper = new UrlHelper(Request);
                foreach (var product in order.Products)
                {
                    var productUrl = helper.Link("GetProduct", new { id = product.Id });
                    productUrls.Add(productUrl);
                }
                orderViewModel.Add(new OrderViewModel()
                {
                    Id = order.Id,
                    Products = productUrls
                });
            }

            return Ok(orderViewModel);
        }

    }
```

For sample there is no difference in v1 and v2 of orders. 
I may solve this by version interleaving. I can add [ApiVersion("2.0")] to the product controller so that the version is available. But without any reason I am adding one version.

Please suggest or advise

**Comment by commonsensesoftware** [comment]
If I understand the question correctly, you're asking whether you _need_ two different controllers because they have the exact same implementation between `1.0` and `2.0`. The decision mostly comes down to preference.

If you're asking _what I would do_, in this case I would probably do one of two things:

1. Simply decorate the `1.0` implementation with `[ApiVersion("2.0")]` to indicate it also supports `2.0`.
    a. How things are mapped on the server is an _implementation detail_
    b. If I need or want to shift `2.0` somewhere later, I can with little consequence
2. I wouldn't even have a `2.0` because services can and should evolve independently

I can tell you that I, personally, would **never** version by URL segment. It's a violation of the REST _Uniform Interface_ constraint. Having the API version in the URL suggests that `api/v1/orders/1` and `api/v2/orders/1` are somehow different orders, but they aren't. In addition, you are also observing the challenges with HATEOAS when you version that way. The only practical way it works is if you have version symmetry across all services. This can be a pain to maintain. It can also be confusing for clients. Using `2.0` of _Orders_ forces the adoption of `2.0` of _Products_ even if the client doesn't need that. _Products_ `2.0` might not even have a change, but clients don't intrinsically know that. In all other styles of versioning, the URL is the same for all versions and a client expresses which _representation_ they want by way of an API version.

If I were shipping a platform or product, I _might_ choose **Option 1** as the affinity is to a collection of services. If I were building services in an enterprise, then I would likely choose **Option 2** because having version symmetry isn't really helping me achieve anything.

There's no one _right_ answer. The decision is up to you. I hope that helps give you some ideas.

BTW: The issue title says:

>_"Route Not correct while each controller have different version"_

But nothing you've indicated so far suggests that things are not working. Is something not actually working the way you expect?

**Comment by commonsensesoftware** [comment]
OK... I _think_ I understand now. If I'm not mistaken, your setup is as follows:

1. **Orders** - has versions `1.0` and `2.0`
2. **Products** - has version `1.0` (only)

When you make a request to _Orders_ you are returning hyperlinks to the corresponding _Products_. However, when you ask for _Orders_ `2.0`, the response contains hyperlinks that refer to _Products_ `2.0`, which does not exist.

Assuming that's the issue, this is happening because the **UrlHelper** is satisfying the `version` route parameter in the generated URL using the value resolved from the current request. To produce the correct URL, you need to explicitly specify the `version` parameter when you generate the link. Something like:

```c#
helper.Link("GetProduct", new { id = product.Id, version = "1.0" });
```

Driving HATEOAS with links this way is perfectly acceptable; however, what you are observing is one of the challenges of versioning by a URL segment. There's no _real_ way to know which version of _Products_ you should return or that the client wants. In this case, _Products_ only has one version so the answer is easy. Consider a more complex scenario where _Products_ had `1.0` and `3.0`. There are two choices and neither are the same as _Orders_. Which do you choose? In my opinion, the answer is _"None of the Above"_. The client should be _choosing_ in their request. I don't think there is an easy or feasible way to solve this when versioning by URL segment.

Arguably the _best_ method of versioning is via media type. This is really the only method that Fielding himself can get behind. There are examples of this in the wild. The GitHub API, for example, versions this way.

The perhaps less RESTful, but pragmatic approach is to version using a query string parameter. This is the default behavior in the API versioning libraries. This would have requests such as `api/orders/1?api-version=2.0` and `api/products/1?api-version=1.0`. The **path** component of the URL is the resource identifier and never changes between API versions. This would solve your problem above because the links to _Products_ would **always** be `api/products/{id}`. It is the client's, not the server's, job to append the `api-version` query parameter during each request. Clients intrinsically know what API versions they are bound to. This gives them the flexibility to ask for different versions of different resources. For example, even if _Products_ had a `2.0`, the client might still want to use `1.0` or have no need to advance to `2.0` (because it's not useful to them). Using this type of approach, your URLs are stable and versions of related resources are driven by the client.

I hope that helps clear things up.

**Comment by akhilrajau** [comment]
Understood. Thanks for the explanation.

Like you told I have the exact scenario in my original implementation. Say Product have version 2 and 3. 
Actually I am changing my existing API project which actually using media type through accept header only
`Accept: application/json;version=2`

I changing this to UR:L segment due to the following reasons
1. I feel version in the URL get clear idea to the client that which version of API they are using. This is useful when sharing document to them also like we can easily tell them about the version even though non technical person.
2. I thought best practice is URL segment than media type as my third party APIs gives me the URL like this.

I avoided query string parameters as I personally don;t like the way of adding parameter like version =1 which is not related any functionality.

I can accept that URL segment changed the API URL for each version but I feel it easy to understand by anyone.

Thanks for your answer and it mostly solved my issue. But like you told it is challenging one when have multiple versions. Also i am creating this in Auto-mapper after map method.

Please give your comments. Thanks again

Regards,
Akhil

**Comment by akhilrajau** [comment]
Hi,
I wrote one helper method to get the URL according to the version. I wrote this with some sample code from other article. I think this solve my problem.

```
	public static class UrlHelper1
	{
		public static string Link(HttpRequestMessage request, string routeName, object routeValues)
		{
			HttpConfiguration configuration = request.GetConfiguration();
			if (configuration == null)
			{
				throw new InvalidOperationException("Http Configuration not found.");
			}
			object routes = configuration.Routes;
			var fieldName = "_dictionary";

			if (routes == null)
				return null;

			var type = routes.GetType();

			if (type.FullName ==
			  "System.Web.Http.WebHost.Routing.HostedHttpRouteCollection")
			{
				var hostedField = type.GetField("_routeCollection",
				  BindingFlags.NonPublic | BindingFlags.Instance);
				type = hostedField.FieldType;
				routes = hostedField.GetValue(routes);
				fieldName = "_namedMap";
			}

			var field = type.GetField(fieldName,
			  BindingFlags.NonPublic | BindingFlags.Instance);

			var dictionary = field.GetValue(routes) as IDictionary;
			if (!dictionary.Contains(routeName))
				return null;

			var link = (dictionary[routeName] as Route).Url;
			if (link == null)
				return null;
			IDictionary<string, object> convertedRouteValues = new HttpRouteValueDictionary(routeValues);
			foreach (var routeValue in convertedRouteValues)
			{
				link = link.Replace("{" + routeValue.Key + "}", routeValue.Value.ToString());
			}

			//Generate Link

			string baseUrl = request.RequestUri.GetLeftPart(UriPartial.Authority) + configuration.VirtualPathRoot;
			link = new Uri(Path.Combine(baseUrl, link)).AbsoluteUri;

			return link;
		}

	}
```

Please suggest / comment

**Comment by commonsensesoftware** [comment]
If the collection of route parameters contain keys that are not found in the route template, they are automatically converted to query parameters. If you've removed the `version` route parameter from your template, then this is what is happening. You can confirm this behavior be the fact that the default API version query parameter is `api-version` (unless you changed it in the configuration), but the query parameter added is `version`.

For all methods of API versioning with the exception of the URL method, you don't need to specify the API version in link generation. The API version is a well-known value that the client is supposed to know and provide. It wouldn't appear in the header or media type methods because the API version isn't in the URL. The query string method doesn't require it and _shouldn't_ include the API version to avoid the same problems you face with URL method link generation.

Your helper looks more like a hack. You should be able to achieve your goals without resorting to Reflection on internal types. If it works for you, go for it. Know that this particular approach will only work when hosting over HTTP.SYS such as with IIS (any flavor).

**Comment by akhilrajau** [comment]
Thanks.
