### ISSUE TITLE
What is the significance of API Version Selector?

### ISSUE THREAD

**Issue by DreamingDevs** [Microsoft/aspnet-api-versioning#45]
Hi Chris,

what is the significance of API Version Selector when we have DefaultApiVersion? I am not able to understand the outcome when we have both `ApiVersionSelector` and `DefaultApiVersion` is configured.

when I have 4 versions - `1.0, 2.0, 3.0 and 3.1-alpha`. I have following configuration.
```
services.AddApiVersioning(options =>
{
     options.ReportApiVersions = true;
     options.AssumeDefaultVersionWhenUnspecified = true;
     options.ApiVersionReader = new HeaderApiVersionReader("api-version");
     options.DefaultApiVersion = new Microsoft.AspNetCore.Mvc.ApiVersion(2, 0);
     options.ApiVersionSelector = new CurrentImplementationApiVersionSelector(options);
});
```
Now when I make a request without a version, then I am always getting 3.0 (and not 2.0 which I specified as default API version).
When I was making a request with wrong version (say for example 3.6), then I am getting 400 Bad Request stating that API doesn't support specified version.

Can you tell me how API Version Selector works?

**Comment by commonsensesoftware** [comment]
I think I need to add a FAQ section with this topic in the wiki. It seems to confuse a lot of folks.  Ideally, you should not mess with the **ApiVersionSelector**. It's provided as a hook so you have options, but I usually discourage it.

Once you opt into API versioning, **every** controller now has an API version, even if you didn't previously have any concept of versioning. This is required or you can never completely remove a service. The default behavior is to assume that services that fall into this bucket are **1.0**. The default API version can also be thought of as the _initial API version_. In your services, **1.0** might not be appropriate for the _initial_ or _default_ version of a service (e.g. you version by date). The **DefaultApiVersion** keeps this value from being hardcoded.

The **IApiVersionSelector** is used to a select an appropriate API version given a request and a pre-aggregated API version model.  Currently, this is **only** used when you allow implicitly versioning by opting in with the **AssumeDefaultVersionWhenUnspecified** and the client does not actually provide a version. In these cases, the selection process needs to know which version it should select. The design allows for this to be used in other contexts, but thus far, this is the only one.

The options use the **DefaultApiVersionSelector** as the initially configured value, which simply always returns the value of **DefaultApiVersion**. To some extent these two things are mutually exclusive and you don't need to configure them both. There are a few places where the **DefaultApiVersion** is used when all selection and fallback methods have been exhausted.

I've provided a pretty detailed explanation in #43 that may shed some additional insight.

If you're retro-fitting existing services, then the best and most explicit option is to:

* Enable **AssumeDefaultVersionWhenUnspecified**
* Set the **DefaultApiVersion** to your _initial_ API version; this may be arbitrary because clients don't know what this value is nor will likely ever specify it
* Update your existing controllers with your _initial_/_default_ API version (ex: ```[ApiVersion( "2.0" )]```)

I would avoid changing the **IApiVersionSelector**; especially to an instance where the results are not deterministic. This will cause things to shift for clients over time and potentially break them. You want your clients to be bound to a stable version even when they are not aware that they are bound to a version.

**Comment by commonsensesoftware** [comment]
I've added an entry to the [FAQ](../wiki/FAQ) section on the wiki that covers this topic. Let me know if you feel the explanation requires further elaboration; otherwise, I will mark this question as answered and closed.
