### ISSUE TITLE
[Route( "api/v{version:apiVersion}/helloworld" )] vs [Route( "api/v1/helloworld" )]

### ISSUE THREAD

**Issue by ricmrodrigues** [Microsoft/aspnet-api-versioning#456]
Hi.
I'm trying to understand why not use the route as the ApiVersion definer rather than having the `[ApiVersion("1.0")]` and then the `[Route("api/v{version:apiVersion}/helloworld")]`.
Is it just so it's more elegant or there are trade-offs there?
Internal discussion on my team.

**Comment by commonsensesoftware** [comment]
The simplest answer is that such an approach would be very prescriptive about _how_ you version APIs. API versioning provides 4 ways to version your APIs out-of-the-box and also has support for composition (e.g. allow multiple styles together).

The `[ApiVersion("1.0")]` attribute is just metadata. It doesn't care or know about anything else. It describes _which_ versions an API supports. Versioning by URL segment is just one method of versioning. A route constraint is used to allow you to define _where_ the API version is in your route template. This negates the matching and parsing of _magic strings_ by API versioning. It gives you a lot of control over where and how the API version appears in your routes. A good example of this is the `v` prefix character. This is not part of the API version, but is a common prefix in the URL segment method. This design allows you to use the prefix (though I've also seen no prefix) without compromising the form of the API version.

If you only have one API version per controller, you're probably still wondering why this is necessary. API versioning also supports _interleaving_. Consider the following:

```c#
[ApiVersion("1.0")]
[ApiVersion("2.0")]
[Route("api/v{version:apiVersion}/[controller]")]
public class HelloWorldController : ControllerBase
{
    [HttpGet]
    public IActionResult Get(ApiVersion version) => Ok($"Hello world from v{version}");

    [HttpGet]
    [MapToApiVersion("2.0")]
    public IActionResult GetV2(ApiVersion version) => Ok($"Hello world from v{version}");
}
```

Now you have a single route template on a single controller with two routable actions:

* `GET api/v1/helloworld` → Hello world from v1
* `GET api/v2/helloworld` → Hello world from v2

This is just one reason for this approach. Ultimately, a route constraint is necessary to understand where the API version is your route template. This is a consequence of the URL segment method. Versioning by URL segment is supported because it's common, but it's also the least RESTful as it violates the _Uniform Interface_ constraint.

If your goal is to simplify things, you might consider using _conventions_. Conventions are an alternative to using attributes to indicate API versions. You can build them imperatively, use a built-in convention, or create and register your own convention. Aside from imperatively conventions, the only currently built-in convention is the _Version By Namespace_ convention. This convention allows inference of an API version using the namespace in which the controller is defined. If you logically separate your controllers by version in a namespace without interleaving, then this can be a good choice. More on this configuration is in the [wiki](../wiki/API-Version-Conventions#version-by-namespace-convention).

Hopefully that answers your question and gets you on your way.

**Comment by ricmrodrigues** [comment]
@commonsensesoftware thanks! clarified 👍
