### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Versioning 3.1 + can not find action with lower version

### ISSUE THREAD

**Issue by kirillta** [Microsoft/aspnet-api-versioning#457]
I have two controllers in different namespaces:

`[ApiVersion("1.5")] [Route("api/v{version:apiVersion}")] public class AddressesController ` and `[ApiVersion("1.6")] [Route("api/v{version:apiVersion}")] public class AddressesController `

When I have tried to call the "1.5" action with the package with version 3.1.0 or bigger, I get a BadRequest response with the header `api-supported-versions →1.6`, and the content is "The HTTP resource that matches the request URI 'http://localhost:51007/api/v1.5/addresses' does not support the API version '1.5'."

But both actions are available with lower versions of the package (like 3.0.0 and 2.3.0): `api-supported-versions →1.5, 1.6`

**Comment by commonsensesoftware** [comment]
Since you said it worked in 3.0, but not 3.1 I'm guessing that this is due to the change in honoring _API behaviors_. Prior to 3.1, `options.UseApiBehavior` defaulted to `false`. Starting in 3.1, the value defaults to `true`. 3.1 is the first time that API versioning bumped the required ASP.NET Core version. ASP.NET Core 2.1+ is required for API behaviors. This is called out in the release notes.

I'm willing to bet that your controllers do not have `[ApiController]` applied, which is how you opt into the API behaviors. You have 3 options:

* Decorate your controllers with `[ApiController]`
* Revert to `options.UseApiBehavior = false` in your setup
* Define your own **IApiControllerSpecification** as outlined in the [wiki](../wiki/API-Versioning-Options#behavior-in-31)

If this is somehow not the cause of the problem you're facing, I'll need some more details about your setup and possibly your controllers. The world's smallest repro is always best. The sample projects tend to be a good place to start from.

**Comment by kirillta** [comment]
Yes, the solution was a combination of first two options. Thank you.
