### ISSUE TITLE
Configuring entity as both Singleton and EntitySet causes 404 on functions

### ISSUE THREAD

**Issue by bdebaere** [microsoft/aspnet-api-versioning#465]
Consider the following configuration.

```csharp
var myFunctionConfiguration = builder
    .Singleton<User>("Me")
    .EntityType
    .Function("MyFunction")
    .Returns<User>();
myFunctionConfiguration.Parameter<DateTime>("begin");
myFunctionConfiguration.Parameter<DateTime>("end");

builder
    .EntitySet<User>("Users");
```

This will function properly without using versioning. However as soon as I enable versioning /Me/MyFunction(begin=2001-01-01,end=2019-02-04) returns a 404.

**Comment by commonsensesoftware** [comment]
Which flavor of OData are you using? Web API or ASP.NET Core?

Your sample request URL doesn't include an API version (assuming it's the default query string method). Have you tried it with the corresponding version? (ex: `?api-version=1.0`) That _could_ result in a 404, though it _should_ more likely be 400 or 405.

**Comment by bdebaere** [comment]
@commonsensesoftware /Me/MyFunction(begin=2001-01-01,end=2019-02-04)?api-version=1.0 returns a 404. I use .NET Core, the latest and greatest version of every package is used.

**Comment by bdebaere** [comment]
@commonsensesoftware An extra bit of useful information by the way might be that if you apply the workaround below, it does work.

```csharp
public class Me : User {}

var myFunctionConfiguration = builder
    .Singleton<Me>("Me")
    .EntityType
    .Function("MyFunction")
    .Returns<User>();
myFunctionConfiguration.Parameter<DateTime>("begin");
myFunctionConfiguration.Parameter<DateTime>("end");

builder
    .EntitySet<User>("Users");
```

**Comment by commonsensesoftware** [comment]
I'll have to dig into what `Singleton<T>(string)` does. Honestly, I've never used it. It _should_ work though. Glad you at a least have a workaround. I'll see what I can find out. Thanks for reporting it.

**Comment by bdebaere** [comment]
@commonsensesoftware I could try and help debug if you could tell me where I should look for routing that returns a 404. Can you tell me what's (probably) missing where?

**Comment by commonsensesoftware** [comment]
Out of curiousity, are you using attribute routing or convention-based routing? I'm noticing an issue with convention-based routing and I'm wondering if this might be related.

**Comment by bdebaere** [comment]
@commonsensesoftware Convention-based routing.

**Comment by commonsensesoftware** [comment]
Apologies for the long delay. I've finally had some time to dig into this. Unfortunately, I'm not able to repro your scenario. I added the following controller as a singleton and added a function to it as well. This is based on the existing **Person** model in the basic sample project. This results in the entity being used in an entity set and as a singleton.

```c#
[ApiVersion( "1.0" )]
[ApiVersion( "2.0" )]
[ApiVersion( "3.0" )]
public class AnonymousController : ODataController
{
    public IActionResult Get( ODataQueryOptions<Person> options ) =>
        Ok( new[] {
            new Person() {
                Id = 42,
                FirstName = "Guess",
                LastName = "Who",
                Email = "anonymous@somewhere.com",
                Phone = "555-555-5555" } } );

    [MapToApiVersion( "2.0" )]
    [MapToApiVersion( "3.0" )]
    public IActionResult GetEmail() => Ok( "anonymous@somewhere.com" );

    [HttpGet]
    public IActionResult Speak() => Ok( "Hello world!" );
}
```

I updated the model configuration as:

```c#
public void Apply( ODataModelBuilder builder, ApiVersion apiVersion )
{
    var singleton = default( EntityTypeConfiguration<Person> );

    switch ( apiVersion.MajorVersion )
    {
        case 1:
            ConfigureV1( builder );
            singleton = builder.Singleton<Person>( "Anonymous" ).EntityType;
            singleton.Ignore( p => p.Email );
            singleton.Ignore( p => p.Phone );
            singleton.Function( "Speak" ).Returns<string>();
            break;
        case 2:
            ConfigureV2( builder );
            singleton = builder.Singleton<Person>( "Anonymous" ).EntityType;
            singleton.Ignore( p => p.Phone );
            singleton.Function( "Speak" ).Returns<string>();
            break;
        default:
            ConfigureCurrent( builder );
            singleton = builder.Singleton<Person>( "Anonymous" ).EntityType;
            singleton.Function( "Speak" ).Returns<string>();
            break;
    }
}
```

Here's the results:

| Request URL | Response |
| -------------- | ---------- |
| api/anonymous?api-version=1.0 | 200 |
| api/anonymous/email?api-version=1.0 | 404 (expected) |
| api/anonymous/speak?api-version=1.0 | 200 |
| api/anonymous?api-version=2.0 | 200 |
| api/anonymous/email?api-version=2.0 | 200 |
| api/anonymous/speak?api-version=2.0 | 200 |
| api/anonymous?api-version=3.0 | 200 |
| api/anonymous/email?api-version=3.0 | 200 |
| api/anonymous/speak?api-version=3.0 | 200 |

I tried the following scenarios:
* ASP.NET Core using OData conventions
* ASP.NET Core using OData attributes
* ASP.NET Web API using OData conventions
* ASP.NET Web API using OData attributes

I know you said you were using ASP.NET Core, but I checked both platforms for completeness.

Based on your configuration, I can't help but wonder if something wasn't configured correctly. I see that you used `Returns<User>`; however, because **User** is an entity, I believe it's supposed to be `ReturnsFromEntitySet<User>("Users")`. In fact, I tried replicating that behavior using: `singleton.Function("Self").Returns<Person>()` and OData ends up throwing an unhandled exception which produces a 500; however, if I use `singleton.Function("Self").ReturnsFromEntitySet<Person>("People")` it works as expected. I'm not sure how you managed to make it work otherwise.

Without an end-to-end repro, I'm not sure I can replicate your exact conditions. Given that all of the expected scenarios seem to work and you have a workaround for your specific scenario, I'm inclined to say this issue is resolved, but I'll give you a bit of time to say one way or the other. If you have a complete repro for me to work from, that would be useful; otherwise, I suspect the issue may simply be configuration-based.

Thanks.

**Comment by bdebaere** [comment]
Hi @commonsensesoftware,

No need to apologize, we are all busy. I made some small changes to the ODataBasicSample which you can view at https://github.com/bdebaere/aspnet-api-versioning/tree/bug/routing. This demonstrates a potential issue. Can you take a look please? Am I doing something wrong in the configuration?

**Comment by commonsensesoftware** [comment]
OK … I think I have the configuration ironed out. Due to the inconsistent behaviors of when OData requires help for conventions versus all attributes, I've gone with the all attributes approach for years now. I won't try to convince anyone, but it's frustrating to try and go all convention-based, only to discover you still need some attributes. Furthermore, the convention model has gotten so complex you need to understand both the conventions of the OData protocol as well as the conventions of how that implicitly maps in code. >_<

The first issue with your setup is you that you **cannot** map two different functions with the same name. Method overloads are not supported. This isn't unique to OData. In HTTP (and thus REST) the URL is the identifier. OData provides a fluent interface to build up the EDM. When you attempt to create the second version of the function, you are getting an instance of the first configuration. Since the union of the configuration always yields a function with takes a string and returns a string, this will always be the final configuration no matter which order you set it up in.

This is the (working) configuration I used:

```c#
var function = builder.Singleton<Person>( "Me" ).EntityType.Function( "Speak" );
function.Parameter<string>( "phrase" );
function.Returns<string>();
```

For the controller, it seems the reason that the parameter is `null` is due to failed model binding. To make it work, we just need to add `[FromODataUri]`. This is infuriating IMO. Sometimes it will work without it (ex: entity set routes) and other times it won't - like now.

This is the (working) controller code I used:

```c#
[ApiVersion( "1.0" )]
[ApiVersion( "2.0" )]
public class MeController : ODataController
{
    [HttpGet]
    public IActionResult Speak( [FromODataUri] string phrase ) => Ok( phrase );
}
```

Also note that you do not need to explicitly use `[MapToApiVersion]` unless you are _interleaving_ multiple versions with different implementations. All actions on a controller implicitly map to all versions defined by the containing controller.

Here's the results:

| URL | Response |
| ---- | ----------- |
| api/me/speak(phrase='Hello world!')?api-version=1.0 | 200, 'Hello world!' |
| api/me/speak(phrase='Hello world!')?api-version=2.0 | 200, 'Hello world!' |
| api/me/speak(phrase='Hello world!')?api-version=3.0 | 400 (UnsupportedApiVersion) |

3.0 was not mapped in your example, which is ok. This example demonstrates you receive the proper 400 response when it's unmapped.

I hope this helps.

**Comment by bdebaere** [comment]
Could you clarify what you mean with:

> The first issue with your setup is you that you cannot map two different functions with the same name. Method overloads are not supported. This isn't unique to OData. In HTTP (and thus REST) the URL is the identifier.

Adding the code below to a default .NET Core web API I can access the methods. /api/values/Method/1 routes me to the first function. /api/values/Method/1/1 routes me to the second function.

```csharp
        // GET api/values/5
        [HttpGet("Method/{id}")]
        public ActionResult<string> Method(int id)
        {
            return "value";
        }

        // GET api/values/5
        [HttpGet("Method/{id}/{id2}")]
        public ActionResult<string> Method(int id, int id2)
        {
            return "value";
        }
```

And I did succeed in making overloading work in the past for OData. It just doesn't work when I enable versioning. Check out this sample I made at https://github.com/bdebaere/ODataSamples/tree/sample/method.overloading. Can you elaborate on what's wrong here and why it is working with OData default but not when I enable versioning?

**Comment by commonsensesoftware** [comment]
Your code example is not OData nor does it demonstrate an actual _overload_. You have overlapping routes that just happen to use the same name in the implementation code. From a service (e.g. HTTP), these are distinctly different endpoints.

I can't say I've righty used a function or action this way. Maybe OData will let you map it like this. OData actions and functions are already a gray area, but I'd argue using them this way is the anathema of REST as they have all the characteristics of RPC.

I'll have to look more closely. The OData implementation is not extensible so I've had to fork their code. Versioning doesn't do anything extra special except disambiguate otherwise duplicate routes by API version. The OData implementation is also painful because it always assumes zero or one match.

The simplest workaround until I can confirm something else would be:
* Do not attemp to use _overloading_, even if it is supposed to be supported
* Use a single action or function with all parameters, marking appropriate parameters as optional.

**Comment by bdebaere** [comment]
@commonsensesoftware I apoligize if this is coming off as blunt, I don't mean it as such. Did you check out the sample in my last link? https://github.com/bdebaere/ODataSamples/tree/sample/method.overloading

**Comment by bdebaere** [comment]
@commonsensesoftware Do you have a source on overloading being against "the anathema of REST"? It would give me the ammunition I need.

**Comment by commonsensesoftware** [comment]
Not to worry. I'm not easily offended. Text cannot emphasis tone. Sorry if it sounded that way. I do my best not to be pedantic. I enjoy being a proliferator of knowledge, but I certainly have my own (strong) opinions as well; many from hard-learned lessons.

You can literally read almost anything about REST and it would surface this scenario as a _code smell_. When REST is applied to HTTP (which it doesn't _have_ to be), the HTTP method (aka verb) **is** the action/function. This is one of the reasons that OData is called _RESTful_ as opposed to a _REST_ protocol. Some parts fall within the constraints, but some do not. Fielding has said many times - _"Either you adhere to all of the constraints of REST or you aren't doing REST"_. Actions and functions alone questionably violate the _Uniform Interface_ constraint, while an _overload_ certainly does.

If you've never read Fielding's dissertation, I encourage you to do so. There are many, many things still relevant from 20 years ago. It's also surprisingly shorter than you might think. At a minimum, I would read the [REST](https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm) chapter, which should only take about 5 minutes. If you care about truly adhering to REST, then Fielding is the utmost authority. Not everyone cares about following REST, which is ok; however, just because an API uses HTTP doesn't make it REST (SOAP services are commonly transmitted over HTTP after all ;))

Another source I like to use is Robert Daigneau's [Web Service Interaction Styles](http://www.servicedesignpatterns.com/WebServiceAPIStyles). Specifically, the [Resource API](http://www.servicedesignpatterns.com/WebServiceAPIStyles/ResourceAPI) is modeled after the REST architectural style. Since he also calls out the **RPC** and **Message** API styles, you can compare and contrast various styles.

Ultimately, REST architectures are about _resources_ not actions or functions. It's a different way of thinking that requries time and experience to acclimate to. I can say I naturally evolved from RPC systems to Message-Oriented systems over many years before I fully wrapped my head around Resource-Oriented systems.

Where I personally think the gray areas of OData are acceptable are actions/functions bound to a resource. For example, `GET movie/42` gets a specific movie, while `POST movie/42/checkout` checks a movie out. There are some concepts in OData such as unbound actions/functions that I don't feel belong in a REST service. Of course using these features is up to the service author.

I could go on for a long time. Hopefully, that gives you a few references and some context. Within the realm of what should be supported, I try to make sure that product features align. If they don't, I'll still take work to align them; regardless of whether I agree with them. I'll give opinions and advice, but I'm not here to preach my dogma. Ultimately, people have to make their own decisions based on what works for them. This is often influenced by time, money, and/or experience.

I hope that helps.

**Comment by commonsensesoftware** [comment]
Attempting to circle back around and catch up on issues. It's been a crazy past few months.

I'm not sure if you ever found an answer, but I've looked at your example and incorporated the configuration into what I had. It would appear that the primary culprit was that you did not have `[FromODataUri]` applied to your parameter. Again - I find it very frustrating that sometimes you need this and sometimes you don't. To be safe, you can always apply it, but it can be tedious. It _should_ have worked, but I should also point out that you don't need `[MapToApiVersion]` because that already implicitly happens in your configuration.

Here's the final controller code:

```c#
[ApiVersion( "1.0" )]
[ApiVersion( "2.0" )]
public class MeController : ODataController
{
    [HttpGet]
    public IActionResult Speak( [FromODataUri] string phrase ) => Ok( phrase );

    [HttpGet]
    public IActionResult Test() => Ok("No param");

    [HttpGet]
    public IActionResult Test( [FromODataUri] string param ) => Ok( param );
}
```

For completeness, here's the configuration code too:

```c#
void ConfigureFunction( ODataModelBuilder builder )
{
    var entity = builder.Singleton<Person>( "Me" ).EntityType;

    var function = entity.Function( "Speak" );
    function.Parameter<string>( "phrase" );
    function.Returns<string>();

    function = entity.Function( "Test" );
    function.Parameter<string>( "param" );
    function.Returns<string>();

    entity.Function( "Test" ).Returns<string>();
}
```

The following routes work as expected:

* `api/v1/me/test`
* `api/v1/me/test(param='Hello%20World!')`

Better late than never. I hope that helps. Let me know if there's anything more on this issue.

Thanks

**Comment by commonsensesoftware** [comment]
It would appear that you're satisfied with the final result; especially considering you already had your own workaround. I believe we've driven this to conclusion with a complete end-to-end, working solution. If your issue has not be resolved or you have more questions, feel free to come back or reopen the issue. Thanks.
