### ISSUE TITLE
Getting System.FormatException when using Header Api Versioning with .NET Core 2.2

### ISSUE THREAD

**Issue by akshayshah2050** [Microsoft/aspnet-api-versioning#467]
I created a brand new ASP.NET Core Empty Project
Installed the package: Microsoft.AspNetCore.Mvc.Versioning Version: 3.1.2
Configured the Startup.cs file to use ApiVersioning (refer screenshot)
Create a test web api controller and run the project

Getting error:  System.FormatException: The specified API version status "0" is invalid
![apiversioningerror](https://user-images.githubusercontent.com/22302386/53493917-8f138b80-3ac2-11e9-82e6-56d086fed0cf.png)

**Comment by commonsensesoftware** [comment]
I'm not sure how this is possible because there is no processing until a request comes in. It would appear that you have an invalid API version that is being parsed from a string via `ApiVersion.Parse` - somewhere. I was able to apply your configuration to the basic example and it worked as expected.

I also see that you are using `app.UseApiVersioning()` this is not required and is only intended to be used in advanced middleware configurations. I suggest removing it, but it should have no effect on your configuration. Furthermore, you have to specify `options.RegisterMiddleware = false` to use it this way.

I see you have some other middleware configured. Is there any chance you have something adding or otherwise inspecting the API version elsewhere in the pipeline?

**Comment by akshayshah2050** [comment]
The only middleware that i have added is Swagger.
I tried it even after removing swagger but still the same error

**Comment by commonsensesoftware** [comment]
I don't see that in your screenshot. I see `app.UseHsts()` (no idea what that is) and `app.UseHttpsRedirection()` (should not be an issue).

I don't see anything about Swagger and you didn't mention that before. Which Swagger library are you using? Swashbuckle? Is your API application and Swagger application co-hosted? If not, you'll have challenges because the browser will require CORS requests. A CORS _preflight_ does not automatically include custom headers. Since you're trying to version by header, you'd have to tweak the Swagger UI to inject the header. If things are co-hosted, then CORS is a non-issue.

**Comment by akshayshah2050** [comment]
I added swagger (Swashbuckle) and ApiVersioning both together and got the mentioned error so in order to figure out what caused it i removed swagger and then tested it, hence you can't see swagger references in the screenshot
And about Hsts it is a method that adds Strict Transport security header 
To know more please visit: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.hstsbuilderextensions.usehsts?view=aspnetcore-2.2

**Comment by commonsensesoftware** [comment]
Have you tried the [sample](../tree/master/samples/aspnetcore/SwaggerSample) and worked backward from that? I simply added `options.ApiVersionReader = new HeaderApiVersionReader( "api-version" );` [here](../blob/master/samples/aspnetcore/SwaggerSample/Startup.cs#L48) in the **Startup.cs** and everything, including Swagger, works as expected. It's worth trying that out to compare what's different from your application.

**Comment by akshayshah2050** [comment]
ok...will try and update here soon...
Thanks :)

**Comment by commonsensesoftware** [comment]
Were you able to resolve this from experimenting with the sample project?

**Comment by programmersommer** [comment]
@akshayshah2050 Check your version attribute. Probably you have extra 0. Like  [ApiVersion("2.0.0")] should be  [ApiVersion("2.0")]

**Comment by commonsensesoftware** [comment]
Good point @programmersommer. @akshayshah2050, just confirming, did you finally resolve this? It seems so. Thanks.

**Comment by commonsensesoftware** [comment]
It seems this issue is resolved. If you continue to face challenges or have more questions, feel free to come back or reopen the issue. Thanks.
