### ISSUE TITLE
Multiple Controllers in Odata with Version support

### ISSUE THREAD

**Issue by brat15** [Microsoft/aspnet-api-versioning#468]
I have a project which has more than one endpoint , like /odata/test1 /odata/test2  with there now set of models to achieve this i had to make a Custom Attribute Routing Convention as below

public class CustomAttributeRoutingConvention : AttributeRoutingConvention
{
    private readonly List<Type> _controllers = new List<Type> { typeof(MetadataController) };

    public CustomAttributeRoutingConvention(string routeName, HttpConfiguration configuration, IEnumerable<Type> controllers) : base(routeName, configuration)
    {
        _controllers.AddRange(controllers);
    }

    public override bool ShouldMapController(HttpControllerDescriptor controller)
    {
        return _controllers.Contains(controller.ControllerType);
    }
}

Now I would like to add version support, but there is no way to scope the path to a specific controller. the  MapVersionedODataRoutes seems to scan all the controllers and no way to separate the models to specific controllers. Can this be achieved?

**Comment by commonsensesoftware** [comment]
In the most technical sense, I _believe_ the answer is yes; however, it will be a horrible mess to do. You might have to effectively fork the setup that **MapVersionedODataRoutes** does. There is a new hook to inject or modify the route conventions, but I haven't tried it for a scenario like this. OData doesn't really care what the _prefix_ is. The URI parser only considers everything **after** the prefix.

You'll want to look at one of the overloads of **MapVersionedODataRoutes** that has the `configureRoutingConventions` callback such as [here](../blob/master/src/Microsoft.AspNet.OData.Versioning/System.Web.Http/HttpConfigurationExtensions.cs#L114). The information supplied and mutable can be seen in the [ODataConventionConfigurationContext](../blob/master/src/Common.OData/AspNet.OData/Routing/ODataConventionConfigurationContext.cs).

You shouldn't have to muck with the MetadataController as the versioned flavor _should_ already be doing the _right_ thing - I believe. Also use caution changing the any of the API versioning related conventions. If you _really_ need to change them, I would suggest either subclassing or adapting over them as opposed to outright swapping them out. If you find that difficult to do because the types don't have the necessary virtual members, etc, I'm willing to consider refactoring so that you can.

Give that a start and let me know how it goes. I only know of a few cases of people wanting to do this and I don't know of anyone with a working solution. If you get something working, it'd be worth sharing.

**Comment by brat15** [comment]
Thanks, I tried to add a new VersionedAttributeRoutingConvention to ODataConventionConfigurationContext using the HttpControllerDescriptor , but HttpControllerDescriptor itself calling the applyAttributes which leads to the same error that the action is not found on the controller (since it is expecting it)

[InvalidOperationException: The path template in controller is not a valid is not a valid OData path template. Resource not found for the segment
 Microsoft.AspNet.OData.Routing.VersionedAttributeRoutingConvention.GetODataPathTemplate(String prefix, String pathTemplate, IServiceProvider serviceProvider, String controllerName, String actionName) +455
   Microsoft.AspNet.OData.Routing.<>c__DisplayClass14_0.<GetODataPathTemplates>b__0(ODataRouteAttribute route) +49
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +238
   System.Linq.WhereEnumerableIterator`1.MoveNext() +124
   Microsoft.AspNet.OData.Routing.VersionedAttributeRoutingConvention.BuildAttributeMappings(IEnumerable`1 controllers) +626
   Microsoft.AspNet.OData.Routing.<>c__DisplayClass3_1.<.ctor>b__0(HttpConfiguration config) +143
   System.Web.Http.HttpConfiguration.ApplyControllerSettings(HttpControllerSettings settings, HttpConfiguration configuration) +94
   System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type) +200
   System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type) +63
   System.Web.Http.Controllers.HttpControllerDescriptor.InvokeAttributesOnControllerType(HttpControllerDescriptor controllerDescriptor, Type type) +63
   System.Web.Http.Controllers.HttpControllerDescriptor..ctor(HttpConfiguration configuration, String controllerName, Type controllerType) +131

Will try to check if there is any other way out. If you have any further hints , that would be helpful .

**Comment by commonsensesoftware** [comment]
Not sure if you ever resolved this, but I can shed a little more light on your original objective. OData doesn't see the paths as `odata/test1` and `odata/test2` as different. The prefix is virtually cosmetic. The OData URI parser does **not** consider it. This is way it's setup the way that it is. Without versioning, I believe you can make it work by manually registering different EDMs using `MapODataServiceRoute`.

API Versioning allows mapping multiple EDMs, but the default behavior uses the same prefix as a convenience. If you want to use different prefixes, you can use `MapVersionedODataRoute` as opposed to `MapVersionedODataRoutes`, which will contain a parameter for the EDM. You can still use the **VersionedODataModelBuilder**, but you'll have to match up the correct EDM on your own. You can do this by getting the applied annotation. API versioning adds the **ApiVersionAnnotation** to each EDM that is created and returned by `VersionedODataModelBuilder.GetEdmModels()`. You simply need to extract the annotation and match the API version and EDM to the route configuration you want with a particular prefix.

You request it like this:

```c#
var apiVersion = edmModel.GetAnnotationValue<ApiVersionAnnotation>( edmModel ).ApiVersion;
```

With the set of generated EDMs and API versions, you should be able to register individual routes using alternate prefixes.

I hope that helps.

**Comment by commonsensesoftware** [comment]
It would seem that you've resolved this issue or found a suitable alternative. If not, feel free to come back with more questions and/or reopen the issue.

**Comment by jm5599** [comment]
Thank you for your explanations, I was facing a similar issue that I was able to resolve.
One question though, I've ended up using MapVersionedODataRoute so I can have multiple route prefixes (test1 & test2 & ...) but I would have like an overload that accepted "configureAction" as a param.

Right now I am stuck using the (routePrefix, model, apiVersion, pathHandler, batchHandler, routingConventions) overload and so I can't figure out how to  add this service :

builder.AddService<ODataUriResolver>(Singleton, sp => new UnqualifiedCallAndEnumPrefixFreeResolver() { EnableCaseInsensitive = true });

How should I go about things?

Thank you

**Comment by commonsensesoftware** [comment]
[MapVersionedODataRoute](../blob/master/src/Microsoft.AspNet.OData.Versioning/System.Web.Http/HttpConfigurationExtensions.cs) has a lot of overloads so I'm not sure exactly which one you need, but one of them should satisfy your needs. A couple of them are just shortcuts (from legacy setups) that configure things in the container. You _might_ have to use an overload where you configure things yourself in the container.

The configuration should be virtually the same as in the [basic example](../blob/master/samples/webapi/BasicODataWebApiSample/Startup.cs#L48), even though it's for multiple EDMs.

I hope that helps point you in the right direction.

**Comment by jm5599** [comment]
I can't find an overload that has both "model" and "configureAction" so when I use the overload that doesn't include the model then the odata routes do not work anymore.... so I'm trying to understand how to specify model and still be able to interact with the container builder

I might be missing something here, help much appreciated.

**Comment by commonsensesoftware** [comment]
Use [this](../blob/master/src/Microsoft.AspNet.OData.Versioning/System.Web.Http/HttpConfigurationExtensions.cs#L371) overload:

```c#
configuration.MapVersionedODataRoute(
    "test1",
    "test1",
    new ApiVersion(1, 0),
    builder => builder.AddService(ServiceLifetime.Singleton, typeof(IEdmModel), sp => model)
                      .AddService(ServiceLifetime.Singleton, typeof(IODataPathHandler), sp => pathHandler)
                      .AddService(ServiceLifetime.Singleton, typeof(IEnumerable<IODataRoutingConvention>), sp => routeConventions.ToArray())
                      .AddService(ServiceLifetime.Singleton, typeof(ODataBatchHandler), sp => batchHandler)
                      .AddService(ServiceLifetime.Singleton, typeof(HttpMessageHandler), sp => defaultHandler));
);
```

Add or remove more stuff to the container as necessary. The other overloads are essentially just a shortcut for this same process. If you're not sure what to put in for defaults, just look at the source. The input is usually the same or very, very close to the default OData setup.

**Comment by jm5599** [comment]
works great! Thanks for the quick response!

**Comment by jm5599** [comment]
Sorry to bother you again, it seems like I spoke too soon... it's not working like I'd hoped.

I'm calling "MapVersionedODataRoute" with a set of model configurations for each route prefix I use, so for every set of models the following gets done  :

![image](https://user-images.githubusercontent.com/55287048/65164346-013ac600-da3d-11e9-97b7-843069b87094.png)

This, I was hoping, should give me "api/v2/prefixOne/query-one", "api/v2/prefixOne/query-two", "api/v2/prefixTwo/query-one", "api/v2/prefixTwo/query-two"... 

When the web api is initializing, VersionedAttributeRoutingConvention calls GetODataPathTemplate and it supplies a serviceProvider whose value is set from action.Configuration.GetODataRootContainer(routeName). This value is in turn used by DefaultODataPathHandler.Parse to get the actual model used to parse the uri. My problem is that when DefaultODataPathHandler  calls requestContainer.GetRequiredService<IEdmModel> it gets the wrong model! It seems to always get the model that was associated with the first call to MapVersionedODataRoute.

I tried changing the scope of services on the builder.AddService calls but that didn't help. I've been looking through the source code quite a bit today and I'm sure I'm missing something pretty straight forward...

Any ideas would be appreciated!
Thanks

**Comment by jm5599** [comment]
ok so I've got it working now but I've had to modify BuildAttributeMappings in VersionedAttributeRoutingConvention so as to use the correct routeName based on the controller and not the one that was set right before configuration.Initializer was fired. 

Is this a bug then or am I doing something incorrectly?

Thanks again

**Comment by commonsensesoftware** [comment]
I don't have all of the pieces so I'm not entirely sure. OData is very, very picky when it comes to this mapping. Entity set and controller names **must** exactly match up. The only variation is allowing case-insensitivity.

I'm not sure if you're using attribute routing or pure conventions. If you're using pure conventions, you can use the provided **ControllerNameAttribute** attribute to provide an alternate name. This is the name that will be used when looking up the controller. This helps bridge the scenario where the controller type name may not match the resource segment (e.g. entity set in this case).

For example:

```c#
[ApiVersion("1.0")]
[ControllerName("Query-One")]
public class QueryOneController : ODataController
{
}
```

I'm not sure if that's your scenario, but it sounds like it might be.

Let me know whether that helps.

**Comment by jm5599** [comment]
I'm using AttributeRouting yes, everything matches up ok, the controllers are found and matched up to the queries if I use the same odata route prefix for all of them (for example api/**odata**/query[-one,-two-three...].

But as soon as I start adding different odata prefixes there is a problem. I'm using MapVersionedODataRoute (singular) and registering a different VersionedODataModelBuilder on each call : 

Call 1 : VersionedODataModelBuilder which contains ModelConfigurations for query-one and query-two, set up using MapVersionedODataRoute("first-route-version", "routePrefixOne",...)

Call 2 : VersionedODataModelBuilder which contains ModelConfigurations for query-three and query-four, set up using MapVersionedODataRoute("second-route-version", "routePrefixTwo",...)

I would expect to get the following routes :

o /api/**routePrefixOne**/query-one and /api/**routePrefixOne**/query-two
o /api/**routePrefixTwo**/query-three and /api/**routePrefixOne**/query-four

But instead the web api fails to start altogether. It fails because of the initializer code in VersionedAttributeRoutingConvention :

![image](https://user-images.githubusercontent.com/55287048/65263300-9fe22800-db0c-11e9-9e21-8943e21cd58d.png)

BuildAttributeMappings basically always uses the "routeName" used by the first call to MapVersionedODataRoute. So the method tries to resolve "query-three" and "query-four" on the service container linked to "first-route-version" and not "second-route-version" which it obviously can't do. 

I've had to modify BuildAttributeMappings and replace the class scoped routeName by a "fixedRouteName" that points to the correct routeName. Now everything works as expected. the odata route prefixes resolve correctly with the versions.

Not sure if it's a bug or as designed...

**Comment by commonsensesoftware** [comment]
It's more likely a _limitation_ than a bug, but I wouldn't rule out a bug. Web API (OData or no) was simply not designed to support multiple controllers or actions mapped to a single route. In fact, if you poked around in the source (since it seems you have), you'd notice that the `IHttpControllerSelector.GetControllerMapping` method does something quite _weird_. The design only allowed for a single **HttpControllerDescriptor**, but I've extended it with a new type of descriptor that supports aggregation of all possible versioned descriptors.

There is a lot of inflexibility with Web API routing; especially in OData. If you have an end-to-end working example that you can share, I'd consider seeing if there is a way to refactor things to support your scenario out-of-the-box. Quite a few people have asked about this behavior in OData.
