### ISSUE TITLE
Actions with the same name

### ISSUE THREAD

**Issue by JeffMushmo** [Microsoft/aspnet-api-versioning#469]
When defining entity & collection actions , action name cannot be the same for both the entity level and the collection level.

```c#
entityType.Collection.Action("MyActionName").Returns<MyActionResult>();
entityType.Action("MyActionName").Returns<MyActionResult>();
```

This worked fine when using ODataConventionModelBuilder, but breaks when using the versioned one.

The exception I get is:

> Found more than one action with name 'MyActionName' bound to the same type 'WebApp.Models.MyEntity'. Each bound action must have a different binding type or name.

**Comment by commonsensesoftware** [comment]
Is this Web API or ASP.NET Core? I suspect this might be an issue with URL parsing. There is a separate EDM for each API version, which means the behavior _should_ be the same with respect to how the action is resolved.

**Comment by JeffMushmo** [comment]
Asp.Net Core

**Comment by JeffMushmo** [comment]
I found the issue. I was following a code example that suggested I do this:

```C#
            app.UseMvc(routes =>
            {
                CommonModelConfiguration commonModelConfig = new CommonModelConfiguration();
                modelBuilder.ModelConfigurations.Add(commonModelConfig);
                
                var models = modelBuilder.GetEdmModels();
                routes.MapVersionedODataRoutes("odata", "api/v{version:apiVersion}", models);
```

I changed it to this:
```C#
            app.UseMvc(routes =>
            {             
                var models = modelBuilder.GetEdmModels();
                routes.MapVersionedODataRoutes("odata", "api/v{version:apiVersion}", models);
```

And everything works.

**Comment by commonsensesoftware** [comment]
Ah … for your (and anyone else's) future reference, the reason this happened is because **IModelConfiguration** implementations are automatically discovered through dependency injection. **However**, this is not a requirement for the feature to work. There are cases where DI might not find the model configurations automatically or you want to modify the collection before building the EDM models (adding or removing).

Ultimately, it sounds like the issue was that DI found and added your model configuration and then you explicitly added it again. This resulted in the EDM truly generating duplicate actions with the same name.

Since Web API doesn't intrinsically provide DI out-of-the-box, the wiki shows explicitly adding the models. This provides parity between the Web API and ASP.NET Core examples and, hopefully, makes it clear what's happening. I know this threw a few people for a loop when migrating from the Web API to ASP.NET Core implementation. I do call out DI usage in the wiki and the examples all use DI solely. I don't have a great answer for the opportunity to mix and match. If there's a suggestion to improve the documentation, I'm happy to update it.

Regardless, I'm glad you got things working. :)
