### ISSUE TITLE
IsDeprecated() overwrites the previous value

### ISSUE THREAD

**Issue by jo-ninja** [microsoft/aspnet-api-versioning#470]
In `SwaggerDefaultValues.cs` sample code,

`operation.Deprecated = apiDescription.IsDeprecated();`

will overwrite and reset the deprecated flag already set to `true` by SwaggerGenerator because of the presence of `Obsolete` attribute in the user code (controller action).
I also wrote about this in a detailed blog post:
https://medium.com/@joni2nja/swashbuckle-and-api-versioning-obsolete-attribute-is-not-rendered-as-deprecated-in-swagger-ui-c44415111085

Is it possible to update the sample code to something like this?
`operation.Deprecated |= apiDescription.IsDeprecated();`

Any thoughts on this change?

**Comment by commonsensesoftware** [comment]
Reasonable. Nice write-up BTW.

Before I go ahead with the change, I am a little curious as to how the values do not match. I suspect this is because API Versioning and Swashbuckle have different ways for marking an API version as deprecated. Swashbuckle honors `[Obsolete]` decorated on a method, but API Versioning considers the value from `IApiVersionProvider.Options`, which may have the _Deprecated_ flagged applied and is realized through methods, classes, attributes, and/or conventions (ex: `[ApiVersion("42.0", Deprecated = true)]`). There's nothing wrong with using `[Obsolete]` as long as you don't mind those pesky compiler warnings. ;)

I don't anything wrong with having the example play _nice_ with both styles. I'll sneak the update in on the next set of changes.
