### ISSUE TITLE
swagger UI Try it now doesn't enclose the string params with single quotes

### ISSUE THREAD

**Issue by cfcGH** [microsoft/aspnet-api-versioning#473]
I was following with the SwaggerOdata sample to get the Odata endpoints to be shown with swagger.
For some reason when I click the Try it now, the test URL doesn't have string params enclosed in single quotes and swagger UI responds with "Resource cannot be found". This is an unbound function and args are prefixed with [OdataFromUri] attribute. I  was able to make everything else work just following with sample code, great help Chris!, any thoughts in this issue ?

**Comment by commonsensesoftware** [comment]
If I understand correctly, you're saying that user string input is being put in as `foo bar` instead of `'foo bar'`? Is this happening in the path or the query string? If it's in the path, then it _might_ be a bug. Convention-based string parameters are supposed to build the template with the required single quotes. If you're using attribute-routing, you are required to put the single quotes in. The API Explorer uses the exact templates for attribute routing. If the value is in the query string, I'm not sure there is anything that can be done without tweaking some stuff on the Swagger side. There's not a way to tell it to encode values with single quotes. Sounds like this might be in the path though. Do you have examples of the template and values being supplied?

**Comment by commonsensesoftware** [comment]
Did you have some examples of for this? Are you using attribute routing or OData conventions? If you're using attribute routing, you might be missing the `'` in your template. If it's OData conventions, there could be a bug that isn't producing the correct quotes for the template.

I need some scenario or repro before I can do anything. Thanks.

**Comment by commonsensesoftware** [comment]
It would seem this issue was resolved or otherwise abandoned. If you still need assistance, feel free to come back or reopen this issue. Thanks.
