### ISSUE TITLE
Should return 400 ApiVersionUnspecified but instead returns 404

### ISSUE THREAD

**Issue by sabmah** [microsoft/aspnet-api-versioning#477]
I have following setup and I want version specified in the route path.

```csharp
config.AddApiVersioning(opt =>
	{
		opt.ReportApiVersions = true;
		opt.AssumeDefaultVersionWhenUnspecified = false;
	}
);

config.AddVersionedApiExplorer();

// Web API routes
config.MapHttpAttributeRoutes(
	new DefaultInlineConstraintResolver
	{
		ConstraintMap =
		{
			["apiVersion"] = typeof(ApiVersionRouteConstraint)
		}
	}
);
config.Routes.MapHttpRoute(
	"DefaultApi",
	"api/{controller}/{id}",
	new { id = RouteParameter.Optional }
);
```
Following tests were done:
 - api/v1/values => 200
 - api/v2/values => 200
 - api/v3/values => 400 (UnsupportedApiVersion)
 - **api/values => 404 (should return 400 ApiVersionUnspecified)**

Error Resposne: 
```json
{"Message":"No HTTP resource was found that matches the request URI 'http://localhost:56057/api/values'.","MessageDetail":"No type was found that matches the controller named 'values'."}
```

**Comment by commonsensesoftware** [comment]
@sabmah apologies for the delayed response. Unfortunately, in the particular scenario this is the expected behavior and is yet another consequence of versioning by URL segment (which I'm not a fan of).

API versioning can tell that an API version is required in the path when you have the route constraint present in your route template. It can also allow it to be omitted if you so configure it that way. However, it cannot disambiguate between a route that truly doesn't exist (ex: `api/i-do-not-exist`) and should return 404 versus a route that is missing an API version by _convention_. The only way API versioning knows that an API version is required in this scenario is via the route constraint.

In your particular scenario and configuration, there is never a scenario were `api/values` _could_ exist so 404 is the correct response. The reason responses are 400 versus 404 all the time is a bit of a gray area. API Versioning will use 400 when an unmatched route _could_ match. The correlation is all done with URLs and in this case, the paths do not match up.

I hope that helps clarify things.

**Comment by commonsensesoftware** [comment]
It seems this issue was resolved or otherwise abandoned. If you still have questions or issues, feel free to come back and/or reopen the issue. Thanks.
