### ISSUE TITLE
api versioning reports v1 when no controllers don't have it 

### ISSUE THREAD

**Issue by ericbehughes** [Microsoft/aspnet-api-versioning#480]
Dear Microsoft , 

We created a blank web api that uses versioning and we cannot deprecate v1.
We wanted to know why the Api versioning reports v1 when no controllers don't have it.

We are using 
Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer 3.2.0
Microsoft.AspNetCore.Odata.Versioning 3.1.0

Thanks.

**Comment by commonsensesoftware** [comment]
To clarify, do you want to _deprecate_ v1 or do you want to get rid of it? An API version that is deprecated is still accessible. From your description, it sounds like you added API versioning and are surprised to find that all of your controllers have v1. This would be the default behavior. Once API versioning is enabled, **all** controllers have an API version, even controllers that didn't before. Attributes are only one way that versioning can be enabled. As documented in the wiki, if a controller has no other API version information provided via an attribute or convention, then that controller and all of its actions will have the API version defined by `ApiVersioningOptions.DefaultApiVersion`. This property has a default value of `1.0`, which appears to be what you are describing. This behavior enables service authors to quickly enable API versioning by _grandfathering_ in all the existing APIs with an initial, default version (which you always had, but didn't give a name or value to). There is no way to make this initial API version _deprecated_. If you want to keep `1.0`, then you'll need to define (by attributes if you wish) API versions for `1.0`  and whatever your current version is. You can optionally mark `1.0` as _deprecated_. If you don't want to keep `1.0`, then simply defining any other API version will make that version gone for good.

I hope that helps. Let me know if you have more questions.

**Comment by ericbehughes** [comment]
Dear common, 

We would like to completely remove it from the swagger docs.  However, if we create another version say 1.1 or 1.4 the 1.0 still remains in the web page.

As you said that if you do not want to keep 1.0 then simply define any other does not work in our case.

Thanks

**Comment by commonsensesoftware** [comment]
Are you saying that `1.0` is reported/discovered as an API version, but there are no APIs listed in Swagger?

Do you by chance have _version-neutral_ APIs? Version-neutral routes will always match the default API version, even if nothing else does. To address this issue, you'll need to make `ApiVersioningOptions.DefaultApiVersion` the lowest API version you've defined.

I was able to reproduce this behavior by changing the API versions in the sample project to use dates instead of numbers. Without changing the default API version, `1.0` is still reported for **GetSalesTaxRate** action because it is _version-neutral_. This results in 4 API versions being displayed instead of 3. After changing the default API version to the lowest version (which is a date), `1.0` is no longer reported.

I'm not sure if that's your scenario, but perhaps it will help.

**Comment by ericbehughes** [comment]
ApiVersioningOptions.DefaultApiVersio worked !

**Comment by commonsensesoftware** [comment]
Awesome! Glad you were able to sort it out.

**Comment by commonsensesoftware** [comment]
This issue appears to be resolved. Come back if you have more questions. Thanks.
