### ISSUE TITLE
Get Request without Content-Type Header returns 415 Unsupported Media Type

### ISSUE THREAD

**Issue by frankpeacht** [microsoft/aspnet-api-versioning#489]
This error occurs for Versions greater than 3.0 

Steps to reproduce
- Add `[Consumes("application/json")]` to Controller Class
- Make a GET HTTP call to Controller without Content-Type headder
- 415 Unsupported Media Type is returned

Downgrade to 3.0 and the above steps return 200

GET and DELETE should not require Content-Type I do not know if this is related to a similar core 2.2 bug https://github.com/aspnet/AspNetCore/issues/4396 even though I am currently using core 2.1

**Comment by commonsensesoftware** [comment]
I'm not sure I completely follow. It _sounds_ like you want to version by media type. Obviously `Content-Type` doesn't make sense for `GET` or `DELETE` since there is no content. You need to use **Accept** instead. If that's not the case, I need more information.

**Comment by frankpeacht** [comment]
versioning in this case is done via url `[Route("api/v{version:apiVersion}/[controller]")]`
I have not attempted to use version by media type. 

The bug is that one is _required_ to add Content-Type to GET and DELETE or 415 is returned. But as you stated this makes no sense as there is no content. 

`GET` and `DELETE` should return successfully without Content-Type headers. I had to downgrade to version 3.0 as higher versions contain this bug.

**Comment by commonsensesoftware** [comment]
OK … now I think I understand what's going on.

To be completely pedantic, `GET` and `DELETE` should **not** _consume_ anything - they are not expected to receive content. This is particularly true for `GET`. There's nothing in the RFC that states `DELETE` cannot have content, but it's unusual.

<end soapbox>

Ultimately, this is a bug/behavior in ASP.NET Core which I do not have any control over. Since there are already open issue(s), your best bet is to engage with the ASP.NET team (which I'm not a part of).

Depending on your objectives, you should be able to work around this issue a number of different ways. If all you want is the request to work, then remove `[Consumes]` and I would expect it to _just work_, since there are no constraints and there are matching media type formatters. If you're trying to make it work with Swagger, then you'll likely need to customize your Swagger generator (ex: Swashbuckle) to add the content types outside of the purview of ASP.NET Core.

**Comment by frankpeacht** [comment]
Thank you so much for your replies. We had the consumes on a base controller class so we would not have to decorate every method. And I do understand that there are workarounds outlined in the .NET Core issue.

I understand that this is an ASP.NET Core issue, but I do have one final question and it may show my lack of understanding of the dynamics between API Versioning and .NET Core.

Why does this but show up in API Versioning when I am not using the version of .NET Core that has this bug?

**Comment by commonsensesoftware** [comment]
I can't right say. It could be that an unintended change in 2.2 broke things even with backward compatibility enabled. API Versioning does not directly care about, use, or inspect the **ConsumesAttribute** or the **ProducesAttribute** for that matter - not even by the API Explorer. It's all based on what first comes from ASP.NET Core.

I can investigate, but I'm not sure I'll find anything.

**Comment by commonsensesoftware** [comment]
Were you able to ever resolve this or come up with a solution? I've looked into this a bit more, but I haven't found anything specific to API Versioning itself. I'm not there is anything directly in API Versioning that can be done to address this issue. There are no explicit scenarios where API Versioning ever returns 415.

**Comment by commonsensesoftware** [comment]
It appears this issue has been resolved or is otherwise external to API Versioning. If you continue to have issues or have more questions, feel free to come back or reopen the issue. Thanks.
