### ISSUE TITLE
Support media type subtype parameter as version source

### ISSUE THREAD

**Issue by peteraritchie** [Microsoft/aspnet-api-versioning#491]
There are benefits and drawbacks with each method of versioning relating to Web APIs.  Almost all take into account the "API" version.  An API is a representation of functionality or capability, if there's a major functional change to an API, it should have an endpoint that better describes the functionality.  In all other cases, the required versioning involves _content_.  Both request and response. 
One benefit of putting the version in the subtype parameter (e.g. `application/vnd.null.entity+json; v=2` ) is that it is the only method that supports different versions of _content_. `application/vnd.null.entity+json; v=2` signifies version two of the JSON format of the content.  I would hazard to say that more often than not that if one format changes so does the other.  But, there are several scenarios where one format can change and _not_ the other.  e.g. an API that supports JSON and XML has two different syntaxes to deal with.  XML, for example, has "attributes" and while there are conventions to have attribute-like things in JSON, the fact remains that two different syntaxes can have two different reasons to change.  Two different reasons to change means two different version lineages.

**Comment by commonsensesoftware** [comment]
I'll start by marking this as a question because I believe you asking for versioning to be supported by way of media type negotiation using a media type parameter. It may not be super obvious, but this is already support today and has been for some time (🤯). 

This is described in the [Versioning by Media Type](../wiki/Versioning-by-Media-Type) and [Media Type API Version Reader](../wiki/API-Version-Reader#media-type-api-version-reader) wiki topics. The default parameter name is `v`, but you can use whatever parameter name you like. If you're interested in a more comprehensive view of how it works, you can take a peek at the [acceptance tests](../blob/master/test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/Mvc/MediaTypeNegotiation/given%20a%20versioned%20Controller/when%20using%20media%20type%20negotiation.cs) that use this style of versioning.

The wiki mentions the headers involved, but I know it's thrown a few people for a loop. Here's a simple table for all to see:

| Method | Header |
| -------- | --------- |
| GET      | Accept |
| POST    | Content-Type, Accept |
| PUT      | Content-Type |
| PATCH  | Content-Type |
| DELETE | Accept* |

In short, if a request has content, then `Content-Type` is expected; otherwise, `Accept` is used. If both are specified, `Content-Type` is always preferred first as you shouldn't be sending that header unless you are sending content. `DELETE` is more of an enigma that is often not discussed in versioning. It typically neither sends nor receives content. You can use `Accept` or you can now mark that specific action as _version-neutral_ since `DELETE` usually does not vary by API version and would allow no input or output media type to be specified.

If you don't fancy those, you can always create a custom **IApiVersionReader** or extend the default **MediaTypeApiVersionReader**. Custom media types containing the API version in the text is not supported out-of-the-box because there is no standard convention or format to extract it from. I've gone to great lengths to avoid parsing _magic strings_. While the API version type and parsing is supported, it's always performed on an unmodified, discrete string (e.g. no trimming, etc).

I hope that helps. If I totally missed the boat, let me know and I'll be sure to answer you question. Thanks.

**Comment by peteraritchie** [comment]
Sorry, I noticed that after I posted the issue.  I was basing it on 

> Defining new, custom media types (ex: application/vnd.my.company.1+json) to drive API versioning is another variant of this approach that is accepted within the constraints of REST. This method of API versioning, however, is not supported out-of-the-box

In Versioning-by-Media-Type.

I'd do a PR for it, but I would imagine there are some specific examples that would be required?

**Comment by commonsensesoftware** [comment]
Such an implementation would have to support **all** flavors of an API version. The API version has a prescribed format that can be used in whatever input. This would mean you example would have the form of: `application/vnd.my.company.{version}+json`. The following media type would, therefore, be completely valid: `application/vnd.my.company.2019-04-01.1.0-beta1+json`. No one would probably use that format, but it's still valid.

The reason this has never been supported out-of-the-box is that there isn't a clear way to reason about the format of custom media types. This can probably only be achieved with some gnarly regex. The other reason it wasn't intrinsically supported is that you _really_ have to want to do it that way because it requires remapping media type formatters. The built-in logic doesn't consider media type parameters so `application/json;v=1.0` works effortlessly without having to remap anything.

I'm not opposed to the idea of supporting this, but I'm a bit skeptical as to whether it can really be made generic and whether it's that valuable to anyone. I don't have metrics, but versioning by media type doesn't appear to be all that common (though I agree - it's the only _true_ way to do it RESTfully).

**Comment by peteraritchie** [comment]
> Such an implementation would have to support **all** flavors of an API version. The API version has a prescribed format that can be used in whatever input. This would mean you example would have the form of: `application/vnd.my.company.{version}+json`. The following media type would, therefore, be completely valid: `application/vnd.my.company.2019-04-01.1.0-beta1+json`. No one would probably use that format, but it's still valid.
> 
> The reason this has never been supported out-of-the-box is that there isn't a clear way to reason about the format of custom media types. This can probably only be achieved with some gnarly regex. The other reason it wasn't intrinsically supported is that you _really_ have to want to do it that way because it requires remapping media type formatters. The built-in logic doesn't consider media type parameters so `application/json;v=1.0` works effortlessly without having to remap anything.
> 
> I'm not opposed to the idea of supporting this, but I'm a bit skeptical as to whether it can really be made generic and whether it's that valuable to anyone. I don't have metrics, but versioning by media type doesn't appear to be all that common (though I agree - it's the only _true_ way to do it RESTfully).

Agreed.  When I used "subtype parameter" I mean `application/subtype; parameter` or `application/vnd.null.entity+json;v=1.0`

**Comment by commonsensesoftware** [comment]
The built-in **MediaTypeApiVersionReader** doesn't care what the actual media type is. It only considers and extracts the configured media type parameter which defaults to `v`. This means that a media type such as `application/vnd.my.company.entity+json;v=1.0` will work just fine. Of course you still have to map the media type formatters for ASP.NET Core, but that's your choice.
