### ISSUE TITLE
.NET Core 3.0 support

### ISSUE THREAD

**Issue by saukun** [Microsoft/aspnet-api-versioning#492]
Is there any plan supporting .NET Core 3.0? as now nuget package is showing dependency Microsoft.AspNetCore.Mvc.Core (>= 2.2.0 && < 3.0.0).

**Comment by commonsensesoftware** [comment]
I think you're confusing .NET Core with ASP.NET Core (thanks marketing guys!). .NET Core is a runtime and that's already supported. ASP.NET Core is the platform, which is currently 2.2. There currently is no ASP.NET Core 3.0 in any form. When that happens, 3.0 will be supported by this library.

I've gotten into the habit of clipping off dependencies at the next major version. It's caused me grief in the past, especially with OData. In general, that's a reasonable practice since one can expect breaking changes after a major version change. I'm not aware of any forthcoming breaking changes - yet.

I hope that answers your question.

**Comment by saukun** [comment]
Yes, thanks, definitely confused it with .NET Core runtime. Good to know it already supports upcoming .NET Core 3.0 runtime.
