### ISSUE TITLE
Unclear how to provide an alternative IApiVersionSelector

### ISSUE THREAD

**Issue by swageblock** [Microsoft/aspnet-api-versioning#495]
I am attempting to implement a new version selector that selects the latest (non-alpha) minor version of the major version specified by the url segment.  I have the following code in my WebApiConfig
``` 
public static void Register(HttpConfiguration configuration)
        {
            var constraintResolver = new DefaultInlineConstraintResolver() { ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) } };
            configuration.AddApiVersioning(options =>
            {
                options.ApiVersionSelector = new LatestMinorVersionSelector(options);
                options.ReportApiVersions = true;
            });
            configuration.MapHttpAttributeRoutes(constraintResolver);
        }
```

When I inspect the contents of configuration.GetApiVersioningOptions() I can see that the selector is a reference to my expected implementation.  When I put a breakpoint in the SelectVersion() method it is never hit.  Is this the correct approach or am I misunderstanding how to best extend this functionality.

**Comment by commonsensesoftware** [comment]
There is often some confusion with how/when the **IApiVersionSelector** is used. To level set the behaviors, let me clarify that API Versioning **requires** an API version be specified by the client. This would almost certainly be a breaking change for existing APIs. An existing API always has a version, even if it's unstated or has no official value. Some people call it the initial version, legacy version, or simply "v1".

This means that API Versioning has two key services:
- **IApiVersionReader** - read/select/extract the explicit API version provided by a client
- **IApiVersionSelector** - select an API version from known versions when a client does **not** specify a version and it is allowed

API Versioning will, therefore, not use the **IApiVersionSelector** when a client does specify version as you might expect; this is by design. The server should return the version the client asked for or fail. In the case where a client doesn't specify a version, the **IApiVersionSelector** is used to implement the policy you want. Again - this was mostly meant for _grandfathering_ in existing services, but some people have been using it for net new services. I do not recommend this practice for new services. A client should know the version they want/need and ask the server for it. The server should honor that in a predictable way. _Floating_ versions, even the minor version, _can_ break a client.

To trigger the execution of the **IApiVersionSelector**, you need to enable `options.AssumeDefaultVersionWhenUnspecified = true;` and make a request without a version. Arguably, this interface _could_ have been named differently; however, it _could_ be used for other scenarios, even though it's not.

You said you're versioning by URL segment, which will cause another level of issues for you as well. It is not possible to have an optional URL segment in the middle of the path. This means that you'll have to use double route templates for the _latest_ route template which _float_ between controllers if you expect to implement this behavior.

Something like:

```c#
[ApiVersion("1.0")]
[RoutePrefix("api")]
public class ValuesController : ApiController
{
    [Route("values")]
    [Route("v{version:apiVersion}/values")]
    public IHttpActionResult Get() => Ok();
}
```

where `api/values` moves to a new controller when the _latest_ implementation changes. This is simply a limitation of how the routing system works when you version by URL segments. Other versioning methods do not have this limitation.

Alternatively, you could use URL Rewriting or HTTP redirects that forwards a request to the latest minor version.

**Comment by swageblock** [comment]
Thanks for that clarification!  It will be great detail for discussions on how we move forward.
