### ISSUE TITLE
Does not build on VS for mac

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [microsoft/aspnet-api-versioning#497]
I'm trying to build the "AspNetCore -> SwaggerSample" on my VS for MAC but i'm getting an error:

> /Users/leonardo/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta-63127-02/build/Microsoft.Build.Tasks.Git.targets(5,5): Error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
> System.BadImageFormatException: Method has no body
> File name: 'LibGit2Sharp'
>   at LibGit2Sharp.Core.Proxy.git_buf_free (LibGit2Sharp.Core.Handles.GitBuf buf) [0x00000] in <06ab184b4ccd4259a7a7af2756f77645>:0 
>   at LibGit2Sharp.Core.Handles.GitBuf.Dispose () [0x00000] in <06ab184b4ccd4259a7a7af2756f77645>:0 
>   at LibGit2Sharp.Core.Proxy.ConvertPath (System.Func`2[T,TResult] pathRetriever) [0x0002e] in <06ab184b4ccd4259a7a7af2756f77645>:0 
>   at LibGit2Sharp.Core.Proxy.git_repository_discover (LibGit2Sharp.Core.FilePath start_path) [0x00005] in <06ab184b4ccd4259a7a7af2756f77645>:0 
>   at LibGit2Sharp.Repository.Discover (System.String startingPath) [0x00006] in <06ab184b4ccd4259a7a7af2756f77645>:0 
>   at Microsoft.Build.Tasks.Git.GitOperations.LocateRepository (System.String directory) [0x00000] in /_/src/Microsoft.Build.Tasks.Git.Operations/GitOperations.cs:24 
>   at Microsoft.Build.Tasks.Git.RepositoryTasks.LocateRepository (Microsoft.Build.Tasks.Git.LocateRepository task) [0x00000] in /_/src/Microsoft.Build.Tasks.Git.Operations/RepositoryTasks.cs:50 
>   at Microsoft.Build.Tasks.Git.LocateRepository.Execute () [0x00038] in /_/src/Microsoft.Build.Tasks.Git/LocateRepository.cs:32 
>   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:573 
>   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:810  (MSB4018) (Microsoft.AspNetCore.Mvc.Versioning)

any ideas?

**Comment by commonsensesoftware** [comment]
I can't rightly say. I don't use a Mac nor have access to one to verify the build.

I don't recognize a lot of this information. I see stuff related to Git and Jenkins which would **not** be any part of the normal build process. It looks more like you are trying to automate a CI build in Jenkins. That's certainly possible, but I don't have any experience with it to provide you guidance on how. I can say that a **BadImageFormatException** most often happens due a processor architecture mismatch (e.g. x86 vs x64).

You should be able to simply run `msbuild -v:m` from the command-line to build the solution with minimal logging. If that is failing for you, then I can probably give you some pointers on resolving it.

I hope that helps - at least a little.

**Comment by Leonardo-Ferreira** [comment]
I only cloned, opened, and "Rebuild"... it failed with that message...

**Comment by commonsensesoftware** [comment]
Interesting... Hmm... I guess VS on Mac must be using some of that behind the scenes.

As a rhetorical question, do you have VS up-to-date? Are you using VS2017 or VS2019? It should theoretically work for both even though I work exclusively on VS2019 now, but I started on VS2017.

It seems that VS for Mac uses the Mono flavor of MSBuild. I know MSBuild well, but I know nothing of the idiosyncrasies of it in Mono or on a Mac.

I don't expect it will help you in VS, but you can build everything with the .NET Core SDK too. Unfortunately, there apparently isn't a way to make VS build using the SDK. Simply running `dotnet build` from the root should build everything. I'm using the current version of the SDK - **2.2.101**.

It's painful, but if you're able to build command-line, then you should be able to attach the debugger from VS if you need to debug anything.

There isn't anything Windows-specific - intentional or otherwise, that I'm aware being used in the solution. I'm not sure why it's not working.

**Comment by commonsensesoftware** [comment]
Were you ever able to resolve this?

**Comment by commonsensesoftware** [comment]
It seems you either got this working or abandon your attempts to do so. If you never got things working and are still interested in resolving the issue, feel free to come back or reopen the issue. Thanks.
