### ISSUE TITLE
Add routing constraint support

### ISSUE THREAD

**Issue by TsengSR** [Microsoft/aspnet-api-versioning#5]
It's nice to have a way to version your WebAPI, but as a query parameter it's quite useless unless we can encode this inside a route constraint, i.e. `/api/v2/values`, which is common practice and way to encode and it becomes a natural part of the WebAPIs base url, when used in rest clients.

**Comment by commonsensesoftware** [comment]
The libraries default to using a query string parameter because the resource URLs are more stable that way and it's easier to integrate API versioning into existing codebases. Consider that ```/api/v1/orders/1``` and ```/api/v2/orders/1``` both refer to the same resource (e.g. order 1), but with different URLs. The uniform interface constraint states that a resource should be unique identifiable by it's URL path. The query string is not considered part of the path. When using a query string parameter, the identifier is always ```api/orders/1```, regardless of which version of the order you ask for because the resource is logically the same, even though its representation or behavior is different.

Nevertheless, you are correct that having part of the URL path represent an API version is quite common. Heated arguments have been made as to which approach is better. While the libraries do have a default configuration, the approach you choose to use to version your APIs is up to you.

API versioning using a URL path segment is supported and documented.  Please review the wiki topic on [Versioning via the URL Path](../wiki/Versioning-via-the-URL-Path).
