### ISSUE TITLE
NU1202: Version 3.1.2 is not compatible with netcoreapp2.2

### ISSUE THREAD

**Issue by he-dev** [microsoft/aspnet-api-versioning#506]
I cannot install the latest version of the versioning package as VS2019 is saying:

> NU1202: Package Microsoft.AspNetCore.Mvc.Versioning 3.1.2 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2). Package Microsoft.AspNetCore.Mvc.Versioning 3.1.2 does not support any target frameworks.

However, it is possible to instal `3.1.1` without errors. How can I fix that and install the `3.1.2`?

**Comment by commonsensesoftware** [comment]
Hmmm... that seems very strange since 3.1.2 is just a patch over 3.1.1.

Visual Studio does occasionally give me grief on package restore. You might try:

1. Edit the project and manually change the package version to 3.1.2
2. Open the **Developer Command Prompt for VS2019** in the project location
3. Run `dotnet restore` or `msbuild -v:m -t:Restore`; they should both have the same net effect
4. Go back to Visual Studio and try building again

If package restore is still failing on the command-line, then something else is wrong. All of the test and sample projects target **netcoreapp2.2** so 3.1.2 is definitely compatible.

Try that first and if it doesn't work, we can dig into other details.

**Comment by commonsensesoftware** [comment]
Were you able to resolve this issue and get things working?

**Comment by he-dev** [comment]
@commonsensesoftware I was able to fix it with your checklist. Thanks! I guess upgrading packages must have messed up nuget catches or something.

**Comment by sillysachin** [comment]
I upgraded to aspnetcore 3.1 https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio-mac

The issue gets resolved.
