### ISSUE TITLE
ApiVersionMapping Flags

### ISSUE THREAD

**Issue by JoshKeegan** [microsoft/aspnet-api-versioning#508]
Hi,
The [`ApiVersionMapping` enum](https://github.com/microsoft/aspnet-api-versioning/blob/c8d7ff7c4a9012c389a98c36d56e833e240e8346/src/Common/Versioning/ApiVersionMapping.cs) gets [used with bitwise logic](https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Abstractions/ActionDescriptorExtensions.cs#L43).
Should it be marked as `[Flags]`?
Cheers,
Josh

**Comment by commonsensesoftware** [comment]
This was a really _interesting_ design decision, which arguably doesn't have a _perfect_ answer. There are only a handful of scenarios where you might ask for both implicit and explicit mappings. Most, if not all, of those touch points are abstracted away with extension methods or other components such as the API Explorer. If we were only considering how you _ask_ for an API model to be populated, you'd be 100% correct.

The inverse of this scenario is that you can ask _how_ an API version is mapped a la the `MappingTo` extension method which returns the same **ApiVersionMapping** enumeration. The code analysis rules state that a bitwise enumeration should be plural (e.g. _ApiVersionMappings_). Ultimately, the real reason that it's not a bitwise enumeration though is that it would not make any sense in this context. An API version cannot be mapped explicitly and implicitly at the same time. Every API version is mapped explicitly, implicitly, or not at all (e.g. _None_).

This put things in an interesting place because the enumeration values are the same, but on the way in there is a scenario for them to be bitwise and on the way out there isn't. An alternate solution would have been to have two enumerations, but that seemed like overkill. Since there will only ever be these 3 values I decided to go ahead without making the enumeration bitwise. I also assumed that testing how an API version is mapped would be more prevalent than asking for the model itself. .NET doesn't perform much validation on enumerations, so I errored on what I thought would be the proverbial 80%.

I'm not sure it's truly needed, but I'm open to hear arguments about why this should be a bitwise enumeration. I hope that clarifies things.

**Comment by JoshKeegan** [comment]
Thanks for the detailed (and speedy) explanation :)
I guess it should technically be two enums, possibly with mapping between them but I agree that it would be overkill here, and if done now it would be a breaking change with very little benefit.

I'd stumbled across this because we're doing a logical OR on the enum in our code & resharper was warning about it. I'll just add a link to this issue and otherwise leave everything as-is 👍
