### ISSUE TITLE
CreatedAtRouteResult on versioned API

### ISSUE THREAD

**Issue by rossbuggins** [microsoft/aspnet-api-versioning#517]
On a controller I want to return a 201 through CreatedAtRouteResult and return the location of an OdataController (different controller to one request is being handled in).  Currently struggling to get it to generate the correct route and am just getting a 500 with ` No route matches the supplied values.`

**Comment by rossbuggins** [comment]
I've just answered my own question, the issue here is that odata uses odatapath instead of controller:

```
        var result = this.CreatedAtAction(
                "Get",
                new { odataPath = "MyOdataControllerName", value = "string", version = apiVersion.ToString() },
                "string");


```

**Comment by rossbuggins** [comment]
Although, looking at the location uri, its adding extra query parameters on that it doesn't need.

'''
api-supported-versions: 1.0 
 content-length: 0 
 date: Mon, 15 Jul 2019 15:14:47 GMT 
 location: https://localhost:5001/api/v1/WebHook?controller=WebHook&action=Get 
 server: Kestrel 
'''

Any thoughts on how to get it to not do this? Thanks

**Comment by commonsensesoftware** [comment]
Correct. For good measure, I would recommend always specifying the `apiVersion` route parameter in **CreatedAtRouteResult** and **CreatedAtAction**.

**Comment by commonsensesoftware** [comment]
That's because OData doesn't use the standard MVC routing mechanism. Although the `controller` and `action` route parameters are used in matching within the pipeline, they are not provided in the route template. Instead, there is only the `odataPath` route parameter.

It would appear that you want return an appropriate 201 response that includes the correct `Location` header. The **ODataController** base class provides a built-in method to do this for you. Use and return `this.Created` instead. Alternatively, you can use the **CreateODataLink** extension method for **IUrlHelper** to build the URL yourself.

I hope that helps.

**Comment by rossbuggins** [comment]
Its a non-odata controller that im creating the 201 in, but want it to give the url of an odata controller, gone round in circles a few times now ... :-O!

**Comment by rossbuggins** [comment]
I'm thinking the CreateODataLink helper method would be the way to go, could you give me point on the params it needs please? cheers

**Comment by commonsensesoftware** [comment]
Ah … now I see. In this type of scenario, you may be stuck generating the URL completely, or at least mostly, by hand. This is because you need the underlying EDM model to build the URL, which will not be available/resolved in a non-OData route context.

I haven't tried this particular operation, but in _theory_ if you can get the available OData routes, then you _should_ be able to generate the link. The minimum requirement is to get the current OData container. From there you can ask it for the current **IEdmModel**. You can determine if it's the correct model by querying `model.GetAnnotationValue<ApiVersionAnnotation>(model).ApiVersion` and evaluating whether it matches the currently requested API version.

If this sounds complicated, that's because it kind of is. The link generation process is also not API version aware. Your original approach might be the best case in this scenario. If you omit the `controller` and `action` route parameters, you should get the correct URL without the query parameters. These values are not externally known and will be resolved by the appropriate **IODataRouteConvention** at request-time.

I suspect your implementation is split between an **ODataController** and **ControllerBase** base class. That should mean that you want to use **CreatedAtRouteResult** instead of **CreatedAtAction**. **CreatedAtRouteResult** will resolve and build the route template based on the corresponding route name. **CreatedAtAction** uses the name of the action name on the current controller.

**Comment by rossbuggins** [comment]
Ok thanks, will take a break and relook at this tomorrow. Just noticed as well that my above "solution" doesn't play ball with parameters nicely for the id of the object - i.e. puts it as a query parameter rather than controllername/id? etc.

I'm just about to swap from url versioning to query string as url versioning is doing my head in some what as well... :-) cheers

**Comment by commonsensesoftware** [comment]
Sounds good. Yeah, despite being popular, putting the API version in the URL segment causes many headaches; especially for HATEOAS.

**Comment by commonsensesoftware** [comment]
Were you able to get a working solution? Has this issue been resolved.

**Comment by commonsensesoftware** [comment]
I seems you found a workable solution or another approach. If you didn't solve your issue, feel free to come back or reopen the issue. Thanks.
