### ISSUE TITLE
How to make ApiVersionNeutral as default behavior ?

### ISSUE THREAD

**Issue by GreatFireWall** [microsoft/aspnet-api-versioning#523]
In other words, if I don't specify any `ApiVersion` attributes, it works as `ApiVersionNeutral`.

**Comment by commonsensesoftware** [comment]
In short, out-of-the-box there is not a way because, honestly, it wouldn't make any sense. API _version-neutral_ means that an API accepts any and all versions, including none at all. If this was a supported default behavior, then it would be like you didn't have API versioning at all.

I suspect you have a specific reason why you want to enable such a behavior. If you can articulate you scenario in more detail, I can help you come up with a configuration to reach your goals.

**Comment by GreatFireWall** [comment]
Thanks your answer.

Because I currently have a small asp.net core project, its backend is mixed with API for desktop application calls, website payment interface, some other functions of the website interface.
Only the "API for desktop application calls" needs versioning. Sometimes I forget to add an `ApiVersionNeutral` attribute to `Controller`, then causes the request to return an error, then I'll add `ApiVersionNeutral`. 

Although this can solve the problem, it seems that every time a new controller is added, there are some obstacles.

**Comment by commonsensesoftware** [comment]
I see... it sounds like you want to enable:

```c#
options.AssumeDefaultVersionWhenUnspecified = true;
```

This feature was meant to ease _grandfathering_ in existing services as you have, although some people have tried to use it for other purposes.

The way to think about this is that all of your services have some existing, logical API version that you never assigned a value to. Maybe you all it "V1", "Initial Release", or something else, but it has _some_ kind of version. As you're observing, if all APIs suddenly require an explicit API version for every call (the default behavior) that breaks existing clients. Enabling this option allows clients to call these existing services without explicitly specifying an API version. When that happens, the default behavior will be to match the `options.DefaultApiVersion` value. Controllers which do not have any attribution or conventions will implicitly have this API version. That means without any code changes, all of your existing controllers have this API version and clients can explicitly or implicitly match it with your existing route configuration.

The result of these behaviors is that your existing services do have an API version, but existing clients do not have to specific to continue using it. In this configuration, the behavior **only** applies to that API version. In order for clients to use new API versions, they will have to specify the API version explicitly. Existing clients are already bound to a specific API version, they just don't know (or care) what API version that is. If they want to use a newer API, then requiring an explicit API version to request it is part of that migration process.

The default value for `options.DefaultApiVersion` is `1.0`. You can change it to whatever version you want, but once you set it, you shouldn't change it - ever. If you're using a numeric scheme, then you might choose a value `0.9`. If you're using a date scheme, then you might use the (approximate) date you released your services.

Ultimately, this configuration allows you to transition your existing services over time. You almost certainly do **not** want existing APIs to be _version-neutral_ because that would mean your existing services support all versions now and in the future. It is possible to configure large swaths of controllers as API _version-neutral_, but you should be careful in doing so. Once you configure that it _may_ be difficult or impossible to configure explicit versioning against them without breaking existing clients. Only APIs that have **zero** visible contract changes in their wire protocols should be _version-neutral_. Possible examples include health monitoring APIs such as pings and heartbeats or `DELETE` APIs.

I hope that helps clear things up.

**Comment by GreatFireWall** [comment]
Thank you for your detailed answer. I will take some time to understand it.

**Comment by commonsensesoftware** [comment]
Did this make sense? Were you able to get things working the way you wanted and expected?

**Comment by GreatFireWall** [comment]
Yes, `AssumeDefaultVersionWhenUnspecified` works well. :)
