### ISSUE TITLE
Remove a service on a predetermined date without redeploying 

### ISSUE THREAD

**Issue by Abduolrhman** [microsoft/aspnet-api-versioning#524]
Is it possible to outdate an action on a predetermined date without deleting the action method code, and redeploying?

**Comment by commonsensesoftware** [comment]
First, let's make sure we're on the same page with terminology. By _outdate_, I assume you mean _remove_. API Versioning does support _deprecation_, but that means it will go away, not that it's gone. When an API is no longer supported at all, the expectation is that the code doesn't exist anymore. _Deprecation_ is a way to advertise this going to happen according to some established policy (ex: 6 months).

Web API and ASP.NET Core both do quite a bit of upfront or one-time computation of route information. ASP.NET Core, in particular, is designed such that most, if not all, of this information to be read-only once an application starts taking traffic. To that end, I'm not sure there is really a way to remove or otherwise exclude things once an application is started. It might be possible without redeploying, but it will almost certainly require restarting the application so that it reinitializes.

While you can't _remove_ deployed code, you _could_ inject a _time bomb_ via middleware or an action filter. The exact implementation depends on the platform. If you're using version groups (e.g. dates), then it is the pretty straight forward to do. If the version of the incoming request is less then your configured policy, you can short-circuit the pipeline and return 400, 404, or 405 (which is what API Versioning would do). This would give an impression to a client that the API no longer exists, even though the code still exists on the server.

You scenario isn't that unusual, but many service authors use a policy of something like _N-2_ versions. When the next window of versions slides forward, you'll naturally have to publish the newest version. This is the time where old versions are permanently removed. Unfortunately, there isn't really a way to say _when_ an API will become deprecated ahead of time. It's an interesting thought to ponder, but I would surmise that the majority of the time, it's not known when a particular version will be deprecated, or removed for that matter, ahead of time.

I hope that helps give you some ideas.
