### ISSUE TITLE
Running API versioning with latest ASP.NET Core 1.1.0 preview and full DotNet Framework 4.6.1.

### ISSUE THREAD

**Issue by AlonCG** [Microsoft/aspnet-api-versioning#53]
I know this is a stupid question, and probably just a RTFM situation ... but I can not seem to get this to work using the latest (pre)release versions of the frameworks. I am testing a freshly created project and may have an update soon, but any direction pointing would be appreciative.

Is this even possible (I thought I had no problem referencing other libraries from my code) and where am I going wrong? 

I am working on a small demo project from a cleaner solution ... so I will see what happens and try to resolve it directly. 

Update ... I can get the test project to run using "1.1.0-preview1-final". What does not run is the MVC Controllers (& Views) that I have set up.  All controller/actions return a 404 ... and ... "Microsoft.AspNetCore.Mvc.Versioning.ApiVersionActionSelector: Information: Request did not specify a service API version, but multiple candidate actions were found..." So I'll play with the configuration somewhat.

All the best.

**Comment by AlonCG** [comment]
So far ... I added the "[ApiVersionNeutral]" attribute to my MVC controllers and made sure to use settings like : 
services.AddApiVersioning( options => {
                options.ReportApiVersions = true;
                options.AssumeDefaultVersionWhenUnspecified = true;
                options.DefaultApiVersion = new ApiVersion(1, 0);
            } );

API Controllers now use querystring versioning (so defaults would work) ... 

Trying this on my primary project.

**Comment by commonsensesoftware** [comment]
If I understand correctly, you have a project that has both MVC controllers (e.g. web pages) and API controllers (e.g. APIs), but you only want the API controllers to be versioned. Since MVC controllers never care about versioning, you're correct to mark them as API version-neutral. This opts them completely out of any versioning. I can't really think of any reason to version a MVC controller unless you are trying to implement some type of _flighting_ mechanism.

You don't have to explicitly set the **DefaultApiVersion** to **1.0**; that's already it's default value. I would avoid **AssumeDefaultVersionWhenUnspecified** since you said this a new project. I'm seeing a lot of service authors using this option. It's only meant to bootstrap API versioning over legacy services that don't have any versioning.  Trying to rationalize where requests route to are much easier if all your API versions are explicit.  Just a suggestion.

I've come to develop a _love / hate_ relationship with **project.json**. There a number of good things it brings, but so many more that drive me crazy. In this scenario, updating your dependencies to use ASP.NET Core 1.0.1 should be pretty straight forward. One thing I've learned is to not use the UI and just update the **project.json** by hand.  Also, with the new transitive dependency support in NuGet, you only want to declare the explicit packages you require. All other dependencies will be brought in as necessary. The tooling can be brittle at times. If you're sure you've declared your dependencies correctly, then I would manually delete the **project.lock.json** file and then try package restore again. On occasion, you may need to go to the .NET CLI and run ```dotnet restore``` and rarer still, you may have to restart Visual Studio. None of those are ideal, but those are some things that have worked for me in the past.

I hope that helps.

**Comment by AlonCG** [comment]
Thanks! I just rolled back to a "v1" and this works fine. Still not sure how to get it running on the latest bits (but once I figure it out, I'll let you know!)

Thanks again!
