### ISSUE TITLE
How to Correctly Create a Versioned OData API to existent versioned Web API Solution

### ISSUE THREAD

**Issue by uwdev15** [microsoft/aspnet-api-versioning#530]
I've been stuck on this problem for a while. I have an existent versioned web API solution and I want to add in some versioned OData API controllers as well. Currently I keep getting an error that says

System.InvalidOperationException: 'The path template 'v{version:apiVersion}/People/GetPeople' on the action 'GetPeople' in controller 'People' is not a valid OData path template. Resource not found for the segment 'v{version:apiVersion}'.'

I was previously able to get this project working with no versioning for both controllers but adding it in causes me not to be able to hit either.

Any help would be greatly appreciated. Thanks in advance!

Global.asax.cs

public class WebApiApplication : System.Web.HttpApplication
{
    protected void Application_Start()
    {
        GlobalConfiguration.Configure(config => {
            ODataConfig.Register(config);
            WebApiConfig.Register(config);
        });
    }
}
ODataConfig.cs

public static void Register(HttpConfiguration config)
    {
        var constraintResolver = new DefaultInlineConstraintResolver()
        {
            ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) }
        };

        config.MapHttpAttributeRoutes(constraintResolver);
        config.AddApiVersioning(o => o.ReportApiVersions = true);

        var builder = new VersionedODataModelBuilder(config)
        {
            ModelBuilderFactory = () => new ODataConventionModelBuilder().EnableLowerCamelCase(),
            ModelConfigurations =
            {
                new tblPeopleModelConfiguration()
            }
        };

        var models = builder.GetEdmModels();

        config.MapVersionedODataRoutes("odata", "v{apiVersion}", models);
WebAPIConfig.cs

public static void Register(HttpConfiguration config)
    {
        config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "v1/{controller}/{id}",
                defaults: new { id = RouteParameter.Optional }
        );
    }
ProductsController.cs

[ApiVersion("2")]
[RoutePrefix("v{version:apiVersion}/products")]
public class ProductsController : ApiController
{
    Product[] products = new Product[]
    {
        new Product { Id = 1, Name = "Tomato Soup", Category = "Groceries", Price = 1 },
        new Product { Id = 2, Name = "Yo-yo", Category = "Toys", Price = 3.75M },
        new Product { Id = 3, Name = "Hammer", Category = "Hardware", Price = 16.99M }
    };

    public IEnumerable<Product> GetAllProducts()
    {
        return products;
    }

    [Route("GetProduct")]
    [HttpGet]
    public IHttpActionResult GetProduct(int id)
    {
        var product = products.FirstOrDefault((p) => p.Id == id);
        if (product == null)
        {
            return NotFound();
        }
        return Ok(product);
    }
PeopleController.cs

[ApiVersion("2")]
[ODataRoutePrefix("v{version:apiVersion}/People")]
public class PeopleController : ODataController
{
    People_Entities _People_Entities = new People_Entities();

    protected override void Dispose(bool disposing)
    {
        _People_Entities.Dispose();
        base.Dispose(disposing);
    }

    [ODataRoute("GetPeople")]
    [HttpGet]
    [EnableQuery]
    public IQueryable<tblPeople> GetPeople()
    {
        return _People_Entities.tblPeople;
    }
}
tblPeopleModelConfiguration.cs

public class tblPeopleModelConfiguration : IModelConfiguration
{
    private static readonly ApiVersion V2 = new ApiVersion(2, 0);

    private EntityTypeConfiguration<tblPeople> ConfigureCurrent(ODataModelBuilder builder)
    {
        var people = builder.EntitySet<tblPeople>("GetPeople").EntityType;
        return people;
    }

    public void Apply(ODataModelBuilder builder, ApiVersion apiVersion)
    {
        // note: the EDM for orders is only available in version 2.0
        if (apiVersion == V2)
        {
            ConfigureCurrent(builder);
        }
    }
}

**Comment by commonsensesoftware** [comment]
There's a multitude of issues.

First, I **strongly recommend** that you do **not** use attribute routing in this scenario. Despite having _attributes_, OData does not use _Direct Routing_ (aka _Attribute Routing_). Due to limitations in the Web API routing system, there are scenarios where API Versioning simply will not work when mixing routing styles. I've tried numerous attempts and came to the conclusion that it's not possible to guarantee things will work in all cases without completely redoing the routing system (which I'm not going to do). I haven't encountered any issues using traditional convention-based routing, even though it may be undesirable and/or inconvenient. You should remove `config.MapHttpAttributeRoutes`. You also do not need to register the route constraint either. The necessary setup for OData will be done for you.

You already have a convention-based route mapped for non-OData controllers, but it's not set up correctly. You **cannot** use a literal `v1` or any other value to represent the API version. API Versioning uses a custom route constraint to extract this value. There is no _magic_ regular expression matching, etc happening to extract the value. The route should be registered like this instead:

```c#
config.Routes.MapHttpRoute(
    name: "DefaultApi",
    routeTemplate: "v{apiVersion}/{controller}/{id}",
    defaults: new { id = RouteParameter.Optional },
    constraints: new { apiVersion = new ApiVersionRouteConstraint() } );
```

If you remove all `[RoutePrefix]` and `[Route]` attributes from **ApiController** classes, things should work as expected.

The OData configuration can be finicky. Your controller should be set up as:

```c#
[ApiVersion("2")]
[ODataRoutePrefix("People")]
public class PeopleController : ODataController
{
    [HttpGet]
    [EnableQuery]
    [ODataRoute]
    public IQueryable<tblPeople> GetPeople() => { }
}
```

The controller name and, hence, `[ODataRoutePrefix]` must match the registered entity set name. The entity set _should_ be configured as: `builder.EntitySet<tblPeople>("People")`, or at least that's what I would expect it to be. You already have `config.MapVersionedODataRoutes("odata", "v{apiVersion}", models);` so your _People_ controller will match the route `v2/people`.

I recommend taking a deep look at the [Advanced OData Web API Example](../tree/master/samples/webapi/AdvancedODataWebApiSample), which demonstrates mixing and     matching OData with non-OData controllers in Web API.

I hope that helps.

**Comment by uwdev15** [comment]
That works! Thanks a lot! I really appreciate it!

**Comment by commonsensesoftware** [comment]
It looks like this issue is resolve. Feel free to come back if you have more questions. Thanks.
