### ISSUE TITLE
Custom API Attribute fails to trigger an action constraint

### ISSUE THREAD

**Issue by qska** [microsoft/aspnet-api-versioning#536]
I wrote a custom attribute class - very rudimentary, but it's a part of a Proof of Concept:

 [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
    public class ApiVersionRouteAttribute : Attribute, IApiVersionProvider
    {
        private int MaximumVersion;
        private int MinimumVersion;

        public ApiVersionRouteAttribute(int fromVersion) ////: base(fromVersion.ToString())
        {
            this.MinimumVersion = fromVersion;

            // TODO: inject from configuration
            this.MaximumVersion = 10;
        }

        public ApiVersionRouteAttribute(int fromVersion, int toVersion)
        {
            this.MinimumVersion = fromVersion;
            this.MaximumVersion = toVersion;
        }

        public new ApiVersionProviderOptions Options
        {
            get { return ApiVersionProviderOptions.Mapped; }
        }

        public new IReadOnlyList<ApiVersion> Versions
        {
            get
            {
                List<ApiVersion> supportedVersions = new List<ApiVersion>();
                for (int v = MinimumVersion; v <= this.MaximumVersion; v++)
                {
                    supportedVersions.Add(new ApiVersion(v, 0));
                }

                return supportedVersions;
            }
        }
}

I attempted to embed it within my controller:

  [ApiController]
    public class VersionedController : ControllerBase
    {
        [ApiVersionRoute(2, 3)]
        [Route("api/v{version:apiVersion}/[controller]/endpoint")]
        [HttpGet]
        public ActionResult V1AndV2Get()
        {
            return new JsonResult("v2 and v3");
        }

        [ApiVersionRoute(4)]
        [Route("api/v{version:apiVersion}/[controller]/endpoint")]
        [HttpGet]
        public ActionResult V15Get()
        {
            return new JsonResult("v4");
        }
    }

But when running the api/v2/versioned/endpoint I get the following error:

Multiple actions matched. The following actions matched route data and had all constraints satisfied:
MyCompany.WebApp.Controllers.VersionedController.V1AndV2Get() 
MyCompany.WebApp.Controllers.VersionedController.V4Get() 

What helps is to add the built in attribute, like this:
[ApiVersion("20.0")]

This gets around the startup issue, and the custom attribute code is executed correctly - ie the API Version range is working as expected, routing v2 and v3 requests to one endpoint, and v4 endpoint to the other.

I think I might have missed some runtime registration that is required to make my attribute correct.

In Startup, I have both:
            app.UseApiVersioning();

and 

services.AddApiVersioning(o =>
            {
                o.AssumeDefaultVersionWhenUnspecified = true;
            });

I'm using version 3.0.0 of the Versioning library, as we're still on DotNet Core 2.1.

**Comment by commonsensesoftware** [comment]
There are multiple issues here:

1. You don't need to use the `new` keyword when implementing an interface
2. It looks like you might have been trying to extend [ApiVersionAttribute](../blob/master/src/Common/ApiVersionAttribute.cs), but you likely want [ApiVersionsBaseAttribute](../blob/master/src/Common/Versioning/ApiVersionsBaseAttribute.cs) instead
   a. **ApiVersionBaseAttribute** doesn't implement **IApiVersionProvider** by default so that you have full control over the behavior and visibility of members. Don't forget to inherit it.
3. The main issue appears that you have the wrong [ApiVersionProviderOptions](../blob/master/src/Common/Versioning/ApiVersionProviderOptions.cs). You have **Mapped**, when you want **None**.

The provider options describe additional metadata about a set of API versions. For example, are these API versions deprecated, for advertisement only, both, and so on. _Mapped_ means that the API versions **only** represent a mapping; they do not _declare_ any API versions. This is the behavior of [MapToApiVersionAttribute](../blob/master/src/Common/MapToApiVersionAttribute.cs). _Mapping_ an API version pairs an API version to an implementation method. _Declaring_ an API version indicates that it should be discovered as a supported API version. This most commonly happens when you _declare_ API versions on a controller and _map_ API versions to different actions. An option of **None** means that there are no additional options or metadata and the API versions are simply declared.

Your particular setup is taking you down a path of misleading and partial success. `options.AssumeDefaultVersionWhenUnspecified = true` is **not** going to do what you think or expect because you are versioning by URL segment. It is simply not possible to have an optional URL segment in the path. The only way to make this approach work is if you use double route declarations (e.g. `[Route("api/v{version:apiVersion}/[controller]/endpoint")]` and `[Route("api/[controller]/endpoint")]` ). This is one of the many reasons I do **not** recommend that style of versioning. It's also the least RESTful of all styles. It's not clear if you changed `options.DefaultApiVersion` or you had a typo and meant `[ApiVersion("2.0")]` instead of `[ApiVersion("20.0")]`. I still wouldn't expect your configuration to work unless it was **2.0**. Assuming you mean 2.0, things start working because now your controller or action _declares_ 2.0 **and** has a mapping to a method for 2.0, which is `V1AndV2Get()`.

Ultimately, if you get your provider options configured correctly, it should start working the way you want. I hope that helps.

**Comment by qska** [comment]
Many thanks for a great response and patience. You were spot on.
