### ISSUE TITLE
unexpected query parameters in odata actions and functions swagger document

### ISSUE THREAD

**Issue by anranruye** [microsoft/aspnet-api-versioning#540]
Hi!

I'm working with swagger, asp.net core with odata and Microsoft.AspNetCore.OData.Versioning.ApiExplorer(3.2.3).

I find that when i use
``` C#
app.UseMvc(routeBuilder =>
            {
//...
                routeBuilder.Select().Expand().Filter().OrderBy().MaxTop(100).Count();
//...
            });
```
there will be two additional query parameters $select and $expand in swagger output for odata actions and functions.

This is unreasonable for an action that return nothing.

Another condition is that the method has same name with the function or action defined in edm model.If they have different names(case sensitivity) with odata attribute route,this will not happen.

This problem is something like [https://github.com/microsoft/aspnet-api-versioning/issues/514#issue-465999680](url) #514 ,but I only find this problem for actions and functions.

I'm not sure whether this is a bug.Well, this behavior of odata api explorer must relate to method name.

Hope to help people who meet the same problem.

**Comment by commonsensesoftware** [comment]
I can't really comment on the behavior you're seeing without seeing the action. By configuring:

```c#
routeBuilder.Select().Expand();
```

You have _globally_ indicated that the `$select` and `$expand` query options are available on **everything**. When it can be detected, some options like `$orderby` and `$filter` will be omitted for queries; for example, when the result is determined to be a single result. `$select` and `$expand`, however, can still be used, even on a single result.

Functions can definitely have these options because the can be composed. Actions, on the other hand, _could_ support them, but shouldn't provide them by default.

**Comment by anranruye** [comment]
@commonsensesoftware 
Well,my action method is not special.
Just add
```
routeBuilder.Select().Expand();
```
to your SwaggerODataSample project and run the program,you will see the behavior.

However,when change
```
order.Action( "**Rate**" ).Parameter<int>( "rating" );
```
to
```
order.Action( "**rate**" ).Parameter<int>( "rating" );
```
the two parameters disappear in swagger document of the action _Rate_.

**Comment by commonsensesoftware** [comment]
### Issue 1
The first issue is purely a case-sensitivity limitation. Many of the OData and EDM APIs are case-sensitive. In this context, **"Rate"** is not the route, but the name of the action. By convention, the name of the OData action in the EDM and the corresponding controller action name **must** match, including by case. This is beyond my control. The action is looked up by [EdmModel.FindDeclaredOperations](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Edm/Schema/EdmModelBase.cs#L139). As far as I can tell, there is no way to look up the action in a case-insensitive manner. If you know of a way, I'm happy to entertain it. Regardless, the casing limitation of the action mapping has no effect on routing. The OData URL parser can match the request URL in a case-insensitive manner.

The API Explorer will handle the **ODataActionParameters** just fine; however, when the OData action and controller action names don't match, then the API Explorer doesn't match an OData action. If an OData action is not properly resolved, then there's no way to build the corresponding parameters. This issue is mitigated by simply ensuring your OData action and controller action name match.

If you _really_ want to match the OData action and controller action without using the standard conventions, you can achieve this with the **ActionNameAttribute**. For example, the following will allow things to match up, even though the method name doesn't match:

```c#
[HttpPost]
[ActionName("rate")]
[ODataRoute( "({key})/Rate" )]
public IActionResult Rate( int key, ODataActionParameters parameters ) { }
```
_Figure 1: Map method with a lowercase name_

```c#
order.Action( "rate" ).Parameter<int>( "rating" );
```
_Figure 2: Map action with a lowercase name_

### Issue 2
I'll reiterate that you've enabled the global query options by using:

```c#
routeBuilder.Select().Expand();
```

The `$select` and `$expand` operators are completely allowed to be in all query operations, including functions. There's nothing in the protocol that says you cannot have query options in other scenarios, but those are probably edge cases. Arguably, only `GET` operations should support query options. I can get onboard with making that the default filtering mechanism, while enabling people to still include query options in non-standard scenarios. That behavior still wouldn't completely address your issue.

The query options are evaluated as follows:

1. Global query options
2. Query options defined by `[EnableQuery]`
3. Model-bound query options
4. Explicitly by declared in the API Explorer options

The result is a unioned set of options. Explicit options always override any implicit convention. By enabling global query options, the only sensible way to disable them is through model-bound query options that explicitly disable them.

It _might_ be worth considering conventions to explicitly disable query options, but I'm not sure how useful that would be. The same result can be achieved by not enabling global query options. If you have to disable a bunch of global query options, that's no different that enabling a bunch of query options individually.

**Comment by anranruye** [comment]
@commonsensesoftware 
Thank you for your detailed explanation.

In fact,using global query options is not necessary for me.There is no need to disable query options explicitly.

Also,I found the regulation of query options discovery in the past two days.But I don't think this priority order is right.Query options in the result don't match actual behavior of api method.

Maybe using global query options is not a good idea.
