### ISSUE TITLE
IControllerConvention own conventions is not getting applied

### ISSUE THREAD

**Issue by FransVanEk** [microsoft/aspnet-api-versioning#541]
i have created a own convention to set the version on a controller. 

```csharp
public class MyCustomApiVersionConvention : IControllerConvention
    {
        public bool Apply(IApiVersionConventionBuilder controller, ControllerModel controllerModel)
        {
            return true;
        }
    }
```

in the startup i added the convention. 

```csharp
    services.AddApiVersioning(options =>
                                        {
                                            options.Conventions.Add(new MyCustomApiVersionConvention());
                                        });
```

when i run this the apply methods doesn;t get called at all.. 

project details 
``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="3.1.6" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.7.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>

</Project>
```

**Comment by commonsensesoftware** [comment]
Rhetorical, I know, but is there a chance that your build is simply out-of-sync? I tried to repro using your exact class in the [Conventions](../tree/master/samples/aspnetcore/ConventionsSample) sample project and it seems to work just fine.

![image](https://user-images.githubusercontent.com/11765008/64192123-dc383780-ce2e-11e9-9ea1-cf0a82ceb1b0.png)

I registered the custom convention exactly as you've shown.

**Comment by FransVanEk** [comment]
Hey Chris,

It gets called but not for the controllers i need to set the version on... 

i have a provider that adds controllers to the pipeline..  These are open generic controllers. 

for these controllers i need to set the version. 

i have attached a sample project... 
[DynamicAndGenericControllersSample.zip](https://github.com/microsoft/aspnet-api-versioning/files/3573109/DynamicAndGenericControllersSample.zip)

**Comment by commonsensesoftware** [comment]
This is almost certainly because your controllers are not decorated with `[ApiController]`. In addition, unless you need UI stuff, I would consider using **ControllerBase** instead of **Controller** as the base class. API Versioning 3.0 introduced [IApiControllerFilter](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/ApplicationModels/IApiControllerFilter.cs) which is used to filter controllers. In earlier versions of ASP.NET Core there wasn't really a clear way to disambiguate UI controllers from API controllers. The built-in implementation will use one or more [IApiControllerSpecification](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/ApplicationModels/IApiControllerSpecification.cs) instances.

You can replace the  default implementation in the service collection or you can opt out of filtering completely via `options.UseApiBehavior = false`. Be aware that if you disable API behaviors, that UI controllers will require an API version. People mixing controllers this way often apply `[ApiVersionNeutral]` to their UI controllers.

I didn't run through your repro (yet), but based on the source, I suspect this is the problem.

**Comment by FransVanEk** [comment]
ok thanks, i will dive into that... and post the results...

**Comment by FransVanEk** [comment]
as promised a working sample of the version on generic controllers. 
starting point was a post

https://cabbagetech.blog/2019/03/02/integrating-swagger-with-url-based-asp-net-core-api-versioning/ 

basically this sample will:
- use a feature provider : 
  - find a source file
  - compile the code
  - by reflection find the types
  - create controllers for them based upon 2 different base generic base controllers
  - add controllers to pipeline.. 
- MyCustomApiVersionConvention
  - for each controller
  - change version when it is a base controller (just to check workings, this should be your own logic to determine the version)

[RestApi.zip](https://github.com/microsoft/aspnet-api-versioning/files/3593904/RestApi.zip)
