### ISSUE TITLE
How to IApiVersionReader.Read() in Middleware

### ISSUE THREAD

**Issue by DavidColemanUK** [microsoft/aspnet-api-versioning#546]
I have an MVC net core 2.2 application with API Versioning.  I only want the middleware to run for v2 of the api or greater.

The middleware class I have written uses the IApiVersionReader.Read(), however that doesn't seem to be populated until after the UseMVC line in startup. 

    var apiVersion = _apiVersionReader.Read(_httpContextAccessor.HttpContext.Request);

So if I register my middleware before UseMVC, then it can't read the version using the versioning method.
But if I put my middleware after the UseMVC line, then it doesn't trigger at all.

It feels like a chicken and egg situation! How can I get this to work?

Here's my brevity startup.

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(config =>
                {
                    // Don't add auth in development.        
                    if (!CurrentEnvironment.IsDevelopment())
                    {
                        var policy = new AuthorizationPolicyBuilder()
                            .RequireAuthenticatedUser()
                            .Build();
                        config.Filters.Add(new AuthorizeFilter(policy));
                    }
                }
            );

            services.AddTransient<IHttpContextAccessor, HttpContextAccessor>();
       
            services.AddMvcCore()
                .AddAuthorization()
                .AddJsonFormatters(config =>
                    config.ReferenceLoopHandling = ReferenceLoopHandling.Ignore);

            services.AddApiVersioning(options =>
            {
                options.ReportApiVersions = true;
                options.AssumeDefaultVersionWhenUnspecified = true;
                options.DefaultApiVersion = new ApiVersion(2, 0);
            });

        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
          
            app.UseMvc();

            app.UseMiddleware(typeof(UserDataLoggingMiddleware));
        }
```

**Comment by commonsensesoftware** [comment]
API Versioning auto-registers it's middleware purely for simplicity. To control the behavior yourself, do the following:

First, opt out of auto-registration:

```c#
services.AddApiVersioning(options => options.RegisterMiddleware = false);
```

Then, register the middleware however you like in the pipeline:

```c#
services.UseApiVersioning();
services.UseMvc();
```

I hope that helps.

**Comment by DavidColemanUK** [comment]
Thanks for that, I had high hopes as it makes sense. However I tried it using:

`services.AddApiVersioning(options => options.RegisterMiddleware = false);`

and 

```
app.UseApiVersioning();
app.UseMiddleware(typeof(UserDataLoggingMiddleware));
app.UseMvc();
```

And this is the middleware:
```
public class UserDataLoggingMiddleware
{

    private readonly RequestDelegate _next;
    private readonly IApiVersionReader _apiVersionReader;

    public UserDataLoggingMiddleware(RequestDelegate next, IApiVersionReader apiVersionReader)
    {
        _next = next;
        _apiVersionReader = apiVersionReader;
    }

    public async Task Invoke(HttpContext context)
    {
        var apiVersion = _apiVersionReader.Read(context.Request);
        // Here will be logic based on version.....

        await _next.Invoke(context);
    }

}
```

With that  the API Version reader still reports null when I hit it specifying v2.

**Comment by commonsensesoftware** [comment]
By the mention of `v2`, I'm guessing you're versioning by URL segment. \<sigh\> (my least favorite and least RESTful). This happens because, despite there being a [UrlSegmentApiVersionReader](.../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/UrlSegmentApiVersionReader.cs), it behaves quite different from other **IApiVersionReader** implementations. API Versioning never relies on _magic string_ parsing in URLs. For the URL segment method, the API version is extracted and set by the [ApiVersionRouteConstraint](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionRouteConstraint.cs).

I suspect the reason that you are encountering `null` in your scenario is because MVC and, hence, route constraints have not yet be evaluated. You may be able to explicitly create and evaluate the necessary route constraints on your own. Alternatively, you can create a custom **IApiVersionReader** or extend  **UrlSegmentApiVersionReader** where you would know how to extract the raw API version value from the request (based on your conventions) if the base implementation returns `null`.

Something like:

```c#
public class MyCustomApiVersionReader : UrlSegmentApiVersionReader
{
    public override string Read( HttpRequest request )
    {
        var value = base.Read( request );

        if ( string.IsNullOrEmpty( value ) ) 
        {
           value = /* TODO: extract API version from request */ ;
        }

        return value;
    }
}
```

Then set it up with:

```c#
services.AddApiVersioning(
    options => options.ApiVersionReader = new MyCustomApiVersionReader() );
```

I hope that helps point you in the right direction.

>BTW: No other supported method of versioning would suffer from this issue because the value can always be deterministically extracted from request information based on established conventions.

**Comment by DavidColemanUK** [comment]
Thanks for that great reply. I’ll give that a shot. 

You’ve peaked my interest about using url segment. What is the better more restful way?

**Comment by commonsensesoftware** [comment]
There's a lot of options out there, but none should be more respected than the man him - Roy Thomas Fielding. He has often been quoted as saying that versioning shouldn't even exist in REST semantics, but - pragmatically - there are a some useful scenarios. Ultimately, he says that the **only** valid method versioning should be via _media type negotiation_ in requests (typically by way of `Accept` or `Content-Type`). This is a reasonable assessment. There are APIs out there that do that. The GitHub API, for example, is versioned this way.

Despite the URL segment method being common, it is riddled with issues in a truly RESTful system. The mere act of using HTTP does not make something RESTful. Fielding himself has asserted this. If I'm being completely honest, the URL segment method really isn't RESTful at all because it violates the _Uniform Interface_ constraint.

Consider the URLs `api/v1/orders/123` and `api/v2/orders/123`. If you ask someone what the identifier of the order in the request is, most people will say that it's **123**; however, that is incorrect. The _Uniform Interface_ constraint states that the URL, more specifically the path, **is** the identifier of the resource. That means that this convention implies that the two URLs are completely different resources when, in fact, they almost certainly not. While it's true that the identifier in some external storage, such as a database, might be **123**, the order is still the same order. What's really meant by the different URLs is _representation_. The V1 and V2 versions of the order probably have different payloads. In REST, this is handled by _media type negotiation_. It's really no different that asking for `application/xml` vs `application/json`. The client simply wants a different representation, which service authors often call an _API Version_.

Things can really go sideways in the URL segment method if you support Hyper Media as the Engine of Application State (HATEOAS). Services can be related and often evolve independently. In fact, we almost always want to evolve independently or we risk introducing unnecessary coupling. So consider that Orders is on V2, but provides a link to a Customer resource that is on V3. How would an Order know which version to use? Worst still, any version selected may not be what the client wants. If an Order says the link is `api/v2/customer/456`, it's entirely possible the client is onboarded to V1 or V3. How do you solve this? The server can't. It's the job of the client to _ask_. Unfortunately, the URL segment method requires _something_ to return to the client. There have be attempts to solve this problem with _symmetrical_ versioning or templates the client has to fill in, but you can start to see there can be a lot of complications.

While media types might be the _best_ and certainly the _purist_ RESTful method to versioning, it isn't really the most pragmatic. For example, it requires setting a header which is _work_ for clients like JavaScript albeit minimal. The query string method largely fits the best of both worlds as a query string is not part of the path and, hence, isn't part of the resource identifier. Query strings are easy to build by even the most basic clients such as JavaScript. Perhaps that isn't the _best_ argument, but the query string method affords convenience and simplicity without breaking REST constraints. This is one of the main reasons why it's the default method in API Versioning. If you're wondering how this differs for HATEOAS, well the link to customer would simply be `api/customer/123`. The onus is on the client to ask for `api/customer/123?api-version=3.0`. It's no different than if the client wanted to ask for XML vs JSON and so on. This also has the benefit of stable resource URLs.

I could go on and on and I probably should start blogging about this type of stuff, but hopefully that provides some context. The URL method is very common, which is why it's supported, but few stop to think about what it means in REST. I've often found it to be the case that it was simply _"Oh that's what [insert company here] does..." (so it **must** be good)_. Fewer still have read Fielding's dissertation or the even the chapter on REST. It's honestly a short read with amazingly still relevant concepts from nearly 20 years ago!

May you find that insightful and useful.

**Comment by commonsensesoftware** [comment]
Just confirming before I close out this issue, were you able to get things working the way you wanted? Thanks.

**Comment by DavidColemanUK** [comment]
Hi,

Yes, this did what I wanted.  I'd like to thank for you the thorough assistance.

Thanks very much.
