### ISSUE TITLE
How to set api-version parameter description?

### ISSUE THREAD

**Issue by tanmayghosh2507** [microsoft/aspnet-api-versioning#547]
I'm using Microsoft.AspNetCore.Mvc.ApiExplorer and Microsoft.AspNetCore.Mvc.Versioning for versioning support on my APIs, and generating the Open API Spec using NSwag.
```
services.AddApiVersioning(options =>
{
    options.ApiVersionReader = new QueryStringApiVersionReader("api-version");
    options.ReportApiVersions = true;
});
services.AddVersionedApiExplorer(options =>
{
    options.GroupNameFormat = "G";
    options.DefaultApiVersionParameterDescription = "The API Version in YYYY-MM-DD format";
});
```

With this config, API versioning works perfectly as desired, also NSwag generates the OAS doc with the added parameter "api-version" like this:
```
{
    "name": "api-version",
    "in": "query",
    "required": true,
    "schema": {
        "type": "string",
        "nullable": true
    },
    "x-position": 2
}
```

But this added parameter doesn't have the description. I thought of below 2 approaches, but couldn't make it work:
1. `options.DefaultApiVersionParameterDescription` didn't work.
2. Is it possible to use `options.ApiVersionReader.AddParameters()` for the same? If so, could someone please explain, how, as the documentation is not quite clear to me.

**Comment by commonsensesoftware** [comment]
API Versioning does not have dependency on Swagger or Open API in any way. It does, however, provide API Explorer extensions that are API Version-aware. Similarly, Swagger generators, such as NSwag, rely purely on the API Explorer to collect data in order to generate Swagger documents.

Swashbuckle still has this problem because it does not use all possible data from the API Explorer. Swashbuckle assumes you'll provide the description yourself or it will come from _XML Comments_. The API Version is _special_ in the sense that it can appear in many different places and may even allow multiple inputs (though usually not useful for Swagger/OpenAPI). As a result, the description of the parameter is only available via the _descriptions_ provided by the API Explorer. This is the entire point of the `options.DefaultApiVersionParameterDescription` so that you can set the value to whatever you want.

I'm not super familiar with NSwag, but I know that it has some common lineage with Swashbuckle. I suspect it suffers from the same flaw and not all of the metadata is being used. We can create issues asking for said Swagger generators to use it, but I can't _make_ them consume the metadata provided.

There are 4 pieces of information that a Swagger generator may not pick up for the API version parameter:

- **Description**: if the `ApiParameterDescription.ModelMetadata.Description` is not considered
- **Default**: if the `ApiParameterDescription.DefaultValue` is not considered; this was unavailable in earlier versions of the ASP.NET Core API Explorer
- **Required**: if the `ApiParameterDescription.Required` is not considered; this was unavailable in earlier versions of the ASP.NET Core API Explorer
- **Deprecated**: this almost certainly will not be considered because there is no standard way to convey this across frameworks. API versioning provides a way to determine the value, but you have to connect it to NSwag

I don't know NSwag well enough to provide an example of how to extend it to fill in the blanks, but I know it's definitely possible. I do have [this Swashbuckle example](../blob/master/samples/aspnetcore/SwaggerSample/SwaggerDefaultValues.cs
) that you can use as reference, which I suspect will be similar.

I hope that helps.

**Comment by tanmayghosh2507** [comment]
Thanks @commonsensesoftware The information was really helpful. However, I figured an alternate approach for NSwag. It is definitely not the cleanest, but easy and working. So, I used Operation Processor to process the "api-version" parameter and then add it's description. Like this:
```
public class ApiVersionProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext context)
    {
        context.OperationDescription.Operation.Parameters.FirstOrDefault(x => x.Name == "api-version").Description = "The API Version in YYYY-MM-DD format";
        return true;
    }
}
```
And while setting the NSwag services, just calling:
`config.OperationProcessors.Add(new ApiVersionProcessor());`
