### ISSUE TITLE
Startup.cs in another assembly causes OData to return 404.

### ISSUE THREAD

**Issue by joshmackey** [microsoft/aspnet-api-versioning#551]
Still tracing down exactly what's happening, but I have a simple ASP.Net Core Startup class that configures OData with api versioning.

If I run the Startup class in the entry dotnet core assembly, everything works as it should, however, if the Startup class is in a separate assembly, all odata related routes start returning 404 (including the $metadata endpoint).

Trace logging shows that the route is being matched, but no matching actions are found.

Will update as I come across more information.

**Comment by joshmackey** [comment]
I don't know if it's related or not, but the OData endpoints start returning 404 the moment I call `AddApiVersioning()`. Seems like the replaced `IActionSelector` can't find them anymore?

**Comment by joshmackey** [comment]
It's the 
```var applicationPartManager = app.ApplicationServices.GetRequiredService<ApplicationPartManager>();
            applicationPartManager.ApplicationParts.Add(new AssemblyPart(typeof(VersionedMetadataController).Assembly));``` call. For unknown reasons, it's adding the wrong assembly to the `ApplicationPartManager`.

**Comment by commonsensesoftware** [comment]
ASP.NET Core usually needs some _help_ in this type of scenario. This would especially be true if all of the OData configuration is external too. It sounds as though that might be the case since you mentioned that you need to add the `VersionedMetadataController`.

Were you able to get things working? It sounds like you did. Let me know if there's anything else required to resolve this issue.

Thanks.

**Comment by joshmackey** [comment]
I worked around it, but it's still an issue to be fixed. `typeof(VersionedMetadataController).Assembly` *should* have fetched the correct assembly, but it didn't.
