### ISSUE TITLE
ASP.NET Core example with OData API Explore Sample not working

### ISSUE THREAD

**Issue by franfr57** [microsoft/aspnet-api-versioning#564]
Hello,

I want to test the ASP.NET Core example with OData API Explorer (https://github.com/microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample))
I downloaded the project here: https://github.com/microsoft/aspnet-api-versioning

I can not run the example I have such errors:
'D:\projets\aspnet-api-versioning-master\src\Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer\bin\Debug\netstandard2.0\Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer.dll' metadata file not found
Unable to locate repository containing 'D:\projets\aspnet-api-versioning-master\src\Microsoft.AspNetCore.Mvc.Versioning' directory.

How can I fix these errors?

I also tried to leave an empty project but the swagger does not work.

Thanks for your help.

**Comment by commonsensesoftware** [comment]
If you downloaded the source, you need to build the entire solution first. The examples intentionally do **not** reference the NuGet packages; otherwise, I end up updating all the samples when new versions are published.

Your options are:
1. Build the entire solution before running the sample (you can do this by opening the \*.sln)
2. Remove the `<ProjectReference>` elements in the project and replace them with `<PackageReference>` elements that refer to the NuGet package versions you want.
   a. You can do this in VS UI if you want; it doesn't have to be hand

I hope that helps.

**Comment by franfr57** [comment]
Thank you for your quick response, I launched the project!

I tested the API API/Orders in v3 and I get this error:
The set 'Orders' can not be used for $ count.

How can I solve it?

**Comment by commonsensesoftware** [comment]
Enable in the route configuration (e.g. inside the `Configure` method of **Startup.cs**). Something like:

```c#
routeBuilder.Count();
```

_Should_ enable the `$count` option.

**Comment by franfr57** [comment]
Thank you it works!

I have a project with swagger already. To integrate ODataVersioning.ApiExplorer I have to rewrite all my controllers or can they work at the same time as the new ones written with OData?

**Comment by commonsensesoftware** [comment]
If you mean mixing OData with non-OData, then - yes - that will work. The API Explorer simply provides extensions in both cases. You don't _lose_ anything by adding a set of extensions; everything is additive.

**Comment by commonsensesoftware** [comment]
It would seem this issue is now resolved. Come back if you have more questions.

**Comment by ZouZou** [comment]
I have downloaded the source and I have tried to build the entire solution, all the nuget packages are downloaded and the references do not show any error, however when I try to build the solution I got a lot of errors that has to do with Git, from file
"C:\Users\MyUser\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets"

    <Microsoft.Build.Tasks.Git.LocateRepository Directory="$(MSBuildProjectDirectory)" >
      <Output TaskParameter="Id" PropertyName="_GitRepositoryRoot" />
    </Microsoft.Build.Tasks.Git.LocateRepository>

**Comment by commonsensesoftware** [comment]
@ZouZou are all your tools up-to-date? I always recommend using the latest versions of Visual Studio 2019 with all of the updates applied. The Community Edition is free if it's not otherwise available to you. The only thing I can think of that _might_ be related to Git is SourceLink. There's nothing else in the build that does or cares anything about Git. Since OData doesn't support .NET Core 3.0 yet, you'll need the .NET Core 2.2 SDK also.

Visual Studio doesn't always tell the _truth_. Try a command-line build with the .NET CLI. It should work as that's the same process that is used in the CI and Release build pipelines. From the root of the repo try:

```batch
dotnet restore
dotnet build
```

**Comment by ZouZou** [comment]
@commonsensesoftware it was the microsoft.sourcelink.github package as you have suggested, the source code was pointing to the beta version so I updated the package and solution built successfully, Thanks.
