### ISSUE TITLE
Default API Version for Accept Header versioning not applying when some service endpoint method in the same controller has an ApiVersion attribute

### ISSUE THREAD

**Issue by Vidyogamasta** [microsoft/aspnet-api-versioning#565]
I still don't completely understand how the versioning works so if I'm just doing this incorrectly, let me know! But I was able to reproduce a minimal set-up in a new project that results in the error "The HTTP resource that matches the request URI 'localhost/TestRepro/controller/method' does not support the API version '1.0'.""

Using the default .Net Core API Template, I installed the Versioning package and added this to the ConfigureServices:

```cs
services.AddApiVersioning(options =>
                {
                    options.ApiVersionReader = new MediaTypeApiVersionReader();
                    options.DefaultApiVersion = new ApiVersion(1, 0);
                    options.AssumeDefaultVersionWhenUnspecified = true;
                    options.ApiVersionSelector = new CurrentImplementationApiVersionSelector(options);
                }
            );
```

I then slightly modified the starting template to give myself something to test off of:

```cs
[HttpGet]
        [Route("test")]
        public string Get()
        {
            return "Default stuff";
        }
```

Navigating to this without specifying a version in the Accept header version works as expected: We get defaulted to 1.0, and it matches the route here that has also been defaulted to 1.0, if my understanding of everything is correct.

The issue comes when we go to version something else in the same controller: adding this

```cs
[HttpGet]
        [Route("versioned")]
        [ApiVersion("1.0")]
        public string BreakItAll()
        {
            return "break?";
        }
```

result in the first route breaking with the error I mentioned at the start. It's no longer recognizing that original route as version 1.0. The route with the explicit version does work, though.

I DO have a workaround so it's not incredibly vital: using MapToApiVersion rather than ApiVersion on the endpoint works as expected. As such, I feel like I may be misusing the ApiVersion attribute, especially since I'm explicitly trying to not label the controllers themselves with ApiVersion (I'm wanting versioning on a per-endpoint basis). But I'm going ahead and post this just in case it's an actual issue.

**Comment by commonsensesoftware** [comment]
This is happening because _implicit_ versioning is **only** allowed when there is no other versioning information. This behavior is primarily meant to address the scenario where tens, hundreds, or even thousands of APIs need to start versioning. In the very first supported versions of the library, this would have required touching untold numbers of files. In truth, all APIs have some initial version albeit unnamed (it might have casually be called _"v1"_). When no other attribution is specified, the value used for this default is `options.DefaultApiVersion`. Often the actual value is inconsequential for that _initial_, _default_ version.

As you have noticed, once you start adding attribution, this behavior goes away. This is an important distinction. Things are all or nothing. If it didn't behave this way, then it would be difficult or perhaps even impossible to permanently sunset an old API. If you're starting fresh, I recommend always using explicit versioning so that things are clear.

There is a distinction between `[MapToApiVersion]` vs `[ApiVersion]`. A _mapped_ version is just that - it's only mapped. A mapped version does **not** declare an API version. All actions implicitly map to the versions declared by their parent controller. The `[MapToApiVersion]` is needed and used when you interleave multiple versions to different actions within the same controller. If you don't interleave, then you should never have to worry about mapping specific actions to particular API versions.

Allowing `[ApiVersion]` directly on actions was something I started with a couple of years ago in the early adopter stages, but removed it because it was confusing to some folks. That ultimately brought about the idea of `[MapToApiVersion]`, which has virtually the same public surface area, but a significantly different meaning under the hood. Due to the routing improvements in ASP.NET Core, I revisited the idea of allowing `[ApiVersion]` directly on actions (since controllers no longer really matter). This behavior does allow you to declare versions directly on an action. This will supersede anything on the controller. Ultimately, this is another way to interleave, but with a bit more flexibility. It can get quite confusing, so use it with caution. The primary motivation to support it was to also allow `[ApiVersionNeutral]` at the action level, which makes a lot of sense for certain types of actions such as `DELETE`. Without that, you have to keep indicating support for the action at every version, even though it doesn't change.

I hope that helps clear things up - it not a little. ;)

**Comment by Vidyogamasta** [comment]
Thank you very much for the thorough explanation! I agree that it's probably best that I declare every endpoint as its API version anyway, but I was playing around with the idea of leaving everything un-set as default and then upgrading only the endpoints that needed it. The driving philosophy of doing it in the same controller would be "I don't wanna have to track down what the current version is by looking through several controller versions to find the last version this particular route updated," though separate controllers per version would work just as well as long as I don't mind just always using the most recent controller and having endpoints skip to the most recent controller. 

Thanks again for confirming that this is how that is intended to work, I'll go ahead and close the issue.
