### ISSUE TITLE
Target Framework versions that are supported

### ISSUE THREAD

**Issue by jtillman** [microsoft/aspnet-api-versioning#569]
Currently `Microsoft.AspNetCore.Mvc.Versioning` targets .net standard but changes supported base on the .Net Core Version. Shouldn't this package target the Framework Versions specific to its support rather than .Net Standard due to individuals having to install the package and run it to discover it is not supported. 

We should target `netcoreapp2.2` and not `netstandard2.0` since `netcoreapp3.0` does not have support for this package.

**Comment by commonsensesoftware** [comment]
.NET 3.0 **is** supported, but it's still in [preview](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/4.0.0-preview8.19405.7). I'm working on getting it out now. It's just about done.

The ASP.NET team changed things in ASP.NET Core 3.0. In addition to only targeting .NET Core 3.0, they changed the way you reference ASP.NET Core assemblies. Instead of referencing individual packages or even a _meta_ package, you reference the entire framework. This automatically happens when you use the SDK **Microsoft.Net.Sdk.Web**. If when you build a library instead of an application, you use the new **FrameworkReference** to reference the entire framework. The compiler is smart enough to only link what you need. Ultimately, they felt it was easier for developers to have a single reference that includes the entire framework. It also reduces the size of distributions.

As you can see the preview, **Microsoft.AspNetCore.Mvc.Versioning** targets .NET Core 3.0 and .NET Standard 2.0. The .NET Standard 2.0 support is primarily for ASP.NET Core 2.2 in order to support OData. It's also useful for anyone that hasn't moved to .NET Core 3.0. That support will eventually be dropped, but I'm not sure when yet. It will likely correspond with OData's support for .NET Core 3.0/3.1. .NET Core 3.1 is due out next month and will be marked for LTS.

I hope that helps clear things up.

**Comment by jtillman** [comment]
I believe this issue is addressed in the newer version. The root of the issue mostly was not setting upper bounds on references. Thanks!
