### ISSUE TITLE
Parsing issue in API version via route

### ISSUE THREAD

**Issue by bderveni** [microsoft/aspnet-api-versioning#580]
This is the same issue as [here](https://github.com/aspnet/AspNetCore/issues/17242). I was instructed to open the issue here as well.

### Describe the bug
Api versioning via the URL Path fails when the status contains the same character as the literal.

### Assumption

I read over the [API Version Format documentation](https://github.com/microsoft/aspnet-api-versioning/wiki/Version-Format) to see if there were any constrains on the values that **Status** in *[Version Group.]<Major>.<Minor>[-Status]* can take, but did not find anything. I assumed that this is not desired behavior.

In our case we have a v1-preview version for some of the routes, which fails even when there is a match.

### To Reproduce

[Repo](https://github.com/bderveni/ApiVersioningIssue) with a simple Web API project to reproduce the issue. 
I have included an [insomnia](https://insomnia.rest/) config [file](https://github.com/bderveni/ApiVersioningIssue/blob/master/ApiVersioningIssue.json) with all the following calls. No postman config as I do not use it ¯\_(ツ)_/¯.

Either way the following cURL calls will work just as good once the app is running:

##### Routes with literal A

```cURL
curl -X GET -d "" https://localhost:5001/a1/WeatherForecastVersionLiteralA
```

```cURL
curl -X GET -d "" https://localhost:5001/a1-preview/WeatherForecastVersionLiteralA
```

##### Routes with literal V

```cURL
curl -X GET -d "" https://localhost:5001/v1/WeatherForecastVersionLiteralV
```

```cURL
curl -X GET -d "" https://localhost:5001/v1-status/WeatherForecastVersionLiteralV
```

#### Version parsed but no matching routes with that version

```cURL
curl -X GET -d "" https://localhost:5001/a1-sts/WeatherForecastVersionLiteralA
```

```json
{
  "error": {
    "code": "UnsupportedApiVersion",
    "message": "The HTTP resource that matches the request URI 'https://localhost:5001/a1-sts/WeatherForecastVersionLiteralA' does not support the API version '1-sts'.",
    "innerError": null
  }
}
```

```cURL
curl -X GET -d "" https://localhost:5001/v1-sts/WeatherForecastVersionLiteralV
```

```json
{
  "error": {
    "code": "UnsupportedApiVersion",
    "message": "The HTTP resource that matches the request URI 'https://localhost:5001/a1-sts/WeatherForecastVersionLiteralA' does not support the API version '1-sts'.",
    "innerError": null
  }
}
```

##### Routes with literal A

```cURL
curl -X GET -d "" https://localhost:5001/a1-statusWithAIn/WeatherForecastVersionLiteralA
```

```json
{
  "error": {
    "code": "ApiVersionUnspecified",
    "message": "An API version is required, but was not specified.",
    "innerError": null
  }
}
```

##### Routes with literal V

```cURL
curl -X GET -d "" https://localhost:5001/v1-statusWithVIn/WeatherForecastVersionLiteralV
```

```json
{
  "error": {
    "code": "ApiVersionUnspecified",
    "message": "An API version is required, but was not specified.",
    "innerError": null
  }
}
```

### Culprit

The app uses serilog and is configured to log debug messages from the middleware.

The following messages provided good insight into where the issue was:

```log
[Debug] ({ Id: 1002, Name: "CandidateRejectedByComplexSegment" }) Endpoint '"RouteVersioningIssue.Controllers.WeatherForecastVersionLiteralVController.Get (RouteVersioningIssue)"' with route pattern '"v{version:apiVersion}/WeatherForecastVersionLiteralV"' was rejected by complex segment '"v{version:}"' for the request path '"/v1-statusWithVIn/WeatherForecastVersionLiteralV"'

[Debug] ({ Id: 1003, Name: "CandidateRejectedByConstraint" }) Endpoint '"RouteVersioningIssue.Controllers.WeatherForecastVersionLiteralVController.Get (RouteVersioningIssue)"' with route pattern '"v{version:apiVersion}/WeatherForecastVersionLiteralV"' was rejected by constraint '"version"':'"Microsoft.AspNetCore.Mvc.Routing.ApiVersionRouteConstraint"' with value 'null' for the request path '"/v1-statusWithVIn/WeatherForecastVersionLiteralV"'

[Debug] ({ Id: 1004, Name: "CandiateNotValid" }) Endpoint '"RouteVersioningIssue.Controllers.WeatherForecastVersionLiteralVController.Get (RouteVersioningIssue)"' with route pattern '"v{version:apiVersion}/WeatherForecastVersionLiteralV"' is not valid for the request path '"/v1-statusWithVIn/WeatherForecastVersionLiteralV"'
```

After some debugging I think the issue is at the following [line](https://github.com/aspnet/AspNetCore/blob/6cc99ea04f8254da4963740e627fc2e61b446063/src/Http/Routing/src/Patterns/RoutePatternMatcher.cs#L384).

After LastIndexOf(literal.Content, StringComparison.OrdinalIgnoreCase) the literal ends up being the corresponding matching char in the **Status** instead of the first character. The parameter is determined at this [line](https://github.com/aspnet/AspNetCore/blob/6cc99ea04f8254da4963740e627fc2e61b446063/src/Http/Routing/src/Patterns/RoutePatternMatcher.cs#L454). As a result the condition at this [line](https://github.com/aspnet/AspNetCore/blob/6cc99ea04f8254da4963740e627fc2e61b446063/src/Http/Routing/src/Patterns/RoutePatternMatcher.cs#L495) is not satisfied and the complex segment is not matched, hence the behavior. 

### Further technical details

- Microsoft.AspNetCore.Mvc.Versioning 4.0.0

- ASP.NET Core version

 Microsoft.AspNetCore.App 3.0.0

- Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

Microsoft Visual Studio Professional 2019, Version 16.3.9

**Comment by rynowak** [comment]
Note that matching in complex segments works from *right-to-left* *non-greedy* based on the appearance of literals. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.0#complex-segments

**Comment by commonsensesoftware** [comment]
Apologies for the delay. I've been out of the country for the last 3 weeks.

I can confirm that I can repro the behavior. I'm not convinced this is necessarily an issue with the segment matcher. What I'm seeing is that if the _status_ component of the API version (in this context) contains **any** of the characters in the segment literal, then the route template does not parse the route constraint segment. In debugging, I can see that the **ApiVersionRouteConstraint** does not receive a value for the `version` parameter at all.

As illustrated in detail above, given the template `v{version:apiVersion}/action`, the results can be simplified as:

| Route | Value | Comment |
| ------ | ------ | ----------- |
| `v1/action` | Success | No status  |
| `v1-status/action` | Success | Literal status does not contain `v`  |
| `v1-preview/action` | Failure | Literal status contains `v`  |

I also confirmed that if the values were extracted and handed to the **ApiVersionRouteConstraint** they would parse as expected. There are restrictions on the _status_; however, this is imposed **after** parsing and would result in a predictable 400 response. It must be alphabetic and optionally have a trailing number (ex: `preview` or `preview1`). Since the value is never observed or parsed by the route constraint and set to the **IApiVersioningFeature**, it has the appearance that no API version was specified at all.

@rynowak I hate to jump to this being a bug, but surely this can't be the expected behavior. It's not clear to me if this scenario qualifies as a _complex segment_. The example referenced shows a token in the middle of two literals, which is not this scenario. What seems more odd to me is that the route constraint receives no value at all. I suspect we can provide a more general purpose repro that illustrates this problem, even without API versioning (as I would expect this could happen with any custom route constraint). Before investing the time and effort to do so, is there something we're missing about how templates and route constraints are parsed or does something seem awry here?

**Comment by rynowak** [comment]
@commonsensesoftware - `v{version:apiVersion}` is a complex segment. 

So based on my reading of this, we are trying to match the complex segment `v{version:apiVersion}` to the URL path segment `v1-statusWithVIn`. 

We line up `{version:apiVersion}` and `VIn`, and then reject the match because `v` is not a match for `v1-statusWith`.

This matches the documented behavior. I recognize that looking at this case it seems really bad. This behavior is super old (2008), so I'm not certain off the cuff what the impact would be on changing it.

**Comment by commonsensesoftware** [comment]
@rynowak  thanks for confirming. I'm still not 100% sure I have my brain wrapped around why it matches that way, but it's irrelevant; this is, in fact, the expected behavior. As any change would likely be far off anyway, the best option _might_ be to revisit this behavior in some future release of the platform. I'd expect this to have pretty low priority though and not change anytime soon - if ever.

@bderveni this was a really interesting find. it appears as though your best option here is to simply not use a `v` in your status. this shouldn't be the worst thing in the world as many statuses have the form of something such as `1.0-beta1`, `1.0-rc2`, and so on.  The status of `preview` has become more popular in NuGet packages of late, but it seems you're out of luck with this style of versioning.

Of course, the other option is to use another style of versioning. Despite it's popularity, versioning by URL segment is the least RESTful of all methods. Versioning by media type or query string would negate this problem and let you use virtually any status, including `preview`. It may not be feasible for you, but it's an option.

**Comment by rynowak** [comment]
@commonsensesoftware - is the API for parsing versions extensible?

It might be a better experience to write routes as `foo/{version:apiVersion}/bar` and steer people to totally avoid complex segments. That can help in the mean time.

I've reopened the issue on ASP.NET Core to track this feedback.

**Comment by commonsensesoftware** [comment]
@rynowak in the _strictest_ of technical sense - yes, the **ApiVersion** class is extensible and _could_ support custom parsing, but it's unlikely anyone would ever do so. The **ApiVersion** is a fundamental type that supports parsing, comparison, formatting, and more. It's considerable work to for someone to change that. An interface doesn't work because then operator overloads would not work (ex: `==`, `!=`, `>`, etc). Some additional abstractions that could lift out parsing to a custom implementation is _possible_, but not something that is currently supported. Comparison could probably still be largely refactored with some support **IEquatable\<ApiVersion\>** or something like that.

Ultimately, the `v` is not part of the API version. My goal was always to keep other literals out of the way. To my knowledge, this is the only scenario where this arises. Another approach would be to get rid of the `v` altogether. Per your suggestion, that is another route that @bderveni  can take. It may not be as _cosmetically appealing_, but your proposal suggests that `foo/1/bar`, `foo/1-status/bar`, and `foo/1-preview/bar` would all work using that approach. It might be more desireable to move the `v` into it's own segment as well; for example, `foo/v/1-preview/bar`.

A final, but more advanced scenario, would to be author your own route constraint that will accept the `v`, strips it off, parses the value, and then sets the API version via the **IApiVersioningFeature**. This is effectively all that the [ApiVersionRouteConstraint](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionRouteConstraint.cs) does anyway. It's lame that you have to do that yourself, but the amount of work is relatively low. You can then replace the default route constraint key or add it side-by-side (ex: `{version:customApiVersion}`).

**Comment by rynowak** [comment]
> A final, but more advanced scenario, would to be author your own route constraint that will accept the v, strips it off, parses the value, and then sets the API version via the IApiVersioningFeature. This is effectively all that the ApiVersionRouteConstraint does anyway. It's lame that you have to do that yourself, but the amount of work is relatively low. You can then replace the default route constraint key or add it side-by-side (ex: {version:customApiVersion}).

This is what I was suggesting, thanks for finding the words 👍 - @bderveni - this would be a shorter path to getting this to work the way you want.

**Comment by bderveni** [comment]
@rynowak and @commonsensesoftware thanks for getting back on this and providing all the suggestions. I will discuss the options with my team.

I would like to add one more edge case to the table above:

| Route  | Value | Comment |
| v1-preV/action | Success| Literal status contains `v` at the end|

> 
> 
> As illustrated in detail above, given the template `v{version:apiVersion}/action`, the results can be simplified as:
> Route 	Value 	Comment
> `v1/action` 	Success 	No status
> `v1-status/action` 	Success 	Literal status does not contain `v`
> `v1-preview/action` 	Failure 	Literal status contains `v`
>

**Comment by commonsensesoftware** [comment]
There seems to be a workaround for this issue. Since the behavior is intrinsic to the routing system, there isn't anything more API Versioning can do about it. Perhaps the routing system will improve the behavior in the future. Thanks.
