### ISSUE TITLE
Accept header and querystring with default version

### ISSUE THREAD

**Issue by davidodio** [microsoft/aspnet-api-versioning#581]
Hi, I am trying to have both querystring and header versioning. See the repo here https://github.com/davidodio/webapi-versioning

Startup.cs

```            
services.AddApiVersioning(opts => {
  opts.ReportApiVersions = true;
  opts.Conventions.Add(new VersionByNamespaceConvention());
  opts.ApiVersionReader = new MediaTypeApiVersionReader();
            
  opts.AssumeDefaultVersionWhenUnspecified = true;
  opts.DefaultApiVersion = new ApiVersion(1, 0);
});
```

IndexController.cs
```
namespace V1
{
    [ApiController]
    [Route("[controller]")]
    public class ArticleController : ControllerBase
    {
        [HttpGet]
        public string Get() => "v1";
    }
}

namespace V2
{
    [ApiController]
    [Route("[controller]")]
    public class ArticleController : ControllerBase
    {
        [HttpGet]
        public string Get() => "v2";
    }
}```

Using the accept header works as expected. However, the querystring version always returns the version 1.

Thanks!

**Comment by commonsensesoftware** [comment]
This is happening due to your configuration. You've removed the query string version reader and allowed implicit versioning via `opts.AssumeDefaultVersionWhenUnspecified = true`. Since the `opts.DefaultApiVersion` is `1.0` and the query string is ignored, the result will always match `1.0`.

To use multiple API version sources, you need to _combine_ the readers like so:

```c#
opts.ApiVersionReader = ApiVersionReader.Combine(
    new MediaTypeApiVersionReader(),
    new QueryStringApiVersionReader());
```

Keep in mind that all readers are evaluated. There is no _short-circuit_. This ensures you don't end up in a situation with `Accept: application/json; v=1.0` and `?api-version=2.0`, which would be ambiguous (e.g. which one should be selected?). Either value can be specified or they can both be specified as long as they match.

**Comment by davidodio** [comment]
Perfect, thanks!
