### ISSUE TITLE
skip and top disappear with inheritance generic controller

### ISSUE THREAD

**Issue by franfr57** [microsoft/aspnet-api-versioning#582]
Hello,

I want to test the ASP.NET Core example with OData API Explorer (https://github.com/microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/SwaggerODataSample))

I want to create a basic controller to transmit methods to my main controllers via inheritance.

Here is the controller I created with the Get method of PeopleController (v3):
`public class BaseController2 : ODataController
    {
        [Produces("application/json")]
        [ProducesResponseType(typeof(ODataValue<IEnumerable<Person>>), Status200OK)]
        public IActionResult Get(ODataQueryOptions<Person> options)
        {
            var validationSettings = new ODataValidationSettings()
            {
                AllowedQueryOptions = Select | OrderBy | Top | Skip | Count,
                AllowedOrderByProperties = { "firstName", "lastName" },
                AllowedArithmeticOperators = AllowedArithmeticOperators.None,
                AllowedFunctions = AllowedFunctions.None,
                AllowedLogicalOperators = AllowedLogicalOperators.None,
                MaxOrderByNodeCount = 2,
                MaxTop = 100,
            };

            try
            {
                options.Validate(validationSettings);
            }
            catch (ODataException e)
            {
                return BadRequest();
            }

            var people = new[]
            {
                new Person()
                {
                    Id = 1,
                    FirstName = "John",
                    LastName = "Doe",
                    Email = "john.doe@somewhere.com",
                    Phone = "555-987-1234",
                },
                new Person()
                {
                    Id = 2,
                    FirstName = "Bob",
                    LastName = "Smith",
                    Email = "bob.smith@somewhere.com",
                    Phone = "555-654-4321",
                },
                new Person()
                {
                    Id = 3,
                    FirstName = "Jane",
                    LastName = "Doe",
                    Email = "jane.doe@somewhere.com",
                    Phone = "555-789-3456",
                }
            };

            return Ok(options.ApplyTo(people.AsQueryable()));
        }
    }`

Then I inherit PeopleController from the BaseController.

The problem is that in swagger, the skip and top methods disappear.

Do you know how I can solve this problem?

Thank you.

**Comment by commonsensesoftware** [comment]
That's because with this particular setup, there is nothing to inherit. The options are being applied by convention, which can be seen [here](../blob/master/samples/aspnetcore/SwaggerODataSample/Startup.cs#L47).

You have at least 3 options:

1. Apply conventions for your other versions
2. Create and apply your own convention which can support inheritance
3. Use attributes instead (this assumes the attributes are inheritable, which I haven't checked)

In general, inheritance is a bad idea for APIs. APIs do not _inherit_ functionality. This can become really problematic if you need to remove something because you cannot _uninherit_ functionality. Alternatively, I would suggest base classes that provide common functionality, such as responses, transformations, etc, but then let each implementation stand on it's own.

Inheritance is usually sought after to be DRY. Being DRY is fine, but be cautious about letting it come at the expensive of making your APIs difficult to evolve. Inheritance _can_ lead to a path that is hard to unwind 5+ versions from now. In addition, if your test suite isn't comprehensive, you may end up letting an implementation convenience cause a regression in a previous version. The choice is yours, but be warned that _"there be dragons"_. ;)

**Comment by franfr57** [comment]
Thank you for your answer.

I have considered the 3 options but there are limits.
1. When I apply conventions, skip and top operations do not appear in swagger. filter and orderby works.
How can I find out why the skip and top operations do not appear when I applied the convention in the Startup.cs file?

2. I do not know how to create a convention. Is it possible to have information on how to do (code example)?

3. Inheritance only works if the return data type is specified:
[ProducesResponseType(typeof(ODataValue<IEnumerable<Order>>), Status200OK)]
With that the inheritance does not work (the methods skip, top, etc ... do not appear):
[ProducesResponseType, Status200OK)]

**Comment by commonsensesoftware** [comment]
1. You didn't show your configuration so it's not entirely clear. The sample doesn't include `$skip` and `$top`. If I were to guess, it's simply because they haven't been mapped.

2. Creating your convention is simple. You only need to implement [IODataQueryOptionsConvention](../blob/master/src/Common.OData.ApiExplorer/AspNet.OData/Builder/IODataQueryOptionsConvention.cs) and then add it like this:

 ```c#
services.AddODataApiExplorer(options => options.QueryOptions.Add(new MyConventions()));
```

3. If the `[ProducesResponseType]` doesn't specify a response type, then it's based on the method return value. If no capable type is defined, then there's nothing to show.

**Comment by commonsensesoftware** [comment]
Did you ever come up with a solution? It's not 100% clear what your setup is for inheritance. I doesn't seem you show the full working approach described in \#3. It sounds like you may have something working.

**Comment by commonsensesoftware** [comment]
This thread seems to have been abandoned. The latest [5.0.0-RC.1](https://www.nuget.org/packages/Microsoft.AspNetCore.OData.Versioning/5.0.0-rc.1) is out and likely addresses this issue. The official release will likely occur after 2 weeks of _burn-in_. If that doesn't fix it, feel free to reopen the issue or create a new one. Thanks.
