### ISSUE TITLE
.net core 3 Support (nightly build available)

### ISSUE THREAD

**Issue by Diraekt** [microsoft/aspnet-api-versioning#583]
The OData Team pushed a nightly build which works in .net core 3. When I add your package and enable versioning with: `EnableApiVersioning()` the error comes back:

> TypeLoadException: Could not load type 'Microsoft.AspNetCore.Mvc.Internal.ActionConstraintCache' from assembly 'Microsoft.AspNetCore.Mvc.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60

Sorry for cross posting but after found this closed issue, I think you can help 😉

https://github.com/OData/WebApi/issues/1748

_Originally posted by @Diraekt in https://github.com/microsoft/aspnet-api-versioning/issues/568#issuecomment-559601225_

**Comment by commonsensesoftware** [comment]
This happens because OData doesn't support ASP.NET Core 3.0. The release API versioning package multi-targets. The support for OData targets ASP.NET Core 2.2 in the API Versioning 3.1-4.0 packages.

As much as I'd love to help out, nightly builds aren't really an option for me. I run this project completely by myself as _freeware_. I don't have a team or budget to work with. A practical nightly build would mean publishing to a private NuGet feed such as MyGet, which I don't have any resources for.

The OData thread suggests they will be making fundamental design changes to OData's routing infrastructure. If they continue the ways of the past, this will likely end up requiring quite a bit of work on the API versioning side. It's certainly going to be more than just switching to .NET Core 3.0. Historically, I've had to learn, digest, and reimplement a bunch of stuff from 5.x-6.0 and 7.0-Core. Again - as a one man army, it would be difficult for me to stay lock-step with a moving target. Nightlies, I think, would be a bit much, but if there is a stable preview/pre-release build, I'd be willing to consider that.

I've met with the OData team in the past and I've voiced my concerns/thoughts in-person and on the thread. They heard to what I had to say, but we'll see if they _listened_. In the meantime, thanks for your patience and support.

**Comment by NetTecture** [comment]
Oh damn. From the impression I have they will listen and then SOMEONE with so little clue that it hurts will do an implementation that is totally not usable for you. Out of totally not understanding anything.

Would you be able to work with any sort of preview build (from nuget)?

**Comment by commonsensesoftware** [comment]
They _are_ my brothers in arms so I'm hoping that they at least _consider_ the feedback and work it into their design without having to compromise their goals or timelines. In the past, I've had to completely fork and reimplement their routing mechanisms. That's quite unfortunate since the only real difference from a versioning perspective is possible duplicate routes with disambiguation by API version. 

The ASP.NET team definitely took my feedback and that was one of their main Litmus tests against the new _Endpoint Routing_ design. It was significantly less work to support that. Since OData is moving towards _Endpoint Routing_, maybe the stars will align and I won't need to do anything (:v:). Sadly, the news that OData needs _future_ design changes to really make their scenario work worries me 😟. The positive side is that ASP.NET team agreed to it, which means they must have had a compelling argument. Time will tell.

Yeah, once there is a feasible NuGet package - even a preview, I'd consider it. I _might_ even take select pulls from their nightly feed, which I've done in the past for ASP.NET Core previews. It certainly won't be at their nightly cadence, but I'm happy to get something going. I really can't understand what their hold up is for an initial version which runs on .NET Core 3.0. The _legacy_ routing system is still there and still supported by API Versioning. The first step IMHO should simply be to update the targets to .NET 3.0/3.1 and ship that. It _should_ be minimal effort. After that the proverbial monkey would be off their back so they can put the real investment and time into rethinking the routing system with _Endpoint Routing_. It's out of my hands and purview, but that's what I'd do.

**Comment by Diraekt** [comment]
Thanks for all your Effort!

Since 1 week there is s working beta. This Beta also support the legacy routing system.

It would be great when you have a look at this to Tell us how big your work will be 😎

https://www.nuget.org/packages/Microsoft.AspNetCore.OData/7.3.0-beta

Thanks!

**Comment by commonsensesoftware** [comment]
Based on the discussion happening on the OData repo, I need and am waiting for a .NET Core 3.1 build, which I assume will be the next beta. It appears everyone agrees there is no point in bothering with .NET Core 3.0 now that 3.1 is out and it has LTS.

If they are stalling out, then I can consider it. However, as I mentioned on the OData repo it is non-trivial to support multiple runtimes. It causes the most amount of work for me in the build process because I have to support multiple .NET SDKs. I already have to support 2.2 for OData when everything else is already on 3.1.

I got the impression they would move forward to 3.1 _soon_. If that's not the case, then I'll re-evaluate. As a _one man team_, I'm wary of  chasing _dangling carrots_ and moving targets; I simply don't have the capacity for it. My understanding is that 7.3.0+ will largely be simply making things run on .NET Core 3.0+ while the OData team redoes their infrastructure to support _Endpoint Routing_. That _should_ mean minimal effort on my part to get a compatible build out. I won't truly know until I update and run it through the test suite. I suspect it will result in few, if any, changes. ✌️

**Comment by ikemtz** [comment]
My framework is heavily dependent on this library for my framework, and I realize you don't have a team, so if you need assistance in any way just please reach out to me. My twitter handle is the same as my Github username.

It's somewhat disappointing that Microsoft doesn't have more resources behind this project.  In my opinion, this library is a must if you're developing SaaS solutions, more so if you need to support multiple outside vendors.

I looked at the code and you're absolutely right, supporting multiple frameworks is a nightmare.

**Comment by Diraekt** [comment]
FYI: the OData webapi Master was updated to .net core 3.1.

https://github.com/OData/WebApi/commit/4eb6b7fee55d8a8f4382eef643ba3f3a5226d270

**Comment by Diraekt** [comment]
FYI: 7.3 RTM is out.
(Without support of new routing infrastructur).

Hopefully you dont need to make a lot adjustments.

Merry Christmas!

**Comment by ikemtz** [comment]
@commonsensesoftware 

I started working on this and was able to get pretty far.  However, I've hit a roadblock; I'm getting this compile-time error:
Cannot implicitly convert type 'System.Reflection.Emit.TypeBuilder' to 'System.Reflection.TypeInfo'

It's related to a newer version of TypeBuilder that inherits directly from Type instead of TypeInfo, trying to work around this quickly turns into some massive refactoring.  
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Reflection.Emit/ref/System.Reflection.Emit.cs

What are your thoughts on addressing this?  I have pushed my branch up to GitHub:
https://github.com/ikemtz/aspnet-api-versioning/tree/OData_7-3_Update

I didn't want to create a PR because the code is not ready yet.

Thanks,
-Isaac Martinez

**Comment by commonsensesoftware** [comment]
@ikemtz , the reason it's complaining is it looks like **TypeInfo** has been swapped back to just **Type** again. There is been some _switch-a-roos_ on these two types during the evolution from full .NET Framework, through .NET Standard, now .NET Core, and soon to just be ".NET". In most cases, these two types are interchangeable. In this particular case, it would seem that **TypeBuilder** inherits from **Type** once again. It's a relatively straight forward change; all the references to **TypeInfo** need to be swapped back to **Type**.

Despite the OData package only being released for a few days and it's the holiday break, I see people have 🐜 in their pants and are going to light a :fire: under me until there's working version out there. 😜 The work is in-progress. Fortunately, it's a bit easier to rip out the multi-targeting than it was to put it in. There's just a few more kinks to work out and then things should be ready to go. I'm _hoping_ to get it out later today. Check back in a few hours.

**Comment by commonsensesoftware** [comment]
The release is out. It should appear in the NuGet feed in a few minutes after package validation. Thanks for your patience.

**Comment by ikemtz** [comment]
Thank you sir, you rock!!!
