### ISSUE TITLE
Unhandled exception. System.TypeLoadException: Method 'ApplyAsync' in type 'Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy' from assembly 'Microsoft.AspNetCore.Mvc.Versioning, Version=4.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation

### ISSUE THREAD

**Issue by caopengfei** [microsoft/aspnet-api-versioning#585]
Unhandled exception. System.TypeLoadException: Method 'ApplyAsync' in type 'Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy' from assembly 'Microsoft.AspNetCore.Mvc.Versioning, Version=4.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
   at Microsoft.Extensions.DependencyInjection.IServiceCollectionExtensions.AddApiVersioningServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.IServiceCollectionExtensions.AddApiVersioning(IServiceCollection services, Action`1 setupAction)
   at API.Startup.ConfigureServices(IServiceCollection services) in D:\Develop\Projects\AiShi1\ChuGe-API\Startup.cs:line 404
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

**Comment by caopengfei** [comment]
in .net core 3.1

**Comment by commonsensesoftware** [comment]
Going out on a limb here, but without any other context I presume you’re trying to use OData, yes?

**Comment by caopengfei** [comment]
i just use ASP.NET Web API Versioned API Explorer

**Comment by caopengfei** [comment]
![TIM截图20191206113127](https://user-images.githubusercontent.com/10126284/70293679-f877b600-181b-11ea-9c49-aa01800bcfbf.png)

**Comment by commonsensesoftware** [comment]
Do you have a repro or some additional details about your project references?

**Comment by caopengfei** [comment]
It's strange that I can run locally, but an error is reported after publishing with docker

**Comment by commonsensesoftware** [comment]
Sounds like there is a mismatch of ASP.NET Core and/or .NET Core. The API Versioning package multi-targets, which _can_ lead to a successful build with runtime failures with the right combination. The 2.2 libraries target .NET Standard 2.0, but it won’t work on .NET Core 3.0/3.1.

**Comment by caopengfei** [comment]
What should we do now?

**Comment by caopengfei** [comment]
it's ok on .NET Core 3.0 but error on .NET Core 3.1

**Comment by caopengfei** [comment]
I test it,Microsoft.AspNetCore.Mvc.Versioning 4.0 is work on .NET Core 3.0/3.1,but Microsoft.AspNetCore.Mvc.Versioning 4.1 won’t.

**Comment by commonsensesoftware** [comment]
I hate to just punt, but it _sounds_ like there is something misconfigured in your container. Are you 100% sure it's using .NET Core 3.1 and that your build, is in fact, targeted to .NET Core 3.1? Your description of the issue and stack trace has all the symptoms of ASP.NET Core 2.x trying to run on .NET Core 3.0+. That's why I asked about OData because it is still on 2.x and isn't supported on .NET Core 3.0+ - yet (that's out of my hands).

I've successfully had everything build and run through the test suite on multiple machines, including my build pipelines (which wouldn't have anything cached). I was also able to run through the sample applications on .NET Core 3.1. I've been using the 4.1.0 package with some .NET Core 3.1 projects and haven't hit any issues - yet. I might suggest that you perform a full, _clean_ build locally by purging **all** of the _bin_ and _obj_ folders in your solution. Rebuild and test again locally. If that works, then it _should_ confirm that there is something not quite right in your container setup.

**Comment by chrisstaley** [comment]
I also started seeing this error after updating to v4.1. We have an ASP.NET Core 3.0 app. Downgrading back to 4.0 is our current work around.

For reference, this is the versioning config that we're using:
``` c#
services.AddApiVersioning(o =>
{
	o.AssumeDefaultVersionWhenUnspecified = true;
	o.DefaultApiVersion = new ApiVersion(1, 0);
	o.ApiVersionReader = new HeaderApiVersionReader(CustomHttpHeader.ApiVersion);
});
```

**Comment by commonsensesoftware** [comment]
@chrisstaley (and anyone else who is using that configuration), this is what I would expect to happen. ASP.NET Core 3.1 is on .NET Core 3.1, which is a different runtime from .NET Core 3.0. The **only** difference between API Versioning 4.0 vs 4.1 is targeting ASP.NET Core and .NET Core 3.1.

I suspect the reason that people are running into this is because API Versioning multi-targets. It continues to support ASP.NET Core 2.2 until OData officially supports .NET Core 3.0+. Since the other flavor builds against .NET Standard 2.0, it is somehow being seen as compatible. Theoretically, that shouldn't happen since the package _clips_ it at `< 3.0.0`. It's possible there is a bug in the restore logic or something. You can probably confirm this by looking at what was actually restored and/or referenced. What I would have expected to happen is that you get an error stating there are no compatible versions.

The only other time I've seen this specific error is when people have tried to use API Versioning targeting ASP.NET Core 2.2 against .NET Core 3.0/3.1. They are incompatible. I'm not even sure how you can get a successful build, but somehow people are and then things spectacularly fail at runtime.

For now, if you're on 3.0, then you should stay with API Versioning 4.0. If you're on 3.1, then you should move to 4.1. If you're still on ASP.NET Core 2.2, then it doesn't matter; 4.0 and 4.1 are equivalent. The future roadmap will be to support .NET Core 3.1+ since it has been marked for _Long Term Support_ (LTS).

I hope that helps clear things up.

**Comment by chrisstaley** [comment]
@commonsensesoftware Thanks for thorough explanation.

**Comment by commonsensesoftware** [comment]
I believe this issue is now resolved. If not, feel free to reopen it.

For clarity:

| .NET Version | API Versioning |
| -------------- | ---------------- |
| netcoreapp3.0 | 4.0.0 |
| netcoreapp3.1 | 4.1.0+ |

.NET Core 3.0 only lasted a month and 3.1 is LTS so I do not expect to ever patch or release something for 3.0 again.

Thanks
