### ISSUE TITLE
Combine ODataController and ControllerBase based controller in different versions

### ISSUE THREAD

**Issue by brakonstantin** [microsoft/aspnet-api-versioning#586]
Hello!

This must be a very simple question...

I have a versioned API which is based on CotrollerBase-based controllers. We plan to introduce OData support in the next version of the API. Could you please point out what is the best practice to do it?

As a test I tried to add a ControllerBase-based controller to SwaggerODataSample. I attributed it with

```
[ApiController]
[ApiVersion( "2.0" )]
[Route("api/v2.0/TestController")]
```

The result was that loading of swagger/index.html resulted with
```
Failed to load API definition.
Fetch error
Internal Server Error /swagger/v0.9/swagger.json

```

**Comment by commonsensesoftware** [comment]
I guess I never created the _Advanced_ sample for ASP.NET Core that demonstrates this. Probably because it was quite some time before OData was supported on ASP.NET. I'll have to add that at some point. In the meantime, this **is** supported and you can get an idea of how to configure it by looking at the [Advanced Acceptance Tests](../tree/master/test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/OData/Advanced). This will illustrate switching to and from OData between API versions. I haven't walked though setting that up with Swagger too, but there isn't any reason it shouldn't work.

A couple of other notes:
1. You need to use the route constraint, not the literal in your route template; e.g. `v{version:apiVersion}` and not `v2.0`. There is no _magic_ parsing of your template so this is how API Versioning knows where and what in your URL represents the API version in this style.
2. You haven't provided any stack trace info, but I suspect the failure is due to OData/WebApi#1750. This causes the core ASP.NET API Explorer to encounter an exception which cannot be mitigated. It's an easy fix on the OData side, so I'm not sure why it's still not fixed. I outlined a workaround, but the only solution involves you writing code to remove the offending OData formatters.

**Comment by brakonstantin** [comment]
Thank you for your answer! I hope I will be able to figure out what I am doing wrong...

**Comment by igorvelho** [comment]
Is there any new insights on this? I tried this but I couldn't make it work

**Comment by brakonstantin** [comment]
This issue has not been my main focus for some time, but anyway I am still stuck in it...

**Comment by commonsensesoftware** [comment]
@igorvelho what did you _try_ exactly? I have yet to encounter a scenario where mixing the two together does not work. I need a lot more details beyond _"It doesn't work"_ to provide guidance or additional insight. Do your APIs not work or route correctly at all or are you only having issues generating OpenAPI documents? Which OpenAPI library are you using? Swashbuckle, NSwag, `<insert here>`? Do you have stack trace or other log information? Better still, do you have a repro?

**Comment by brakonstantin** [comment]
@commonsensesoftware. In my case the error was
```
Failed to load API definition.
Fetch error
Internal Server Error /swagger/v0.9/swagger.json
```
To be honest, I have not tried whether controllers themselves work OK. Based on your answers I am pretty sure they will work.

I guess the problem is in fact Swashbuckle which fails to generate swagger.json. And this has nothing to do with aspnet-api-versioning, as I see it. I was just hoping that aspnet-api-versioning had an example, handling the case  when ODataController and ControllerBase were used together in different (or the same) API versions...

My problem was that I did not see any exceptions when this problem happened and I did not really had much time to dig more into it, so I just put it on hold and switched to other tasks...

**Comment by commonsensesoftware** [comment]
I suspect if you look at the trace output, you'll see an exception. It's almost certainly related to the second issue I pointed out above. This is technically a bug in OData. I filled the bug, but they've yet to fix it despite it being a very easy and quick fix. I considered submitting a PR to fix it myself, but the PR approval and patching publishing rhythm is seemingly slow, which discourages me from putting forth the effort. I've outlined a workaround, but since it's on the OData side, I'm not inclined to back it into versioning as it's not the right place. Effectively, you need to remove one of the built-in OData input and one of the output formatters. I've mostly seen this occur when you mix OData with non-OData.

**Comment by commonsensesoftware** [comment]
Were you ever able to resolve this? The proposed solution _should_ have worked.

**Comment by commonsensesoftware** [comment]
This scenario is supported and does work, albeit with some modifications as mentioned above. It's beyond belief to me that this OData bug is still open. It is insanely simple to solve. Regardless, you can modify your startup to remove the offending formatters. This issue only occurs when you add the API Explorer extensions for OpenAPI/Swagger.

This thread seems to otherwise have reached an end. If anyone is still having a problem, I'm happy to re-open this or provide additional explanation about how to make it work.

Thanks

**Comment by corruptkernel** [comment]
> I guess I never created the _Advanced_ sample for ASP.NET Core that demonstrates this. Probably because it was quite some time before OData was supported on ASP.NET. I'll have to add that at some point. In the meantime, this **is** supported and you can get an idea of how to configure it by looking at the [Advanced Acceptance Tests](../tree/master/test/Microsoft.AspNetCore.Mvc.Acceptance.Tests/OData/Advanced). This will illustrate switching to and from OData between API versions. I haven't walked though setting that up with Swagger too, but there isn't any reason it shouldn't work.
> 
> A couple of other notes:
> 
> 1. You need to use the route constraint, not the literal in your route template; e.g. `v{version:apiVersion}` and not `v2.0`. There is no _magic_ parsing of your template so this is how API Versioning knows where and what in your URL represents the API version in this style.
> 2. You haven't provided any stack trace info, but I suspect the failure is due to [OData/WebApi#1750](https://github.com/OData/WebApi/issues/1750). This causes the core ASP.NET API Explorer to encounter an exception which cannot be mitigated. It's an easy fix on the OData side, so I'm not sure why it's still not fixed. I outlined a workaround, but the only solution involves you writing code to remove the offending OData formatters.

Did you ever set this up with Swagger?
