### ISSUE TITLE
The inline constraint resolver of type 'DefaultInlineConstraintResolver' was unable to resolve the following inline constraint: 'apiVersion'

### ISSUE THREAD

**Issue by ryanhmaas** [microsoft/aspnet-api-versioning#588]
Hi,

I've done some looking around some of the issues around, and maybe I'm missing something, but I have not been able to resolve the error mentioned in the title.

A stack trace looks something like: 

```
InvalidOperationException: The inline constraint resolver of type &#39;DefaultInlineConstraintResolver&#39; was unable to resolve the following inline constraint: &#39;apiVersion&#39;.]
   System.Web.Http.Routing.InlineRouteTemplateParser.GetInlineConstraint(Group constraintGroup, Boolean isOptional, IInlineConstraintResolver constraintResolver) +399
   System.Web.Http.Routing.InlineRouteTemplateParser.ParseRouteTemplate(String routeTemplate, IDictionary`2 defaults, IDictionary`2 constraints, IInlineConstraintResolver constraintResolver) +338
   System.Web.Http.Routing.DirectRouteFactoryContext.CreateBuilder(String template, IInlineConstraintResolver constraintResolver) +157
   System.Web.Http.Routing.DirectRouteFactoryContext.CreateBuilderInternal(String template) +8
   System.Web.Http.RouteAttribute.System.Web.Http.Routing.IDirectRouteFactory.CreateRoute(DirectRouteFactoryContext context)....
```

This is _not_ a .NET Core Web API, so my setup currently looks something like this:

**Startup.cs**

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using System.Web.Http.Routing;
using Microsoft.Owin;
using Microsoft.Web.Http;
using Microsoft.Web.Http.Routing;
using Microsoft.Web.Http.Versioning.Conventions;
using Owin;

[assembly: OwinStartup(typeof(MyStartupClassHere))]

namespace My.Web.Api
{
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            ConfigureAuth(app);
            // we only need to change the default constraint resolver for services that want urls with versioning like: ~/v{version}/{controller}
            var constraintResolver = new DefaultInlineConstraintResolver() { ConstraintMap = { ["apiVersion"] = typeof(ApiVersionRouteConstraint) } };
            var configuration = new HttpConfiguration();
            var httpServer = new HttpServer(configuration);

            configuration.AddApiVersioning(
                options =>
                {
                    // reporting api versions will return the headers "api-supported-versions" and "api-deprecated-versions"
                    options.ReportApiVersions = true;
                    options.Conventions.Add(new VersionByNamespaceConvention());
                    options.DefaultApiVersion = new ApiVersion(1, 0);
                });

            configuration.Routes.MapHttpRoute(
                    "VersionedUrl",
                    "api/v{apiVersion}/{controller}",
                    defaults: null,
                    constraints: new { apiVersion = new ApiVersionRouteConstraint() }); 

            app.UseWebApi(httpServer);
        }
    }
}

```

**AccountController.cs**

```namespace My.Web.Api.Controllers
{
    [Authorize]
    [RoutePrefix("api/v{version:apiVersion}/account")]
    public class AccountController : ApiController
    {
        public AccountController()
        {
        }

        [AllowAnonymous]
        [HttpPost]
        [Route("Authenticate")]
        public async Task<IHttpActionResult> Authenticate(string username, string password)
        {...
```

Naturally I've changed a few of the class names so I could posit the question here, but I can't get around the error regarding the constraint. I tried removing the `RoutePrefix` but end up with a 404. Thoughts? I'm thinking the issue is attribute routing related but not certain. Thanks in advance.

**Comment by commonsensesoftware** [comment]
It looks like the streams have been crossed between attribute and convention-based routing. While these two styles can technically be used together, it can be very confusing. Unless you have a historical reason for doing both, I **strongly** recommend choosing one or the other. If you're not able to switch for reasons out of your immediate control, I would still jot down a backlog item for technical debt to switch to one form or the other. It makes things much easier to rationalize IMHO.

So, the reason you are seeing this is because you are using _Direct Routing_ (aka _Attribute Routing_) on your controller, but you've only defined the route constraint in your _Convention-Based_ route template. In fact, you didn't even register _Attribute Routing_ at all. While you did add the required constraint the constraint map, it's not registered with anything.

This will enable it with _Attribute Routing_:

```c#
configuration.MapHttpAttributeRoutes( constraintResolver );
```

Of course, you'll now have a _direct_ (or _attribute_) route and convention route for the same template. The underlying provider injects the generated templates from attributes before all other route templates. I would expect things to now work, but it could get really confusing later. Again - I recommend choosing one style or the other. Mixing the two only leads to headaches.

**Comment by ryanhmaas** [comment]
@commonsensesoftware Thank you for the concise and succinct response, I appreciate it. We definitely have that technical debt you allude to then.
