### ISSUE TITLE
System.InvalidOperationException: No route matches the supplied values

### ISSUE THREAD

**Issue by mrinalkumarjha** [microsoft/aspnet-api-versioning#592]
[PhotosController.txt](https://github.com/microsoft/aspnet-api-versioning/files/4010258/PhotosController.txt)

I have attached my controller. i am trying to use CreatedAtRoute method inside AddPhotoForUser method but it gives error "No route matches the supplied values"

Please suggest where i am missing anything.

Here are my git repo link : https://github.com/mrinalkumarjha/DatingApiCore3.1

**Comment by commonsensesoftware** [comment]
This doesn't appear to be related to API Versioning. I don't even see the package referenced. This repo isn't run by the ASP.NET team. This is type of question is usually better suited for Stack Overflow.

To answer your question, however, it's not working because you are missing a route parameter. This has bitten a few people that expect missing route parameters to be _magically_ provided via existing route values. That's not always the case (maybe never anymore). I recommend always being explicit about the required route values.

The following change will make it work:

```c#
return CreatedAtRoute(nameof(GetPhoto), new { userId, id = photo.Id }, photoToReturn);
```

Thanks

**Comment by mrinalkumarjha** [comment]
thanks it worked.
