### ISSUE TITLE
Api Versioning + Dynamic Added Controllers + Swagger not working

### ISSUE THREAD

**Issue by mihai-cloudbrick** [microsoft/aspnet-api-versioning#604]
Hi, 

Im tring to add the controllers dynamically, basic using a ControllerBase Custom with repository and add for each entity in the DB the controllerat runtime. The controllers are added properly and i can access the acctions for each entity, but i can not see the controllers in Swagger. The only controller that i can find its the one that i didnt added dynamically.  
There is any good example on how to have Versioning and swagger with dynamically added controllers using the MS Api Versioning?

**Comment by commonsensesoftware** [comment]
I don't have any details regarding your implementation; however, things will work if all of the pieces are properly implemented. I'm not sure how you are _dynamically_ loading controllers. The issue likely has more to do with how ASP.NET Core works as opposed to API Versioning. In order for your actions to be discovered (because ASP.NET Core doesn't really care about controllers), you must implement a custom **IActionDescriptorProvider**. If things are truly dynamic though, that means you need to also implement **IActionDescriptorChangeProvider** which will tell the infrastructure when the set of available actions has changed. This would naturally occur any time a controller is dynamically loaded and/or potentially unloaded. With these services tailored to your implementation and added in your startup configuration, things should fall inline without further modification.

I hope that helps.

**Comment by mihai-cloudbrick** [comment]
Hi, 
I solved the issue by adding the RouteAttribute and the ApiControllerAttribute on the base controller and then using the conventions i can manipulate the versioning. 

Thanks for the answer.
