### ISSUE TITLE
ODataApiVersionActionSelector difference with ODataActionSelector

### ISSUE THREAD

**Issue by stormleoxia** [microsoft/aspnet-api-versioning#605]
Hello,

I have noticed that `ODataApiVersionActionSelector` algorithm for action selection is a bit different from `ODataActionSelector` one.

*src/Microsoft.AspNetCore.OData/Routing/ODataActionSelector.cs*

```csharp
// Find the action with the all matched parameters from available keys including
// matches with no parameters. Ordered first by the total number of matched
// parameters followed by the total number of parameters.  Ignore case of
// parameter names. The first one is the best match.
//
// Assume key,relatedKey exist in RouteData. 1st one wins:
// Method(ODataPath,ODataQueryOptions) vs Method(ODataPath).
// Method(key,ODataQueryOptions) vs Method(key).
// Method(key,ODataQueryOptions) vs Method(key).
// Method(key,relatedKey) vs Method(key).
// Method(key,relatedKey,ODataPath) vs Method(key,relatedKey).
var matchedCandidates = considerCandidates
    .Where(c => !c.FilteredParameters.Any() || TryMatch(c.FilteredParameters, availableKeys, optionalWrapper))
    .OrderByDescending(c => c.FilteredParameters.Count)
    .ThenByDescending(c => c.TotalParameterCount);

// Return either the best matched candidate or the first
// candidate if none matched.
return (matchedCandidates.Any())
    ? candidates.Where(c => c.Id == matchedCandidates.FirstOrDefault().Id).FirstOrDefault()
    : candidates.FirstOrDefault();
````
*src\Microsoft.AspNetCore.OData.Versioning\AspNetCore.Mvc\Versioning\ODataApiVersionActionSelector.cs*
```csharp
var finalMatches = bestActions.Select( action => new ActionCandidate( action ) )
                                .OrderByDescending( candidate => candidate.FilteredParameters.Count )
                                .ThenByDescending( candidate => candidate.TotalParameterCount )
                                .Take( 1 )
                                .Select( candidate => candidate.Action )
                                .ToArray();
````

It seems that in the versioned flavor, the  `.Where(c => !c.FilteredParameters.Any() || TryMatch(c.FilteredParameters, availableKeys, optionalWrapper))` for matching optional parameters is not used or maybe I missed something.
I'm just wondering if this is intended or not ?
By the way, there is no matching for required parameters (marked with `[Required]`). Is this something done by the constraints or something I should ask to OData team ?

Thank you :)

**Comment by commonsensesoftware** [comment]
The OData route matching policy is very narrowly focused, which makes it difficult to extend. Specifically, there is an expectation that all OData routes have `0:1` matches, but this simply will not work for API Versioning. The whole point is that you may have many _duplicate_ routes that are disambiguated by an API version.

The consequence is that I've had essentially folk and reimplement their routing stack. This is highly undesirable because I'm left chasing any changes they make. To my knowledge, the two runtime behaviors are still aligned. Are you saying you have found something where they are not? I'm crossing my fingers that once they implement _Endpoint Routing_, I'll be out of this business altogether.

In general, you should fine the implementations very similar. I'm strong advocate for code analysis. This repo has very strict policies so you'll likely see some differences due to higher enforcement of _best practices_. I also strive for performance so you see many LINQ statements or other suboptimal code replaced with an appropriate alternative (ex: `for` vs `foreach` on an indexed collection).

Ultimately, if there is a behavior that OData is not doing that you expect, then that should be for the OData repo. However, if you see behavior differently when using API Versioning, then you're in the right spot. I'm sure there are still edge cases where something doesn't line up. Test matrix for all the OData combinations is quite large.

**Comment by stormleoxia** [comment]
Thank you for your answer. It's a lot clearer. I didn't notice any differences in behavior.
I will try to make a test on a call with/without optional parameters to check how if it behaves.

**Comment by commonsensesoftware** [comment]
I believe this question has been adequately answered. I hope/suspect things will be more closely aligned with _Endpoint Routing_, but it's hard to say for sure. The OData team does occasionally change things and I have to fork their code. If you do find a difference in behavior, feel free to call it out. It's quite possible that something is out-of-sync. Thanks.
