### ISSUE TITLE
OData Core 7.4 with endpoint routing support?

### ISSUE THREAD

**Issue by NetTecture** [microsoft/aspnet-api-versioning#608]
It is in beta now and a lot of us jumped to it ;) Had to rip out versioning to get it going and would love to know whether I can somehow put it back in soonish.

That said, if you are talkative, I would also love to know whether this finally bears the fruits of talking to the Odata team and not having to reimplement everything for you and whether they have opened their side of the routing to extract information ;)

**Comment by commonsensesoftware** [comment]
Thanks for bring that to my attention. That would suggest they are close to a final design. I'll start taking a look at what's changed. I've had a face-to-face with them in the past. I've always had the perception that they are receptive to feedback, but thus far the discussions have not yielded any concrete changes.

Part of the reason to discuss those issues in a public forum is so they can see for themselves that the OData community finds versioning important. It's much better when things come from the community rather than me directly. ;)

With any luck, _Endpoint Routing_ will just line up, which may result in little or no changes for versioning. I suspect the will be more changes for the API Explorer than routing, but I won't know until I start digging in.

**Comment by NetTecture** [comment]
To my knowledge they plan to release next week. It is out for a week now, and the target was to release after 2 weeks beta - give people involved time to check out that there are no critical bugs. So far I did not find any - things look very good. Except, obviously, my whole swagger stack not working due to missing api versioning.

**Comment by rossbuggins** [comment]
It's definitely getting there https://github.com/OData/WebApi/issues/2029 - getting versioning support there will be the final jigsaw piece

**Comment by NetTecture** [comment]
@commonsensesoftware 7.4 just got released it seems - at least I am updating my nuget packages now.

**Comment by commonsensesoftware** [comment]
I know folks have been champing at the bit for this. I've been incredibly backed up these past few months. I'm finally getting back into all of this. The basic part of routing working. I'll leave this issue open while I work on it, but I'm going to direct all further communication on #616 since that has a representative from the OData team on that thread. Thanks.
