### ISSUE TITLE
Swagger Example Values no longer showing since upgrade to .NET Core 3.1

### ISSUE THREAD

**Issue by ben5Kuda** [microsoft/aspnet-api-versioning#611]
I have just upgraded to .NET Core 3.1 and i am using your samples. I have updated the following

` <TargetFramework>netcoreapp3.1</TargetFramework>
<PackageReference Include="Microsoft.AspNetCore.OData" Version="7.4.0-beta" />
    <PackageReference Include="Microsoft.AspNetCore.OData.Versioning" Version="4.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OData.Versioning.ApiExplorer" Version="4.1.1" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.1.4" /> 
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.2.1" />`

Everything else seems to work except i can no longer see the Swagger Example values. I am not sure why? They used to be there before. Is there something i am missing?

**Comment by commonsensesoftware** [comment]
Just to be clear, the **Example** values or **Default** values? I didn't have any samples that also setup example values, but I seem to recall that you can do so with Swashbuckle. This _might_ be due to a change in that library, which would be better asked on their repo. If it's the default API version value, it should be working. Can you share the setup code or do you have a repro?

**Comment by ben5Kuda** [comment]
I am referring to the Swagger Examples (Schema Examples). Yes it is true in your samples you had not provided sample values, however by default the values are displayed (without any setup, although this are just default ones). One has to customize these using ISchemaFilter (Swashbuckle). The issue i am having is the example values aren't there anymore so i can't even customize them. So to be sure i created a .NET Core Web Api project without any versioning or OData and just added Swashbuckle and i could see the schema examples. Anyway you can have a look at this repo, although i have upgraded it to  .NET Core 3.1. [(https://github.com/ben5Kuda/SwaggerAspNetCoreODataVersioning)
](url). Before it was targeting netcoreapp2.2 and the schema examples would show but now it doesn't anymore.  
See sample below:
`[
  {
    "id": 0,
    "username": "string",
    "profile": "string",
    "roles": [
      {
        "id": 0,
        "roleName": "string"
      }
    ]
  }
]`

**Comment by commonsensesoftware** [comment]
Hmmm... not much is immediately standing out. I did notice that the service configuration is a little unusual. You _can_, but should **not** change the `AssumeDefaultVersionWhenUnspecified` or `DefaultApiVersion` directly in the API Explorer options. These particular options will be copied over from the `AddApiVersioning`. If you do explicitly set them, they need to be congruent (e.g. the same) with the options in `AddApiVersioning`, which they currently are not.

In addition, if you use `AddODataApiExplorer`, you don't need to use `AddVersionedApiExplorer` because one depends on the other. In this particular case, it shouldn't really matter because they have overlapping settings.

Thanks for the repro. I'll have to investigate further. Does the sample project at least work for you? I see the schema and examples just fine. Perhaps it's worth updating the package references in the sample to what you're using and make sure they still work?

**Comment by ben5Kuda** [comment]
OK, i think i have found a workaround after going through the samples multiple times to see what is different from my implementation, i noticed that adding the annotation `[Produces("application/json")]` at either controller level or method level fixes the issue. Suddenly my schema and examples show up on Swagger. Previously when i was using netcoreapp2.2  adding the annotation was not necessary. I am not sure if this is by design or is it?

**Comment by commonsensesoftware** [comment]
If I'm not mistaken, I believe that is a change in the behavior of Swashbuckle based on information from the API Explorer. Without that, I don't think the UI knows which forms it can show the example as. It doesn't just blindly assume that it's JSON.

Glad you got it working.

**Comment by ben5Kuda** [comment]
I will just use that then, thanks.

**Comment by commonsensesoftware** [comment]
It would seem that this issue has been resolved. Thanks.
