### ISSUE TITLE
MapVersionedODataRoutes with OData endpoint routing

### ISSUE THREAD

**Issue by adrien-constant** [microsoft/aspnet-api-versioning#613]
I have a versioned OData API using ASP.NET Core 3.1.

I used to call MapVersionedODataRoutes in the routeBuilder parameter of UseMvc().

```
var odataModelBuilder = app.ApplicationServices.GetRequiredService<VersionedODataModelBuilder>();

app.UseMvc(routeBuilder =>
{
    var models = odataModelBuilder.GetEdmModels();
    routeBuilder.MapVersionedODataRoutes(
                        "odata",
                        "v{version:apiVersion}",
                        models);
    });
```

It worked well, then I switched to endpoint routing and upgraded to Microsoft.AspNetCore.OData Version 7.4.0-beta following this guide :
https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/

Now I use :

```
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
}
```

What is the proper way to map the versioned routes with endpoint routing ?

Thank you,
Adrien

**Comment by commonsensesoftware** [comment]
_Endpoint Routing_ with OData isn't supported - yet. There is only a beta version available and it's only been available for just over 3 weeks. I don't have a team working on all of this like they do. I avoid working against prereleases because I don't have the capacity to chase changes. It's on my radar and I'm hoping to commit serious time to looking what changes are required soon. Thanks for your patience.

**Comment by adrien-constant** [comment]
Ok, thank you for your quick answer !

**Comment by prasadburugaTR** [comment]
below code is not working in dotnet framework 8.0

   app.UseMvc(routeBuilder =>
   {
       var models = odataModelBuilder.GetEdmModels();
       routeBuilder.MapVersionedODataRoutes(
                           "odata",
                           "v{version:apiVersion}",
                           models);
   });
