### ISSUE TITLE
ASP.NET Core API Versioning - Partially supplant previous method version

### ISSUE THREAD

**Issue by rebeccapowell** [microsoft/aspnet-api-versioning#614]
I'm having an issue with API Versioning (ASP.NET Core API 2.1). I'm trying to supplant one method of an existing controller without having to copy all of the methods in the previous version. I assumed this would work but it gives me a problem with routing conflicts. Example:

    namespace MyApi.Controllers
    {
    	[Produces("application/json")]
    	[Route("api/v{version:apiVersion}")]
    	public class BaseController : Controller
    	{
    		public string VersionNumber => GetRouteValue<string>(ControllerContext, "version");
    
    		protected static TValue GetRouteValue<TValue>(ControllerContext context, string name)
    		{
    			return (TValue)Convert.ChangeType(context.RouteData.Values[name], typeof(TValue));
    		}
    	}
    }
    
    namespace MyApi.Controllers
    {
        [ApiVersion("1.0")]
        [ApiVersion("2.0")]
        public class ValuesController : BaseController
        {
    		[HttpGet("values", Name = "GetValuesV1.0")]
    		public IActionResult GetValues() => Ok(new string[] { "value 1", "value 2" });
    		
    		[HttpGet("values/{value}", Name = "GetValueV1.0")]
    		public IActionResult GetValue(string value) => Ok( value });
    	}
    }
    
    namespace MyApi.Controllers.V2_0
    {
        [ApiVersion("2.0")]
        public class ValuesController : BaseController
        {
    		[HttpGet("values", Name = "GetValuesV2.0")]
    		public IActionResult GetValues() => Ok(new string[] { "value 1", "value 2", "value 3" });
    	}
    }

I then get the error:

> The method 'Get' on path 'xxx' is registered multiple times.

I want to support the method GetValue(string value) in both versions, but I don't want to duplicate the code in the new controller every time I version. I just want to supplant one single method. Is this possible, or do I have to copy the entire previous controller and every method in it? This works, but feels horrible:

    namespace MyApi.Controllers
    {
    	[Produces("application/json")]
    	[Route("api/v{version:apiVersion}")]
    	public class BaseController : Controller
    	{
    		public string VersionNumber => GetRouteValue<string>(ControllerContext, "version");
    
    		protected static TValue GetRouteValue<TValue>(ControllerContext context, string name)
    		{
    			return (TValue)Convert.ChangeType(context.RouteData.Values[name], typeof(TValue));
    		}
    	}
    }
    
    namespace MyApi.Controllers
    {
        [ApiVersion("1.0")]
        public class ValuesController : BaseController
        {
    		[HttpGet("values", Name = "GetValuesV1.0")]
    		public IActionResult GetValues() => Ok(new string[] { "value 1", "value 2" });
    		
    		[HttpGet("values/{value}", Name = "GetValueV1.0")]
    		public IActionResult GetValue(string value) => Ok( value });
    	}
    }
    
    namespace MyApi.Controllers.V2_0
    {
        [ApiVersion("2.0")]
        public class ValuesController : BaseController
        {
    		[HttpGet("values", Name = "GetValuesV2.0")]
    		public IActionResult GetValues() => Ok(new string[] { "value 1", "value 2", "value 3" });

    		[HttpGet("values/{value}", Name = "GetValueV2.0")]
    		public IActionResult GetValue(string value) => Ok( value });
    	}
    }

This now works, but I've just duplicated code for no reason. In controllers with lots of code this just feels like code smell. Is there a workaround?

**Comment by commonsensesoftware** [comment]
Unfortunately, I think this is just an _implementation detail_ challenge. Your revised version would be what I recommend and is how I author services myself. I've seen people try to go down the route of inheritance, but that leads to its own set of problems; most notably, you can't _uninherit_ a method/action.

My suggestion and approach to addressing this problem is lifting as much logic out of controllers as possible. The controller is simply the thing bridging your business logic/code to HTTP, hopefully in a RESTful manner. Any logic in controllers should be specific to the wire protocol (e.g. HTTP). There are lots of ways to make common behaviors such as validation, etc generic by way of extension methods, base classes, etc. Keeping the route definitions completely separate is then very clean, albeit with some level of duplication. The duplication _feels_ inconvenient, until they actually need to diverge; that's when the benefit becomes clear.

Ultimately, there are many ways to tackle this problem. It will largely depend on your service taxonomy and architecture. Each _resource_ (e.g. _service_ ) should map to a single controller. The only place that should vary is something of a _parent-child_ relationship with _containment_; for example, _Order_ and _Line Item_. Changing API Versions often means just a different content/model type. You may be able to create base classes that support each action per resource and then expose the appropriate implementations as actions.

Many people tend to think in terms of the implementation code in controllers, which is often what leads them down the path of inheritance. This is the wrong way to think about the problem IMO. HTTP _is_ the API (e.g. _Uniform Interface_). The HTTP method _is_ the method name. HTTP has no concept of a _method override_. The inability to easily represent this in the implementation code is simply an impedance mismatch. More often that not, the differences between versions is just the content; therefore, customizing media type input/output formatters, etc are better approaches to facilitate this behavior.

A couple of other tips :bulb::
- If you want the current API Version, there are several ways to get it. In a controller action, the best way is declare the parameter `ApiVersion version` (or name of choice). There is a built-in, automatic model binder for this. You can also use the `GetRequestedApiVersion` extension method on **HttpContext** or request the **IApiVersioningFeature** from the registered context features.
- It looks like you're planning or considering to version by namespace. There's an out-of-the-box convention that can do this work for you. If this is of interest, have a look at the [Version By Namespace Convention](../wiki/API-Version-Conventions#version-by-namespace-convention) wiki topic and/or the [sample project](../tree/master/samples/aspnetcore/ByNamespaceSample). Using this approach, each controller derives its version from the containing namespace.
  -  I've seen this approach used as one possible method to isolate changes between versions. New versions are _Copied and Pasted_ into a new version folder and namespace.

I hope that helps give you some ideas.

**Comment by commonsensesoftware** [comment]
This thread has gone idle. Did these suggestions help drive you to a solution to the issue? Double-checking before I close it out.

**Comment by commonsensesoftware** [comment]
It would seem that this issue was resolved or you found another approach. If the suggestions didn't work for you, I'm happy to discuss other options. Thanks.
