### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Versioning.* 4.x is not compatible with netstandard2.1

### ISSUE THREAD

**Issue by CreepyGnome** [microsoft/aspnet-api-versioning#617]
This is a breaking change for people who were using Microsoft.AspNetCore.Mvc.Versioning.* 3.* which was netsteadard2.0.

Telling people to change their .NET Standard to a .NET Core library is not really acceptable without a really good reason why. None has been given.

Was this breaking change made by accident and you could just as easily build and deploy Microsoft.AspNetCore.Mvc.Versioning.* as .NET Standard or was it on purpose and no one documented it in the breaking changes migration documents?

I see no mention of breaking changes between 2.2 and 3.1 doc and this is a breaking change between migrating between those versions as we have to stop using .NET Standard for a lot of our supporting library which kind of defeats one of the purposes of .NET Standard.

https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1

**Comment by commonsensesoftware** [comment]
This is not a **breaking** change. To briefly reiterate the existing issue (#591), .NET Standard is not a target supported by ASP.NET Core 3.0+. You **cannot** correctly use ASP.NET Core 3.0+ libraries while targeting .NET Standard. ASP.NET Core 3.0+ can, however, **consume** external .NET Standard libraries. API Versioning directly references ASP.NET Core libraries, therefore, the **only** target framework it can support are the those matched by ASP.NET Core itself.

The confusion came from multi-target support for OData because there was no support for it on .NET Core 3.0. The choices were to leave OData behind or multi-target. I chose to multi-target because I know what had to be done, but I'm starting to wish I left it behind until it caught up. The target for OData is ASP.NET Core 2.2, which **does** support .NET Standard. Once OData had a suitable version on ASP.NET Core 3.0+, and hence .NET Core 3.0+, it no longer made since to multi-target so it was dropped. I have no intention, capacity, nor do I believe there are any community expectations that a single package version will support ASP.NET 2.2 and 3.0+ long-term and at the same time.

If you are trying to target .NET Standard, but you use ASP.NET Core 3.0+ libraries, including API Versioning, I don't know how to more politely say that you were doing it wrong. It's simply not supported. The reason you likely _thought_ it was working is that NuGet resolved the wrong TFM reference. Depending on what your code does, there's a very real chance that a consumer of your package/library will encounter a nasty runtime error such as **MissingMethodException**.

I've gone through great lengths to explain this to library authors. Please refer to #591. If that's still unclear to you, I'll elaborate further. Apologies for the confusion. Thanks.

**Comment by CreepyGnome** [comment]
It actually was working 100% as the .NET Standard 2.0 library that was referencing these and being consumed by ASP.NET 2.2 projects. Its a breaking change because well it broke the build when upgrading because you took a target away and didn't list it as a breaking change in the official migration documents.  Talking about it in issues is not really the same as the official migration documents posted on docs.microsoft.com.

Therefore if people "were doing it wrong" its because Microsoft was "doing it wrong" then as well and the wrong way was working just fine.  So if it is working production code its not really wrong code.  

This is the VERSIONING libraries, not the primary ASP.NET libraries. This is a supporting library I don't really see why it could not be .NET Standard 2.1.  

**It is what it is**, and it just would be nice if it was in the several official migration documents for going from ASP.NET Core 2.x to ASP.NET Core 3.x they are very useful and the first place most of us look when something breaks during migration to find the replacement, or that is not needed anymore, or the new way of doing it.

**Comment by commonsensesoftware** [comment]
Apologies if it sounded _snooty_. It was a rather heated debate in the past. Let me try to provide some additional guidance / clarification.

I agree that the documentation is not entirely clear on the migration (I reviewed it). Unfortunately, I don't own or have any engagement with those folks. It looks like the only thing they discuss on the topic is _source code_ changes. When the documentation says _breaking changes_, they are referring to changes in the APIs, not the target frameworks.

Maybe an illustration will help. Here's why API Versioning cannot use .NET Standard in ASP.NET 3.0+:

`Microsoft.AspNetCore.Mvc.Versioning → Microsoft.AspNetCore.Mvc.Core → .NET Core 3.0`

However, in 2.2 it looked like:

`Microsoft.AspNetCore.Mvc.Versioning → Microsoft.AspNetCore.Mvc.Core → .NET Standard 2.0`

To summarize:

| Source TFM | Target TFM | Compatibility |
| ------------- | ------------ | --------------- |
| netstandard2.0 | netcoreapp3.0 | Valid |
| netcoreapp3.0 | netstandard2.0 | Invalid |

Since ASP.NET Core 3.0 **only** targets .NET Core 3.0, then that's the only target API Versioning can offer as well. There's no way for it to go backward to .NET Standard 2.0 or 2.1.

I honestly never had the intention of supporting ASP.NET 2.2 after the API Versioning 4.0 release. The only reason it existed was for OData. I was constantly getting pushed by the community to support .NET Core 3.0. I knew there'd still be some ASP.NET 2.2 users, but it didn't really occur to me that so many would want to try and upgrade. That's certainly a failure of communication on my part and I'll own that.

My guidance to you if you need ASP.NET Core 2.2 and .NET Standard 2.0 support is to _clip off_ API Versioning at `4.0.0`. The **only** difference between `4.0.0` and `4.1.0` is the transition from .NET Core 3.0 to .NET Core 3.1, which has no bearing on the ASP.NET Core 2.2 build.

At least one other person has asked, but I do **not** _intend_ to go back and reverse integrate features or fixes that target ASP.NET 2.2. That doesn't mean I won't though. While rare, I have gone back and fixed bugs in older versions. I run this repo by myself and I just don't have to the capacity to support maintaining both versions of ASP.NET.

I hope that helps clear things up. I'm happy to help provide additional guidance or recommendations if you need them.

Thanks
