### ISSUE TITLE
MapToApiVersionAndAbove?

### ISSUE THREAD

**Issue by jez9999** [microsoft/aspnet-api-versioning#624]
The way I'm versioning my controllers, when I change an endpoint somewhere I'm incrementing my API version and using MapToApiVersion to point the old and new endpoints to the old and new versions.  However, if I increment the version again for another endpoint, my endpoints with MapToApiVersion are both lost to the new version.  What I really want is to say "map to API version X and above".  Is there a way to do this?  If not, could an attribute be introduced for it?

**Comment by commonsensesoftware** [comment]
The issue is _"... and above"_. An API Version can support comparison, but there is not a sensible way to support increment and decrement. There are other challenges too, such as deprecation. If an API is supposed to be deprecated, how do you keep it from continuing to increment? Ultimately, API versions need to be discrete in order for things to work. There are reasonable ways to configure or customize your particular application, but it's specific to your application.

There have been many discussions about _ranges_ in the past. There are ways to implement them, but it's only an implementation convenience. In the end, API versions are and must still be a discrete range of know values. There are many older issues that talk about this in more details with a few proposals about how it could be implemented. The most recent and probably most comprehensive is #458.

I would start with that. If that doesn't work or you have additional questions, I can help you flush out your particular scenario. There's definitely a way through attributes, conventions, or a combination of both to achieve your goals.

**Comment by commonsensesoftware** [comment]
This is due to a systemic gap. There is no direct dependency between API Versioning and a Swagger/OpenAPI generator (ex: Swashbuckle, NSwag, etc). They all rely on the API Explorer API, which - unfortunately - expresses no concept of _deprecated_. Without this, there isn't really away to bridge the two automatically.

The sample project [shows](../blob/master/samples/aspnetcore/SwaggerSample/SwaggerDefaultValues.cs#L25) how this is bridged in Swashbuckle with a custom **IOperationFilter**. At some future state, it would nice to have this as a first-class concept in the API Explorer or a common hook in OpenAPI document generators.

You didn't say, but I'm assuming you're probably using Swashbuckle or maybe NSwag (they have the same roots). Those generators have built-in logic to generate a deprecated API if they detect the presence of the **ObsoleteAttribute** on the **ApiDescription**. This is outside of the purview of API Versioning, which is why `HasDeprecatedApiVersion()` doesn't do anything. It's also worth mentioning that API Versioning doesn't care about implementation methods for deprecation. API versions are independent metadata that you can associate with code. The API version itself is the thing that can become deprecated (or obsolete), not the method. Without API Versioning, however, there isn't really another way to express this, which is why `[Obsolete]` is supported.

I hope that helps.

**Comment by jez9999** [comment]
Excellent; I added a similar filter and now it's showing correctly.  Thanks.

**Comment by commonsensesoftware** [comment]
It seems this issue has been resolved. Good question. Thanks.
