### ISSUE TITLE
ASP.NET Core SignalR hub versioning?

### ISSUE THREAD

**Issue by lnaie** [microsoft/aspnet-api-versioning#626]
Hi,

Is the ASP.NET Core SignalR hub versioning supported and, if so, how would that work?

Thanks

**Comment by commonsensesoftware** [comment]
Versioning a hub is not supported out-of-the-box, but it _could_ be made to work. To version an actual hub, you'd have to do one of the following:

- Change the client/server negotiation process to _somehow_ include version information
   - On the server side, this also requires selecting an appropriate hub based on the version
- Add/update a hub method to accept a version (ex: `client.subscribe('2.0')`)
- Version messages

The simplest appropriate is to version the message exchanged. This approach doesn't require changing any infrastructure or existing APIs. This could manifest in a number of ways, but clients would need to indicate that on each message exchange so the server knows how to handle it.

API versioning is about versioning HTTP "APIs". A HTTP APIs that is also RESTful would achieve this using _media type negotiation_ (although the query string is a pragmatic alternative). Web sockets, on the other hand, are raw binary protocols that only the authors fully understand. Versioning messages is common in many message exchange/passing systems. Adapting that to a web socket, and hence SignalR, need not require more than a version in each message.

I suppose it _might_ be possible to graph versioning semantics onto a hub, select a hub, and dispatch to a specific hub method. No one has asked for that before. If there was enough interest, it could warrant investigation into its feasibility as a new extension library.

**Comment by lnaie** [comment]
Good points. Thanks!
It could be done, but maybe it would be merely enough to have the version management done in a different way. Say to support a mobile app, the old backend version won't be useful anyway because the app user could be forced to upgrade to the new version.

**Comment by commonsensesoftware** [comment]
Correct. If you're trying to deal with this in a _real_ situation, this is much like the transition versioned HTTP APIs. In order to avoid a redeploy/upgrade, the server would have to treat the initial _unversioned_ implementation as _v1.0_ and newer clients would need to use explicit versioning. The original implementation has _some_ kind of logical version, it just wasn't baked into the semantics.

This is the case that `options.AssumeDefaultVersionWhenUnspecified = true` is _supposed_ to solve, even though some people are using it for other purposes.

I hope that helps.

**Comment by commonsensesoftware** [comment]
Interesting question, but I believe it's been driven to it's logical conclusion. This might be a some future-state extension. Thanks.
