### ISSUE TITLE
Question: HttpContext in controllers handling batch requests

### ISSUE THREAD

**Issue by geredwards** [microsoft/aspnet-api-versioning#633]
Hi,

I'm using batching and versioning, and have followed the advice given on the wiki page about the startup configurations (note this is a .net Core 3.1 app)
https://github.com/microsoft/aspnet-api-versioning/wiki/OData-Batching
I also call AspnetcoreHttpContext.SetContextAccessor to set up the HttpContext accessor.

The batch handler and the controllers have a HttpContext property set, but if I use the main context accessor, it returns NULL. Code called by the controller needs the security token passed in which is accessible in the context - and I don't really want to be either
- propagating HttpContext down the call stack
- creating statics 

Any thoughts on what's happening here, and how I can get the HttpContextAccessor to actually return the call's HttpContext?

**Comment by commonsensesoftware** [comment]
There's something very amiss in how things must be setup. It _sounds_ you're saying the `ControllerBase.HttpContext` is returning `null` in your controller. This _should_ be impossible. The only way I can see that happening is if you have replaced or otherwise changed how controllers are _activated_. The infrastructure sets this up for every action, for every request.

The **IHttpContextAccessor** is meant to be used in scenarios where the related **HttpContext** isn't available (e.g. outside of a controller or middleware). Do **not** use `static`. That simply will not work - **ever**. The **HttpContext** has _per request_ lifetime semantics, which cannot be modeled with `static`. You could synchronize access to it, but it will tank your performance. The more requests and access to the context you need, the worse it will become.

If you're sure everything else is correct, then this _might_ be a bug in the OData batching middleware. It creates a new **HttpContext** for each batch item. This makes sense since the context cannot be shared and there is effectively a bunch of parallel requests. `ControllerBase.HttpContext` should not be `null`, but any use of **IHttpContextAccessor** might be. It has to be explicitly set and I don't see the OData code doing that.

If this is the scenario you find yourself in, you can certainly file an issue on the OData repo, but it will probably take a while to get resolved. You should be able to mitigate it yourself with the world's simplest middleware which explicitly sets things up directly after the OData batching middleware.

>Despite having _middleware_, API Versioning doesn't _really_ have middleware. The **only** thing the middleware does is register the **IApiVersioningFeature**. This could have been done differently, but I chose that path in case something else was ever needed in the pipeline (which happened in the 1.0 days).

I hope that helps

**Comment by geredwards** [comment]
Thanks for the comments - maybe I should have explained it a bit better!
Definitely avoiding statics :-) and dug a bit deeper into what's going on...

ControllerBase.HttpContext isn't null - the issue is around the value of IHttpContextAccessor.HttpContext.

IHttpContextAccessor.HttpContext is **null** during a batch call, but weirdly, it's **not null** for non-batch calls (so OData is setting it correctly for that scenario). 
So I'm getting inconsistent behaviour depending on whether it ends up in a controller method via a batch call or not.
I can see why it might want to create new contexts for each of the individual batches, but just got some queries though:
- What's the reason of creating new HttpContexts for each parallel call?
- How much of the original batch HttpContext is propagated into the new contexts? What's lost?

Am I right in thinking that these multiple contexts makes IHttpContextAccessor.HttpContext incompatible with the use of any batch endpoint? 
I know it comes with plenty of health warnings, and looks like this could be another one!

Thanks!

**Comment by commonsensesoftware** [comment]
In non-batch scenarios, it's being intrinsically handled by ASP.NET Core so it does the _right_ thing. Batching is purely OData and the core infrastructure knows nothing about it. I'm not 100% sure exactly what assigns the current context to **IHttpContextAccessor**, but it shouldn't be that hard to find the ASP.NET Core code.

**HttpContext** has a _per request_ lifetime, but a batch is logically representing multiple requests; therefore, there must be multiple contexts. Any sharing of context will lead to the wrong results. I could list of a bunch of them, but consider just versioning. The versioning data is stored in the **IApiVersionFeature** in a context. If the batch contains requests for `GET order/123?api-version=1.0` and `GET customer/456?api-version=2.0` one of them will fail or produce the wrong result because they'd map to the same context and features. `1 Incoming Request == 1 Context`. In fact, if you look at the OData source, you'll see that use a _Scatter / Gather_ design with each batch item and context. The final results are merged and sent as the response body of the original context.

You can see what OData is doing when it creates a new context [here](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs#L181). The service container _should_ be copied or cloned. This should mean you just need to add something like:

```c#
var accessor = originalContext.RequestServices.GetService<IHttpContextAccessor>();

if (accessor != null)
{
   accessor.HttpContext = newContext;
}
```

The default implementation of **IHttpContextAccessor** is backed by **AsyncLocal\<T\>**, which is the replacement for **LogicalCallContext**. This means the underlying value _follows_ the logical call flow from this point forward, including across async boundaries.

I hope that makes sense

**Comment by geredwards** [comment]
It's making a **lot** more sense now, yes! Thankyou :-)
I understand what the code you suggest does and how it would work - but what I can't work out is where to put it... Sorry!

There aren't many places in the code which have access to both the originalContext and the new context - the only one I can see is my custom batch handler. Probably in an override of ParseBatchRequestsAsync? That gets passed in the original context, and returns the collection of request items (with their own contexts). But it still doesn't sound like the right place.

If a new batch handler was created for each request, then I could potentially grab the original context, and do something with it in one of the Execute... methods. But that appears to be a singleton (passed to routeBuilder.MapVersionedODataRoutes), so that doesn't seem possible either....
THANKS!

**Comment by commonsensesoftware** [comment]
Sorry for the lapse in follow up. Did you ever get this working?

In reviewing this, there's some additional information I can share and elaborate on. The original **HttpContext** belongs to the batch handler. It **cannot** be share or forwarded on to child requests. This is beyond implementation, it simply is not possible or supported. When the batch handler executes child requests, it creates a new **HttpContext** per request. The **HttpContext** has a 1:1 relationship to **HttpRequest** and **HttpResponse**. [Here](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs#L181) is where OData creates the child **HttpContext**.

One of the problems with OData approach is that there is no way to clone the features and dependency container of the parent context. This is somewhat of a known issue. I've reached to the ASP.NET team about this behavior in the past to support batching. There are some complex edge cases, which is why it's not supported in ASP.NET Core like it was in Web API (even without OData). While that are some ways you can _make_ things work, none are complete or generic. Their recommendation was to use HTTP/2+ and abandon batching. Their assertion is that it is unnecessary.

OData does provide a method of batching, just know that it comes with some limitations. If you need **IHttpContextAccessor**, you'll probably have to setup up somewhere in a custom batch handler prior to executing each child request. If you need something from the parent, then you'll probably have to copy it down.

I hope that's useful.

**Comment by geredwards** [comment]
Based on the info you gave last time, I did get it working, so thanks for it...
I basically derived my own class from DefaultODataBatchHandler, then modified some of the library implementation.

Change 1:
Added a new dictionary
Dictionary<Guid, HttpContext> batchContexts = new Dictionary<Guid, HttpContext>();

Change 2:
Used framework code for ParseBatchRequestsAsync, but additionally got it to add each batch context to the dictionary keyed on batch id.

Change 3:
Implemented this method which retrieved the context accessor for each batch request
```
        private IHttpContextAccessor getContextAccessorForBatch(HttpRequest request)
        {
            IHttpContextAccessor accessor = null;
            Guid? batchId = request.ODataBatchFeature().BatchId;
            if (batchId.HasValue && batchContexts.ContainsKey(batchId.Value))
            {
                accessor = batchContexts[batchId.Value].RequestServices.GetService<IHttpContextAccessor>();
            }
            return accessor;
        }
```
Change 4
Override ExecuteRequestMessagesAsync, and when looping through each request, it sets the accessor's HttpContext to be the request Context. So something like:
```
   accessor = getContextAccessorForBatch(requestItem.Context.Request);
   accessor.HttpContext = request.Context;
```
So you then get the http context appearing when requested using IHttpContextAccessor.

I hope that makes sense anyway! :-)
Let me know if you see some fundamental flaws with it :-|

**Comment by commonsensesoftware** [comment]
This looks about like what you would need to solve it. Glad you go it working. Thanks.

**Comment by SoulKeeper7** [comment]
I think a more easier way would be just retrieve the context n the controller using ```(((System.Web.HttpContextWrapper) Request.Properties["MS_HttpContext"]).Request)```

**Comment by rmanish04** [comment]
@geredwards @commonsensesoftware do you folks think it is a good idea to merge these changes into DefaultODataBatchHandler itself? Or maybe provide a new implementation of ODataBatchHandler that ensures correct population of IHttpContextAccessor? 

I am running into the same issue now. I don't think it's sensible for everyone running into this issue to come up with their own custom handler implementations. Especially considering that the solution involves modifying a copy of a file that can and will change over time.

**Comment by yannolaf** [comment]
Same issue here. It would be great to have this problem solved by DefaultODataBatchHandler.

**Comment by commonsensesoftware** [comment]
@rmanish04 sorry for late reply, I guess I missed the comment after it was closed.

@rmanish04 , @yannolaf Making the experience better in OData is certainly an option, but you'd need to talk to the OData team and open an issue with them. I don't have much influence over the OData team. The ASP.NET team has made it pretty clear they are not interested or willing to invest into batching as a concept because the improvements in HTTP/2 and HTTP/3 supplant most of the original intent. It might be worth evaluating whether improved HTTP connections meet the same needs you wanted from batching. If so, then trying to make batching work may not be worth the headache. Personally, I've given up trying to use batching  and I don't have any regrets.
