### ISSUE TITLE
Route Issues with interleaved versions

### ISSUE THREAD

**Issue by aaronasmith** [microsoft/aspnet-api-versioning#635]
This code seems to match the top route when navigating to api/v3/MyRouteIssues/MyRelatedItems/13, but then returns a 404 because that regex doesn't match.  It should route to the bottom action GetMyRelatedItems.

```csharp
    [ApiVersion("2", Deprecated = true)]
    [ApiVersion("3")]
    [Route("api/v{version:apiVersion}/[controller]")]
    [Produces("application/json")]
    [ApiController]
    public class MyRouteIssuesController : ControllerBase {
        [HttpGet("{param1:regex(^[[0-9]]*$)}/{param2:int}", Order = 1), MapToApiVersion("3")]
        public ActionResult<string> GetMyItem(string param1, int param2) {
            return Ok(param1 + param2);
        }

        [HttpGet("MyRelatedItems/{param1:int}")]
        public ActionResult<IEnumerable<int>> GetMyRelatedItems(int param1) {
            return Ok(new[] { param1 });
        }
    }
```
This repo reproduces this problem:  https://github.com/aaronasmith/aspnetroutingissues

**Comment by pmeijer** [comment]
:+1:

**Comment by commonsensesoftware** [comment]
I've done a cursory examination of this. I can repro the issue. There are some peculiars with routing. Did you try and get this to work without versioning? I can't help, but think the same problem may exist. API Versioning doesn't change routing, it only adds a disambiguator for each action. A 404 response is indicating that no match was found, which is why you don't get 400 with an unmatched API version.

I tried switching the regex constraint to a simple string and, indeed, **GetMyItem** matched with the value `MyRelatedItems`. I've seen this type of issue with overlapping routes before. I also noticed an issue with your regex which allows zero matching numbers; this will not work. I would suggest simply using `\d+` instead. You have to match at least one character as empty segments are not allowed.

I can investigate further, but to be completely transparent, I believe there is a high probability that the issue is how the routes are resolved versus selecting the correct API version. If it's possible, I would consider reshaping your route templates so they do not overlap.

**Comment by aaronasmith** [comment]
I didn't try it without versioning, but I did get it working by changing it to:
```csharp
[HttpGet("MyRelatedItems/{param1:int}"), MapToApiVersion("2"), MapToApiVersion("3")]
```
This is the reason I thought it would have something to do with the versioning library.  I meant to mention that.

**Comment by aaronasmith** [comment]
I just left everything the same except the versioning and the routes work correctly, and like I said they work when set up as the above comment mentions as well.

**Comment by commonsensesoftware** [comment]
Seem like you have a functioning workaround - so that's good.

I tried removing API versioning from your repro and it seems things **do** behave as expected. This seems odd to me. The only think I can think of is that there are 2 ranked results and the wrong one is being selected. I'll have to dig into this a bit deeper.

**Comment by aaronasmith** [comment]
I'm not very familiar with this code base, but it seems like the issue could be coming up here:
https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionMatcherPolicy.cs#L134-L163

It will find 1 explicit match, invalidate all other matches and try to use it.  Though it's not a valid match because the regex doesn't match, so I could be wrong about that.

**Comment by commonsensesoftware** [comment]
I know it's been a while, but I'm finally circling back around to this. Did you ever come up with a solution? I looked at the link you provided again. This match would be fine because if the candidate doesn't match the requested API version, then it is invalid. There was another bug related to not checking `candidates.IsValidCandidate(i)`, but I don't know that would affect it - possibly.

I went through the repro again with the following changes and it works. I don't know if this is due to other change at this point, but you might want to try it:

```c#
[ApiVersion( "2", Deprecated = true )]
[ApiVersion( "3" )]
[Route( "api/v{version:apiVersion}/[controller]" )]
[Produces( "application/json" )]
[ApiController]
public class MyRouteIssuesController : ControllerBase
{
    // NOTE: the update in the regex. a path segment cannot be empty so it needs to match one or more numbers
    [HttpGet( "{param1:regex(^\\d+$)}/{param2:int}", Order = 1 ), MapToApiVersion( "3" )]
    public ActionResult<string> GetMyItem( string param1, int param2 ) => Ok( param1 + param2 );

    [HttpGet( "MyRelatedItems/{param1:int}" )]
    public ActionResult<IEnumerable<int>> GetMyRelatedItems( int param1 ) => Ok( new[] { param1 } );
}
```

### Results

| URL | Status Code |
| ---- | ------------- |
| `api/v2/MyRouteIssues/MyRelatedItems/42` | 200 |
| `api/v3/MyRouteIssues/MyRelatedItems/42` | 200 |
| `api/v3/MyRouteIssues/1/42` | 200 |
| `api/v2/MyRouteIssues/1/42` | 400 (Expected; unmapped/unsupported) |

I hope that helps

**Comment by aaronasmith** [comment]
Shouldn't the GetmyRelatedItems be in api version 3?  The issue is when trying to hit the bottom method, and your changes didn't fix that issue.  Trying to hit this endpoint still results in a 404:
`http://localhost:5000/api/v3/MyRouteIssues/MyRelatedItems/13`

**Comment by commonsensesoftware** [comment]
Maybe there is something amiss. I took your repro and, with the exception of the regex, I was able to get it working _as is_. I was able to get the sample URL you specified working.

From the example:
- **GetMyItem** = 3.0 (explicitly)
- **GetMyRelatedItems** = 2.0, 3.0 (implicitly)

Also ... looking at this one more time, `{param1}` defines an integer. Why bother with regex at all? Just make both parameters integer constraints. For example:

```c#
[HttpGet( "{param1:int}/{param2:int}" ), MapToApiVersion( "3" )]
    public ActionResult<string> GetMyItem( int param1, int param2 ) =>
        Ok( param1.ToString() + param2.ToString() )
```

`Order` shouldn't play a factor here.

Beyond that, everything else seems correct to me.

**Comment by commonsensesoftware** [comment]
I can echo back a repro if that helps. It's also worth mentioning from your previous comment that API Versioning will not make a candidate valid if it's already invalid. This could happen by the core routing system, for example, if a route constraint invalidates something due to a rejected route value.

**Comment by aaronasmith** [comment]
That might help. The route is not invalid though, as I said before when I removed api versioning it works like I expect.

**Comment by commonsensesoftware** [comment]
Attached is the [Basic Sample](https://github.com/microsoft/aspnet-api-versioning/files/5360243/BasicSample.zip) which also includes the controller with the required changes. I tested the URL `api/v3/MyRouteIssues/MyRelatedItems/13` you specified and it returns `[13]` (200 - OK) as expected. Hopefully, this will give you something to compare against your local copy to see what's different.

**Comment by aaronasmith** [comment]
Okay, has nothing to do with the regex.  Updating to 4.2.0 rc fixes it.

**Comment by aaronasmith** [comment]
This appears to be fixed in the upcoming releases, so I will close it.

**Comment by commonsensesoftware** [comment]
Interesting. It's probably something else that has changed. The only thing I can think of is related to candidate matching. There was another related issue that was fixed. Maybe that was it. Glad you have a working solution now. :) The official release will be within 2 weeks. I want to give folks a chance to try out things before the promotion to release. Quality should be on par with the official release. No other changes are anticipated. Thanks.
