### ISSUE TITLE
Violation of SemVer in Microsoft.AspNetCore.Mvc.Versioning: dropped support of .NET Standard 2.0 between versions 4.1.0 and 4.1.1

### ISSUE THREAD

**Issue by pranavkm** [microsoft/aspnet-api-versioning#638]
---
**Issue moved from dotnet/aspnetcore#22548**
- Please respond to @abatishchev.

---

_From @abatishchev on Thursday, June 4, 2020 6:57:17 PM_

### Describe the bug

See [Microsoft.AspNetCore.Mvc.Versioning version 4.1.1](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/4.1.1):

> Dependencies
    .NETCoreApp 3.1
        No dependencies.

See [Microsoft.AspNetCore.Mvc.Versioning version 4.1.0](https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Versioning/4.1.0):

> Dependencies
    .NETCoreApp 3.1
        No dependencies.
    .NETStandard 2.0
        Microsoft.AspNetCore.Mvc.Core (>= 2.2.0 && < 3.0.0)

### To Reproduce

1. Create library having ` <TargetFramework>netstandard2.1</TargetFramework>`
2. Install version 4.1.0
3. Attempt to update to 4.1.1

### Exceptions (if any)

>NU1202: Package Microsoft.AspNetCore.Mvc.Versioning 4.1.1 is not compatible with netstandard2.1 (.NETStandard,Version=v2.1). Package Microsoft.AspNetCore.Mvc.Versioning 4.1.1 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)

**Comment by commonsensesoftware** [comment]
Semantic Versioning does not imply adding or removing addition targets. A _violation_ is, therefore, subjective. I'm not sure what you are trying to achieve, but I suspect you may be trying to target .NET Standard 2.0+ with ASP.NET Core 3.0+. A number of other people have attempted to do this and also fell into the trap. **ASP.NET 3.0+ does not target .NET Standard**.

On the off-hand chance that you are trying to target ASP.NET Core 2.2, you should stick with `4.0.0`. The only difference in `4.1.0` is the move from .NET Core 3.0 to 3.1. The only difference in `4.1.1` removing .NET Standard which was only there for OData. The messaging could have been better in hindsight, but this was always the plan.

Issues #591 and #617 have a lot of context and explanation regarding this direction. I'm happy to provide additional guidance and direction in addressing your larger goals.

**Comment by commonsensesoftware** [comment]
We can split hairs on semantics. If you're targeting ASP.NET Core 2.2, then I understand your frustration. I was trying to support the OData flavors, but in hindsight that caused confusion for everyone else. I should have just left them behind until OData caught up.

If you're trying to target .NET Standard 2.0 for ASP.NET Core 3.0/3.1 (which you still haven't said), I'm sorry to say that you've been doing it wrong. You were already broken and this change simply brought to light a _schroedinbug_ (e.g. it never should have worked in the first place).

To date, the only people really complaining about this issue are library authors targeting .NET Standard and do not realize that ASP.NET Core only targets .NET Core 3.0/3.1 (but it can consume .NET Standard). This wasn't the case in ASP.NET Core 2.2. API Versioning directly consumes the ASP.NET Core libraries so it **must** use the same targets. There was a brief window of major version multi-targeting purely for OData because it didn't support .NET Core. Now that it does, there's no reason to keep it. There was never a plan, nor do I have the capacity, to support 2.2 and 3.0+ going forward. I'll address significant bugs 2.2 as appropriate.

If you can articulate your specific goals and/or challenges, I'm happy to help provide a path forward.

**Comment by abatishchev** [comment]
In my team actual applications (SF services) are targeting .NET Core 3.1 and just libraries are targeting .NET Standard 2.1. You may say there is no reason for that but I don't know, was this way before I joined. Probably was done to support services on both Core 2.2 and  3.1 for time being, maybe due to other reasons, including not enough understanding of the domain.

In most cases if worked fine. Until the case we're discussing here. Even as you say it shouldn't worked in the first place.

Again, I often see that major changes are made between minor versions. I'd like to ask you to pay attention to that aspect and consider the customer's perspective which can be different, have different assumptions and/or goals. Thanks!

(Please close the issue, I don't have permissions to do that, since it was moved)

**Comment by commonsensesoftware** [comment]
I try really hard to ensure I meet customer demands and expectations, but it can be tough running this alone. Of late I've been really tied up with other work responsibilities. The messaging on this change definitely was not well-communicated. Apologies, I own that.

As was hopefully explained in other issues (but maybe not), I think the issue may be conflated with an issue (perhaps even a bug) in the NuGet dependency resolver. For your services running with 2.2, it makes sense for the libraries to target .NET Standard. For services that target 3.1, this is not possible to do correctly. Yes, 3.1 can consume .NET Standard, but ASP.NET Core itself no longer supports that target. Since API Versioning is multi-targeting to solve the OData stop-gap, what's happening is NuGet is selecting the ASP.NET 2.2 target in your library because it targets .NET Standard 2.0. Starting in ASP.NET Core 3.0, you can no longer target .NET Standard or even reference a single package. You have to reference the entire ASP.NET platform as a _Framework Reference_. Enough of the API surface is similar that things _may_ compile and even _work_ at runtime, but it's coincidence. You're setting yourself up for the all so dangerous **MissingMethodException** or **TypeLoadException** at runtime.

This is easy to overlook and I'm willing to bet you can easily confirm that your libraries are referencing only the .NET Standard variant of API Versioning. In the strictest of sense, this not valid and _could_ lead to runtime failures. If you want a single package for both 2.2 and 3.1, then I would suggest that your libraries multi-target. Your library and package should target `netstandard2.0` and `4.0.0` of API Versioning for ASP.NET 2.2 services and `netcoreapp3.1` and `4.1.0`+ API Versioning for ASP.NET Core 3.1.

Again, apologies for all the confusion and mix-up. I wanted to make this cut over at `4.0.0`. I should have done things in reverse - dropped OData completely at `4.0.0` and added it back in at `4.1.1`.

Hopefully, this clarifies why .NET Standard target _should_ not work for .NET Core 3.1, even if it does by happenstance. I'll close out the issue, but if you have more questions (etc), feel free to ask them.
