### ISSUE TITLE
Change to Pascal case in OData result with AspNet Core 3.1 is not working as expected

### ISSUE THREAD

**Issue by rangasurendra** [microsoft/aspnet-api-versioning#639]
Tried following but didn't work.

`services`
            `.AddMvc(options => options.EnableEndpointRouting = false)`
            `.AddJsonOptions(j =>`
               ` {                   `
                   ` j.JsonSerializerOptions.PropertyNamingPolicy = null;`
               ` })`
            `.SetCompatibilityVersion(Latest);`

[Issue re-Created here](https://github.com/rangasurendra/aspnetcoreodataverionsample)

Update: Later find out this was due to OData versioning

`routeBuilder.MapVersionedODataRoutes("odata", "api", modelBuilder.GetEdmModels());`

once the above line change to below

`routeBuilder.MapODataServiceRoute("odata", "api", ModelConfiguration.GetEdmModel());`

Pascal case works fine. looks like this is something to deal with MapVersionedODataRoutes

**Comment by commonsensesoftware** [comment]
Many apologies for the insanely delayed response. I try hard to answer the simple and short answers as quickly as possible. This one slipped by. I must have misread it.

This is a really simple issue. The problem is **not** `MapODataServiceRoute` versus  `MapVersionedODataRoutes`. OData has its own JSON serialization/deserialization. This is why `AddJsonOptions` has no effect.

The **VersionedODataModelBuilder** is just a composition of other **ODataModelBuilder** instances per API version. However, which **ODataModelBuilder** do you want to use? Who knows? There is a default setting that matches 80/20 rule of what most people want.

Excerpt from [here](../blob/master/src/Common.OData/AspNet.OData/Builder/VersionedODataModelBuilder.cs#L25):

```c#
public partial class VersionedODataModelBuilder
{
    // Camel case is on by default
    public Func<ODataModelBuilder> ModelBuilderFactory { get; set; } =
        () => new ODataConventionModelBuilder().EnableLowerCamelCase();

    // ...
}
```

History proved that most people want _Camel Casing_ by default. This is the same behavior as ASP.NET Core itself. If you want _Pascal Casing_, all you need to do is update the factory property.

For example:

```c#
public void Configure( IApplicationBuilder app, VersionedODataModelBuilder modelBuilder )
{
    // EnableLowerCamelCase() is not called; the default behavior is Pascal case
    modelBuilder.ModelBuilderFactory = () => new ODataConventionModelBuilder();
}
```

That's it! With this simple change, you are off to the races. I hope that still helps.

Thanks

**Comment by rangasurendra** [comment]
Many thanks @commonsensesoftware taking your valuable time to answer the question, Thanks again!
