### ISSUE TITLE
HEAD requests result in 400 somewhat unexpectedly

### ISSUE THREAD

**Issue by colemickens** [Microsoft/aspnet-api-versioning#64]
First, thanks for the fast turn around (https://github.com/Microsoft/aspnet-api-versioning/pull/63). Had one more question pop up as a result of the quick testing I just did:

Should HEAD requests against an endpoint return 400s?

`curl -I` sends a HEAD request

```
curl -i localhost:9080/info?api-version=1
HTTP/1.1 200 OK
Date: Mon, 28 Nov 2016 22:09:58 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

{"hostname":"pixel"}
```

```
curl -I localhost:9080/info?api-version=1.0
HTTP/1.1 400 Bad Request
Date: Mon, 28 Nov 2016 22:10:12 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
```

**Comment by commonsensesoftware** [comment]
No problem.

Is a route mapped for ```HEAD```? There's no special handling for specific HTTP methods. All methods are treated like any other routes.  ```HEAD```, ```OPTIONS```, and the remaining (rather esoteric) methods _could_ be versioned. ```HEAD``` is supposed to basically do everything that ```GET``` would do without returning a body.  Although I agree that all such versioned requests would likely be the same, they _could_ be different.

The same could be said for ```OPTIONS```.  ```OPTIONS``` isn't expected to return a body, but the spec doesn't say that it can't.  There are definitely some interesting scenarios for that with respect to documentation. I talked a little bit about how you might implement that in the [version discovery](../wiki/Version-Discovery) wiki topic.

I'm not entirely sure if you expected to get 400 or not. It seems like you were not expecting that to happen. I'd have to see the setup to provide a better explanation. The most basic explanation is that if ```HEAD``` is not mapped for a particular API version, you'll get 400.  This because it _could_ match on some API version. This provides a slightly more meaningful response for scenarios where you enable or disable methods, like ```HEAD```, over time. This is a gray area since we could also return 404 or 405.  405 is probably the most appropriate and is the default, unversioned behavior, but it is a little misleading to clients.  It's not that a method is not allowed at all, it may just not be allowed for a particular API version.

This leads us back to the previous paragraph. You could imagine that ```OPTIONS /info?api-version=1.0``` might return ```Allow: GET, POST``` and ```OPTIONS /info?api-version=2.0``` might return ```Allow: GET, POST, HEAD```.

I can see how there might be some special cases for ```HEAD```, ```OPTIONS```, and perhaps other methods. I'm not exactly sure how those would materialize just yet, but I'm not opposed to improving the common usage patterns in these areas.

**Comment by colemickens** [comment]
Yeah, I guess [HttpGet] doesn't imply [HttpHead] which was my expectation (the HEAD request was including the version query string.). That would be an issue in Mvc anyway rather than here. I'm going to go ahead and close this.
