### ISSUE TITLE
Incorrect supported versions are reported

### ISSUE THREAD

**Issue by reduckted** [microsoft/aspnet-api-versioning#652]
When an ASP.NET Core controller contains multiple actions and each action specifies different specific versions, the `api-supported-versions` header lists the combined set of supported versions from all actions in the controller. I expected the supported API versions to only list the versions that are supported by the specific action that was invoked.

### Reproduction

```cs
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace VersionTest
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddApiVersioning(x => x.ReportApiVersions = true);
        }

        public void Configure(IApplicationBuilder app)
        {
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints => endpoints.MapControllers());
        }
    }

    [ApiController]
    [Route("api/v{version:apiVersion}/test")]
    public class TestController : ControllerBase
    {
        [HttpGet("a")]
        [ApiVersion("2")]
        public int Get2()
        {
            return 2;
        }

        [HttpGet("b")]
        [ApiVersion("3")]
        public int Get3()
        {
            return 3;
        }
    }
}
```

### Actual Behavior
```
> curl -D - 'http://localhost:5000/api/v2/test/a'
HTTP/1.1 200 OK
api-supported-versions: 2, 3

> curl -D - 'http://localhost:5000/api/v3/test/a'
HTTP/1.1 400 Bad Request
api-supported-versions: 2, 3

> curl -D - 'http://localhost:5000/api/v2/test/b'
HTTP/1.1 400 Bad Request
api-supported-versions: 2, 3

> curl -D - 'http://localhost:5000/api/v3/test/b'
HTTP/1.1 200 OK
api-supported-versions: 2, 3
```

As you can see, the version supported by each action is respected - a 200 response when the version is supported and a 400 response when the version is not supported, but in each case the `api-supported-versions` header lists the versions from all actions in the controller.

### Expected Behavior
```
> curl -D - 'http://localhost:5000/api/v2/test/a'
HTTP/1.1 200 OK
api-supported-versions: 2

> curl -D - 'http://localhost:5000/api/v3/test/a'
HTTP/1.1 400 Bad Request
api-supported-versions: 2

> curl -D - 'http://localhost:5000/api/v2/test/b'
HTTP/1.1 400 Bad Request
api-supported-versions: 3

> curl -D - 'http://localhost:5000/api/v3/test/b'
HTTP/1.1 200 OK
api-supported-versions: 3
```

### Workarounds

I don't know if this is safe for all scenarios, but with my specific setup I was able to fix this by removing the `ApiVersionCollator` from the services collection.

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();
    services.AddApiVersioning(x => x.ReportApiVersions = true);
    services.Remove(services.First(x => x.ImplementationType == typeof(ApiVersionCollator)));
}
```

From what I could understand, it groups the actions by controller, gets the combined set of supported versions from all of the actions in the controller, then applies all of those versions to each action in the controller. That seems like a strange thing to do when the action has explicitly defined the versions that it supports.

**Comment by commonsensesoftware** [comment]
This is the expected behavior.

Despite it not being _necessary,_ a controller is the anchor point for many things. For most cases, the controller and resource match up. In this scenario it would be `test`. Declaring API versions down to the action didn't become supported until much later and it comes with it's own set of challenges. The main reason that it was supported to was to enable version-neutral APIs on actions such as `DELETE`.

In theory, it would be sensical to group on the routes, but in practice that is much, much harder than you might think. For example, `api/test/{id}` and `api/test/{id:int}` are semantically equivalent, but they are not equal. This is a trite and simple comparison of the differences, but it only gets more wild from there. Grouping this way is complex and requires understanding of templates. What if the route parameter names _mean_ the same thing, but are different? What if the routes are convention-based? For this reason, _APIs_ are grouped on the controller name. This can always be extracted from the routing system.

There are always edges cases in reporting API versions and you've hit one of them. In this context, _supported_ means an API exists - in some form. _Deprecated_ means it exists, but it's going away. Similar challenges exist without additional paths in the URL. For example, perhaps `test` only supports `GET` and `POST`. Some of these issues can be solved with `OPTIONS` and return `Allow`. Others are better served with a more comprehensive API documentation such as Open API (Swagger).

Advertising APIs is meant to let clients who are monitoring these headers know when a new version is available or when an old version will be going away. It _can_ also be used to help support tooling. This was never meant to be complete API description feature as there is way more information required than what can be shoved into a couple of HTTP headers.

Your _workaround_ is **not** safe; at least, not if you expect for things to keep working. The proper way to change this behavior is to replace the **IReportApiVersions** service. This decides what and how the API versions are reported. The [DefaultApiVersionReporter.cs](../blob/master/src/Common/Versioning/DefaultApiVersionReporter.cs) will show you the default implementation. If you only want to show what's on a specific action, then you are looking for `ApiVersionModel.DeclaredApiVersions`. _Declared_ always corresponds to the API versions applied to a specific action. Note that if you split versions across types, this will only match the declared versions on the match of the action selector or route matching policy.

I hope that helps.

**Comment by reduckted** [comment]
Thanks for the detailed info. 😄 

I've got the behavior I was after by replacing the `IReportApiVersions` service as you suggested.

> This was never meant to be complete API description feature as there is way more information required than what can be shoved into a couple of HTTP headers.

Fair enough. I was thinking it would be most useful for when you receive a 400 response because of an invalid version. The response would indicate that the action isn't supported at the specified version and the header would indicate what version the action _is_ supported at. But if that's not what it was designed to do, then that's fair enough. 👍 

Thanks.
