### ISSUE TITLE
UnsupportedApiVersion returned for all calls with OData

### ISSUE THREAD

**Issue by cts2003258** [microsoft/aspnet-api-versioning#653]
This has been hard to troubleshoot for a long time. I have a service built on OData v4 (Microsoft.OData.Core 7.5, Microsoft.AspNet.OData.Versioning 3.0.0, and Microsoft.AspNet.WebApi.Versioning 3.0.0) and I set it up practically the same as the advanced odata sample. Everything works until I enabled API versioning.

I'm using url segment prefix for versioning and I'm calling config.MapVersionedODataRoutes and config.AddApiVersioning

And my controllers inherits from ODataController. Attributes on them are ApiVersion, ControllerName, and  ODataRoutePrefix; and I have a Get() method in the controller I wish would work which has ODataRoute, EnableQuery, and HttpGet.

I debugged through the controller selector code (part of the default behavior has been overwritten), and found that the controller was successfully found, and the Initialize() method of the OData controller has been called as well. I also noticed that the Apply method on the model configuration classes were called with ApiVersion = 1.0. But requests (https://localhost/prefix/v1.0/Controller) constantly fail with status code 405 "UnsupportedApiVersion" and message:
 `The requested resource with API version 'x.y' does not support HTTP method 'GET'` and inner message:
`No route providing a controller name with API version '1.0' was found to match HTTP method 'GET' and request URI`. 
This even happens on service document and metadata document as well.

One thing I don't know if is related is that my controllers and the startup class are in different assemblies. I had to move the MapVersionedODataRoutes to the controller's assembly to reach my current stage.

Any troubleshooting advice?

**Comment by cts2003258** [comment]
Ok, after more experiments I was able to see it working by moving the model configuration code to the controllers assembly as well. Is there a way to let it work without doing that?

**Comment by cts2003258** [comment]
Ok, I found out that for custom controller selector to work it should inherit the ApiVersionControllerSelector, and the ApiVersionModel property needs to be added into the custom http controller descriptors.

Still I'm wondering how it can work with model configurations and controllers being in different assemblies.

**Comment by commonsensesoftware** [comment]
You've gone deep into the bowels of the routing system. I'm not sure why you want to customize the **IHttpActionSelector**. That level of detail in the design is not documented because almost no one touches it. This is where all the _magic_ in API versioning happens. Specifically, the two services you cannot change unless you extend them are:

- **IHttpActionSelector**
- **IHttpControllerSelector**

These services are **always** replaced so if you're changing them, then you need to do it after `.AddApiVersioning()`. I'm a bit curious why you want to change these.

ASP.NET Web API _supports_ dependency injection, but doesn't provide anything out-of-the-box (which is different from ASP.NET Core). I can't think of anything that would prevent **IModelConfiguration** definitions from being used in other assemblies. The mere act of adding them to the **VersionedODataModelBuilder** should make them get picked up.

There are two parts to the **VersionedODataModelBuilder**. The first is enumerating all possible API versions for all OData controllers. The second part taskes the unioned set of all API versions and then passes to each one to a model configuration to build an **IEdmModel** per API version. You can see that in [VersionedODataModelBuilder.GetEdmModels()](../blob/master/src/Common.OData/AspNet.OData/Builder/VersionedODataModelBuilder.cs#L51). While no services are replaced, [VersionedODataModelBuilder.GetApiVersions()](../blob/master/src/Microsoft.AspNet.OData.Versioning/Builder/VersionedODataModelBuilder.cs#L44) uses a lot of services to do its job. If you've changed any of these, it could be affecting the results. You can see for yourself in the code, but for a quick glance, these services are used:

- **IAssembliesResolver**
- **IHttpControllerTypeResolver**
- **IHttpActionSelector**
- **IHttpControllerSelector**

The only thing that immediately comes to mind that could have broken this behavior is if you are trying to use a plug-in type model with load-on-demand semantics. Since you mentioned the controllers are in different assemblies it sounds like you might be doing something like that. If you are, you'll probably need a different solution from the built-in **VersionedODataModelBuilder**. It is extensible. At a minimum, you'll have to override `GetApiVersions()` which likely uses a separate **AppDomain** to do discovery. You haven't provided enough information to say for sure, but sounds like you might be in this arena.

I hope that helps clear a few things up and get you on the path to a working solution.

**Comment by cts2003258** [comment]
Thanks for the explanations @commonsensesoftware . It does clear things up!

So the reason I need custom controller selection is that part of my controller classes are generated dynamically at run time, and part of them are defined classes. For dynamic ones I want override SelectController to return a desired controller descriptor, and for the others I wish to just call base.SelectController.

I looked into the AddApiVersioning code and found it was ApiVersionControllerSelector that I needed to extend and now that part is mostly working. But the challenge now is how to insert ApiVersion attributes on these dynamic classes. I noticed that on 3.0.0, it could be easily solvesd by inserting a property into the descriptor, but for 2.3.0 it can't work. (I'm now using 2.3.0 and OData 7.2.0). 

And yes, for the cross assembly issue, I did find the code of relying on assembly resolver and controller type resolver for GetApiVersions in your code, so that's probably what I need to overwrite. But given it works when I move the model building and configuration to controller's assembly, I might just live with it for now.

**Comment by cts2003258** [comment]
Also, is there a way to apply some default OData route prefix when it's not specified on a controllers? Most of the time it's supposed to be the prefix of the controller name, and people tend to forget it.

**Comment by commonsensesoftware** [comment]
The term _prefix_ is a bit overloaded in OData, but this can be achieved using the `MapVersionedODataRoute` or `MapVersionedODataRoutes` extension methods (just like `MapODataServiceRoute`). If you mean relative to the controller using attributes, I believe `ODataRoutePrefixAttribute` is the only option. Beyond that you are relying completely on OData conventions.

**Comment by commonsensesoftware** [comment]
Checking in before I close out this issue. Did this resolve your issue?

**Comment by cts2003258** [comment]
@commonsensesoftware Yep, I have moved on with some workarounds and it's working pretty good.

Thank you!!
