### ISSUE TITLE
QueryStringApiVersionReader throws AmbiguousApiVersion error

### ISSUE THREAD

**Issue by alienwareone** [microsoft/aspnet-api-versioning#657]
I've attached a small test project:
https://github.com/alienwareone/EndpointRoutingApiVersioningBug

When I request the following url:
https://localhost:5001/api/values/getvalues?api-version=2.0

`{"error":{"code":"AmbiguousApiVersion","message":"The following API versions were requested: 2.0, b3. At most, only a single API version may be specified. Please update the intended API version and retry the request.","innerError":null}}`

This works:
https://localhost:5001/api/v2.0/values/getvalues

This seems very strange to me...

**Comment by commonsensesoftware** [comment]
Thanks for the repro, it's always helpful. I built the project and requested the URL that you specified, but it did **not** repro. I've never seen someone try to use all of the API version readers at once, but there's no reason that it can't work. The default implementations read **all** possible API versions from all sources. This response occurs if there are multiple read API versions with different values.

This prevents scenarios such as:

#### Wrong - Multiple query values
```http
GET /api/values?api-version=1.0&api-version=2.0 HTTP/1.1
Host: localhost:5001
```

#### Wrong - Different query and header values
```http
GET /api/values?api-version=1.0 HTTP/1.1
Host: localhost:5001
x-api-version: 2.0
```

#### OK - Same query and header values
```http
GET /api/values?api-version=2.0 HTTP/1.1
Host: localhost:5001
x-api-version: 2.0
```

I don't see anything where `b3` would come from. Things look OK and work for me. I requested the URL you specified, but I get these results in Postman:

#### Request
```http
GET /api/values/getvalues?api-version=2.0 HTTP/1.1
Host: localhost:5001
Cookie: XSRF-TOKEN=6c3fb0aa-4eab-4851-8233-179338399d6f
```

#### Response
```http
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8; v=2.0
api-supported-versions: 2.0
api-deprecated-versions: 1.0, 1.1

{"groupVersion":null,"majorVersion":2,"minorVersion":0,"status":null}
```

This should be the expected behavior. I'm not sure where things are going wrong on your side.

**Comment by alienwareone** [comment]
If I remove MediaTypeApiVersionReader it works :)

The problem was, that the Microsoft Edge sets this header:
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;**v=b3**;q=0.9

But thanks alot for your detailed answer! It's rare to find people of your caliber answering with this quality 👍 👍

**Comment by commonsensesoftware** [comment]
Good catch. There's generally not a way (or desire) to limit a specific API version by MIME type. Interesting that this parameter popped up in another media type. If you still want to support versioning by media type, you have options. `v` is the name of the default media type parameter, but you can change it in the **MediaTypeApiVersionReader** constructor. For anything more specific, you'd probably have to implement a custom **IApiVersionReader**, but that's not particular hard.

Glad you found a working solution. Thanks for the kudos. ;)

**Comment by commonsensesoftware** [comment]
It seems like this issue is resolved. Should it not be, we can re-open and drive it to conclusion. Thanks.
