### ISSUE TITLE
API Version Status with Letter 'v' in Middle will Not Resolve API Version

### ISSUE THREAD

**Issue by jeffolmstead** [microsoft/aspnet-api-versioning#659]
Summary: If you have an API Version 'Status' with the letter 'v' in it, the following error will be thrown:

```
{"error":{"code":"ApiVersionUnspecified","message":"An API version is required, but was not specified.","innerError":null}}
```

Repo: [Using .NET Core Basic Sample](https://github.com/microsoft/aspnet-api-versioning/tree/master/samples/aspnetcore/BasicSample).

1. Upon compiling and running, before any changes, this URL will resolve properly: http://localhost:1237/api/v1.0/HelloWorld
2. Modify "HelloWorldController" by changing "ApiVersion" attribute from "1.0" to "1.0-RC" - the updated URL still resolves properly: http://localhost:1237/api/v1.0-RC/HelloWorld
```
[ApiVersion( "1.0-RC" )]
```
3. Modify "HelloWorldController" by changing "ApiVersion" attribute from "1.0-RC" to "1.0-Inventory" (anything with a 'v' in middle of the name) - this will NOT resolve properly: http://localhost:1237/api/v1.0-Inventory/HelloWorld - you will get the error indicated at top of this Issue.
```
[ApiVersion( "1.0-Inventory" )]
```

Though I haven't checked in the code, I am guessing it is using the "v" in analyzing the API Version and trying to do a split operation on it (e.g. as it is often used to mean "version").

Note: I realize this isn't critical as it might be a fringe scenario, but it is a hard one to debug and figure out what is going on without going through source code and it would be nice if there is a way to resolve the issue.

**Comment by commonsensesoftware** [comment]
There is no _magic string_ parsing in API Versioning. While the `v` character is common in URLs, any assumption about it's location or meaning would be an epic fail. This is also why you must define it yourself in route templates and outside of the route constraint. The `v` is never part of the API version.

The real problem, unfortunately, turns out to be a limitation (more like a flaw IMHO) in the routing system. The issue is described in detail in #580. Ryan is the core mastermind behind the routing system, so his answers are authoritative.

The good news is that there are workarounds, but I don't think there is anything out-of-the-box API Versioning can do to directly solve this problem. If someone comes up with something, I'm happy to consider it. If you have questions about how to apply one of the workarounds, I can elaborate.

I chalk this up to yet another reason to not version by URL segment, beyond it being the least RESTful. If you still have an opportunity to choose another method, it might worth considering. All other methods of versioning would not require a workaround for this problem.

**Comment by jeffolmstead** [comment]
Thanks for swift response. Sorry I had missed #580 as that went through the issue very well. At the moment, I am afraid I need to utilize versioning by URL segment (will know more later this week) but will move away from it if possible. In the meantime, I will just drop the "v" in the URL segment:

Change from this:
```
[Route( "api/v{version:apiVersion}/[controller]" )]
```

To this:
```
[Route( "api/{version:apiVersion}/[controller]" )]
```

As that does take care of it and I don't need to carry the 'v' forward. Thanks again.
