### ISSUE TITLE
Strange behavior with versioned GET endpoint

### ISSUE THREAD

**Issue by afriedma** [microsoft/aspnet-api-versioning#665]
Hello,

I am using .net core 2.1.511.  Its a vanilla GET controller withe ApiVersion attribute.  It seems to sporadically work every other time I request data.  I either receive good json model or 405 error below

"error": {
        "code": "UnsupportedApiVersion",
        "message": "The HTTP resource that matches the request URI 'http://localhost:35958/v1/bar' with API version '1' does not support HTTP method ''."
    }

I apologize in advance for being a bit vague and happy to add more details if needed, but I am really hoping someone saw this behavior before and can respond right away.  The reason I am saying it, is the method in the error message is blank, as well as, that endpoint does work sporadically.

Thank you in advance.

**Comment by commonsensesoftware** [comment]
Which version of API Versioning are you using? If you're using .NET Core 2.1, that makes me think this is pretty old version. This _may_ have been a bug that's been fixed. I rarely backport bug fixes because I just don't have the capacity to maintain a ton of versions side-by-side, but occasionally I do; especially if someone is broken/blocked.

Are you able to share your controller setup? If you have a repro, that would be useful too.

**Comment by afriedma** [comment]
Thanks for reply,

I am using Microsoft.AspNetCore.Mvc.Versioning 3.0.6925.33178 .netstandard 2.0

Unfortunately its a private repo, but controller setup is pretty basic, see below

```
[Produces(ContentType.ApplicationJson)]
[Route("v{version:apiVersion}/[controller]")]
[ApiVersion("1.0")]
public class Bar{
     [HttpGet]
     [ProducesResponseType(typeof(IEnumerable<Bar>), (int)HttpStatusCode.OK)]
     public async Task<IActionResult> GetBar(){
     }


```
Hope this helps, thanks in advance.

**Comment by commonsensesoftware** [comment]
This looks ok and seems recent enough to have resolved any of the historical bugs. Things have definitely been largely stable since 3.0.

The curious thing is in the message:

>_"The HTTP resource that matches the request URI 'http://localhost:35958/v1/bar' with API version '1' does not support HTTP method ''."_

Notice that `''` indicates that there is no HTTP method. This would explain why you are getting 405. I'm not sure how this is possible. Do you have logging enabled? Is there any other additional details you're able to dig up?

**Comment by afriedma** [comment]
This is what I see in the logs, I did enable Debug

Each request seems to get logged twice with following
WebHost: Information: Request starting HTTP/1.1 http://localhost:35958/v1/bar
WebHost: Information: Request starting HTTP/1.1 http://localhost:35958/v1/bar
DefaultApiVersionRoutePolicy: Information: Request did not specify a service API version, but multiple candidate actions were found; however, none matched the selected default API version '1'. Candidate actions: Bar"
DefaultApiVersionRoutePolicy: Information: Request did not specify a service API version, but multiple candidate actions were found; however, none matched the selected default API version '1'. Candidate actions: Bar"

If you need me to enable other special logging I certainly can, just sent me what to add to config.

**Comment by commonsensesoftware** [comment]
Can you share your configuration; especially your middleware setup? If you're on .NET Core 2.1, then that means you're still using the (now) legacy routing system. I'm willing to bet the issue has something to do with middleware.

**Comment by afriedma** [comment]
You were correct and gave me a good hint, thank you so much.  I upgraded yhe project to Microsoft.AspNetCore.App to 2.1.22 which is the latest release for .netcore 2.1 and the issue went away.

Thanks again for prompt response and assistance.

**Comment by afriedma** [comment]
Hey @commonsensesoftware ,

I know I closed the issue, but it turns out, our run environment doesn't support 2.1.22, as high as I can go is 2.1.15.  But 2.1.15 still has that bug....

Any idea how I can find what was fixed between those versions.  I clues what I should look for in release notes?

Thanks in advance for your help.

**Comment by commonsensesoftware** [comment]
That's unfortunate. Can you share your middleware setup? If you have anything that does a retry on a failure, that _may_ be the culprit. In the old routing system (e.g. **IRouter**), API Versioning has to evaluate all candidates and make a decision at the end. In this older design, ASP.NET Core may call the **IActionSelector** multiple times. This is a problem for API Versioning because it cannot make a final decision when the action selector is called. A good repro for when this will happen is `api/values/{id}?api-version=1.0` versus `api/values/{id:int}?api-version=2.0`. Even though the routes are semantically equivalent, they are processed in different passes of the routing system. To address this, API Versioning it collects the candidates and makes a decision at the end. This information has some caching to improve performance on subsequent requests. The problem with middleware is that the action selector will **always** report that it didn't match on the first pass. The final decision is made by a _catch-all_ router at the end. If middleware gets in between this process, it can result in the wrong result. This is also how you can experience a weird scenario where the first request behaves differently from subsequent requests.

If you're doing retries, I would suggest removing that from the API routes. Retrying for a UI is fine, but APIs _shouldn't_ do that. You should be able to achieve that by mapping the middleware using `MapWhen` or something like that. It's been quite a while since I've seen this issue, but there's some solutions somewhere here in the history.

Let's start there.

**Comment by afriedma** [comment]
Our middleware config has a bunch of propriety calls, so I am kind of limited with that.

There is a resilience config, but even after commenting it out, bug is still there.

In the logs I see “start request” being called twice, can that be a suspect? Is there configuration for extra logging that can point me to the issue?  Is it possible to see the release notes between 2.1.15 and 2.1.22?

Sorry for being a bit sporadic, it’s just super frustrating.

Thanks again for your assistance.

**Comment by afriedma** [comment]
Also, do you think I can add a custom middleware that can retrieve the dropped verb from earlier in the pipeline, if it’s null or empty?

**Comment by commonsensesoftware** [comment]
Back in this version, the **IApiVersionSelector** implementation is essentially a fork of the default one. The logging should be on par with whatever is possible out-of-the-box. If you dial up the log level to Trace or Debug, you _should_ get some more information.

I'm not part of the ASP.NET team. You'll probably want head over to their repo for information or questions about release notes. I can't think of anything specific off the top of my head.

You might want to review some of the old issues matching `is:issue is:closed IRouter`. Specifically, I believe #221 and #257 are the most relevant in explaining everything in detail with possible workarounds, including some sample code.

Let me know if that doesn't help.

**Comment by commonsensesoftware** [comment]
It's possible. A lot of the issues with middleware are _when_ they run. The solution is likely all about getting the order correct.

**Comment by afriedma** [comment]
One thing I noticed while browsing the similar issues, people having trouble with using Factory instead of HttpClient.  My set up is similar, It’s a simple Mvc set up. With a bunch of AddScoped plus AddHttpClient configuration. Any of this rings the bell?
