### ISSUE TITLE
Endpoint without version

### ISSUE THREAD

**Issue by Lobosque** [microsoft/aspnet-api-versioning#680]
How do I implement an enpoint that is version agnostic? (eg `/foo/bar`).
Using `[ApiVersionNeutral]` Does not work, because you are actually implementing one endpoint for each version.
My API has v1 and v2, so If I try using `[ApiVersionNeutral]` on `/foo/bar` I get an error because the routes clashes. (It tries to implement that same route twice, for v1 and v2).

**Comment by commonsensesoftware** [comment]
Once you opt into API Versioning, there's no such thing. Everything has a version - explicit or implied. The closest is _version-neutral_, which includes all versions or no version at all. You can only define a single implementation for a neutral API. This is for somewhat obvious reasons. How else can you disambiguate implementations? 

You seem to have a versioned API that you are trying to make neutral. What exactly are you trying to achieve?

**Comment by commonsensesoftware** [comment]
Did this answer your question? Do you additional questions or context you can provide?

**Comment by Lobosque** [comment]
@commonsensesoftware so I cannot impliclitly map `v1` AND `v2` to `/foo/bar`?

**Comment by commonsensesoftware** [comment]
I suppose it depends on your definition. A controller/API mapped as _version-neutral_ via `[ApiVersionNeutral]` or `options.Controllers<FooController>().IsApiVersionNeutral()` will route all of the following:

- `foo/bar` - Maps to **FooController** with no API version specified; any lookup will yield `null`
- `foo/bar?api-verison=1.0` -  Maps to **FooController** with `1.0`
- `foo/bar?api-verison=2.0` -  Maps to **FooController** with `2.0`
- `foo/bar?api-verison=42.0` -  Maps to **FooController** with `42.0`, even though you have not defined it in another context

_Declaring_ and _mapping_ API versions are not the same thing. The metadata is the same, but the meaning is different. This is how `[MapToApiVersion("1.0")]` differs. It's been asked before and I can't remember if I ever supported it, but - in _theory_ - you should be able to use `[MapToApiVersion]` with `[ApiVersionNeutral]`. I _might_ not have supported it because the lack of a mapping would break the rules of neutrality (e.g. what happens if you can't dispatch to the action? it can't be 400 or 404).

If it works, it would look like this:

```c#
[ApiVersionNeutral]
[Route("[controller]")]
public class FooController : ControllerBase
{
    [HttpGet("bar")]
    [MapToApiVersion("1.0")]
    public IActionResult BarV1() => Ok();

    [HttpGet("bar")]
    [MapToApiVersion("2.0")]
    public IActionResult BarV2() => Ok();

    [HttpGet("bar")]
    public IActionResult Bar(ApiVersion version) => Ok();
}
```

If it's not supported, you can still do something similar with:

```c#
[ApiVersionNeutral]
[Route("[controller]")]
public class FooController : ControllerBase
{
    [HttpGet("bar")]
    public IActionResult Bar(ApiVersion version)
    {
        if (version = new ApiVersion(1,0))
        {
            return Ok(new { ver = version.ToString() });
        }
        else if (version = new ApiVersion(2,0))
        {
            return Ok(new { ver = version.ToString() });
        }

        return Ok(new { ver = "default impl" });
    }
}
```

What you **cannot** do is split things across multiple types. This is for, what should be, obvious reasons. While there _might_ be a valid edge case to implement something like this, it seems highly suspicious as a _code smell_. A controller/API that is version-neutral should not have a bunch of branching code by version. _"There can be only one."_

Some practical implementations for version-neutral would include things such as:

```c#
// a health endpoint that never changes across versions
// ~/ping
[ApiVersionNeutral]
[Route("[controller]")]
public class PingController : ControllerBase
{
   [HttpGet]
   public IActionResult Get() => Ok();
}

[ApiVersion("1.0")]
[Route("[controller]")]
public class ValuesController : ControllerBase
{
   [HttpGet("{id}")]
   public IActionResult Get(string id) => Ok();

   [HttpPost("{id}")]
   public IActionResult Post(string id, string value) =>
      CreatedAtAction(nameof(Get), new {id}, new {id,value});

   // deleting a value is consistent and idempotent regardless of version
   // DELETE ~/values/{id}
   [ApiVersionNeutral]
   [HttpDelete("{id}")]
   public IActionResult Delete(string id) => NoContent();
}

[ApiVersion("2.0")]
[Route("values")]
public class Values2Controller : ControllerBase
{
   [HttpGet("{id}")]
   public IActionResult Get(string id) => Ok();

   [HttpPost("{id}")]
   public IActionResult Post(string id, string value) =>
      CreatedAtAction(nameof(Get), new {id}, new {id,value});

   // all DELETE operations on /values are neutral and map to ValuesController.Delete
}
```

By _implicit_, you might mean _conventions_ which denote the API versions applied to a versioned controller/API. There are several ways that can be achieved and it is extensible. You can use attributes, the fluent conventions API, or create your own. The only other custom, out-of-the-box convention is implicitly versioning by the containing .NET namespace. There's examples in the wiki and issues on how to create custom conventions if this is what you are referring to. If you need additional input or explanation on how to implement them, should that be what you want, I can elaborate.

Hopefully, one of these answers your question.

**Comment by commonsensesoftware** [comment]
Based on the age and activity of this issue, I believe it has been resolved. If this didn't solve your problem or you have more questions, feel free to reopen the issue or create a new one.
