### ISSUE TITLE
Unified swagger.json across multiple versions?

### ISSUE THREAD

**Issue by venuselite** [microsoft/aspnet-api-versioning#699]
Dear all,

for my dotNetCore project, I need to implement a second API version and would love to use this nugget package.
It looks very promising and I like how swagger can display multiple versions.

However, one customer of my API uses the [openapi-generator-cli ](https://localhost:5001/api/v2/OrdersControllerV2) to automatically generate a client for the api. 
They have asked whether it would be possible to provide them with a unified swagger.json including all paths of all versions so that they can control which version they use per method.

I have been playing with the startup.cs and tried some things but did not succeed.
My plan was to use an environment variable to set whether one unified swagger.json or multiple should be created. 
That way I could set this value to generate the swagger.json for them and normally run it in my environment to have the beautiful multi environment swagger documentation and the unified one showing all paths of the application with among all versions.

Thank you for your help,
Philipp

**Comment by commonsensesoftware** [comment]
This isn't really possible. Open API (Swagger) documents have no concept of versioning or even grouping within a document. Every defined path in the document must be unique, which is impractical for most forms of versioning. Finally, even if you could combine everything into a single document, how would the generator understand how to separate things out? I'm not aware of any client code generator that supports parallel version generation or method overloads in a single client. Clients are typically bound a specific version so code generating for a specific version is the most appropriate behavior.

The only possible way I know that you _could_ make this work is if you version by URL segment. The works because the version in the path produces distinct paths. I highly discourage that because it's not RESTful (it violates the _Uniform Interface_ constraint). Should you attempt to take this path, I still suspect that client code generation would be strange or would not work at all. I'm not super familiar with how it would disambiguate things, but it has historically been a problem for code-generated proxies.

My recommendation for the cleanest, simplest solution is to use one document per version and generate one client per version. I suspect most clients will not be bound to more than one version at time. I can't imagine a single scenario where it would more than two, but perhaps some scenario exists.

**Comment by venuselite** [comment]
Thank you for this fast and very detailed response!
I will go with own clients per version!
