### ISSUE TITLE
SwaggerDefaultValues would throw an exception for GET methods with complex type parameters

### ISSUE THREAD

**Issue by pencho** [microsoft/aspnet-api-versioning#700]
Hello!

The following line throws 'Sequence contains no matching element' when the API method has a complex type parameter and the method verb is a GET:
https://github.com/microsoft/aspnet-api-versioning/blob/beed143f753dc0e5d4b6a1abcd27ff9873e9d0c6/samples/webapi/SwaggerODataWebApiSample/SwaggerDefaultValues.cs#L31
````csharp
public class Foo {
     public int Bar{get;set;}
}
public class FooController : ApiController{
    [HttpGet]
    public async Task<IHttpActionResult> Get(Foo foo) {
        return Task.FromResult(new Foo());
    }
}
````
I have seen a few issues regarding handling of complex parameters on GET methods, however, I cannot find anything which references this particular class. 

Any thoughts on how I can work around this without changing SwaggerDefaultValues?

**Comment by commonsensesoftware** [comment]
Sorry for the **long** overdue response. `GET` operations that take a parameter is a bit strange, but possible and allowed. The only realistic scenario I've see for this is a serialized, complex object via multiple query parameters. I'm not sure that's the case here.

Regardless, it's entirely possible that Swashbuckle is ignoring the parameters here or doing something else. I would never _expect_ a scenario where the two don't jive, but maybe. If you just change `First` to `FirstOrDefault`, I think that solves your problem - for good. :)

**Comment by commonsensesoftware** [comment]
Given the idle time on this thread, I presume the suggestion worked or you found another alternative. The **SwaggerDefaultValues** class is just an example that by no means tries to handle all scenarios. It's entirely possible that it was not setup to handle this case. The sugguestion, or something close to it, _should_ have allowed you to work around the problem. If this issue is still a problem, I'm happy to reopen this and discuss it further.
