### ISSUE TITLE
Cleaner minor versioning 

### ISSUE THREAD

**Issue by Duranom** [Microsoft/aspnet-api-versioning#71]
I was wondering if a more cleaner approach for minor versioning should/will be included, because if you want to add/remove several actions to a minor version of a controller for you have to clutter up the controller with attributes and the more minor version introduce the harder it gets to maintain it. 

For example, lets say there is a ValuesController that has in version 2 only 1 action but has been expanded in minor versions.

```
[ApiVersion("2")]
[Route("api/[controller]")]
public class ValuesController : ApiController
{
 // introduced at version 2.0
[HttpGet]
 public IEnumerable<string> Get() =>  new[]{ "value1", "value2", "value3"};

 // introduced at version 2.1
[HttpGet]
 [Route("{category}")]
 public IEnumerable<string> Get(string category) => new[]{ "value2", "value3"};

 // introduced at version 2.1, dropped at version 2.2
[HttpGet]
 [Route("{category}/{subcategory}/{id}")]
 public IEnumerable<string> Get(string category, string subcategory, int id) => new[]{"value3"};
}
 // introduced at version 2.2
[HttpGet]
 [Route("{category}/{subcategory}")]
 public IEnumerable<string> Get(string category, string subcategory) => new[]{"value3"};
}
```

Now the following goals are trying to be achieved:
- Version 2 should only be able to invoke Get()
- Version 2.1 should be able to invoke Get(), Get(category), Get(category, subcategory, id)
- Version 2.1 should be able to invoke Get(), Get(category), Get(category, subcategory) , but not anymore Get(category, subcategory, id)

Now to get this to work your controller will look as followed 
```
[ApiVersion("2"), ApiVersion("2.1"), ApiVersion("2.2")]
[Route("api/[controller]")]
public class ValuesController : ApiController
{
 // introduced at version 2.0
[HttpGet]
 public IEnumerable<string> Get() =>  new[]{ "value1", "value2", "value3"};

 // introduced at version 2.1
[HttpGet]
[MapToApiVersion("2.1"), MapToApiVersion("2.2")]
 [Route("{category}")]
 public IEnumerable<string> Get(string category) => new[]{ "value2", "value3"};

 // introduced at version 2.1, dropped at version 2.2
[HttpGet]
[MapToApiVersion("2.1")]
 [Route("{category}/{subcategory}/{id}")]
 public IEnumerable<string> Get(string category, string subcategory, int id) => new[]{"value3"};
}
 // introduced at version 2.2
[HttpGet]
[MapToApiVersion("2.2")]
 [Route("{category}/{subcategory}")]
 public IEnumerable<string> Get(string category, string subcategory) => new[]{"value3"};
}
```

While this works and is still clear to maintain with only a few minor versions, this becomes a hassle and polluted with a alot of attributes when you have a lot of minor versions or when it is combined with several major/minor versions in one controller. 
This is because you add an ApiVersion attribute to the controller for every minor version supported and you must add MapToApiVersion to the new actions and to any excisting MapToApiVersion unless you drop it. (Just image if you have a 2.12 and every version had an action or more added)

It would be nice if you only had to add the major ApiVersion attribute to the controller and for minor versions you only had to put an attribute at the actions when it was added/dropped/obsolete like for exampe with an attribute SinceApiVersion("2.1"), DroppedSinceVersion() or ObsoleteSinceVersion().

**Comment by commonsensesoftware** [comment]
This is one of the consequences of _API version interleaving_. The API versioning needs to be explicit in order to support a number of scenarios (ex: resolution, documentation, etc). I've considered ranges, semantic versions, and the likes in the past, but have never been able to come up with a solution that reliably works.

To satisfy  your scenario, there are a couple of options I can think of:
* Break your controllers into explicit types without interleaving. It's easier to understand and attribute.
* Use your own custom attributes. You can extend the built-in attributes or use your own that implement **IApiVersionProvider**.
* Use conventions. Shooting from the hip here, but you should be able build up the version conventions with your own logic using ranges (or whatever) and then apply them using the conventions API.

One of the simplest solutions would to be create a custom attribute that accepts multiple API versions. This doesn't exactly solve the problem, but it reduces the amount of attribution required. In the early, internal days, that's how things were designed, but I received quite a bit of feedback that it was better to have things more explicit in order to understand things.  This is similarly true when you avoid interleaving.  The only reason to support interleaving is to not add a whole bunch of work when there is a small change during a version increment.

I hope that helps. If you have some other ideas, I'm open to them.  I will say, that I've never figured out a way that ranges would ever reliably work.  From the service's perspective, it's really important to understand what version a client is asking for and make sure you support that exact version. Ranges sound good on the surface, but introduce an entire class of problems.

**Comment by commonsensesoftware** [comment]
Circling back on this for some final thoughts. This case, while not unique, is fairly limited in scope. That said, I don't think it makes sense to roll this in the core library at this time. However, the extensibility points enable you to light up this scenario.

Here's an example of how:

```c#
[AttributeUsage( AttributeTargets.Method, AllowMultiple = true, Inherited = false )]
public sealed class MapToApiVersionRangeAttribute : ApiVersionsBaseAttribute, IApiVersionProvider
{
    public MapToApiVersionRangeAttribute( string from, string to )
        : this( from, to, step: 1 ) { }

    public MapToApiVersionRangeAttribute( string from, string to, int step )
        : base( GenerateVersions( from, to, step ) ) { }

    static ApiVersion[] GenerateVersions( string fromValue, string toValue, int step )
    {
        var current = ApiVersion.Parse( fromValue );
        var to = ApiVersion.Parse( toValue );
        var versions = new List<ApiVersion>();

        while ( current <= to )
        {
            versions.Add( current );

            var major = current.MajorVersion;
            var minor = current.MinorVersion + step;

            // note: this can be by convention, configuration, or a property
            if ( minor > 10 )
            {
                major++;
            }

            current = new ApiVersion( major, minor );
        }
    
        return versions.ToArray(); 
    }

    bool IApiVersionProvider.AdvertiseOnly => false;

    bool IApiVersionProvider.Deprecated => false;
}
```

The usage becomes:

```c#
[HttpGet]
[MapToApiVersionRange( "1.0", "3.0" )]
public IEnumerable<string> Get() =>  new[]{ "value1", "value2", "value3"};
```

In practice, the observation has been that most service authors have a versioning support policy of _N-2_. Some authors might have larger ranges, but it's unlikely anyone would support more than 10 variants of a public facing contract simultaneous. Internally, things may change many, many more times than that though.

As a point of clarity to your suggestion. I assume that _Obsolete_ is equivalent to _Deprecated_. The _Dropped_ aspect is not required. The fact that no mapping exists tells the system it's dropped (e.g. gone).

Hopefully that gives you some ideas.

**Comment by Duranom** [comment]
Sorry for late, but we did something similar in those lines with ranges based on advice. The case should preferably not happen for most unless dealing with a lot of third parties and a rapid changing environment.

**Comment by commonsensesoftware** [comment]
Glad you got it working. :)
