### ISSUE TITLE
Add support for PUT and DELETE methods

### ISSUE THREAD

**Issue by olegkap** [Microsoft/aspnet-api-versioning#72]
Hi,

I am getting an error UnsupportedApiVersion

> "{
  "Error": {
    "Code": "UnsupportedApiVersion",
    "Message": "The HTTP resource that matches the request URI 'http://localhost:18030/api/v1/resource/1' does not support the API version '1'."
  }
}"<

GET and POST methods seems to be working fine.

I tried to search thru the samples available but didn't find any PUT examples.
Similar error occurs when trying DELETE method

Thanks,
Oleg

**Comment by commonsensesoftware** [comment]
Can you provide some additional context? It would seem that your route setup is not correct. API versioning does not change or get involved with routing.  Routing works the way it always has. All HTTP methods, including GET, POST, PUT, DELETE, HEAD, OPTIONS, and so on are supported. I'm not just the author, I'm also a consumer. I've used these types of routes in many projects, so I know they work with API versioning.  If you can provide a skeleton of what your controller looks like, I can help point you in the right direction.

**Comment by olegkap** [comment]
Hi Chris,

Thanks for looking into it.

Please take a look at this project: [https://dl.dropboxusercontent.com/u/35163912/WebApiVersionExample.zip](url)

I just created empty WebApi project with nothing but API versioning there.

If I issue 
http://localhost:17195/api/values?api-version=1.0
GET or POST requests, it works fine for version 1.0 or 2.0

but as soon as I try to use PUT or DELETE I get following error:
`{
  "Error": {
    "Code": "UnsupportedApiVersion",
    "Message": "The HTTP resource that matches the request URI 'http://localhost:17195/api/values?api-version=2.0' does not support the API version '2.0'."
  }
}`

Perhaps I do missing something in configuration or somewhere else.

Thanks,
Oleg

**Comment by commonsensesoftware** [comment]
I took your **ValuesController** and dumped it into a sample project that I whipped up earlier today.  It works as expected.  I did notice a couple of things.  First, it seems you're using an older version of ASP.NET Core libraries.  The issue could be within its routing. Maybe there was a fix or update.  You might try updating to a more recent version. I used **Microsoft.AspNetCore (1.0.3)**, **Microsoft.AspNetCore.Mvc (1.0.2)**.

At least for me, `DELETE` worked immediately without issue for both version 1.0 and 2.0.  `PUT` is a little trickier because there is no media type formatter defined for **text/plain** by default and the example model was just a primitive string. This will result in HTTP 415 being returned. I was able to get it to work with **application/json** if I formatted the body as:

```json
{"value":"Test"}
```

I can upload my sample project for you if it helps. I used VS2017 RC4 though. ;)

**Comment by olegkap** [comment]
Thanks for quick response.

I still use VS.NET 2015 but dont think it should matter.
I just updated all assemblies to use latest one, sorry didnt do it earlier, but getting same behavior and error message :(

I was using Postman to test it so also had to add application/json for PUT method.

If you don't mind to upload your working sample, I will appreciate it, this way it can give me point of reference.

Thanks,
Oleg

**Comment by commonsensesoftware** [comment]
Fortunately, I still have VS2015 installed. Loving VS2017 though. Sooooo glad **project.json** is gone. :)

Ok .. so I took your example in VS2015 and messed around with it for a bit. Best as I can tell, something did change in the references and implementation. It might very well have been some kind of bug or something in ASP.NET Core.  I updated the references to mirror what I had in the VS2017 version. I stripped out all the AppInsights and Logging stuff to simplify things. Feel free to add them back. I made **zero** changes to the code. I only updated the **project.json** like this:

```json
{
    "dependencies": {
        "Microsoft.AspNetCore": "1.0.3",
        "Microsoft.AspNetCore.Mvc": "1.0.2",
        "Microsoft.AspNetCore.Mvc.Versioning": "1.0.3"
    },

  "frameworks": {
    "net461": { }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

I've had issues simply updating the **project.json**.  To make sure _everything_ is purged and clean, I would recommend:

1. Update the **project.json** file
2. Close Visual Studio
3. Delete the **project.json.lock** file
4. Delete the hidden **.vs** folder
5. Delete **bin** and **obj**
6. Re-open the project in Visual Studio
7. Rebuild the solution

Doing all this worked for me. The following requests started succeeding:

* `DELETE http://localhost:1690/api/values/1?api-version=1.0`
* `DELETE http://localhost:1690/api/values/1?api-version=2.0`
* `PUT http://localhost:1690/api/values/1?api-version=1.0` with `{"value":"Test"}`
* `PUT http://localhost:1690/api/values/1?api-version=2.0` with `{"value":"Test"}`

Try that and let me know how it goes.

**Comment by olegkap** [comment]
Hi Chris,

Thanks for posting your config.

I finally manage to make demo version working, its strange since when I tried it couple days agao it didnt work.
I had to clean all cached assemblies since I suspect perhaps it used some old or different assembly.

Thanks again for your help.

Thanks,
Oleg

**Comment by orthimnas** [comment]
@commonsensesoftware I'm not sure about the latest version, but we were seeing some craziness where the parameter name of the controller method mattered.  Anything that started with a letter "j" through "z" failed.  Also, if two controller actions had the same variable name - a variable name other than "id" - routing would also fail.  It has been a couple of weeks since we looked at it, but we were able to work around it by changing how we configured it.

I think we traced it to a Microsoft internal MVC library that provided action descriptions, but if the latest version doesn't have that issue then perhaps something else was to blame. ¯\_(ツ)_/¯

**Comment by olegkap** [comment]
I think I tracked down what possibly an issue, in my case perhaps.

On top of multiple libraries I also use ValidateAntiForgeryToken attribute for those methods so after some cleaning and moving things around in my Startup I managed it to work (not sure why but last night I discovered DELETE doesnt work anymore but will figure it out).

So what happens when routing cannot find route for whatever reason, lets say if it has wrong validation token, it goes thru pipe and cannot find action method to execute, then ApiVersioning kicks in and reports that no correct version were found to execute even if the actual error is something else. Perhaps I am wrong there and missing something else but this is my impression so far.

Thanks,
Oleg

**Comment by commonsensesoftware** [comment]
The issue you are seeing is highly like related to a routing issue. It's hard to say for sure if you've configured things wrong or whether it was a bug in an older version of ASP.NET Core.

The API versioning library does not get involved with routing.  Routing works the same way as it always has. Before you added API versioning, if candidates matched the same route, then ASP.NET Core would return a 500 indicating that there are duplicate routes (e.g. a developer mistake). Once API versioning is added, otherwise duplicate routes can be disambiguated by API version. If the API versions are ambiguous, the default behavior is unchanged - 500.

There is one additional behavior. If at least one candidate route exists, but none of the candidates match the requested API version, then you'll get 400 with a message indicating that the API version is not supported.  If no candidate routes match, then you should get a 404; just like the default behavior.

It was a really important design point to keep out of the routing pipeline. Thus far, I haven't been able to repro the behavior. The only oddity I've noticed is the name of the controller type in some cases, but I think that issue was in Web API not ASP.NET Core. If you find something concrete though, I'm happy to take a look at it. I hope that helps clear things up.
