### ISSUE TITLE
Api Version Attribute Model

### ISSUE THREAD

**Issue by ddrdoubled** [microsoft/aspnet-api-versioning#722]
Hi,

currently something like this is not possible, am I right?

``` C#
public class Model 
{
   [ApiVersion("V1")]
   public string PropertyVersion1 { get; set; }

   [ApiVersion("V2")]
   public string PropertyVersion2 { get; set; }
}
```

I think it would make sense because otherwise I have to create new model classes for each version or using '[Obsolete]' for properties which does not support all scenarios, or am I missing anything already possible?

**Comment by commonsensesoftware** [comment]
Correct. This is not something supported today. The primary reason is that the default implementation of ASP.NET and Open API/Swagger generators use Reflection to discover and describe their APIs. What you are hoping to achieve is technically possible, but not something supported out-of-the-box. It's an interesting feature request and has been suggested before. I'm not opposed to such a feature if some one were to draft it up. It will likely take some time to get done, but I can see its usefulness.

This behavior is _sort of_ currently supported in OData. This is possible because OData defines a meta-model using the Entity Data Model (EDM). This _describes_ what the models look like over the wire; regardless, of how the type is defined in code. When combined with API Versioning, there is one EDM model per API version. While the setup is completely different, the net result is the same as what you are hoping to achieve; that is - only the properties defined by the meta-model are returned in the API. Open API/Swagger documents are more challenging because they rely entirely on the Reflection API. To address that, API Versioning for OData introduces the **IModelTypeBuilder**. This _service_ will inspect the reflected **Type** and make sure it is a `1:1` match to the EDM. If it is not, then the **IModelTypeBuilder** will _substitute_ that type by dynamically generating a non-executable runtime **Type** that matches what the EDM says. This has the benefit of defining a single data model and yielding different _shapes_ per API version. All of the OData versioning examples show this at work.

This would be something great to support outside the realm of OData, but it's quite a bit of work. Few people have asked for this, but - again - I'm not opposed to it.

**Comment by ddrdoubled** [comment]
Hi,
thx for this explanation, i would be happy to contribute, but i am bit unsure about how to tackle it. I have looked at the reflection based ModelMetaData Generators but the problem there is to bring the version in that scope. Also if you compare it to the way for example a [JsonIgnore] Attribute is dealt within Swagger/OpenAPI it probably is better dealt with on the Swashbuckle side then on Reflection based API Explorer, or what do you think? Maybe then it makes more sense to introduce an attribute in the Swashbuckle Annotations space, because the API Explorer is still fine returning all property meta data, or not?

**Comment by commonsensesoftware** [comment]
I have to warn you that this is a deep and complex rabbit hole, but if you're up for a challenge, I won't hold you back. A good place to start for both a foundation of what do, where to start, and what you're getting yourself into is to look at the [DefaultModelTypeBuilder.cs](../blob/master/src/Common.OData.ApiExplorer/AspNet.OData/DefaultModelTypeBuilder.cs). This is currently for OData, but it could refactored to work more generically. I wouldn't bother with trying to create one implementation to rule-them-all; that _may_ come later.

Trying to work around Reflection will be hard, so it's probably best to not try. It's fine to start with attributes for simplicity, but understand that API Versioning doesn't care about attributes; it only cares about **IApiVersionProvider**. Attributes just so happen to be **one** of the methods used to realize this.

There are fundamentally two scenarios that have to be covered:

### Scenario 1
When an **InputFormatter** or **OutputFormatter** sees a type, the infrastructure needs to _get in front_ of this. On the way in, properties that do not apply to the requested API version should be skipped. A substitution **cannot** occur here because this will be handed to the developers code for execution. The best that can be done is glue over the existing model. Honestly, this may require no work because **InputFormatter** implementations typically already implement the _Tolerant Reader_ pattern. On the way out, things are more complex. I'm unsure if the whole formatter has to be replaced, decorated, or what. Essentially, the formatter needs to skip properties that do not apply to the requested API version. Things start getting really complicated once you have complex hierarchies.

By the time any of these components are reached, a valid API version has been negotiated. You can always find out what that is through `HttpContext.GetRequestedApiVersion()` or `HttpContext.Features.Get<IApiVersioningFeature>().RequestedApiVersion`. They refer to the same thing. Note that in the case of something that is API _version-neutral_, it's possible that no API version is specified. This is the one and only case were the API version can be `null`. In this case, you'd short-circuit and make no modifications. Since nothing specific was asked for, you get everything.

### Scenario 2
The second scenario is for the API Explorer. This would be much closer to how things work for OData. Essentially, you would _visit_ the discovered **ApiDescription** and potentially _substitute_ in a surrogate type for input parameters, the body, and/or the response.

### All Cases
In all scenarios, you'd want some type of dictionary that hands caching and storing the generated models. This dictionary needs to be thread-safe given the nature of asynchronous requests. This shouldn't be too difficult, but you should be aware of it. Both the request pipeline and the API Explorer _should_ be able to share the same cache. That _might_ require the introduction of a new _service_.

**Comment by ddrdoubled** [comment]
Ok thank you very much. So if understood correctly and i also followed the code [DefaultModelTypeBuilder](https://github.com/microsoft/aspnet-api-versioning/blob/master/src/Common.OData.ApiExplorer/AspNet.OData/DefaultModelTypeBuilder.cs) you generate for OData runtime types to be able to use the reflection based approach. So obviously your opinion is and was that the reflection and type connection of the ApiExplorer is buried too deep to avoid it. 
I will try to do some tests without reflection but probably you are right and the first steps are relatively ok but the last will be very hard. But it will be an interesting exercise to see whether the intended abstractions in the ApiExplorer are able to cope with it to such an extent.

**Comment by commonsensesoftware** [comment]
The Reflection bit has more to do with how formatters and Open API/Swagger generators work. The API Explorer only provides the `ModelMetadata.ModelType` which is `System.Type`. Unless a full metadata model was created to describe it (e.g. EDM), there aren't really any alternatives. Code-generating a non-executable type provides enough information to describe things without breaking any APIs. Unfortunately, it's pretty complex to generate these things.

I'd take a peek at the related tests too. That will give you some good tips how what is/isn't covered already. You can also step through the code which may provide additional clarity.

**Comment by commonsensesoftware** [comment]
This issue was posed as a question, which has been answered; however, it led to a possible future feature enhancement. Should you put together something for a PR or just have more questions, feel free to ask them. If you'd like to flush out the design of a feature more thoroughly, it's probably better to start a new issue which is accordingly described that way.

The additional of _Source Generators_ to the compiler makes for an interesting and compelling approach to code generate different models at compile-time rather than run-time. That will provide the best performance and likely the simplest implementation. I would definitely support this idea if you decide to take it forward.

Thanks.
