### ISSUE TITLE
Metadata endpoint returns 404

### ISSUE THREAD

**Issue by martinussuherman** [microsoft/aspnet-api-versioning#726]
I have the repo [here](https://github.com/martinussuherman/odata-test). When I run it things are working good, except for the metadata endpoint (it returns 404). Could someone help me as what I've might missing in setup or something maybe I missed something else?

Regards,

Martinus

**Comment by commonsensesoftware** [comment]
Apologies for the delayed response.

You are using multiple variations of versioning. You _can_ do that, but I suggest just one if possible. I recommend versioning by query string.

The primary issue appears to be that you don't actually have any API versions. You've marked **all** of the controllers as API _version-neutral_. If you that, there's not really any point to API versioning. Every controller accepts any and all versions as if nothing was versioned.

Contrary to what you might believe, the `$metadata` endpoint is **not** _version-neutral_. It is versioned by convention using the aggregation of all known API versions. This endpoint requires an API version, but makes a special exception for the first defined version for backward compatability (similar to `ApiVersioningOptions.AssumeDefaultVersionWhenUnspecified`). An API version is required to make that work properly because it is correlated to a specific EDM. You've hit a known (by me), but intentionally unhandled edge case if there are no API versions. Only this scenario causes this behavior. I imagine the same thing will happen if there are no controllers (you _might_ get an empty EDMX, but it's equally nonsensical).

I suspect if you have at least one versioned controller, things will work.

**Comment by martinussuherman** [comment]
Thanks @commonsensesoftware for the explanation. I think you've clearly described what I'd need to do to make it works. 

Regards,

Martinus
