### ISSUE TITLE
Equivalent of passing ApiVersion to MapVersionedODataRoute

### ISSUE THREAD

**Issue by mikeobrien** [microsoft/aspnet-api-versioning#730]
I'm upgrading a service to core 3.1 and moving it to endpoint routing. Older versions had an overload of `MapVersionedODataRoute` that took an `ApiEndpoint` but that param has been removed. What would the equivalent of that be in the latest versions? Been looking though the docs and source but research-fu is failing me. :(

```
app.UseEndpoints(options =>
{
    ...
    var version = new ApiVersion(1, 0);
    options.MapVersionedODataRoute("odata", "v{version:apiVersion}", model, version); // <-- no bueno
});

**Comment by commonsensesoftware** [comment]
These overloads were intentionally removed in the latest version because they have a lot of underlying ceremony with little value-add. The typical reason that someone want to register a route this way is to have a subset of versions and/or EDM configuration for a particular route prefix combination. There was a parallel issue of it being difficult to _bucketize_ EDMs for a particular version and route prefix pairing. The new design solves both and supplants the old _one-off_ route registration.

To merge the models, `IModelConfiguration.Apply` now includes a `routePrefix` parameter. For each API version, the corresponding route prefix is also provided, if any. If you only have one route prefix and do not inspect this parameter, then the behavior is like that of the previous version.

A goal of the most recent changes was to have more aligned symmetry to `MapODataServiceRoute`. The key difference is between a single `IEdmModel` versus a sequence of them a la `IEnumerable<IEdmModel>`. Now that the `VersionedODataModelBuilder.GetEdmModels` accepts a `routePrefix` parameter, it might look like:

```c#
app.UseEndpoints(
    options => options.MapVersionedODataRoute(
        "odata",
        "v{version:apiVersion}",
        modelBuilder.GetEdmModels("v{version:apiVersion}") /* <-- filter by route prefix /* );
```

Of course, this is unnecessarily verbose, so there is an even more simplified overload:

```c#
app.UseEndpoints(options => options.MapVersionedODataRoute("odata", "v{version:apiVersion}", modelBuilder));
```

Hopefully that explains the _how_ and _why_ the change happened. It's also worth noting that the new design registers a single route where it was a route per API version before. This also simplifies a number of things.

Succinctly, I will say that it _is_ possible to define a route using a single API version the way it was before. It's a bit of a pain, so I won't explain it unless you _really_ want to go down that path. I made it a point to expose all of the extension hooks and configuration so that it's possible for you to do that (which OData itself typically does not do). To get a sense of what happens or what's involved, you need to look at:

- [IEndpointRouteBuilderExtensions.cs](../blob/master/src/Microsoft.AspNetCore.OData.Versioning/AspNet.OData/Extensions/IEndpointRouteBuilderExtensions.cs)
- [IContainerBuilderExtensions.cs](../blob/master/src/Microsoft.AspNetCore.OData.Versioning/OData/IContainerBuilderExtensions.cs)

Let me know if that resolves your issue.

**Comment by mikeobrien** [comment]
Wow, thx so much for the detailed explanation! I'm taking over this project (so don't know the original design rationale) and not used api versioning before so my main concern was not breaking anything upgrading to the latest version. 😉 I'll need to chew on this but I think this should be enough to get me going tho so I'll close. Thx again for such a thorough response!
