### ISSUE TITLE
Question: Is it possible to route to versioned endpoint delegates without any MVC controller?

### ISSUE THREAD

**Issue by markphillips100** [microsoft/aspnet-api-versioning#733]
Suppose I am only using AspNetCore Endpoint Routing **without** controllers, i.e. only RouteEndpoint instances with delegates, is it possible to use this package to route to the correct delegate using the incoming api version?

I realise the MVC ApplicationModel is used to determine routes and disambiguate where required but wondering if there's something that can be implemented by extension to support a scenario where the ApplicationModel isn't available and only RouteEndpoint with metadata.

A simplified setup below using url versioning (as an example but could use query, etc) where the 2 route templates are the same but have different ApiVersion metadata:

```
endpoints.MapGet("/api/v{version:apiVersion}/hello", async context =>
{
    await context.Response.WriteAsync("Hello World v1!");
}).WithMetadata(new ApiVersionAttribute("1.0"));

endpoints.MapGet("/api/v{version:apiVersion}/hello", async context =>
{
    await context.Response.WriteAsync("Hello World v2!");
}).WithMetadata(new ApiVersionAttribute("2.0"));
```

You could argue to just use explicit route templates and do away with the metadata and API versioning package, e.g. first template becomes "/api/v1/hello" second template becomes "/api/v2/hello", however that forces the use of url versioning to disambiguate the route paths so no chance of using a header or query string.  It also means no automatic nice api version reporting.

**Comment by commonsensesoftware** [comment]
Succinctly, I'll just say that this isn't supported out-of-the-box today. It _might_ be technically possible, but you'll almost certainly have to jump through a flaming hula hoop. ;)

But why...

It's not intrinsically obvious, but the issue really comes down to how you collate routes and their API versions. Most people think that the grouping is done on route template, but it is not. While that sounds logical and was my initial thought process why back when, it doesn't work without a lot of complexity. Consider that v1 had the route template `order/{id}` and v2 had the route template `order/{id:int}`. These are semantically equivalent route templates, but they are **not** the same.

Attempting to _understand_ or _interpret_ the route template (even with the typed parsing) is complex and slow. It would also eliminate a scenario where the entire route template changed between versions. Remember that REST states the path **is** the identifier of the resource, which is often overlooked. As a result, versioned are grouped by the name of the controller, which _should_ correspond the a specific resource; for example, _Order_, _Customer_, etc. The name then becomes something easy and straight forward to group on. This will have the form `<Name>Controller`. API Versioning also supports the convention of `<Name>[Number]Controller` (ex: `Order2Controller`) to facilitate side-by-side types. For any other scenario, the name can be defined using the **ControllerNameAttribute**. Ultimately, this name becomes the key that all related versions and routes are grouped on, regardless of route template.

Hopefully, that explains why simply mapping a route endpoint will not work out-of-the-box. There is no metadata or key to group the endpoint on. Honestly, a controller is _really_ necessary, but that is the most obvious and natural pivot point. Technically, if you were to add the relevant metadata to the endpoint, then it _should_ work. Honestly, I would expect it to work. If explore around in the tests, you will likely find a scenario where things are setup without using an actual controller. I don't have specific place to point to, but I know all of the bits necessary to set things up do exist in there - _somewhere_. Essentially, you just need to manually create the appropriate **ApiVersionModel**, **ControllerModel**, **ActionModel**, and associate it with the endpoint. You'll need at least the **ApiVersionModel**. You can use a _fake_ controller by indicating the type is `typeof(ControllerBase)` and any other relevant information. This is the approach that test cases use.

API Versioning does **not** care about attributes. Using **ApiVersionAttribute** is just one way to realize the metadata. Instead it looks for implementations of **IApiVersionProvider**, which can be a built-in attribute, user-defined attribute, convention, etc. However, this information is typically only useful at start up when the application model is built. This is the time when the **ApiVersionModel** metadata instances are created. No implementations of **IApiVersionProvider** are considered after that. The **ApiVersionModel** is just a composite of the supported and deprecated API versions. The model is immutable, but there are numerous constructors and methods to build them up. In the simplest case, you would create a model with a single API version. Now that I'm thinking about it, if you have that, then things will like work. At the end of the day, the routing extensions just disambiguate otherwise duplicate routes by comparing the requested API version against the implemented (e.g. supported + deprecated) API versions associated with an endpoint. If you look at the [ApiVersionMatcherPolicy](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Routing/ApiVersionMatcherPolicy.cs), it will show you what to do. You need to create a _fake_ **ActionDescriptor** with the associated **ApiVersionModel**. With that in place, I would expect it to work.

While this _should_ all be possible, I'm not sure exactly _why_ someone would want to go through this much trouble. I can only guess that the reason is to version things that are not controllers. Not unreasonable, but there haven't been many asks for it. I can see how that would be a useful enhancement. For anything else, a controller, even the world's simplest controller, seems to be a better option.

I hope that helps get you started.

**Comment by markphillips100** [comment]
Thanks for the reply @commonsensesoftware .  You've given me lots of info to digest there but I think I understand what you've said.  I shall investigate the tests also to see if I can fake the required models.

As for why to do this, I imagine you are correct in that there probably wouldn't be too many asks for this as controllers usually are the simplest way to go.

I make use of a [ServiceComposer.AspNetCore](https://github.com/ServiceComposer/ServiceComposer.AspNetCore) package that allows me to implement ViewModel Composition in an API whilst minimizing coupling between individual ViewModel composition components.  This uses MVC's endpoint routing for route management but **does not use a controller**.   I'd still like to be able to version the routes though.

**Comment by commonsensesoftware** [comment]
This was an interesting question, but I think we completed the discussion - for now. It _could_ certainly lead to a new feature, but few people have asked for it. A couple of basic challenges:

1. The route registration would have to include a name/key to group (which is how it's done behind the scenes)
2. Routing management might be easier, but I could see implementation being less desirable for APIs this way (just my opinion)
3. API versions would seemingly _have_ to be applied with a fluent interface or _maybe_ with attributes as shown above

I could see something like this possibly working:

```c#
endpoints.MapGet(
    "HelloWorld",
    "/api/v{version:apiVersion}/hello",
    context => context.Response.WriteAsync("Hello World v2!")
   .ApiVersionModel()
   .HasApiVersion( 2, 0 );
```

It appears this conversation has expanded on the Service Composer repo. Happy to answer any additional questions.
