### ISSUE TITLE
If requirement comes for release Patch/Hotfix version inside Main V1 version?

### ISSUE THREAD

**Issue by AvasarGithub** [microsoft/aspnet-api-versioning#736]
I follow above folder structure like V1,V2,V3 etc for Api versioning with release. Now suppose need requirement for release Patch/Hotfix version for V1 version then how can manage code structure of it ? Please give me appropriate example if possible.
Thank You
Ramesh Dhandhukiya

**Comment by commonsensesoftware** [comment]
I presume this means you are using the **VersionByNamespaceConvention**. The **ApiVersion** does not have a _patch_ or _hotfix_ component by design. There are several other forms you can use though. The corresponding [wiki topic](../wiki/API-Version-Conventions#version-by-namespace-convention) has a lot of details on the various supported forms.

A _patch_ or _hotfix_ version is not something that is typically exposed to a client. In traditional binary versioning, a patch or hotfix would have a new version, but **zero** visible changes to consumers. In a web API, this concept is irrelevant. A web API version is **not** the same as a binary version. As such, if there are no visible changes in the API, then there's no need to change the version. To do so just adds more work for clients.

Despite what some people may think, there are no implied guarantees about compatibility between API versions. There is absolutely no guarantee that `1.1.` is backward-compatible with `1.0`; regardless of what you might think. This is counter intuitive from binary versioning, but highlights how the two are different. It might very well be that `1.1` is backward-compatible with `1.0`, but that API version doesn't actually tell you that. When a date is used, it not only tells you when the API version became effective, but you no longer make assumptions across versions. For example, you would not assume that `2021-03-01` is backward-compatible with `2021-01-01`, even if it is.

**Comment by commonsensesoftware** [comment]
This issue appears to have gone idle and reached it's conclusion.

Ultimately, a HTTP client does not, and should not, know about a patch or hotfix version. Tracking or logging it is certainly not unreasonable, but that is a service implementation detail. If the change you need to apply makes any visible change to a client, then you should bump the version - by date, minor version, etc. If it doesn't, then there is no real reason to change the API version.

If this didn't answer your question or you'd like to discuss further, feel free to reopen the issue or post a new question.
