### ISSUE TITLE
"No Scope available" on non-versioned controllers

### ISSUE THREAD

**Issue by twenzel** [microsoft/aspnet-api-versioning#740]
Given:
ASP.NET Core 5 API App using Castle Windsor DI 

When using Microsoft API versioning (Startup.cs line 29) the controller is only working when the request is using the versioned url "/api/v1/weatherforecast". When using the non-versioned url "/weatherforecast" services resolved inplace creates a InvalidOperationException "No Scope available"

This was working with ASP.NET Core 2.2 and Microsoft.AspNetCore.Mvc.Versioning, Version=4.X
[AspCoreVersionedApis.zip](https://github.com/microsoft/aspnet-api-versioning/files/6346539/AspCoreVersionedApis.zip)

**Comment by commonsensesoftware** [comment]
I'm afraid I don't know much about Windsor. I can't think of the last time anything significant changed in relation to DI. I need some additional information about how Windsor resolves controllers by this URL.

>When using the non-versioned url "/weatherforecast"...

Is incorrect. There is no such thing as _unversioned_ once you opt into API versioning. The closest thing is API _version-neutral_, which means you will accept any and all versions, including none at all.

The configuration:
* `[Route("[controller]")]`
* `options.AssumedDefaultVersionWhenUnspecified = true`
* `options.DefaultApiVersion = new ApiVersion(1,0)` (already the default BTW)

Results in `/weatherforecast` routing to the same place as `/api/v1/weatherforecast`. This type of double-route registration is required when you version by URL segment, which is one of many reasons why I don't recommend it.

**Comment by commonsensesoftware** [comment]
Apologies for the delay. I've looked into this deeper and it appears to be related to Windsor, which I honestly don't know a ton about. I **was** able to reproduce the error. Thank you for providing that. API Versioning does add services to the DI container, but it doesn't change anything about DI itself nor controller activation.

I did find, however, that things appear to work as expected if you use declarative, on-demand service activation instead of imperative activation within the controller action. This may simply be a mismatch in the way that Windsor maps to Microsoft.Extensions.DependencyInjection. This might also be due to trying to resolve services directly through the Windsor container instead of the Microsoft.Extensions.DependencyInjection abstraction over it.

The following change worked successful for both route templates:

### Existing - Failing
This calls into the Windsor container directly

```c#
[HttpGet]
public IEnumerable<WeatherForecast> Get()
{
    var service = _windsorContainer.Resolve<IScopedService>();
    var service1 = _windsorContainer.Resolve<ITransientService>();

   // ...
}
```

### Updated - Working
This call into the Windsor container indirectly through `IServiceProvider.GetService`

```c#
[HttpGet]
public IEnumerable<WeatherForecast> Get([FromServices] IScopedService service, [FromServices] ITransientService service1)
{
   // ...
}
```

May that still be useful to you.

**Comment by commonsensesoftware** [comment]
I'm burning down my issues. I'm going to presume the 👍🏽 denotes this issue has been adequately answered. If not, feel free to reopen the issue or post a new one. Thanks.

**Comment by StefanoVuerich** [comment]
Hi Guys, I'm having same issue as @twenzel 

Any news? I think this should not be closed

**Comment by commonsensesoftware** [comment]
@StefanoVuerich As far as I can tell, this is an external issue with Windsor/DI and has nothing specific to do with API Versioning. Are you saying that things work/worked without API Versioning and merely adding it causes this issue? I don't really see how. API Versioning doesn't explicitly create any DI containers or scopes.

If you can provide repo that highlights simply enabling API Versioning breaks Windsor, I'm happy to reopen the issue and investigate. Based on the previous repo and investigation, I suspect this has more to do with the Windsor configuration, DI mapping, and/or a potential change in the Windsor mapping to the DI abstractions. Most, if not all, of the services that API Versioning needs/uses do not run in a scope (as per request would be highly inefficient).
