### ISSUE TITLE
Add support for extending ApiControllerSelector

### ISSUE THREAD

**Issue by ngRevan** [Microsoft/aspnet-api-versioning#75]
I have the case where I want to extend the existing ApiControllerSelector to consider an additional custom route constraint.

I have the following controllers:

- V1
  - Tenant1
    - ValuesController.cs
  - Tenant2
    - ValuesController.cs

Which should get me the following routes:
- api/v1/Tenant1/Values
- api/v1/Tenant2/Values

Similar to the existing Selector I want to match the requested Tenant based on the attribute(s) on the controller.
```csharp
[ApiVersion("1.0")]
[Tenant("Tenant1")]
[Route("v{version:apiVersion}/{tenant:tenant}/Values")]
public class ValuesController : ApiController { }
```

Currently it is extremly difficult to extend the ApiControllerSelector as most of the selection logic is internal. It would already be extremely helpful, if one could register a handler to resolve ambigious versions/controllers.

**Comment by commonsensesoftware** [comment]
A few people have asked to open more of the **ApiControllerSelector** up.  I'm not opposed to it, but I mirrored approximately the same public surface area as the default implementation. The work originally started by literally copying the default implementation and reworking it.

My only real concern with opening things up more is diverging the visible surface area between Web API and ASP.NET Core as well as exposing methods and types that may cause breaking changes over time. I've had an ancillary goal of having the implementations look as similar as possible. It's easier to rationalize and makes for a good transition story for devs moving from Web API to ASP.NET Core. Again, I'm not completely opposed to the idea, but I haven't seen a very compelling reason to open the flood gates - yet.

In the scenario you describe, I'm not sure how extending the **ApiControllerSelector** helps solve your problem. The main purpose of the **ApiControllerSelector** is to disambiguate between controllers with the same route by API version. Controllers that route using the URL path segment method intrinsically do not have ambiguous routes.

The API version route constraint provides a few basic functions:
* Ensure the API version is well-formed
* Extract the API version from the URL without relying on string manipulation (like regular expressions)
* Enable switching between or using multiple API versioning methods
* Enable API version interleaving (e.g. multiple API versions implemented by the same controller type)

The last point is a scenario where extending the **ApiControllerSelector** would be necessary. Supporting multi-tenancy generally means implementing segregation between tenants. Accepting that premise means that it's quite unlikely that you'd ever want to interleave tenants on the same controller implementation.

There are several ways to split up multi-tenant, versioned controllers.  For example:

```c#
namespace Tenant1
{
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/Tenant1/Values")]
    public class ValuesController : ApiController { }
}

namespace Tenant2
{
    [ApiVersion("1.0")]
    [Route("api/v{version:apiVersion}/Tenant2/Values")]
    public class ValuesController : ApiController { }
}
```

Another approach might be that the web API is the same for all tenants, but data storage is segregated (a common scenario). In this case, you might use a route constraint as you original showed and then you would make storage decisions based on the requesting tenant.

Perhaps I'm missing something, but one of these approaches or one like it should satisfy your needs. Changing the **ApiControllerSelector** (in Web API in particular) is not for the faint of heart.  I got it wrong and found edge case bugs many, many times before reaching a level of stability. If you can elaborate on your case to open things up, I'm happy to chat further about enabling it; however - warning - there be dragons.

**Comment by ngRevan** [comment]
Thank you for your fast reply.

What I wanted to achieve was that one controller could support multiple tenants and another one handles one specific tenant, so that tenants who share the model also share the same controller. But you're right that implementing segregation between tenants is my final goal. 

Is there a way, if I don't have a constraint, to get the tenant from the request dynamically? Or to create a constraint with a specific value to map to? Because I would like to have a general implementation which serves the right data store based on the version (for tenant unrelated data) and optionally the tenant (for tenant related data).

The version 1 of the API is basically a port of existing API's, which were seperated in multiple applications.
The final goal is to create a version 2 of the API which is an OData Endpoint with following endpoints:
- api/v2/Locations -> Tenant unrelated data
- api/v2/Tenant1/People -> Tenant1 related data
- api/v2/Tenant2/People -> Tenant2 related data
....

- V2
  - LocationsController.cs
  - Tenant1
    - PeopleController.cs
  - Tenant2
    - PeopleController.cs

Would you mind giving me some advice as to how I could extend the existing Routing Conventions and Model Builder to support this?

Thank you very much for your help and I appreciate your work.

**Comment by commonsensesoftware** [comment]
I see. I think I understand what you're trying to achieve. The context definitely helps.

If the model varies by tenant, then it would seem that every tenant has it's own, unique model. That seems like it could get untenable to manage over time. If each tenant has it's own model, then is API versioning even needed? The version of each endpoint should only be applicable to a single tenant. You mentioned reusing models for different tenants. That feels like an over-normalization in my opinion. There might be some ways you achieve that behind the the curtains, but I would recommend keeps things 100% _per tenant_ on the API surface area.  That will make the separation very clear. Usually service authors want API versioning so they can advance/change the behavior of their services while continuing to support older clients. In this scenario, it seems that each tenant has a one-to-one affinity with an endpoint and the corresponding model.

If the models are _mostly_ the same and there are just minor differences, then using dynamic properties is another approach to fill in that gap. It's not ideal, but it's relatively easy to implement. In my opinion, it's also more favorable than _loosey-goosey_ models that use key/value pairs (though that would also work). Yet another approach would to be have a unioned model with serialization settings that completely ommit unused members to the corresponding tenants. Again, it's not ideal, but it might be better than a _model per tenant_. It would also seem that almost all of these scenarios would require creating one or more new controllers every time a new tenant is onboarded.  That seems really undesirable.

Unfortunately, integrating custom route constraints in OData (Web API) isn't as easy and flexible as it should be. It's significantly easier to use a query parameter or header. Since you are using a route segment though, you'll have to add the constraints to the **ODataRoute** items returned by the **MapVersionedODataRoutes**. I'm not sure exactly what your tenant route constriant does, but it really just needs to capture the value and store it in the property bag of the incoming request (**HttpRequestMessage.Properties**). You can then access it later in the pipeline when an extension method. This is what the API versioning route constraint does (a la **Request.GetRequestedApiVersion**).

If you can somehow map models to API version and segregate data by tenant, then your setup looks something like:

```c#
var routes = configuration.MapVersionedODataRoutes( "odata", "v{apiVersion}/{tenant}", models );

foreach ( var route in routes )
{
    route.Constraints.Add( "tenant", new TenantRouteConstraint() );
}
```

Then your controllers might look like:

```c#
[ApiVersion( "2.0" )]
[ODataRoutePrefix( "Values" )]
public class ValuesController : ODataController
{
   [ODataRoute]
   public async Task<IHttpActionResult> Get( ODataQueryOptions<Value> options )
   {
        var tenant = Request.GetTenant();
        Ok( await repository.GetAsync( query => options.ApplyTo( query.Where( i => i.Tenant == tenant ) ) );
   }
}
```

Alternatively, you could use a factory of repositories that split things up by tenant like:

```c#
[ApiVersion( "2.0" )]
[ODataRoutePrefix( "Values" )]
public class ValuesController : ODataController
{
   [ODataRoute]
   public async Task<IHttpActionResult> Get( ODataQueryOptions<Value> options )
   {
        var tenant = Request.GetTenant();
        var repository = factory.GetRepositoryForTenant( tenant );
        Ok( await repository.GetAsync( query => options.ApplyTo( query ) );
   }
}
```

Hopefully that gives you some ideas. There are of course other possible solutions. A _model per tenant_ design, however, will be challenging to implement using out-of-the-box features from the OData API. This type of scenario is supportable by the protocol, but it's quite complex to setup and enable. You'd likely have to swap out a lot of the default components.

A couple of final notes. The API versioning support for OData is still tied to 5.9.1. There are significant breaking changes in 6.0 and I haven't had enough time to get support updated yet. There are also limitations in switching between normal Web API controller routes and OData routes. Specifically, if you want to to reiably enable that scenario, you should use _conventional-based_ routing for all. I've documented this behavior in the [known limitations](https://github.com/Microsoft/aspnet-api-versioning/wiki/Known-Limitations) section. I've talked to the ASP.NET about this and there is really no way around it without completely replumping the default router in Web API. Fortunately, that won't be a probably in ASP.NET Core, but it still doesn't support OData. :(

**Comment by ngRevan** [comment]
Hi Chris

Thank you very much for your answer. Based on your answer I may have found a way which would work for me.

Basically I now have a controller per version rather than per tenant and version. But I configure the EdmModels and routes per tenant, so that I can ignore certain properties which don't exist in other tenants. 

Also I tried to map a certain action on the ApiController to a specific tenant. But this only works if the OData routes aren't mapped. It seems, that the unversioned OData route matches before the configured HttpRoutes. If I configure the HttpRoutes first, the HttpRoutes overwrite (match before) the OData Routes.

My setup looks like this:
```csharp
var builderTenant1 = new VersionedODataModelBuilder(httpConfiguration)
{
    ModelBuilderFactory = () => new ODataConventionModelBuilder(),
    ModelConfigurations = { new Tenant1ModelConfiguration() }
};

var builderTenant2 = new VersionedODataModelBuilder(httpConfiguration)
{
    ModelBuilderFactory = () => new ODataConventionModelBuilder(),
    ModelConfigurations = { new Tenant2ModelConfiguration() }
};

var tenant1Routes = httpConfiguration.MapVersionedODataRoutes("odata-tenant1", "{tenant}", builderTenant1.GetEdmModels());

var tenant2Routes = httpConfiguration.MapVersionedODataRoutes("odata-tenant2", "{tenant}", builderTenant2.GetEdmModels());

foreach (var route in tenant1Routes )
    route.Constraints.Add("tenant", new TenantRouteConstraint("tenant1"));

foreach (var route in tenant2Routes )
    route.Constraints.Add("tenant", new TenantRouteConstraint("tenant1"));


httpConfiguration.Routes.MapHttpRoute("NamedTenant1Action", "{tenant}/Values/NamedAction", new { controller = "Values", action = "NamedAction" }, new { tenant = new TenantRouteConstraint("tenant1") });
httpConfiguration.Routes.MapHttpRoute("DefaultGet", "{tenant}/{controller}/{id}", new { action = "Get", id = RouteParameter.Optional }, new { tenant = new TenantRouteConstraint("tenant1", "tenant2"), httpMethod = new HttpMethodConstraint(HttpMethod.Get) });
httpConfiguration.Routes.MapHttpRoute("Default", "{tenant}/{controller}/{id}", new { id = RouteParameter.Optional }, new { tenant = new TenantRouteConstraint("tenant1", "tenant2") });
```

Am I missing something?

**Comment by commonsensesoftware** [comment]
There are a couple of options for action selection (or _filtering_ in your case). The simplest would be to use an IAuthorizationFilter (ex: AuthorizeAttribute) on the action that restricts things by tenant. You'll probably want to do that anyway, since the action can be called by anyone who knows what the URL is. In terms of _hiding_ an action from a specific client or tenant, you can choose not to document the action.  For OData, you can choose not to advertise or otherwise emit the action link in the EDM.  This can be done with a custom link factory for the action.

Another option would be to extend and replace the ApiVersionActionSelector.  This class is much simpler and easier to extend than the ApiVersionControllerSelector.  You should be able to extend or decorate the API version implementation and then apply your additional logic before/after the versioning logic.

Bear in mind that vanilla and OData routes aren't really treated differently from a routing perspective.  You can't have the same API version for both protocols given a route template; it's one or the other.  This is equally true for the _unversioned_ (e.g. _initial_ or _default_) routes.  The versioning story thus far been primarily transitioning clients to OData, but transitioning away from OData is a supported scenario too.  Unfortunately, the routing implementation in Web API is less than stellar.  Whenever the team gets OData working in ASP.NET Core, things will be much better.

I hope that helps.

**Comment by commonsensesoftware** [comment]
I think we've covered some sound alternatives here so I'm going to close this out. The **ApiVersionControllerSelector** implementation in ASP.NET Web API is a horrible rat's nest that is forked and tweaked from the original implementation. The types and design required to open things up is not very desirable and is in low demand. If we can establish exactly where additional extensibility and customization hooks need to be, I'd rather discuss that as opposed to just opening up the flood gates.

The implementation of **ApiVersionActionSelector** in the ASP.NET Core flavor is radical simpler thanks to the improvements made by the ASP.NET team. Since that's the ultimate future, I'd like to make the strongest critiques and improvements there. The follow-up actions will be to replicate those hooks and abstractions as closely as possible in the Web API stack.
