### ISSUE TITLE
ApiVersion status does not support all words

### ISSUE THREAD

**Issue by jnlycklama** [microsoft/aspnet-api-versioning#750]
Hi,

I am trying to create a preview version (v1.0-preview), but keep running into 404s when I try to hit the endpoint. I am using URL versioning so the endpoint is something like /v1.0-preview/route.

I tried to configure the version in Startup.cs
```
            services.AddApiVersioning(c =>
            {
                c.AssumeDefaultVersionWhenUnspecified = true;
                c.DefaultApiVersion = new AspNetCore.Mvc.ApiVersion(1, 0, "preview");
                c.ReportApiVersions = true;
                c.Conventions.Controller<StoreController>().HasApiVersion(1, 0, "preview");
            });
```
and as a controller attribute
`[ApiVersion("1.0-preview")]
`
Either way got a 404. If I try the route without a version (which I have also enabled), I see "1.0-preview" in the api-supported-versions header
![image](https://user-images.githubusercontent.com/8868475/121609692-3f45fd80-ca09-11eb-8a3a-aaabcab42aaa.png)

However, when I replace the word "preview" with "beta", everything works as expected, I can hit the endpoint successfully.

Is there a set list of words that are allowed here? The summary of "status" seems to imply that any string of letters would work.
```
        //
        // Summary:
        //     Gets the optional version status.
        //
        // Value:
        //     The version status.
        //
        // Remarks:
        //     The version status typically allows services to indicate pre-release or test
        //     versions that are not release quality or guaranteed to be supported. Example
        //     values might include "Alpha", "Beta", "RC", etc.
```

**Comment by commonsensesoftware** [comment]
The issue, interestingly enough, is not that only certain words are allowed, it has to do specifically with `v` in the status because you are versioning by URL segment. Unfortunately, this is a limitation in the template parsing and routing system in ASP.NET Core itself. API Versioning is not capable of _fixing_ or working around it. An in-depth explanation can be found in #580 by the person who designed and wrote much of the routing system.

There are several possible alternatives:

1. Use another status name; for example `prerelease`
2. Use another method of versioning; no other method suffers from this. (By URL segment is the least RESTful anyway)
3. Ditch the initial `v` prefix (e.g. `1-preview`)
3. Create and register a custom **IRouteConstraint** that can accept the `v` prefix, but strips it off (as API Versioning will not accept it)

I also couldn't help notice that you've set `AssumeDefaultVersionWhenUnspecified = true`. This probably doesn't do what you hope or expect it to do. It's sadly the most abused feature. It was **only** meant for backward compatibility. It is impossible to have an optional route parameter in the middle of a template. The **only** way that this feature will work when versioning by URL segment is if you have double-route registration; in other words: `/v{version:apiVersion}/route` and `/route`. The same behavior is true for a template such as `order/{id}/items`. There is simply no way to provide a default value in the middle. Ultimately, this feature _should_ only be used if you have existing clients that are not version-aware and you are now applying versioning; otherwise, a client should always be expected to ask for the version they want.

**Comment by jnlycklama** [comment]
Very interesting! Thank you for the detailed response. I thought there might be something tricky going on, but would have never guessed it was because of the `v`.

& thank you for the advice on `AssumeDefaultVersionWhenUnspecified`. The case you described is actually exactly our scenario. We have some preview customers already using the API, and don't want to break them when we roll out the version. The plan is to use double routing for now, but eventually get rid of that after existing customers have moved to the version URL.
