### ISSUE TITLE
Could we use the implicit default api version with path route?

### ISSUE THREAD

**Issue by WeihanLi** [microsoft/aspnet-api-versioning#761]
When we try to access the versioned API without a specific version, we got a 404 returned.

service register:

``` c#
services.AddApiVersioning(options =>
{
    options.DefaultApiVersion = new ApiVersion(2, 0);
    options.AssumeDefaultVersionWhenUnspecified = true;
})
```

controller code:

``` c#
[ApiVersion("2.0")]
[ApiController]
[Route("api/v{version:apiVersion}/[controller]")]
public class TestController : ControllerBase
{
    [HttpGet]
    public IActionResult Test()
    {
        return Ok();
    }
}
```

When we try to access `/api/test`, we got 404 returned, when access `/api/v2/test`, it works.

How could we get it works for `/api/test` also? Is there something I missed?

**Comment by commonsensesoftware** [comment]
You _can_, but it's not as straight forward as you might expect. When you version by URL segment and you assume a default version, the default version _is_ used, but it will not change the routing behavior. This would be the same issue if you had `api/test/{id}/values`. You **must** specify a value for `{id}`. The simplest approach to implement this is _double route registration_. If you add an additional route template - say `[Route("api/[controller]")]`, then it will match the controller. Since no API version was specified or readable from the URL, the default API version will be used (e.g. `2.0` as you've configured it).

Additional information and possible alternatives are described in the [URL Path Segment Routing with a Default API Version
](../wiki/Known-Limitations#url-path-segment-routing-with-a-default-api-version) wiki topic. This is just one of several problems with versioning by URL segment, which is the least RESTful method. All other methods of versioning do not have this issue.

**Comment by WeihanLi** [comment]
Great thanks for your answer @commonsensesoftware
