### ISSUE TITLE
Enable versioning only for specific routes

### ISSUE THREAD

**Issue by AnthonyOSX** [Microsoft/aspnet-api-versioning#80]
My application runs MVC and web API within the same project. Unless I explicitly define a default version (which I don't want to) going to any route besides my API ones with versions defined results in an error due to no API version (ex. mywebsite.com/about/ results in an error while mywebsite.com/api/v1/users works as expected).

It would be useful to toggle the API versioning middleware for specific routes only.

**Comment by commonsensesoftware** [comment]
In general, if you own both the client (UI) and server (API) side of things, you probably don't need API versioning because you have total control over everything. From the looks of things, you want to have a documentation page for your API. That's a different scenario and completely reasonable.

As you've discovered, all routes get some intrinsic, default route once API versioning is applied. This is primarily to help _grandfather_ in existing services. There are a number of situations where a service or some other route, like a UI page, will want to [opt-out of versioning](../wiki/Opting-Out-of-Versioning).

The simplest approach to achieve this is to decorate your controller as follows:
```c#
[ApiVersionNeutral]
public class AboutController : Controller { }
```
This configuration is also achievable using the [conventions](../wiki/API-Version-Conventions) approach.

I hope that helps.

**Comment by AnthonyOSX** [comment]
The offered methods of opting out of versioning is a bit cumbersome. It doesn't make much sense to thread ApiVersionNeutral attributes throughout a web application when a simple route mapping would suffice. You also risk creating UI specific controllers, forgetting to add the attribute and scratching your head why mywebsite.com/about/ is throwing no version defined errors.

The current library works great for strict API projects but falls short if using it intertwined with MVC. Being able to do something like so would be incredibly powerful:

`services.AddApiVersioning(options => options.EnableForRoutePrefix("api"));`

Or:

`services.AddApiVersioning(options => options.DisableForRoutePrefix("admin/dashboard"));`

**Comment by commonsensesoftware** [comment]
Sorry, I saw the terms _MVC_ and _Web API_ and that threw me off for a second. As you know, a controller is just a controller in ASP.NET Core. There is no clear way to determine if a controller is for a UI, an API, or maybe even both.

Something that seems to confuse a lot of consumers of this library is the role of routing. The API Versioning libraries **do not change** any part of the routing infrastructure. Things work by letting routing do what routing has always done and then the results are disambiguated by using the API version information. If things are still ambiguous, then you get a failure identical to the behavior of duplicate routes. This is why you don't see any configuration or options for API Versioning that are related to routing. Furthermore, it was an important design decision to not make developers learn a new routing mechanism; you're able to capitalize on what you already know. The closest thing to a new routing concept is the single custom route constraint, but that is only used to extract the strongly-typed API version from a URL version segment without using _magic strings_.

Since there is no standard or out-of-the-box mechanism to determine which controller types are UI controllers and which ones aren't, I'm not sure how this library would necessarily provide that for you. I do agree that it would be something useful to have though.

Aside from documentation, I'm not sure (nor convinced) why you would have UI and API code together, while still needing API versioning. I can't imagine that there'd ever be an unmanageable number of documentation pages that require a large number of opt-out configurations.

If you want to manage all of that configuration in a single location, then the using the conventions support is the recommended way to go:

```c#
services.AddApiVersioning( o => o.Conventions.Controller<AboutController>().IsApiVersionNeutral() );
```

In case you're wondering, the convention and attribute-based models can be used simultaneously. If the two overlap, the attribute model overrides any conventions.

If you still don't fancy these methods given the additional context, you can fairly easily add your own conventions via the standard **IApplicationModelConvention** MVC interface. For example, something like:

```c#
public class UIApiVersionNeutralConvention : IApplicationModelConvention
{
  public void Apply( ApplicationModel application )
  {
    // RendersViewsOnly is your custom extension method that determines if
    // a controller is for views only (e.g. UI)
    var uiControllers = application.Controllers.Where( c => c.RendersViewsOnly() );

    foreach ( var controller in uiControllers  )
    {
      // this is same method that API versioning uses to wire up the model under the hood
      controller.Properties[typeof(ApiVersionModel)] = ApiVersionModel.Neutral;
    }
  }
}
```

Hopefully this helps clarify the challenge with identifying UI-based controllers. To my knowledge, there is not a base class, attribute, or other out-of-the-box method that would allow API Versioning to add a filtering capability in a straight forward manner. This division can be done many, many different ways in a project; potentially without any convention or method to the organization.

If we, or anyone else out there, has a suggestion on how this can be done, I'm open to entertaining the idea. However, if it can't be achieved without using an attribute, interface, or base class, then I don't see how it's any better than just applying the `ApiVersionNeutralAttribute` or defining a convention configuration for the target controller.

**Comment by commonsensesoftware** [comment]
Circling back around to revisit this issue.  I don't want to get into the business of changing or otherwise enhancing the routing infrastructure. It's one of the API versioning _prime directives_ to not make you learn a new way of routing.

All that said, your requirement is still valid.  API version neutrality should be inheritable, which would simplify these types of scenarios and meet your needs. However, I noticed that the **ApiVersionNeutralAttribute** is not currently inherited.  This is a mistake. I've filed #93 to specifically track this issue. The fix is simple and will arrive in the forthcoming [1.1.0 milestone release](../milestone/1).

If you don't want to wait, you can get implement your own solution today.  You just need an attribute that implements the marker interface (which is what the code really cares about).

```c#
[AttributeUsage( AttributeTargets.Class, AllowMultiple = false, Inherited = true )]
public sealed class NotVersionedAttribute : Attribute, IApiVersionNeutral { }

[NotVersioned]
public abstract class UIController : Controller { }

[Route( "[controller]" )]
public class AboutController : UIController { /* omitted */ }
```

Once the fix is publicly available, you can swap out **[NotVersioned]** with **[ApiVersionNeutral]** and delete your custom attribute - if you want. Things will continue to work if you keep your custom attribute.

I hope that gets you closer to your goal.

**Comment by commonsensesoftware** [comment]
Issue #94 provides a long-term, permanent solution and an alternate solution is provided here; therefore, I'm closing this issue out. Feel free to re-open or create a new issue if you have additional thoughts. Thanks for the in-depth feedback.
