### ISSUE TITLE
Do candidate actions have to appear in log if multiple matches?

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/aspnet-api-versioning#83]
In log I see
```
Microsoft.AspNetCore.Mvc.Versioning.ApiVersionActionSelector:Information: Multiple candidate actions were found, but none matched the requested service API version '1'. Candidate actions:
```
And I can't figure out what is wrong/

**Comment by commonsensesoftware** [comment]
The candidate action list is a multi-line list of candidates that the routing infrastructure discovered. If you don't see any matches, then there aren't any candidates.  This process happens before any API version-related logic and is unchanged from the default, built-in behaviors. If you're not seeing any candidates, then I suspect that your routes are not configured correctly (either by template or attributes).

**Comment by commonsensesoftware** [comment]
After some investigation, this looks like a bug in [ApiVersionActionSelector.cs (Line 215)](../blob/master/src/Microsoft.AspNetCore.Mvc.Versioning/Versioning/ApiVersionActionSelector.cs#L215). The logged set of candidate action names should derive from `candidates` instead of `context.MatchingActions` (which may be none).  Good catch.
