### ISSUE TITLE
Issue with QueryStringOrHeaderApiVersionReader

### ISSUE THREAD

**Issue by scoleman81** [Microsoft/aspnet-api-versioning#88]
I am trying to allow query string or Header Values for api version declaration.  When I use:
`services.AddApiVersioning(o =>
     o.ApiVersionReader = new QueryStringOrHeaderApiVersionReader("api-version")
);`
Query string parameters work but I get an ApiVersionUnspecified error.  If I switch and use:
`o.ApiVersionReader = new HeaderApiVersionReader("api-version")`
I have no issues using headers but obviously query strings won't work.  Am I missing something here or is this a bug?

**Comment by commonsensesoftware** [comment]
The default behavior uses the **QueryStringApiVersionReader**, which only reads from the query string. When you switch to **QueryStringOrHeaderApiVersionReader**, then either the query string or a HTTP header can be specified. They can actually both be specified by a client as long as they aren't different. The **HeaderApiVersionReader** only reads from a HTTP header.

Currently, the **QueryStringApiVersionReader** only allows a single query string parameter. The **QueryStringOrHeaderApiVersionReader** and **HeaderApiVersionReader** implementations, however, allow multiple HTTP headers. Usually you only need one, but in legacy header scenarios, there have often been numerous variations. In addition, neither implementation defines any HTTP headers by default. The constructor for the **QueryStringOrHeaderApiVersionReader** is thus a little confusing because it extends and duplicates the constructor for **QueryStringApiVersionReader**, which only accepts a single query string parameter name; no headers are defined.

I suspect this will get you what you want:
```c#
o.ApiVersionReader = new QueryStringOrHeaderApiVersion( parameterName: "api-version" )
{
  HeaderNames = { "api-version", "x-ms-version" }
}
```

This enables the following client requests:
```http
GET http://localhost/svc?api-version=1.0 HTTP/1.1
```
```http
GET http://localhost/svc HTTP/1.1
api-version:1.0
```
```http
GET http://localhost/svc HTTP/1.1
x-ms-version:1.0
```

I hope that helps clear things up. Let me know if you have more questions.

**Comment by scoleman81** [comment]
Thanks, it was the second part specifying the header names I was missing.  That did the trick.  Thanks for the quick response.
