### ISSUE TITLE
This project should be run by the ASP.NET Team

### ISSUE THREAD

**Issue by RehanSaeed** [Microsoft/aspnet-api-versioning#89]
@aspnet should be the owner of the this repository, I had a hard time re-discovering it.

I suspect this project is run by a team other than the ASP.NET team at Microsoft. If that is the case, then ownership should be moved there also. 

As it stands, this project has not been maintained, it still does not support ASP.NET Core 1.1.1 (https://github.com/Microsoft/aspnet-api-versioning/issues/78). Ideally new versions should be released with each minor/major version of ASP.NET Core.

**Comment by commonsensesoftware** [comment]
There's no team in "I". If you mean another team at Microsoft, then - yes - that'd be me; the army of one.

I've had a couple of chats with the ASP.NET team. They are interested in incorporating the core abstractions in the platform, but that's about as far as it's gotten.  Furthermore, my impressions have been they are primarily interested in ASP.NET Core. There are still a lot of people out there using ASP.NET Web API, so it's important (to me) that they are covered too.

Honestly, I'd love more help - internally or externally. Thus far, no one has expressed any interest in stepping up.  I do have a day job and I do what I can to keep up with all of the incoming requests.  Some are significantly more involved than others.

I'll circle back around on #78.  I have a hard time believing the whole thing falls down based on a minor version update. Admittedly, stranger things have happened though.

**Comment by RehanSaeed** [comment]
I was taking another look at this project to add it as an optional feature to my [API project template](https://github.com/ASP-NET-MVC-Boilerplate/Templates/blob/master/MVC%206%20API.md) that uses `dotnet new`, so as a fellow solo developer, I totally appreciate your efforts.

The ASP.NET team are probably too busy working on 2.0 and Signal-R. Not sure if 1.1.1 is any different to 1.1.0 for this project.

**Comment by commonsensesoftware** [comment]
I'm sure they are too busy to _own_ it, but any assistance I could get from them, or otherwise, would certainly be helpful; not just to me, but also the community. There's a couple of big ticket items in the queue right now. Addressing breaking changes is one of the larger challenges to solve. In the case of #36, I know I need to break compatibility as well in order to support the new features of OData 6.0+.

Clearly there are some blocking issues here. I'll do what I can to speed things up. I don't _really_ need sleep anyway; it's highly overrated. =P

**Comment by commonsensesoftware** [comment]
I'm going to close this out because there's not really anything publicly actionable on my side. If you cross-link this over to the @aspnet repo and get some traction, I'm happy to re-open the issue. In terms of discoverability, I think it's actually the ASP.NET repo that is the outlier. This project is under the official [Microsoft company GitHub page](https://github.com/Microsoft). The ASP.NET repo is older and under it's own root. The company policy to keep OSS work under the company page so that people _can_ easily find them. I guess the ASP.NET team figured the repo was too big and well-known to bother moving it once the policy was formally established. If @aspnet ever decides they want to move this repo under their official repo, I'm sure we'll do that and add a forward pointer link from the old location.

The fix for referencing ASP.NET Core 1.1.1 is in. I'm working on a few other changes for the overall [1.1.0 milestone release](../milestone/1).  The fix will go out in the wild for that release.  Thanks for your patience.
